var searchData=
[
  ['iets_20verzinnen_0',['Principe: NOOIT iets verzinnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md382',1,'']]],
  ['immediate_20scheduling_1',['K_NO_WAIT voor Immediate Scheduling',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md239',1,'']]],
  ['impact_2',['Impact',['../energy_pulse_doc.html#autotoc_md50',1,'Resultaten &amp; Impact'],['../md_modules_2timing_2timing__doc.html#autotoc_md173',1,'Resultaten en Impact']]],
  ['implementatie_20design_20rationale_3',['2. Implementatie Design Rationale',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md365',1,'']]],
  ['implementatie_20vereisten_20voor_20modules_4',['Implementatie Vereisten voor Modules',['../md_modules_2reboot_2reboot__doc.html#autotoc_md157',1,'']]],
  ['implementatie_20voorbeelden_5',['1. Code Implementatie Voorbeelden',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md377',1,'']]],
  ['in_20c_20files_6',['Include Order (in .c files)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md277',1,'']]],
  ['in_20moet_7',['in moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md363',1,'✅ Wat ER WEL in moet'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md376',1,'❗ Wat ER NIET in moet']]],
  ['in_20parent_20cmakelists_8',['Integration in Parent CMakeLists',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md305',1,'']]],
  ['in_20thread_9',['Message Processing in Thread',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md231',1,'']]],
  ['in_20volgorde_10',['Standaard Secties (in volgorde)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md285',1,'']]],
  ['include_20guards_20en_20headers_11',['Include Guards en Headers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md275',1,'']]],
  ['include_20order_20in_20c_20files_12',['Include Order (in .c files)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md277',1,'']]],
  ['inconsistente_20titel_20formaten_13',['❗ Inconsistente Titel Formaten',['../group__Titel.html#autotoc_md458',1,'']]],
  ['indentatie_20en_20formattering_14',['Indentatie en Formattering',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md322',1,'']]],
  ['indien_20module_20eigen_20thread_20heeft_15',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md314',1,'']]],
  ['inhoudsopgave_16',['Inhoudsopgave',['../md_modules_2network_2network__doc.html#autotoc_md83',1,'Inhoudsopgave'],['../md_modules_2reboot_2reboot__doc.html#autotoc_md143',1,'Inhoudsopgave'],['../md_modules_2timing_2timing__doc.html#autotoc_md160',1,'Inhoudsopgave']]],
  ['initialisatie_17',['Initialisatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md296',1,'Module Initialisatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md311',1,'Module Initialisatie']]],
  ['initialisatie_20flow_18',['Initialisatie Flow',['../md_modules_2network_2network__doc.html#autotoc_md91',1,'']]],
  ['initialisatie_20sequence_19',['Initialisatie Sequence',['../energy_pulse_doc.html#autotoc_md45',1,'']]],
  ['initialization_20',['Initialization',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md342',1,'']]],
  ['input_20validation_21',['Input Validation',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md269',1,'']]],
  ['insights_20lessons_20learned_22',['5.7 Key Insights &amp;amp; Lessons Learned',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md427',1,'']]],
  ['int_20return_23',['Void vs Int Return',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md224',1,'']]],
  ['integer_20fixed_20point_24',['Waarom Integer Fixed-Point?',['../p_one_doc.html#autotoc_md113',1,'']]],
  ['integratie_25',['Integratie',['../index.html#autotoc_md196',1,'☁️ Cloud Integratie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md298',1,'Kconfig Integratie'],['../p_one_doc.html#autotoc_md105',1,'ZBUS Integratie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md310',1,'ZBUS Integratie']]],
  ['integration_20in_20parent_20cmakelists_26',['Integration in Parent CMakeLists',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md305',1,'']]],
  ['intended_20behaviour_27',['6. Intended Behaviour',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md369',1,'']]],
  ['inter_20byte_20timeout_28',['2. UART RX Timeout (Inter-byte timeout)',['../p_one_doc.html#autotoc_md125',1,'']]],
  ['inter_20byte_20timeout_20392_20ms_29',['Inter-byte Timeout (392 ms)',['../p_one_doc.html#autotoc_md129',1,'']]],
  ['inter_20byte_20timeout_20trigger_30',['Scenario 3: Inter-byte Timeout Trigger',['../p_one_doc.html#autotoc_md135',1,'']]],
  ['interaction_31',['Hardware Interaction',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md249',1,'']]],
  ['interface_32',['Interface',['../app_doc.html#autotoc_md9',1,'4. ZBUS Interface'],['../cloud_doc.html#autotoc_md29',1,'4. ZBUS Interface'],['../message_queue_module.html#mq_zbus',1,'ZBUS Interface']]],
  ['interfaces_33',['Interfaces',['../energy_pulse_doc.html#autotoc_md42',1,'ZBUS Interfaces'],['../led_doc.html#autotoc_md68',1,'ZBUS Interfaces']]],
  ['interrupt_20thread_20scheiding_34',['Architectuur: Interrupt/Thread Scheiding',['../md_modules_2timing_2timing__doc.html#autotoc_md169',1,'']]],
  ['inventory_20objectieve_20waarheid_35',['Fase 1: Build Code Inventory (Objectieve Waarheid)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md400',1,'']]],
  ['inverterende_20buffer_36',['GPIO Data Request Pin &amp;amp; Inverterende Buffer',['../p_one_doc.html#autotoc_md101',1,'']]],
  ['investigation_37',['5.2 Fundamenteel Principe: Code-First Investigation',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md397',1,'']]],
  ['iot_20device_38',['Visuele Feedback voor IoT Device',['../led_doc.html#autotoc_md63',1,'']]],
  ['is_20dit_20zo_20belangrijk_39',['Waarom is dit zo belangrijk?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md390',1,'']]],
  ['is_5fcloud_5fready_40',['is_cloud_ready',['../message__queue_8c.html#a6f1182cd9184295f68d09c18dc04ba36',1,'message_queue.c']]],
  ['is_5fqueue_5fempty_41',['is_queue_empty',['../message__queue_8c.html#a0a18dae9147827c899adc85732e672cd',1,'message_queue.c']]]
];
