var searchData=
[
  ['garanties_20via_20buffering_0',['Delivery Garanties via Buffering',['../message_queue_doc.html#autotoc_md128',1,'']]],
  ['gas_20meting_20acquisitie_1',['Gas Meting Acquisitie',['../p_one_doc.html#autotoc_md190',1,'']]],
  ['gas_20unit_20clarification_2',['Gas Unit Clarification',['../message_queue_doc.html#autotoc_md147',1,'']]],
  ['gas_5fconsumed_5fm3_3',['gas_consumed_m3',['../structp__one__msg.html#afb8226a2ab2ab6f50ec759e17b76f7f3',1,'p_one_msg']]],
  ['gas_5fm3_5fconsumed_4',['gas_m3_consumed',['../p__one_8c.html#af63330db3054db5e11af8a1b7b170841',1,'p_one.c']]],
  ['gdb_20debugging_5',['GDB Debugging',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md348',1,'']]],
  ['gebruik_6',['SYS_INIT Gebruik',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md497',1,'']]],
  ['gebruik_20named_20constants_7',['Gebruik Named Constants',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md549',1,'']]],
  ['gebruiken_8',['Wanneer Gebruiken',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md480',1,'']]],
  ['gecoördineerde_20data_20collectie_9',['Gecoördineerde Data Collectie',['../message_queue_doc.html#autotoc_md127',1,'']]],
  ['gecoördineerde_20data_20collectie_20flow_10',['Gecoördineerde Data Collectie Flow',['../message_queue_doc.html#autotoc_md131',1,'']]],
  ['gecoördineerde_20timing_11',['Gecoördineerde Timing',['../timing_doc.html#autotoc_md263',1,'']]],
  ['gedrag_12',['Gedrag',['../reboot_doc.html#autotoc_md249',1,'Graceful Shutdown Gedrag'],['../energy_pulse_doc.html#autotoc_md82',1,'Hoe? (Architectuur &amp; Gedrag)'],['../led_doc.html#autotoc_md109',1,'Hoe? (Architectuur &amp; Gedrag)'],['../message_queue_doc.html#autotoc_md135',1,'Hoe? (Architectuur &amp; Gedrag)'],['../network_doc.html#autotoc_md170',1,'Hoe? (Architectuur &amp; Gedrag)'],['../reboot_doc.html#autotoc_md242',1,'Hoe? (Architectuur &amp; Gedrag)'],['../timing_doc.html#autotoc_md271',1,'Hoe? (Architectuur &amp; Gedrag)'],['../message_queue_doc.html#autotoc_md149',1,'Queue Overflow Gedrag'],['../energy_pulse_doc.html#autotoc_md84',1,'Runtime Gedrag']]],
  ['gedreven_13',['GPIO Interrupt Gedreven',['../energy_pulse_doc.html#autotoc_md75',1,'']]],
  ['geen_20tabs_14',['Spaties (GEEN Tabs)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md523',1,'']]],
  ['geheugen_20performance_15',['Geheugen Performance',['../energy_pulse_doc.html#autotoc_md89',1,'Geheugen &amp; Performance'],['../timing_doc.html#autotoc_md278',1,'Geheugen &amp; Performance']]],
  ['generatie_16',['FOTA Image Generatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md369',1,'']]],
  ['genereren_17',['1.5 Certificaten Genereren',['../provisioning.html#autotoc_md387',1,'']]],
  ['get_5fqueue_5fusage_18',['get_queue_usage',['../message__queue_8c.html#adca8ee032108f348cf8ea3936481854d',1,'message_queue.c']]],
  ['get_5freboot_5ftype_5fstr_19',['get_reboot_type_str',['../reboot__zbus_8c.html#ade3f3b087041c1ad9a0f490df51df19b',1,'reboot_zbus.c']]],
  ['geverifieerd_20_3a_20',['✅ CORRECT (geverifieerd):',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md588',1,'']]],
  ['git_20history_20commands_20context_21',['Git History Commands (Context)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md622',1,'']]],
  ['gpio_20callbacks_22',['GPIO Callbacks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md451',1,'']]],
  ['gpio_20interrupt_20gedreven_23',['GPIO Interrupt Gedreven',['../energy_pulse_doc.html#autotoc_md75',1,'']]],
  ['gpio_5fcb_24',['gpio_cb',['../energy__pulse_8c.html#a2c1fdb2a55600085d534b2305e5c3385',1,'energy_pulse.c']]],
  ['graceful_20shutdown_25',['Graceful Shutdown',['../index.html#autotoc_md297',1,'🛑 Graceful Shutdown'],['../reboot_doc.html#autotoc_md233',1,'Graceful Shutdown']]],
  ['graceful_20shutdown_20gedrag_26',['Graceful Shutdown Gedrag',['../reboot_doc.html#autotoc_md249',1,'']]],
  ['graphs_27',['📊 Call Graphs',['../index.html#autotoc_md312',1,'']]],
  ['green_28',['green',['../structled__pattern.html#aefbeaf6636b283b65c02a7229da25e36',1,'led_pattern']]],
  ['groepen_20definiëren_29',['Module Groepen Definiëren',['../doxygen_guidelines.html#autotoc_md647',1,'']]],
  ['guards_20en_20headers_30',['Include Guards en Headers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md475',1,'']]],
  ['guide_31',['Development Guide',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html',1,'']]],
  ['guidelines_32',['Doxygen Documentatie Guidelines',['../doxygen_guidelines.html',1,'']]]
];
