var searchData=
[
  ['v2_200_203_0',['Download Modem Firmware v2.0.3',['../provisioning.html#autotoc_md382',1,'']]],
  ['v2_203_208_1',['Download PTI Modem Firmware v2.3.8',['../provisioning.html#autotoc_md383',1,'']]],
  ['validatie_2',['Validatie',['../p_one_doc.html#autotoc_md200',1,'CRC16 Validatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md552',1,'NULL Checks en Validatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md553',1,'Pointer Validatie']]],
  ['validation_3',['Validation',['../cloud_doc.html#autotoc_md51',1,'Build Validation'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md469',1,'Input Validation']]],
  ['value_4',['value',['../p__one_8c.html#a354b99b030bdfe136490f848c05d4788',1,'p_one.c']]],
  ['value_20conventies_5',['Return Value Conventies',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md422',1,'']]],
  ['value_5fformat_6',['value_format',['../structobis__code__entry__t.html#af46c15f3b998059fb2fcc7fe1f421556',1,'obis_code_entry_t']]],
  ['values_7',['Error Handling en Return Values',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md419',1,'']]],
  ['van_20_5fdoc_20md_8',['Structuur van &lt;span class=&quot;tt&quot;&gt;&amp;lt;module&amp;gt;_doc.md&lt;/span&gt;',['../doxygen_guidelines.html#autotoc_md644',1,'']]],
  ['van_20andere_20modules_9',['10. Afhankelijkheden van Andere Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md573',1,'']]],
  ['van_20blokken_20code_10',['2. Herhalingen van Blokken Code',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md578',1,'']]],
  ['van_20documentatie_3a_11',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md583',1,'']]],
  ['van_20dsmr_20meters_12',['Data Acquisitie van DSMR Meters',['../p_one_doc.html#autotoc_md185',1,'']]],
  ['van_20fouten_20door_20niet_20te_20verifiëren_3a_13',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md586',1,'']]],
  ['variabelen_14',['Variabelen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md530',1,'']]],
  ['variable_20declaratie_15',['Error Variable Declaratie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md420',1,'']]],
  ['variable_20declarations_16',['Variable Declarations',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md541',1,'']]],
  ['verboden_3a_17',['❗ VERBODEN:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md585',1,'']]],
  ['vereisten_18',['Module Shutdown Implementatie Vereisten',['../reboot_doc.html#autotoc_md253',1,'']]],
  ['vergelijkingen_19',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md579',1,'']]],
  ['verifiëren_3a_20',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md586',1,'']]],
  ['verificatie_21',['Verificatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md329',1,'Toolchain Verificatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md333',1,'Verificatie']]],
  ['verificatie_20en_20synchronisatie_20kritiek_20⚠️_22',['4. Code Verificatie en Synchronisatie (KRITIEK! ⚠️)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md581',1,'']]],
  ['verificatie_20per_20claim_20type_23',['Fase 3: Systematische Verificatie Per Claim Type',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md604',1,'']]],
  ['verificatie_20protocol_24',['5. AI Agent Documentatie Verificatie Protocol',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md594',1,'']]],
  ['verificatie_20strategie_25',['5.3 Systematische Verificatie Strategie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md599',1,'']]],
  ['verification_20shortcuts_26',['Verification Shortcuts',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md623',1,'']]],
  ['verification_20workflow_205_20fasen_27',['5.4 Verification Workflow (5 Fasen)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md618',1,'']]],
  ['verkrijgen_28',['1.6 IMEI Lijst Verkrijgen',['../provisioning.html#autotoc_md389',1,'']]],
  ['verplichte_20stappen_3a_29',['✅ VERPLICHTE STAPPEN:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md584',1,'']]],
  ['version_30',['version',['../p__one_8c.html#af1c7e5e925151edc04c2424009ab7892',1,'p_one.c']]],
  ['verwerking_31',['📊 Data Verwerking',['../index.html#autotoc_md301',1,'']]],
  ['verzend_20logica_32',['Verzend Logica',['../message_queue_doc.html#autotoc_md138',1,'']]],
  ['verzinnen_33',['Principe: NOOIT iets verzinnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md582',1,'']]],
  ['verzonnen_20content_20_3a_34',['❗ FOUT (verzonnen content):',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md587',1,'']]],
  ['via_20buffering_35',['Delivery Garanties via Buffering',['../message_queue_doc.html#autotoc_md128',1,'']]],
  ['via_20nrfjprog_20direct_36',['Via nrfjprog (Direct)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md343',1,'']]],
  ['via_20rtt_37',['Stap 4: IMEI Schrijven via RTT',['../provisioning.html#autotoc_md396',1,'']]],
  ['via_20west_38',['Via West',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md342',1,'']]],
  ['visibility_39',['Header Visibility',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md504',1,'']]],
  ['visueel_20overzicht_40',['Visueel Overzicht',['../index.html#autotoc_md290',1,'']]],
  ['visuele_20feedback_20voor_20iot_20device_41',['Visuele Feedback voor IoT Device',['../led_doc.html#autotoc_md101',1,'']]],
  ['voer_20onboarding_20uit_42',['Voer Onboarding Uit',['../provisioning.html#autotoc_md409',1,'']]],
  ['void_20vs_20int_20return_43',['Void vs Int Return',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md424',1,'']]],
  ['volgorde_44',['Volgorde',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html',1,'Code Structure - Organisatie en Volgorde'],['../app_doc.html#autotoc_md12',1,'Initialisatie Volgorde'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md482',1,'Volgorde']]],
  ['volgorde_45',['Standaard Secties (in volgorde)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md485',1,'']]],
  ['voor_20documentatie_20review_20sessie_46',['5.6 Checklist: Voor Documentatie Review Sessie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md625',1,'']]],
  ['voor_20elke_20documentatie_20wijziging_3a_47',['Checklist voor elke documentatie wijziging:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md589',1,'']]],
  ['voor_20immediate_20scheduling_48',['K_NO_WAIT voor Immediate Scheduling',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md439',1,'']]],
  ['voor_20iot_20device_49',['Visuele Feedback voor IoT Device',['../led_doc.html#autotoc_md101',1,'']]],
  ['voor_20modules_50',['CMakeLists.txt voor Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md500',1,'']]],
  ['voor_20na_20vergelijkingen_51',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md579',1,'']]],
  ['voor_20nieuwe_20module_52',['Checklist voor Nieuwe Module',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md447',1,'']]],
  ['voor_20specifiek_20board_53',['Build voor Specifiek Board',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md339',1,'']]],
  ['voorbeelden_54',['Voorbeelden',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md577',1,'1. Code Implementatie Voorbeelden'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md621',1,'Code Analysis Commands (Voorbeelden)']]],
  ['voorbeelden_20van_20fouten_20door_20niet_20te_20verifiëren_3a_55',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md586',1,'']]],
  ['voordelen_56',['Remote Support Voordelen',['../led_doc.html#autotoc_md116',1,'']]],
  ['vs_20define_57',['enum vs define',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md548',1,'']]],
  ['vs_20definitions_58',['Channel Declarations vs Definitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md494',1,'']]],
  ['vs_20int_20return_59',['Void vs Int Return',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md424',1,'']]]
];
