var searchData=
[
  ['behavior_0',['Watchdog Callback Behavior',['../app_doc.html#autotoc_md14',1,'']]],
  ['behavior_20claims_1',['3.4 Timing &amp;amp; Behavior Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md568',1,'']]],
  ['behavior_20en_20portability_2',['Undefined Behavior en Portability',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md411',1,'']]],
  ['behaviour_3',['6. Intended Behaviour',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md526',1,'']]],
  ['belangrijk_4',['Waarom is dit zo belangrijk?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md547',1,'']]],
  ['belangrijke_20features_5',['⚙️ Belangrijke Features',['../index.html#autotoc_md307',1,'']]],
  ['belangrijke_20links_6',['🔗 Belangrijke Links',['../index.html#autotoc_md323',1,'']]],
  ['benefits_7',['User Experience Benefits',['../led_doc.html#autotoc_md119',1,'']]],
  ['berekening_8',['Timing Berekening',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md403',1,'']]],
  ['best_20practices_20praktische_20richtlijnen_9',['Best Practices - Praktische Richtlijnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html',1,'']]],
  ['best_2dpractices_2emd_10',['best-practices.md',['../best-practices_8md.html',1,'']]],
  ['bestanden_20structuur_11',['Bestanden Structuur',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md465',1,'']]],
  ['bestandsnaam_20conventie_12',['Bestandsnaam Conventie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md516',1,'']]],
  ['betrouwbaarheid_13',['Betrouwbaarheid',['../energy_pulse_doc.html#autotoc_md90',1,'Betrouwbaarheid'],['../timing_doc.html#autotoc_md288',1,'Betrouwbaarheid'],['../reboot_doc.html#autotoc_md256',1,'Shutdown Betrouwbaarheid']]],
  ['bewerken_20van_20documentatie_3a_14',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md540',1,'']]],
  ['bij_20errors_15',['Logging Bij Errors',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md380',1,'']]],
  ['bij_20het_20schrijven_20of_20bewerken_20van_20documentatie_3a_16',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md540',1,'']]],
  ['blocking_20led_20control_17',['Non-Blocking LED Control',['../led_doc.html#autotoc_md102',1,'']]],
  ['blokken_20code_18',['2. Herhalingen van Blokken Code',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md535',1,'']]],
  ['blue_19',['blue',['../structled__pattern.html#ad4f15da5e81832978bc2fb35d9d64e20',1,'led_pattern']]],
  ['board_20definition_20',['Custom Board Definition',['../index.html#autotoc_md315',1,'']]],
  ['bool_20checks_21',['Bool Checks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md511',1,'']]],
  ['boot_20confirmation_22',['Boot Confirmation',['../cloud_doc.html#autotoc_md32',1,'']]],
  ['boot_20confirmation_20window_23',['Boot Confirmation Window',['../cloud_doc.html#autotoc_md58',1,'']]],
  ['boot_20loop_20protection_24',['Boot Loop Protection',['../cloud_doc.html#autotoc_md39',1,'']]],
  ['bouwen_25',['1.4 Modem Shell (MoSh) Bouwen',['../provisioning.html#autotoc_md342',1,'']]],
  ['brace_20style_26',['Brace Style',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md482',1,'']]],
  ['branding_27',['🎨 Styling &amp;amp; Branding',['../doxygen_guidelines.html#autotoc_md596',1,'']]],
  ['broken_20links_28',['❗ Broken Links',['../group__Titel.html#autotoc_md616',1,'']]],
  ['buffer_20overflow_20prevention_29',['Buffer Overflow Prevention',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md427',1,'']]],
  ['buffer_20size_20constraint_30',['Buffer Size Constraint',['../p_one_doc.html#autotoc_md232',1,'']]],
  ['buffering_31',['Delivery Garanties via Buffering',['../message_queue_doc.html#autotoc_md132',1,'']]],
  ['buffers_32',['Arrays en Buffers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md501',1,'']]],
  ['build_20code_20inventory_20objectieve_20waarheid_33',['Fase 1: Build Code Inventory (Objectieve Waarheid)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md557',1,'']]],
  ['build_20de_20dinnis_20application_34',['Build de Dinnis Application',['../provisioning.html#autotoc_md360',1,'']]],
  ['build_20systeem_35',['Build Systeem',['../index.html#autotoc_md314',1,'']]],
  ['build_20system_36',['🛠️ Build System',['../group__Titel.html#autotoc_md609',1,'']]],
  ['build_20validation_37',['Build Validation',['../cloud_doc.html#autotoc_md51',1,'']]],
  ['build_5fassert_38',['BUILD_ASSERT',['../cloud_8c.html#ab532862c61299bd0b47021aa0f87e486',1,'BUILD_ASSERT(CONFIG_APP_CLOUD_MODULE_WATCHDOG_TIMEOUT_SECONDS &gt; CONFIG_APP_CLOUD_MODULE_MSG_PROCESSING_TIME_SECONDS, &quot;Cloud watchdog timeout must be greater than message processing time&quot;):&#160;cloud.c'],['../energy__pulse_8c.html#a6f5d7596cae44d6b771c19d31ab2ee88',1,'BUILD_ASSERT(CONFIG_APP_ENERGY_PULSE_MODULE_WATCHDOG_TIMEOUT_SECONDS &gt; CONFIG_APP_ENERGY_PULSE_MODULE_MSG_PROCESSING_TIME_SECONDS, &quot;Watchdog timeout must be greater than message processing time&quot;):&#160;energy_pulse.c'],['../led_8c.html#a594fa21d5414cf92769b88318aae5eb8',1,'BUILD_ASSERT(CONFIG_LED_MODULE_WATCHDOG_TIMEOUT_SECONDS &gt; CONFIG_LED_MODULE_MSG_PROCESSING_TIME_SECONDS, &quot;LED watchdog timeout must be greater than message processing time&quot;):&#160;led.c'],['../message__queue_8c.html#af2a996a587e51f1c9bae9e4d484afc61',1,'BUILD_ASSERT(CONFIG_APP_MESSAGE_QUEUE_MODULE_WATCHDOG_TIMEOUT_SECONDS &gt; CONFIG_APP_MESSAGE_QUEUE_MODULE_MSG_PROCESSING_TIME_SECONDS, &quot;Watchdog timeout must be greater than message processing time&quot;):&#160;message_queue.c'],['../network_8c.html#a7b2dba7d23da63e6b0612fb6bf77097c',1,'BUILD_ASSERT(CONFIG_APP_NETWORK_MODULE_WATCHDOG_TIMEOUT_SECONDS &gt; CONFIG_APP_NETWORK_MODULE_MSG_PROCESSING_TIME_SECONDS, &quot;Watchdog timeout must be greater than message processing time&quot;):&#160;network.c'],['../p__one_8c.html#ac443f384418e78ab17ab43660ffc0ef7',1,'BUILD_ASSERT(CONFIG_APP_P_ONE_MODULE_WATCHDOG_TIMEOUT_SECONDS &gt; CONFIG_APP_P_ONE_MODULE_MSG_PROCESSING_TIME_SECONDS, &quot;Watchdog timeout must be greater than message processing time&quot;):&#160;p_one.c'],['../p__one_8c.html#a3f48fcbc19fe59b24bda25731cea5c00',1,'BUILD_ASSERT(((8191 *(unsigned long)(1000 *1000/(DT_PROP(DT_NODELABEL(uart3), current_speed)/10)+1) *1.1)/1000)&lt;(CONFIG_APP_P_ONE_MODULE_WATCHDOG_TIMEOUT_SECONDS *1000), &quot;UART timeout must be less than watchdog timeout&quot;):&#160;p_one.c'],['../reboot_8c.html#a2a365c51a72d9c96164b785aa1b8e3b7',1,'BUILD_ASSERT(CONFIG_APP_REBOOT_MODULE_WATCHDOG_TIMEOUT_SECONDS &gt; CONFIG_APP_REBOOT_MODULE_MSG_PROCESSING_TIME_SECONDS, &quot;Watchdog timeout must be greater than message processing time&quot;):&#160;reboot.c'],['../timing_8c.html#a9b716235ae4ead084e316689fb2a428c',1,'BUILD_ASSERT(CONFIG_APP_TIMING_MODULE_PUBLISH_OFFSET_SECONDS&lt; CONFIG_APP_TIMING_MODULE_SLOW_INTERVAL_SECONDS, &quot;Publish offset must be less than slow interval&quot;):&#160;timing.c'],['../timing_8c.html#add29ebb1b22f0db1c54b7136f487b62e',1,'BUILD_ASSERT(CONFIG_APP_TIMING_MODULE_SEND_INTERVAL_SECONDS &gt;=CONFIG_APP_TIMING_MODULE_SLOW_INTERVAL_SECONDS, &quot;Send interval should be &gt;= slow interval for buffering&quot;):&#160;timing.c']]],
  ['build_5fcombined_5fenergy_5fjson_39',['build_combined_energy_json',['../message__queue_8c.html#a16e0c8c199c4c428750fd989c79f437b',1,'message_queue.c']]],
  ['bulk_20onboarding_40',['Bulk Onboarding',['../provisioning.html#autotoc_md373',1,'']]],
  ['bulk_20onboarding_20naar_20nrf_20cloud_41',['☁️ Fase 3: Bulk Onboarding naar nRF Cloud',['../provisioning.html#autotoc_md363',1,'']]],
  ['byte_20timeout_42',['2. UART RX Timeout (Inter-byte timeout)',['../p_one_doc.html#autotoc_md219',1,'']]],
  ['byte_20timeout_20392_20ms_43',['Inter-byte Timeout (392 ms)',['../p_one_doc.html#autotoc_md223',1,'']]],
  ['byte_20timeout_20trigger_44',['Scenario 3: Inter-byte Timeout Trigger',['../p_one_doc.html#autotoc_md229',1,'']]]
];
