var searchData=
[
  ['h_0',['Header Files (.h)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md429',1,'']]],
  ['h_20template_1',['Header File (.h) Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md442',1,'']]],
  ['handle_5freboot_5frequest_2',['handle_reboot_request',['../reboot_8c.html#a09d1eebce7f3acb2cf7ec6ede42a8cb8',1,'reboot.c']]],
  ['handle_5fshutdown_5fack_3',['handle_shutdown_ack',['../reboot_8c.html#a9ac6fc80b9d5615ff2ba8b1b66705fcf',1,'reboot.c']]],
  ['handleidingen_4',['📚 Handleidingen',['../index.html#autotoc_md320',1,'']]],
  ['handler_20functions_5',['State Handler Functions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md388',1,'']]],
  ['handlers_6',['Work Queue Handlers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md394',1,'']]],
  ['handling_7',['Handling',['../energy_pulse_doc.html#autotoc_md85',1,'Error Handling'],['../app_doc.html#autotoc_md15',1,'Native Sim Handling']]],
  ['handling_20en_20return_20values_8',['Error Handling en Return Values',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md372',1,'']]],
  ['handling_20periodieke_20triggers_9',['2. ZBUS Message Handling (Periodieke Triggers)',['../p_one_doc.html#autotoc_md200',1,'']]],
  ['hardware_20interaction_10',['Hardware Interaction',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md402',1,'']]],
  ['hardware_20interface_11',['Hardware Interface',['../led_doc.html#autotoc_md113',1,'']]],
  ['hardware_20ondersteuning_12',['🔌 Hardware Ondersteuning',['../index.html#autotoc_md304',1,'']]],
  ['hardware_20watchdog_20als_20safety_20mechanism_13',['Hardware Watchdog als Safety Mechanism',['../app_doc.html#autotoc_md4',1,'']]],
  ['has_5fdata_14',['has_data',['../message__queue_8c.html#a6a0e977ab733be8d10cfdeabb12314b4',1,'message_queue.c']]],
  ['has_5fnew_5fpulses_5fsince_5fsave_15',['has_new_pulses_since_save',['../energy__pulse_8c.html#a0c3e33e28926531c22ff5e7400a9776f',1,'energy_pulse.c']]],
  ['has_5fp1_5fdata_16',['has_p1_data',['../structcombined__energy__msg.html#a385585f54433211b263348a460b2165d',1,'combined_energy_msg']]],
  ['has_5fpulse_5fdata_17',['has_pulse_data',['../structcombined__energy__msg.html#a4b16966a3fbd08bcf2c6cba973bdd708',1,'combined_energy_msg']]],
  ['header_20file_20h_20template_18',['Header File (.h) Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md442',1,'']]],
  ['header_20files_20h_19',['Header Files (.h)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md429',1,'']]],
  ['header_20html_20',['Header HTML (&lt;span class=&quot;tt&quot;&gt;docs/header.html&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md594',1,'']]],
  ['header_20html_20docs_20header_20html_21',['Header HTML (&lt;span class=&quot;tt&quot;&gt;docs/header.html&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md594',1,'']]],
  ['header_20visibility_22',['Header Visibility',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md457',1,'']]],
  ['headers_23',['Headers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md428',1,'Include Guards en Headers'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md437',1,'Sectie Headers']]],
  ['heeft_24',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md467',1,'']]],
  ['herhalingen_20van_20blokken_20code_25',['2. Herhalingen van Blokken Code',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md531',1,'']]],
  ['het_20schrijven_20of_20bewerken_20van_20documentatie_3a_26',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md536',1,'']]],
  ['historische_20referenties_20en_20voor_20na_20vergelijkingen_27',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md532',1,'']]],
  ['history_20commands_20context_28',['Git History Commands (Context)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md575',1,'']]],
  ['hoe_29',['Hoe',['../app_doc.html#autotoc_md9',1,'']]],
  ['hoe_20architectuur_20gedrag_30',['Hoe Architectuur Gedrag',['../energy_pulse_doc.html#autotoc_md82',1,'Hoe? (Architectuur &amp; Gedrag)'],['../led_doc.html#autotoc_md110',1,'Hoe? (Architectuur &amp; Gedrag)'],['../message_queue_doc.html#autotoc_md139',1,'Hoe? (Architectuur &amp; Gedrag)'],['../network_doc.html#autotoc_md174',1,'Hoe? (Architectuur &amp; Gedrag)'],['../reboot_doc.html#autotoc_md246',1,'Hoe? (Architectuur &amp; Gedrag)'],['../timing_doc.html#autotoc_md275',1,'Hoe? (Architectuur &amp; Gedrag)']]],
  ['hook_31',['Modem Initialization Hook',['../network_doc.html#autotoc_md167',1,'']]],
  ['how_20implementatie_32',['How? (Implementatie)',['../cloud_doc.html#autotoc_md31',1,'']]],
  ['html_33',['Header HTML (&lt;span class=&quot;tt&quot;&gt;docs/header.html&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md594',1,'']]],
  ['html_20docs_20header_20html_34',['Header HTML (&lt;span class=&quot;tt&quot;&gt;docs/header.html&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md594',1,'']]],
  ['hw_5fwdt_5fdev_35',['HW_WDT_DEV',['../app_8c.html#a0cc4ea5e0b2cd9b48dcea6c51cf46c54',1,'app.c']]],
  ['hw_5fwdt_5fdev_36',['hw_wdt_dev',['../app_8c.html#a5da63552532df2c76add9942e6fbeec1',1,'app.c']]]
];
