var searchData=
[
  ['garanties_20via_20buffering_0',['Delivery Garanties via Buffering',['../message_queue_doc.html#autotoc_md132',1,'']]],
  ['gas_20meting_20acquisitie_1',['Gas Meting Acquisitie',['../p_one_doc.html#autotoc_md194',1,'']]],
  ['gas_20unit_20clarification_2',['Gas Unit Clarification',['../message_queue_doc.html#autotoc_md151',1,'']]],
  ['gas_5fconsumed_5fm3_3',['gas_consumed_m3',['../structp__one__msg.html#afb8226a2ab2ab6f50ec759e17b76f7f3',1,'p_one_msg']]],
  ['gas_5fm3_5fconsumed_4',['gas_m3_consumed',['../p__one_8c.html#af63330db3054db5e11af8a1b7b170841',1,'p_one.c']]],
  ['gebruik_5',['SYS_INIT Gebruik',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md450',1,'']]],
  ['gebruik_20named_20constants_6',['Gebruik Named Constants',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md502',1,'']]],
  ['gebruiken_7',['Wanneer Gebruiken',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md433',1,'']]],
  ['gecoördineerde_20data_20collectie_8',['Gecoördineerde Data Collectie',['../message_queue_doc.html#autotoc_md131',1,'']]],
  ['gecoördineerde_20data_20collectie_20flow_9',['Gecoördineerde Data Collectie Flow',['../message_queue_doc.html#autotoc_md135',1,'']]],
  ['gecoördineerde_20timing_10',['Gecoördineerde Timing',['../timing_doc.html#autotoc_md267',1,'']]],
  ['gedrag_11',['Gedrag',['../reboot_doc.html#autotoc_md253',1,'Graceful Shutdown Gedrag'],['../energy_pulse_doc.html#autotoc_md82',1,'Hoe? (Architectuur &amp; Gedrag)'],['../led_doc.html#autotoc_md110',1,'Hoe? (Architectuur &amp; Gedrag)'],['../message_queue_doc.html#autotoc_md139',1,'Hoe? (Architectuur &amp; Gedrag)'],['../network_doc.html#autotoc_md174',1,'Hoe? (Architectuur &amp; Gedrag)'],['../reboot_doc.html#autotoc_md246',1,'Hoe? (Architectuur &amp; Gedrag)'],['../timing_doc.html#autotoc_md275',1,'Hoe? (Architectuur &amp; Gedrag)'],['../message_queue_doc.html#autotoc_md153',1,'Queue Overflow Gedrag'],['../energy_pulse_doc.html#autotoc_md84',1,'Runtime Gedrag']]],
  ['gedreven_12',['GPIO Interrupt Gedreven',['../energy_pulse_doc.html#autotoc_md75',1,'']]],
  ['geen_20tabs_13',['Spaties (GEEN Tabs)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md476',1,'']]],
  ['geheugen_20performance_14',['Geheugen Performance',['../energy_pulse_doc.html#autotoc_md89',1,'Geheugen &amp; Performance'],['../timing_doc.html#autotoc_md282',1,'Geheugen &amp; Performance']]],
  ['genereren_15',['1.5 Certificaten Genereren',['../provisioning.html#autotoc_md340',1,'']]],
  ['get_5fqueue_5fusage_16',['get_queue_usage',['../message__queue_8c.html#adca8ee032108f348cf8ea3936481854d',1,'message_queue.c']]],
  ['get_5freboot_5ftype_5fstr_17',['get_reboot_type_str',['../reboot__zbus_8c.html#ade3f3b087041c1ad9a0f490df51df19b',1,'reboot_zbus.c']]],
  ['geverifieerd_20_3a_18',['✅ CORRECT (geverifieerd):',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md541',1,'']]],
  ['git_20history_20commands_20context_19',['Git History Commands (Context)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md575',1,'']]],
  ['gpio_20callbacks_20',['GPIO Callbacks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md404',1,'']]],
  ['gpio_20interrupt_20gedreven_21',['GPIO Interrupt Gedreven',['../energy_pulse_doc.html#autotoc_md75',1,'']]],
  ['gpio_5fcb_22',['gpio_cb',['../energy__pulse_8c.html#a2c1fdb2a55600085d534b2305e5c3385',1,'energy_pulse.c']]],
  ['graceful_20shutdown_23',['Graceful Shutdown',['../index.html#autotoc_md301',1,'🛑 Graceful Shutdown'],['../reboot_doc.html#autotoc_md237',1,'Graceful Shutdown']]],
  ['graceful_20shutdown_20gedrag_24',['Graceful Shutdown Gedrag',['../reboot_doc.html#autotoc_md253',1,'']]],
  ['graphs_25',['📊 Call Graphs',['../index.html#autotoc_md316',1,'']]],
  ['green_26',['green',['../structled__pattern.html#aefbeaf6636b283b65c02a7229da25e36',1,'led_pattern']]],
  ['groepen_20definiëren_27',['Module Groepen Definiëren',['../doxygen_guidelines.html#autotoc_md600',1,'']]],
  ['guards_20en_20headers_28',['Include Guards en Headers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md428',1,'']]],
  ['guidelines_29',['Doxygen Documentatie Guidelines',['../doxygen_guidelines.html',1,'']]]
];
