var searchData=
[
  ['behavior_0',['Watchdog Callback Behavior',['../app_doc.html#autotoc_md14',1,'']]],
  ['behavior_20claims_1',['3.4 Timing &amp;amp; Behavior Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md611',1,'']]],
  ['behavior_20en_20portability_2',['Undefined Behavior en Portability',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md454',1,'']]],
  ['behaviour_3',['6. Intended Behaviour',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md569',1,'']]],
  ['belangrijk_4',['Waarom is dit zo belangrijk?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md590',1,'']]],
  ['belangrijke_20features_5',['⚙️ Belangrijke Features',['../index.html#autotoc_md299',1,'']]],
  ['belangrijke_20links_6',['🔗 Belangrijke Links',['../index.html#autotoc_md315',1,'']]],
  ['benefits_7',['User Experience Benefits',['../led_doc.html#autotoc_md115',1,'']]],
  ['berekening_8',['Timing Berekening',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md446',1,'']]],
  ['beschikbare_20targets_9',['Beschikbare Targets',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md352',1,'']]],
  ['best_20practices_20praktische_20richtlijnen_10',['Best Practices - Praktische Richtlijnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html',1,'']]],
  ['best_2dpractices_2emd_11',['best-practices.md',['../best-practices_8md.html',1,'']]],
  ['bestanden_20structuur_12',['Bestanden Structuur',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md508',1,'']]],
  ['bestandsnaam_20conventie_13',['Bestandsnaam Conventie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md559',1,'']]],
  ['betrouwbaarheid_14',['Betrouwbaarheid',['../energy_pulse_doc.html#autotoc_md90',1,'Betrouwbaarheid'],['../timing_doc.html#autotoc_md280',1,'Betrouwbaarheid'],['../reboot_doc.html#autotoc_md248',1,'Shutdown Betrouwbaarheid']]],
  ['bewerken_20van_20documentatie_3a_15',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md583',1,'']]],
  ['bij_20errors_16',['Logging Bij Errors',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md423',1,'']]],
  ['bij_20het_20schrijven_20of_20bewerken_20van_20documentatie_3a_17',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md583',1,'']]],
  ['blocking_20led_20control_18',['Non-Blocking LED Control',['../led_doc.html#autotoc_md102',1,'']]],
  ['blokken_20code_19',['2. Herhalingen van Blokken Code',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md578',1,'']]],
  ['blue_20',['blue',['../structled__pattern.html#ad4f15da5e81832978bc2fb35d9d64e20',1,'led_pattern']]],
  ['board_21',['Build voor Specifiek Board',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md339',1,'']]],
  ['board_20definitie_22',['🔧 Custom Board Definitie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md355',1,'']]],
  ['board_20definition_23',['Custom Board Definition',['../index.html#autotoc_md307',1,'']]],
  ['board_20not_20found_24',['&quot;Board not found&quot;',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md363',1,'']]],
  ['bool_20checks_25',['Bool Checks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md554',1,'']]],
  ['boot_20confirmation_26',['Boot Confirmation',['../cloud_doc.html#autotoc_md32',1,'']]],
  ['boot_20confirmation_20window_27',['Boot Confirmation Window',['../cloud_doc.html#autotoc_md58',1,'']]],
  ['boot_20loop_20protection_28',['Boot Loop Protection',['../cloud_doc.html#autotoc_md39',1,'']]],
  ['bouwen_29',['1.4 Modem Shell (MoSh) Bouwen',['../provisioning.html#autotoc_md385',1,'']]],
  ['brace_20style_30',['Brace Style',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md525',1,'']]],
  ['branding_31',['🎨 Styling &amp;amp; Branding',['../doxygen_guidelines.html#autotoc_md639',1,'']]],
  ['broken_20links_32',['❗ Broken Links',['../group__Titel.html#autotoc_md659',1,'']]],
  ['buffer_20overflow_20prevention_33',['Buffer Overflow Prevention',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md470',1,'']]],
  ['buffer_20size_20constraint_34',['Buffer Size Constraint',['../p_one_doc.html#autotoc_md224',1,'']]],
  ['buffering_35',['Delivery Garanties via Buffering',['../message_queue_doc.html#autotoc_md128',1,'']]],
  ['buffers_36',['Arrays en Buffers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md544',1,'']]],
  ['build_37',['Build',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md337',1,'Clean Build'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md338',1,'Debug Build'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md336',1,'Standard Build']]],
  ['build_20cache_20corrupt_38',['&quot;Build cache corrupt&quot;',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md364',1,'']]],
  ['build_20code_20inventory_20objectieve_20waarheid_39',['Fase 1: Build Code Inventory (Objectieve Waarheid)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md600',1,'']]],
  ['build_20de_20dinnis_20application_40',['Build de Dinnis Application',['../provisioning.html#autotoc_md403',1,'']]],
  ['build_20instructies_41',['🏗️ Build Instructies',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md335',1,'']]],
  ['build_20systeem_42',['Build Systeem',['../index.html#autotoc_md306',1,'']]],
  ['build_20system_43',['🛠️ Build System',['../group__Titel.html#autotoc_md652',1,'']]],
  ['build_20targets_44',['📊 Build Targets',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md351',1,'']]],
  ['build_20troubleshooting_45',['📝 Build Troubleshooting',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md361',1,'']]],
  ['build_20validation_46',['Build Validation',['../cloud_doc.html#autotoc_md51',1,'']]],
  ['build_20voor_20specifiek_20board_47',['Build voor Specifiek Board',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md339',1,'']]],
  ['build_5fassert_48',['BUILD_ASSERT',['../cloud_8c.html#ab532862c61299bd0b47021aa0f87e486',1,'BUILD_ASSERT(CONFIG_APP_CLOUD_MODULE_WATCHDOG_TIMEOUT_SECONDS &gt; CONFIG_APP_CLOUD_MODULE_MSG_PROCESSING_TIME_SECONDS, &quot;Cloud watchdog timeout must be greater than message processing time&quot;):&#160;cloud.c'],['../energy__pulse_8c.html#a6f5d7596cae44d6b771c19d31ab2ee88',1,'BUILD_ASSERT(CONFIG_APP_ENERGY_PULSE_MODULE_WATCHDOG_TIMEOUT_SECONDS &gt; CONFIG_APP_ENERGY_PULSE_MODULE_MSG_PROCESSING_TIME_SECONDS, &quot;Watchdog timeout must be greater than message processing time&quot;):&#160;energy_pulse.c'],['../led_8c.html#a594fa21d5414cf92769b88318aae5eb8',1,'BUILD_ASSERT(CONFIG_LED_MODULE_WATCHDOG_TIMEOUT_SECONDS &gt; CONFIG_LED_MODULE_MSG_PROCESSING_TIME_SECONDS, &quot;LED watchdog timeout must be greater than message processing time&quot;):&#160;led.c'],['../message__queue_8c.html#af2a996a587e51f1c9bae9e4d484afc61',1,'BUILD_ASSERT(CONFIG_APP_MESSAGE_QUEUE_MODULE_WATCHDOG_TIMEOUT_SECONDS &gt; CONFIG_APP_MESSAGE_QUEUE_MODULE_MSG_PROCESSING_TIME_SECONDS, &quot;Watchdog timeout must be greater than message processing time&quot;):&#160;message_queue.c'],['../network_8c.html#a7b2dba7d23da63e6b0612fb6bf77097c',1,'BUILD_ASSERT(CONFIG_APP_NETWORK_MODULE_WATCHDOG_TIMEOUT_SECONDS &gt; CONFIG_APP_NETWORK_MODULE_MSG_PROCESSING_TIME_SECONDS, &quot;Watchdog timeout must be greater than message processing time&quot;):&#160;network.c'],['../p__one_8c.html#ac443f384418e78ab17ab43660ffc0ef7',1,'BUILD_ASSERT(CONFIG_APP_P_ONE_MODULE_WATCHDOG_TIMEOUT_SECONDS &gt; CONFIG_APP_P_ONE_MODULE_MSG_PROCESSING_TIME_SECONDS, &quot;Watchdog timeout must be greater than message processing time&quot;):&#160;p_one.c'],['../p__one_8c.html#a3f48fcbc19fe59b24bda25731cea5c00',1,'BUILD_ASSERT(((8191 *(unsigned long)(1000 *1000/(DT_PROP(DT_NODELABEL(uart3), current_speed)/10)+1) *1.1)/1000)&lt;(CONFIG_APP_P_ONE_MODULE_WATCHDOG_TIMEOUT_SECONDS *1000), &quot;UART timeout must be less than watchdog timeout&quot;):&#160;p_one.c'],['../reboot_8c.html#a2a365c51a72d9c96164b785aa1b8e3b7',1,'BUILD_ASSERT(CONFIG_APP_REBOOT_MODULE_WATCHDOG_TIMEOUT_SECONDS &gt; CONFIG_APP_REBOOT_MODULE_MSG_PROCESSING_TIME_SECONDS, &quot;Watchdog timeout must be greater than message processing time&quot;):&#160;reboot.c'],['../timing_8c.html#a9b716235ae4ead084e316689fb2a428c',1,'BUILD_ASSERT(CONFIG_APP_TIMING_MODULE_PUBLISH_OFFSET_SECONDS&lt; CONFIG_APP_TIMING_MODULE_SLOW_INTERVAL_SECONDS, &quot;Publish offset must be less than slow interval&quot;):&#160;timing.c'],['../timing_8c.html#add29ebb1b22f0db1c54b7136f487b62e',1,'BUILD_ASSERT(CONFIG_APP_TIMING_MODULE_SEND_INTERVAL_SECONDS &gt;=CONFIG_APP_TIMING_MODULE_SLOW_INTERVAL_SECONDS, &quot;Send interval should be &gt;= slow interval for buffering&quot;):&#160;timing.c']]],
  ['build_5fcombined_5fenergy_5fjson_49',['build_combined_energy_json',['../message__queue_8c.html#a16e0c8c199c4c428750fd989c79f437b',1,'message_queue.c']]],
  ['builds_20mcuboot_20app_50',['Multi-Image Builds (MCUboot + App)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md368',1,'']]],
  ['bulk_20onboarding_51',['Bulk Onboarding',['../provisioning.html#autotoc_md416',1,'']]],
  ['bulk_20onboarding_20naar_20nrf_20cloud_52',['☁️ Fase 3: Bulk Onboarding naar nRF Cloud',['../provisioning.html#autotoc_md406',1,'']]],
  ['byte_20timeout_53',['2. UART RX Timeout (Inter-byte timeout)',['../p_one_doc.html#autotoc_md211',1,'']]],
  ['byte_20timeout_20392_20ms_54',['Inter-byte Timeout (392 ms)',['../p_one_doc.html#autotoc_md215',1,'']]],
  ['byte_20timeout_20trigger_55',['Scenario 3: Inter-byte Timeout Trigger',['../p_one_doc.html#autotoc_md221',1,'']]]
];
