var searchData=
[
  ['waarde_0',['LED Feedback Waarde',['../led_doc.html#autotoc_md114',1,'']]],
  ['waarheid_1',['Fase 1: Build Code Inventory (Objectieve Waarheid)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md549',1,'']]],
  ['waarom_2',['Waarom',['../app_doc.html#autotoc_md3',1,'']]],
  ['waarom_20design_20rationale_3',['Waarom Design Rationale',['../message_queue_doc.html#autotoc_md126',1,'Waarom? (Design Rationale)'],['../network_doc.html#autotoc_md161',1,'Waarom? (Design Rationale)']]],
  ['waarom_20dit_20protocol_4',['5.1 Waarom dit Protocol?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md544',1,'']]],
  ['waarom_20integer_20fixed_20point_5',['Waarom Integer Fixed-Point?',['../p_one_doc.html#autotoc_md199',1,'']]],
  ['waarom_20is_20dit_20zo_20belangrijk_6',['Waarom is dit zo belangrijk?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md539',1,'']]],
  ['waarom_20motivatie_7',['Waarom? (Motivatie)',['../cloud_doc.html#autotoc_md22',1,'']]],
  ['waarom_20probleem_20motivatie_8',['Waarom Probleem Motivatie',['../energy_pulse_doc.html#autotoc_md73',1,'Waarom? (Probleem &amp; Motivatie)'],['../led_doc.html#autotoc_md100',1,'Waarom? (Probleem &amp; Motivatie)'],['../reboot_doc.html#autotoc_md232',1,'Waarom? (Probleem &amp; Motivatie)'],['../timing_doc.html#autotoc_md262',1,'Waarom? (Probleem &amp; Motivatie)']]],
  ['wanneer_20gebruiken_9',['Wanneer Gebruiken',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md429',1,'']]],
  ['warning_3a_20intentional_20crash_10',['Rollback Test (Warning: Intentional Crash)',['../cloud_doc.html#autotoc_md53',1,'']]],
  ['wat_11',['Wat',['../app_doc.html#autotoc_md6',1,'']]],
  ['wat_20er_20niet_20in_20moet_12',['❗ Wat ER NIET in moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md525',1,'']]],
  ['wat_20er_20wel_20in_20moet_13',['✅ Wat ER WEL in moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md512',1,'']]],
  ['wat_20functionaliteit_14',['Wat? (Functionaliteit)',['../cloud_doc.html#autotoc_md26',1,'']]],
  ['wat_20functionaliteit_20data_20flow_15',['Wat Functionaliteit Data Flow',['../energy_pulse_doc.html#autotoc_md77',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../led_doc.html#autotoc_md104',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../message_queue_doc.html#autotoc_md130',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../network_doc.html#autotoc_md165',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../reboot_doc.html#autotoc_md236',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../timing_doc.html#autotoc_md266',1,'Wat? (Functionaliteit &amp; Data Flow)']]],
  ['watchdog_16',['Watchdog',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md392',1,'Task Watchdog'],['../p_one_doc.html#autotoc_md202',1,'Timing &amp; Watchdog']]],
  ['watchdog_20als_20safety_20mechanism_17',['Hardware Watchdog als Safety Mechanism',['../app_doc.html#autotoc_md4',1,'']]],
  ['watchdog_20callback_20behavior_18',['Watchdog Callback Behavior',['../app_doc.html#autotoc_md14',1,'']]],
  ['watchdog_20indien_20module_20eigen_20thread_20heeft_19',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md463',1,'']]],
  ['watchdog_20relationship_20',['Watchdog Relationship',['../p_one_doc.html#autotoc_md223',1,'']]],
  ['watchdog_5finit_21',['watchdog_init',['../app_8c.html#a77f632fe498946ff94d869ff8acdd21c',1,'app.c']]],
  ['wel_20in_20moet_22',['✅ Wat ER WEL in moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md512',1,'']]],
  ['whole_23',['whole',['../structobis__fixed__point__t.html#a1e7ff764f46fc123bd4a2f164e35770f',1,'obis_fixed_point_t']]],
  ['why_20these_20specific_20timeouts_20matter_24',['Why These Specific Timeouts Matter',['../p_one_doc.html#autotoc_md213',1,'']]],
  ['wijziging_3a_25',['Checklist voor elke documentatie wijziging:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md538',1,'']]],
  ['window_26',['Boot Confirmation Window',['../cloud_doc.html#autotoc_md58',1,'']]],
  ['windows_27',['Priority 2: Scheduled FOTA Windows',['../cloud_doc.html#autotoc_md62',1,'']]],
  ['work_20pattern_28',['Periodic Work Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md410',1,'']]],
  ['work_20queue_20handlers_29',['Work Queue Handlers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md390',1,'']]],
  ['work_20queue_20pattern_30',['Work Queue Pattern',['../reboot_doc.html#autotoc_md246',1,'']]],
  ['workflow_205_20fasen_31',['5.4 Verification Workflow (5 Fasen)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md567',1,'']]]
];
