var searchData=
[
  ['validatie_0',['Validatie',['../p_one_doc.html#autotoc_md114',1,'CRC16 Validatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md352',1,'NULL Checks en Validatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md353',1,'Pointer Validatie']]],
  ['validation_1',['Input Validation',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md269',1,'']]],
  ['value_2',['value',['../p__one_8c.html#a354b99b030bdfe136490f848c05d4788',1,'p_one.c']]],
  ['value_20conventies_3',['Return Value Conventies',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md222',1,'']]],
  ['value_5fformat_4',['value_format',['../structobis__code__entry__t.html#af46c15f3b998059fb2fcc7fe1f421556',1,'obis_code_entry_t']]],
  ['values_5',['Error Handling en Return Values',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md219',1,'']]],
  ['van_20_5fdoc_20md_6',['Structuur van &lt;span class=&quot;tt&quot;&gt;&amp;lt;module&amp;gt;_doc.md&lt;/span&gt;',['../doxygen_guidelines.html#autotoc_md444',1,'']]],
  ['van_20andere_20modules_7',['10. Afhankelijkheden van Andere Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md373',1,'']]],
  ['van_20blokken_20code_8',['2. Herhalingen van Blokken Code',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md378',1,'']]],
  ['van_20documentatie_3a_9',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md383',1,'']]],
  ['van_20dsmr_20meters_10',['Data Acquisitie van DSMR Meters',['../p_one_doc.html#autotoc_md98',1,'']]],
  ['van_20fouten_20door_20niet_20te_20verifiëren_3a_11',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md386',1,'']]],
  ['variabelen_12',['Variabelen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md330',1,'']]],
  ['variable_20declaratie_13',['Error Variable Declaratie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md220',1,'']]],
  ['variable_20declarations_14',['Variable Declarations',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md341',1,'']]],
  ['verantwoordelijkheden_15',['2. Doel en Verantwoordelijkheden',['../app_doc.html#autotoc_md3',1,'']]],
  ['verboden_3a_16',['❗ VERBODEN:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md385',1,'']]],
  ['vereisten_20voor_20modules_17',['Implementatie Vereisten voor Modules',['../md_modules_2reboot_2reboot__doc.html#autotoc_md157',1,'']]],
  ['vergelijkingen_18',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md379',1,'']]],
  ['verifiëren_3a_19',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md386',1,'']]],
  ['verificatie_20en_20synchronisatie_20kritiek_20⚠️_20',['4. Code Verificatie en Synchronisatie (KRITIEK! ⚠️)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md381',1,'']]],
  ['verificatie_20per_20claim_20type_21',['Fase 3: Systematische Verificatie Per Claim Type',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md404',1,'']]],
  ['verificatie_20protocol_22',['5. AI Agent Documentatie Verificatie Protocol',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md394',1,'']]],
  ['verificatie_20strategie_23',['5.3 Systematische Verificatie Strategie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md399',1,'']]],
  ['verification_20shortcuts_24',['Verification Shortcuts',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md423',1,'']]],
  ['verification_20workflow_205_20fasen_25',['5.4 Verification Workflow (5 Fasen)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md418',1,'']]],
  ['verplichte_20stappen_3a_26',['✅ VERPLICHTE STAPPEN:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md384',1,'']]],
  ['version_27',['version',['../p__one_8c.html#af1c7e5e925151edc04c2424009ab7892',1,'p_one.c']]],
  ['verwerking_28',['📊 Data Verwerking',['../index.html#autotoc_md195',1,'']]],
  ['verzending_20naar_20de_20cloud_29',['� Data Verzending naar de Cloud',['../index.html#autotoc_md187',1,'']]],
  ['verzinnen_30',['Principe: NOOIT iets verzinnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md382',1,'']]],
  ['verzonnen_20content_20_3a_31',['❗ FOUT (verzonnen content):',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md387',1,'']]],
  ['visibility_32',['Header Visibility',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md304',1,'']]],
  ['visueel_20overzicht_33',['Visueel Overzicht',['../index.html#autotoc_md183',1,'']]],
  ['visuele_20feedback_20voor_20iot_20device_34',['Visuele Feedback voor IoT Device',['../led_doc.html#autotoc_md63',1,'']]],
  ['void_20vs_20int_20return_35',['Void vs Int Return',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md224',1,'']]],
  ['volgorde_36',['Volgorde',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html',1,'Code Structure - Organisatie en Volgorde'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md282',1,'Volgorde']]],
  ['volgorde_37',['Standaard Secties (in volgorde)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md285',1,'']]],
  ['voor_20documentatie_20review_20sessie_38',['5.6 Checklist: Voor Documentatie Review Sessie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md425',1,'']]],
  ['voor_20elke_20documentatie_20wijziging_3a_39',['Checklist voor elke documentatie wijziging:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md389',1,'']]],
  ['voor_20immediate_20scheduling_40',['K_NO_WAIT voor Immediate Scheduling',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md239',1,'']]],
  ['voor_20iot_20device_41',['Visuele Feedback voor IoT Device',['../led_doc.html#autotoc_md63',1,'']]],
  ['voor_20modules_42',['voor Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md300',1,'CMakeLists.txt voor Modules'],['../md_modules_2reboot_2reboot__doc.html#autotoc_md157',1,'Implementatie Vereisten voor Modules']]],
  ['voor_20na_20vergelijkingen_43',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md379',1,'']]],
  ['voor_20nieuwe_20module_44',['Checklist voor Nieuwe Module',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md247',1,'']]],
  ['voorbeelden_45',['Voorbeelden',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md377',1,'1. Code Implementatie Voorbeelden'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md421',1,'Code Analysis Commands (Voorbeelden)']]],
  ['voorbeelden_20van_20fouten_20door_20niet_20te_20verifiëren_3a_46',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md386',1,'']]],
  ['voordelen_47',['Remote Support Voordelen',['../led_doc.html#autotoc_md76',1,'']]],
  ['vs_20define_48',['enum vs define',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md348',1,'']]],
  ['vs_20definitions_49',['Channel Declarations vs Definitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md294',1,'']]],
  ['vs_20geforceerde_20shutdown_50',['Graceful vs. Geforceerde Shutdown',['../md_modules_2reboot_2reboot__doc.html#autotoc_md156',1,'']]],
  ['vs_20int_20return_51',['Void vs Int Return',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md224',1,'']]]
];
