var searchData=
[
  ['iets_20verzinnen_0',['Principe: NOOIT iets verzinnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md535',1,'']]],
  ['image_1',['Corrupte Firmware Image',['../cloud_doc.html#autotoc_md37',1,'']]],
  ['imei_20lijst_20verkrijgen_2',['1.6 IMEI Lijst Verkrijgen',['../provisioning.html#autotoc_md342',1,'']]],
  ['imei_20programmeren_3',['2.1 IMEI Programmeren',['../provisioning.html#autotoc_md345',1,'']]],
  ['imei_20schrijven_20via_20rtt_4',['Stap 4: IMEI Schrijven via RTT',['../provisioning.html#autotoc_md349',1,'']]],
  ['immediate_20scheduling_5',['K_NO_WAIT voor Immediate Scheduling',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md392',1,'']]],
  ['impact_6',['Impact',['../energy_pulse_doc.html#autotoc_md88',1,'Resultaten &amp; Impact'],['../timing_doc.html#autotoc_md281',1,'Resultaten &amp; Impact']]],
  ['implementatie_7',['How? (Implementatie)',['../cloud_doc.html#autotoc_md31',1,'']]],
  ['implementatie_20design_20rationale_8',['2. Implementatie Design Rationale',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md518',1,'']]],
  ['implementatie_20vereisten_9',['Module Shutdown Implementatie Vereisten',['../reboot_doc.html#autotoc_md257',1,'']]],
  ['implementatie_20voorbeelden_10',['1. Code Implementatie Voorbeelden',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md530',1,'']]],
  ['implementation_11',['Pattern Implementation',['../led_doc.html#autotoc_md114',1,'']]],
  ['in_20c_20files_12',['Include Order (in .c files)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md430',1,'']]],
  ['in_20moet_13',['in moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md516',1,'✅ Wat ER WEL in moet'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md529',1,'❗ Wat ER NIET in moet']]],
  ['in_20parent_20cmakelists_14',['Integration in Parent CMakeLists',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md458',1,'']]],
  ['in_20thread_15',['Message Processing in Thread',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md384',1,'']]],
  ['in_20volgorde_16',['Standaard Secties (in volgorde)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md438',1,'']]],
  ['inbound_20fota_20requires_17',['Inbound (FOTA Requires)',['../cloud_doc.html#autotoc_md42',1,'']]],
  ['include_20guards_20en_20headers_18',['Include Guards en Headers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md428',1,'']]],
  ['include_20order_20in_20c_20files_19',['Include Order (in .c files)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md430',1,'']]],
  ['inconsistente_20titel_20formaten_20',['❗ Inconsistente Titel Formaten',['../group__Titel.html#autotoc_md611',1,'']]],
  ['indentatie_20en_20formattering_21',['Indentatie en Formattering',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md475',1,'']]],
  ['indien_20module_20eigen_20thread_20heeft_22',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md467',1,'']]],
  ['initialisatie_23',['Initialisatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md449',1,'Module Initialisatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md464',1,'Module Initialisatie']]],
  ['initialisatie_20sequence_24',['Initialisatie Sequence',['../energy_pulse_doc.html#autotoc_md83',1,'']]],
  ['initialisatie_20volgorde_25',['Initialisatie Volgorde',['../app_doc.html#autotoc_md12',1,'']]],
  ['initialization_26',['Initialization',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md495',1,'']]],
  ['initialization_20details_27',['Modem Initialization Details',['../network_doc.html#autotoc_md177',1,'']]],
  ['initialization_20hook_28',['Modem Initialization Hook',['../network_doc.html#autotoc_md167',1,'']]],
  ['input_20validation_29',['Input Validation',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md422',1,'']]],
  ['insights_20lessons_20learned_30',['5.7 Key Insights &amp;amp; Lessons Learned',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md580',1,'']]],
  ['installeren_31',['2.2 Certificaten Installeren',['../provisioning.html#autotoc_md351',1,'']]],
  ['int_20return_32',['Void vs Int Return',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md377',1,'']]],
  ['integer_20fixed_20point_33',['Waarom Integer Fixed-Point?',['../p_one_doc.html#autotoc_md203',1,'']]],
  ['integratie_34',['Integratie',['../index.html#autotoc_md306',1,'☁️ Cloud Integratie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md451',1,'Kconfig Integratie'],['../p_one_doc.html#autotoc_md195',1,'ZBUS Integratie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md463',1,'ZBUS Integratie']]],
  ['integration_35',['Integration',['../cloud_doc.html#autotoc_md29',1,'LED Integration'],['../network_doc.html#autotoc_md176',1,'Zephyr Connection Manager Integration']]],
  ['integration_20in_20parent_20cmakelists_36',['Integration in Parent CMakeLists',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md458',1,'']]],
  ['intended_20behaviour_37',['6. Intended Behaviour',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md522',1,'']]],
  ['intentional_20crash_38',['Rollback Test (Warning: Intentional Crash)',['../cloud_doc.html#autotoc_md53',1,'']]],
  ['inter_20byte_20timeout_39',['2. UART RX Timeout (Inter-byte timeout)',['../p_one_doc.html#autotoc_md215',1,'']]],
  ['inter_20byte_20timeout_20392_20ms_40',['Inter-byte Timeout (392 ms)',['../p_one_doc.html#autotoc_md219',1,'']]],
  ['inter_20byte_20timeout_20trigger_41',['Scenario 3: Inter-byte Timeout Trigger',['../p_one_doc.html#autotoc_md225',1,'']]],
  ['interacties_42',['🔄 Data Flow &amp;amp; Module Interacties',['../index.html#autotoc_md293',1,'']]],
  ['interaction_43',['Hardware Interaction',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md402',1,'']]],
  ['interface_44',['Interface',['../led_doc.html#autotoc_md113',1,'Hardware Interface'],['../app_doc.html#autotoc_md8',1,'ZBUS Interface']]],
  ['interface_20contract_45',['External Interface Contract',['../message_queue_doc.html#autotoc_md145',1,'']]],
  ['interfaces_46',['Interfaces',['../energy_pulse_doc.html#autotoc_md80',1,'ZBUS Interfaces'],['../led_doc.html#autotoc_md106',1,'ZBUS Interfaces'],['../message_queue_doc.html#autotoc_md136',1,'ZBUS Interfaces'],['../network_doc.html#autotoc_md171',1,'ZBUS Interfaces']]],
  ['interrupt_20gedreven_47',['GPIO Interrupt Gedreven',['../energy_pulse_doc.html#autotoc_md75',1,'']]],
  ['inventory_20objectieve_20waarheid_48',['Fase 1: Build Code Inventory (Objectieve Waarheid)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md553',1,'']]],
  ['investigation_49',['5.2 Fundamenteel Principe: Code-First Investigation',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md550',1,'']]],
  ['iot_20device_50',['Visuele Feedback voor IoT Device',['../led_doc.html#autotoc_md101',1,'']]],
  ['is_20dit_20zo_20belangrijk_51',['Waarom is dit zo belangrijk?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md543',1,'']]],
  ['is_5fcloud_5fready_52',['is_cloud_ready',['../message__queue_8c.html#a6f1182cd9184295f68d09c18dc04ba36',1,'message_queue.c']]],
  ['is_5fqueue_5fempty_53',['is_queue_empty',['../message__queue_8c.html#a0a18dae9147827c899adc85732e672cd',1,'message_queue.c']]]
];
