var searchData=
[
  ['v2_200_203_0',['Download Modem Firmware v2.0.3',['../provisioning.html#autotoc_md331',1,'']]],
  ['v2_203_208_1',['Download PTI Modem Firmware v2.3.8',['../provisioning.html#autotoc_md332',1,'']]],
  ['validatie_2',['Validatie',['../p_one_doc.html#autotoc_md200',1,'CRC16 Validatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md501',1,'NULL Checks en Validatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md502',1,'Pointer Validatie']]],
  ['validation_3',['Validation',['../cloud_doc.html#autotoc_md51',1,'Build Validation'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md418',1,'Input Validation']]],
  ['value_4',['value',['../p__one_8c.html#a354b99b030bdfe136490f848c05d4788',1,'p_one.c']]],
  ['value_20conventies_5',['Return Value Conventies',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md371',1,'']]],
  ['value_5fformat_6',['value_format',['../structobis__code__entry__t.html#af46c15f3b998059fb2fcc7fe1f421556',1,'obis_code_entry_t']]],
  ['values_7',['Error Handling en Return Values',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md368',1,'']]],
  ['van_20_5fdoc_20md_8',['Structuur van &lt;span class=&quot;tt&quot;&gt;&amp;lt;module&amp;gt;_doc.md&lt;/span&gt;',['../doxygen_guidelines.html#autotoc_md593',1,'']]],
  ['van_20andere_20modules_9',['10. Afhankelijkheden van Andere Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md522',1,'']]],
  ['van_20blokken_20code_10',['2. Herhalingen van Blokken Code',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md527',1,'']]],
  ['van_20documentatie_3a_11',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md532',1,'']]],
  ['van_20dsmr_20meters_12',['Data Acquisitie van DSMR Meters',['../p_one_doc.html#autotoc_md185',1,'']]],
  ['van_20fouten_20door_20niet_20te_20verifiëren_3a_13',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md535',1,'']]],
  ['variabelen_14',['Variabelen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md479',1,'']]],
  ['variable_20declaratie_15',['Error Variable Declaratie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md369',1,'']]],
  ['variable_20declarations_16',['Variable Declarations',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md490',1,'']]],
  ['verboden_3a_17',['❗ VERBODEN:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md534',1,'']]],
  ['vereisten_18',['Module Shutdown Implementatie Vereisten',['../reboot_doc.html#autotoc_md253',1,'']]],
  ['vergelijkingen_19',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md528',1,'']]],
  ['verifiëren_3a_20',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md535',1,'']]],
  ['verificatie_20en_20synchronisatie_20kritiek_20⚠️_21',['4. Code Verificatie en Synchronisatie (KRITIEK! ⚠️)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md530',1,'']]],
  ['verificatie_20per_20claim_20type_22',['Fase 3: Systematische Verificatie Per Claim Type',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md553',1,'']]],
  ['verificatie_20protocol_23',['5. AI Agent Documentatie Verificatie Protocol',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md543',1,'']]],
  ['verificatie_20strategie_24',['5.3 Systematische Verificatie Strategie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md548',1,'']]],
  ['verification_20shortcuts_25',['Verification Shortcuts',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md572',1,'']]],
  ['verification_20workflow_205_20fasen_26',['5.4 Verification Workflow (5 Fasen)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md567',1,'']]],
  ['verkrijgen_27',['1.6 IMEI Lijst Verkrijgen',['../provisioning.html#autotoc_md338',1,'']]],
  ['verplichte_20stappen_3a_28',['✅ VERPLICHTE STAPPEN:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md533',1,'']]],
  ['version_29',['version',['../p__one_8c.html#af1c7e5e925151edc04c2424009ab7892',1,'p_one.c']]],
  ['verwerking_30',['📊 Data Verwerking',['../index.html#autotoc_md301',1,'']]],
  ['verzend_20logica_31',['Verzend Logica',['../message_queue_doc.html#autotoc_md138',1,'']]],
  ['verzinnen_32',['Principe: NOOIT iets verzinnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md531',1,'']]],
  ['verzonnen_20content_20_3a_33',['❗ FOUT (verzonnen content):',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md536',1,'']]],
  ['via_20buffering_34',['Delivery Garanties via Buffering',['../message_queue_doc.html#autotoc_md128',1,'']]],
  ['via_20rtt_35',['Stap 4: IMEI Schrijven via RTT',['../provisioning.html#autotoc_md345',1,'']]],
  ['visibility_36',['Header Visibility',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md453',1,'']]],
  ['visueel_20overzicht_37',['Visueel Overzicht',['../index.html#autotoc_md290',1,'']]],
  ['visuele_20feedback_20voor_20iot_20device_38',['Visuele Feedback voor IoT Device',['../led_doc.html#autotoc_md101',1,'']]],
  ['voer_20onboarding_20uit_39',['Voer Onboarding Uit',['../provisioning.html#autotoc_md358',1,'']]],
  ['void_20vs_20int_20return_40',['Void vs Int Return',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md373',1,'']]],
  ['volgorde_41',['Volgorde',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html',1,'Code Structure - Organisatie en Volgorde'],['../app_doc.html#autotoc_md12',1,'Initialisatie Volgorde'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md431',1,'Volgorde']]],
  ['volgorde_42',['Standaard Secties (in volgorde)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md434',1,'']]],
  ['voor_20documentatie_20review_20sessie_43',['5.6 Checklist: Voor Documentatie Review Sessie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md574',1,'']]],
  ['voor_20elke_20documentatie_20wijziging_3a_44',['Checklist voor elke documentatie wijziging:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md538',1,'']]],
  ['voor_20immediate_20scheduling_45',['K_NO_WAIT voor Immediate Scheduling',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md388',1,'']]],
  ['voor_20iot_20device_46',['Visuele Feedback voor IoT Device',['../led_doc.html#autotoc_md101',1,'']]],
  ['voor_20modules_47',['CMakeLists.txt voor Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md449',1,'']]],
  ['voor_20na_20vergelijkingen_48',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md528',1,'']]],
  ['voor_20nieuwe_20module_49',['Checklist voor Nieuwe Module',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md396',1,'']]],
  ['voorbeelden_50',['Voorbeelden',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md526',1,'1. Code Implementatie Voorbeelden'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md570',1,'Code Analysis Commands (Voorbeelden)']]],
  ['voorbeelden_20van_20fouten_20door_20niet_20te_20verifiëren_3a_51',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md535',1,'']]],
  ['voordelen_52',['Remote Support Voordelen',['../led_doc.html#autotoc_md116',1,'']]],
  ['vs_20define_53',['enum vs define',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md497',1,'']]],
  ['vs_20definitions_54',['Channel Declarations vs Definitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md443',1,'']]],
  ['vs_20int_20return_55',['Void vs Int Return',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md373',1,'']]]
];
