var searchData=
[
  ['gas_20meting_20acquisitie_0',['Gas Meting Acquisitie',['../p_one_doc.html#autotoc_md104',1,'']]],
  ['gebruik_1',['SYS_INIT Gebruik',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md297',1,'']]],
  ['gebruik_20named_20constants_2',['Gebruik Named Constants',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md349',1,'']]],
  ['gebruiken_3',['Wanneer Gebruiken',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md280',1,'']]],
  ['gecoördineerde_20timing_4',['Gecoördineerde Timing',['../md_modules_2timing_2timing__doc.html#autotoc_md163',1,'']]],
  ['gedrag_5',['Gedrag',['../md_modules_2reboot_2reboot__doc.html#autotoc_md150',1,'Architectuur en Gedrag'],['../md_modules_2timing_2timing__doc.html#autotoc_md168',1,'Architectuur en Gedrag'],['../energy_pulse_doc.html#autotoc_md44',1,'Hoe? (Architectuur &amp; Gedrag)'],['../led_doc.html#autotoc_md71',1,'Hoe? (Architectuur &amp; Gedrag)'],['../energy_pulse_doc.html#autotoc_md46',1,'Runtime Gedrag']]],
  ['geen_20tabs_6',['Spaties (GEEN Tabs)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md323',1,'']]],
  ['geforceerde_20shutdown_7',['Graceful vs. Geforceerde Shutdown',['../md_modules_2reboot_2reboot__doc.html#autotoc_md156',1,'']]],
  ['geheugen_20en_20performance_8',['Geheugen en Performance',['../md_modules_2timing_2timing__doc.html#autotoc_md174',1,'']]],
  ['geheugen_20performance_9',['Geheugen &amp;amp; Performance',['../energy_pulse_doc.html#autotoc_md51',1,'']]],
  ['geobserveerde_20kanalen_10',['Geobserveerde Kanalen',['../cloud_doc.html#autotoc_md30',1,'4.1 Geobserveerde Kanalen'],['../app_doc.html#autotoc_md11',1,'4.2 Geobserveerde Kanalen']]],
  ['gepubliceerde_20kanalen_11',['Gepubliceerde Kanalen',['../app_doc.html#autotoc_md10',1,'4.1 Gepubliceerde Kanalen'],['../cloud_doc.html#autotoc_md31',1,'4.2 Gepubliceerde Kanalen']]],
  ['gerelateerde_20modules_12',['Gerelateerde Modules',['../md_modules_2timing_2timing__doc.html#autotoc_md176',1,'']]],
  ['geverifieerd_20_3a_13',['✅ CORRECT (geverifieerd):',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md388',1,'']]],
  ['git_20history_20commands_20context_14',['Git History Commands (Context)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md422',1,'']]],
  ['gpio_20callbacks_15',['GPIO Callbacks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md251',1,'']]],
  ['gpio_20data_20request_20pin_20inverterende_20buffer_16',['GPIO Data Request Pin &amp;amp; Inverterende Buffer',['../p_one_doc.html#autotoc_md101',1,'']]],
  ['graceful_20shutdown_17',['🛑 Graceful Shutdown',['../index.html#autotoc_md191',1,'']]],
  ['graceful_20vs_20geforceerde_20shutdown_18',['Graceful vs. Geforceerde Shutdown',['../md_modules_2reboot_2reboot__doc.html#autotoc_md156',1,'']]],
  ['grand_5fparent_3a_20design_19',['grand_parent: Design',['../md_modules_2network_2network__doc.html#autotoc_md81',1,'grand_parent: Design'],['../md_modules_2reboot_2reboot__doc.html#autotoc_md141',1,'grand_parent: Design'],['../md_modules_2timing_2timing__doc.html#autotoc_md158',1,'grand_parent: Design']]],
  ['graphs_20',['📊 Call Graphs',['../index.html#autotoc_md206',1,'']]],
  ['groepen_20definiëren_21',['Module Groepen Definiëren',['../doxygen_guidelines.html#autotoc_md447',1,'']]],
  ['guards_20en_20headers_22',['Include Guards en Headers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md275',1,'']]],
  ['guidelines_23',['Doxygen Documentatie Guidelines',['../doxygen_guidelines.html',1,'']]]
];
