var searchData=
[
  ['ram_0',['&quot;Out of Flash/RAM&quot;',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md365',1,'']]],
  ['rationale_1',['Rationale',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md565',1,'2. Implementatie Design Rationale'],['../message_queue_doc.html#autotoc_md126',1,'Waarom? (Design Rationale)'],['../network_doc.html#autotoc_md161',1,'Waarom? (Design Rationale)']]],
  ['rationale_3a_20short_20key_20names_2',['Design Rationale: Short Key Names',['../message_queue_doc.html#autotoc_md144',1,'']]],
  ['readiness_20checks_3',['Device Readiness Checks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md450',1,'']]],
  ['readme_20s_4',['📁 Module README&apos;s',['../index.html#autotoc_md313',1,'']]],
  ['real_20time_20transfer_20logging_5',['RTT (Real-Time Transfer) Logging',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md349',1,'']]],
  ['reason_20tracking_6',['Reboot Reason Tracking',['../reboot_doc.html#autotoc_md234',1,'']]],
  ['reboot_20module_20documentatie_7',['Reboot Module - Documentatie',['../reboot_doc.html',1,'']]],
  ['reboot_20reason_20tracking_8',['Reboot Reason Tracking',['../reboot_doc.html#autotoc_md234',1,'']]],
  ['reboot_20redenen_9',['Reboot Redenen',['../reboot_doc.html#autotoc_md238',1,'']]],
  ['reboot_20types_10',['Reboot Types',['../reboot_doc.html#autotoc_md237',1,'']]],
  ['recoveren_11',['Stap 2: Device Recoveren',['../provisioning.html#autotoc_md394',1,'']]],
  ['red_20flags_12',['Red Flags',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md614',1,'4.1 Taalgebruik Red Flags'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md615',1,'4.2 Structurele Red Flags'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md616',1,'4.3 Feature Consistency Red Flags'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md613',1,'Fase 4: Documentatie Anti-Patterns (Red Flags)']]],
  ['redenen_13',['Reboot Redenen',['../reboot_doc.html#autotoc_md238',1,'']]],
  ['referencing_14',['🔗 Cross-Referencing',['../doxygen_guidelines.html#autotoc_md646',1,'']]],
  ['referentie_15',['📄 API Referentie',['../index.html#autotoc_md311',1,'']]],
  ['referentie_20modules_16',['Referentie Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md518',1,'']]],
  ['referenties_17',['📚 Referenties',['../provisioning.html#autotoc_md411',1,'']]],
  ['referenties_20en_20voor_20na_20vergelijkingen_18',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md579',1,'']]],
  ['regels_19',['Regels',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html',1,'Code Style - Formattering Regels'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md524',1,'Lege Regels']]],
  ['related_20pages_20',['📚 Related Pages',['../group__Titel.html#autotoc_md650',1,'']]],
  ['relationship_21',['Watchdog Relationship',['../p_one_doc.html#autotoc_md223',1,'']]],
  ['remote_20support_20voordelen_22',['Remote Support Voordelen',['../led_doc.html#autotoc_md116',1,'']]],
  ['requires_23',['Inbound (FOTA Requires)',['../cloud_doc.html#autotoc_md42',1,'']]],
  ['resource_20management_24',['Resource Management',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md438',1,'']]],
  ['resources_25',['Resources',['../index.html#autotoc_md317',1,'🌐 Externe Resources'],['../group__Titel.html#autotoc_md662',1,'📚 Resources'],['../group__Titel.html#autotoc_md665',1,'📚 Resources']]],
  ['response_26',['Scenario 1: Slow P1 Device Response',['../p_one_doc.html#autotoc_md219',1,'']]],
  ['response_20timeout_27',['3. Total Response Timeout',['../p_one_doc.html#autotoc_md212',1,'']]],
  ['response_20timeout_2010_208s_28',['Response Timeout (10.8s)',['../p_one_doc.html#autotoc_md217',1,'']]],
  ['resultaten_20impact_29',['Resultaten Impact',['../energy_pulse_doc.html#autotoc_md88',1,'Resultaten &amp; Impact'],['../timing_doc.html#autotoc_md277',1,'Resultaten &amp; Impact']]],
  ['return_30',['Void vs Int Return',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md424',1,'']]],
  ['return_20patterns_31',['Return Patterns',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md421',1,'']]],
  ['return_20value_20conventies_32',['Return Value Conventies',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md422',1,'']]],
  ['return_20values_33',['Error Handling en Return Values',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md419',1,'']]],
  ['review_20sessie_34',['5.6 Checklist: Voor Documentatie Review Sessie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md625',1,'']]],
  ['richtlijnen_35',['Richtlijnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html',1,'Best Practices - Praktische Richtlijnen'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html',1,'Module Documentatie Richtlijnen']]],
  ['robustness_20features_36',['🛡️ Robustness Features',['../index.html#autotoc_md303',1,'']]],
  ['robuustheid_37',['Edge Cases &amp;amp; Robuustheid',['../p_one_doc.html#autotoc_md201',1,'']]],
  ['rollback_20test_20warning_3a_20intentional_20crash_38',['Rollback Test (Warning: Intentional Crash)',['../cloud_doc.html#autotoc_md53',1,'']]],
  ['rolling_20statistics_20sampling_39',['Rolling Statistics &amp;amp; Sampling',['../p_one_doc.html#autotoc_md189',1,'']]],
  ['rtt_40',['Stap 4: IMEI Schrijven via RTT',['../provisioning.html#autotoc_md396',1,'']]],
  ['rtt_20real_20time_20transfer_20logging_41',['RTT (Real-Time Transfer) Logging',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md349',1,'']]],
  ['runner_42',['Flash met Custom Runner',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md344',1,'']]],
  ['runtime_20gedrag_43',['Runtime Gedrag',['../energy_pulse_doc.html#autotoc_md84',1,'']]],
  ['rx_20timeout_20inter_20byte_20timeout_44',['2. UART RX Timeout (Inter-byte timeout)',['../p_one_doc.html#autotoc_md211',1,'']]]
];
