var searchData=
[
  ['v2_200_203_0',['Download Modem Firmware v2.0.3',['../provisioning.html#autotoc_md339',1,'']]],
  ['v2_203_208_1',['Download PTI Modem Firmware v2.3.8',['../provisioning.html#autotoc_md340',1,'']]],
  ['validatie_2',['Validatie',['../p_one_doc.html#autotoc_md208',1,'CRC16 Validatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md509',1,'NULL Checks en Validatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md510',1,'Pointer Validatie']]],
  ['validation_3',['Validation',['../cloud_doc.html#autotoc_md51',1,'Build Validation'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md426',1,'Input Validation']]],
  ['value_20conventies_4',['Return Value Conventies',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md379',1,'']]],
  ['values_5',['Error Handling en Return Values',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md376',1,'']]],
  ['van_20_5fdoc_20md_6',['Structuur van &lt;span class=&quot;tt&quot;&gt;&amp;lt;module&amp;gt;_doc.md&lt;/span&gt;',['../doxygen_guidelines.html#autotoc_md601',1,'']]],
  ['van_20andere_20modules_7',['10. Afhankelijkheden van Andere Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md530',1,'']]],
  ['van_20blokken_20code_8',['2. Herhalingen van Blokken Code',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md535',1,'']]],
  ['van_20documentatie_3a_9',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md540',1,'']]],
  ['van_20dsmr_20meters_10',['Data Acquisitie van DSMR Meters',['../p_one_doc.html#autotoc_md193',1,'']]],
  ['van_20fouten_20door_20niet_20te_20verifiëren_3a_11',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md543',1,'']]],
  ['variabelen_12',['Variabelen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md487',1,'']]],
  ['variable_20declaratie_13',['Error Variable Declaratie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md377',1,'']]],
  ['variable_20declarations_14',['Variable Declarations',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md498',1,'']]],
  ['verboden_3a_15',['❗ VERBODEN:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md542',1,'']]],
  ['vereisten_16',['Module Shutdown Implementatie Vereisten',['../reboot_doc.html#autotoc_md261',1,'']]],
  ['vergelijkingen_17',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md536',1,'']]],
  ['verifiëren_3a_18',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md543',1,'']]],
  ['verificatie_20en_20synchronisatie_20kritiek_20⚠️_19',['4. Code Verificatie en Synchronisatie (KRITIEK! ⚠️)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md538',1,'']]],
  ['verificatie_20per_20claim_20type_20',['Fase 3: Systematische Verificatie Per Claim Type',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md561',1,'']]],
  ['verificatie_20protocol_21',['5. AI Agent Documentatie Verificatie Protocol',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md551',1,'']]],
  ['verificatie_20strategie_22',['5.3 Systematische Verificatie Strategie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md556',1,'']]],
  ['verification_20shortcuts_23',['Verification Shortcuts',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md580',1,'']]],
  ['verification_20workflow_205_20fasen_24',['5.4 Verification Workflow (5 Fasen)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md575',1,'']]],
  ['verkrijgen_25',['1.6 IMEI Lijst Verkrijgen',['../provisioning.html#autotoc_md346',1,'']]],
  ['verplichte_20stappen_3a_26',['✅ VERPLICHTE STAPPEN:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md541',1,'']]],
  ['verwerking_27',['📊 Data Verwerking',['../index.html#autotoc_md309',1,'']]],
  ['verzend_20logica_28',['Verzend Logica',['../message_queue_doc.html#autotoc_md142',1,'']]],
  ['verzending_3a_20unix_20epoch_20conversion_29',['2. Verzending: Unix Epoch Conversion',['../message_queue_doc.html#autotoc_md146',1,'']]],
  ['verzinnen_30',['Principe: NOOIT iets verzinnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md539',1,'']]],
  ['verzonnen_20content_20_3a_31',['❗ FOUT (verzonnen content):',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md544',1,'']]],
  ['via_20buffering_32',['Delivery Garanties via Buffering',['../message_queue_doc.html#autotoc_md132',1,'']]],
  ['via_20rtt_33',['Stap 4: IMEI Schrijven via RTT',['../provisioning.html#autotoc_md353',1,'']]],
  ['visibility_34',['Header Visibility',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md461',1,'']]],
  ['visueel_20overzicht_35',['Visueel Overzicht',['../index.html#autotoc_md298',1,'']]],
  ['visuele_20feedback_20voor_20iot_20device_36',['Visuele Feedback voor IoT Device',['../led_doc.html#autotoc_md101',1,'']]],
  ['voer_20onboarding_20uit_37',['Voer Onboarding Uit',['../provisioning.html#autotoc_md366',1,'']]],
  ['void_20vs_20int_20return_38',['Void vs Int Return',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md381',1,'']]],
  ['volgorde_39',['Volgorde',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html',1,'Code Structure - Organisatie en Volgorde'],['../app_doc.html#autotoc_md12',1,'Initialisatie Volgorde'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md439',1,'Volgorde']]],
  ['volgorde_40',['Standaard Secties (in volgorde)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md442',1,'']]],
  ['voor_20documentatie_20review_20sessie_41',['5.6 Checklist: Voor Documentatie Review Sessie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md582',1,'']]],
  ['voor_20elke_20documentatie_20wijziging_3a_42',['Checklist voor elke documentatie wijziging:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md546',1,'']]],
  ['voor_20immediate_20scheduling_43',['K_NO_WAIT voor Immediate Scheduling',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md396',1,'']]],
  ['voor_20iot_20device_44',['Visuele Feedback voor IoT Device',['../led_doc.html#autotoc_md101',1,'']]],
  ['voor_20modules_45',['CMakeLists.txt voor Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md457',1,'']]],
  ['voor_20na_20vergelijkingen_46',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md536',1,'']]],
  ['voor_20nieuwe_20module_47',['Checklist voor Nieuwe Module',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md404',1,'']]],
  ['voorbeelden_48',['Voorbeelden',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md534',1,'1. Code Implementatie Voorbeelden'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md578',1,'Code Analysis Commands (Voorbeelden)']]],
  ['voorbeelden_20van_20fouten_20door_20niet_20te_20verifiëren_3a_49',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md543',1,'']]],
  ['voordelen_50',['Remote Support Voordelen',['../led_doc.html#autotoc_md120',1,'']]],
  ['vs_20define_51',['enum vs define',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md505',1,'']]],
  ['vs_20definitions_52',['Channel Declarations vs Definitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md451',1,'']]],
  ['vs_20int_20return_53',['Void vs Int Return',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md381',1,'']]]
];
