var searchData=
[
  ['behavior_0',['Watchdog Callback Behavior',['../app_doc.html#autotoc_md14',1,'']]],
  ['behavior_20claims_1',['3.4 Timing &amp;amp; Behavior Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md560',1,'']]],
  ['behavior_20en_20portability_2',['Undefined Behavior en Portability',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md403',1,'']]],
  ['behaviour_3',['6. Intended Behaviour',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md518',1,'']]],
  ['belangrijk_4',['Waarom is dit zo belangrijk?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md539',1,'']]],
  ['belangrijke_20features_5',['⚙️ Belangrijke Features',['../index.html#autotoc_md299',1,'']]],
  ['belangrijke_20links_6',['🔗 Belangrijke Links',['../index.html#autotoc_md315',1,'']]],
  ['benefits_7',['User Experience Benefits',['../led_doc.html#autotoc_md115',1,'']]],
  ['berekening_8',['Timing Berekening',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md395',1,'']]],
  ['best_20practices_20praktische_20richtlijnen_9',['Best Practices - Praktische Richtlijnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html',1,'']]],
  ['bestanden_20structuur_10',['Bestanden Structuur',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md457',1,'']]],
  ['bestandsnaam_20conventie_11',['Bestandsnaam Conventie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md508',1,'']]],
  ['betrouwbaarheid_12',['Betrouwbaarheid',['../energy_pulse_doc.html#autotoc_md90',1,'Betrouwbaarheid'],['../timing_doc.html#autotoc_md280',1,'Betrouwbaarheid'],['../reboot_doc.html#autotoc_md248',1,'Shutdown Betrouwbaarheid']]],
  ['bewerken_20van_20documentatie_3a_13',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md532',1,'']]],
  ['bij_20errors_14',['Logging Bij Errors',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md372',1,'']]],
  ['bij_20het_20schrijven_20of_20bewerken_20van_20documentatie_3a_15',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md532',1,'']]],
  ['blocking_20led_20control_16',['Non-Blocking LED Control',['../led_doc.html#autotoc_md102',1,'']]],
  ['blokken_20code_17',['2. Herhalingen van Blokken Code',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md527',1,'']]],
  ['board_20definition_18',['Custom Board Definition',['../index.html#autotoc_md307',1,'']]],
  ['bool_20checks_19',['Bool Checks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md503',1,'']]],
  ['boot_20confirmation_20',['Boot Confirmation',['../cloud_doc.html#autotoc_md32',1,'']]],
  ['boot_20confirmation_20window_21',['Boot Confirmation Window',['../cloud_doc.html#autotoc_md58',1,'']]],
  ['boot_20loop_20protection_22',['Boot Loop Protection',['../cloud_doc.html#autotoc_md39',1,'']]],
  ['bouwen_23',['1.4 Modem Shell (MoSh) Bouwen',['../provisioning.html#autotoc_md334',1,'']]],
  ['brace_20style_24',['Brace Style',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md474',1,'']]],
  ['branding_25',['🎨 Styling &amp;amp; Branding',['../doxygen_guidelines.html#autotoc_md588',1,'']]],
  ['broken_20links_26',['❗ Broken Links',['../group__Titel.html#autotoc_md608',1,'']]],
  ['buffer_20overflow_20prevention_27',['Buffer Overflow Prevention',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md419',1,'']]],
  ['buffer_20size_20constraint_28',['Buffer Size Constraint',['../p_one_doc.html#autotoc_md224',1,'']]],
  ['buffering_29',['Delivery Garanties via Buffering',['../message_queue_doc.html#autotoc_md128',1,'']]],
  ['buffers_30',['Arrays en Buffers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md493',1,'']]],
  ['build_20code_20inventory_20objectieve_20waarheid_31',['Fase 1: Build Code Inventory (Objectieve Waarheid)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md549',1,'']]],
  ['build_20de_20dinnis_20application_32',['Build de Dinnis Application',['../provisioning.html#autotoc_md352',1,'']]],
  ['build_20systeem_33',['Build Systeem',['../index.html#autotoc_md306',1,'']]],
  ['build_20system_34',['🛠️ Build System',['../group__Titel.html#autotoc_md601',1,'']]],
  ['build_20validation_35',['Build Validation',['../cloud_doc.html#autotoc_md51',1,'']]],
  ['bulk_20onboarding_36',['Bulk Onboarding',['../provisioning.html#autotoc_md365',1,'']]],
  ['bulk_20onboarding_20naar_20nrf_20cloud_37',['☁️ Fase 3: Bulk Onboarding naar nRF Cloud',['../provisioning.html#autotoc_md355',1,'']]],
  ['byte_20timeout_38',['2. UART RX Timeout (Inter-byte timeout)',['../p_one_doc.html#autotoc_md211',1,'']]],
  ['byte_20timeout_20392_20ms_39',['Inter-byte Timeout (392 ms)',['../p_one_doc.html#autotoc_md215',1,'']]],
  ['byte_20timeout_20trigger_40',['Scenario 3: Inter-byte Timeout Trigger',['../p_one_doc.html#autotoc_md221',1,'']]]
];
