var searchData=
[
  ['a_3a_20uart_20timing_20analyse_0',['📐 Appendix A: UART Timing Analyse',['../p_one_doc.html#autotoc_md120',1,'']]],
  ['aan_20de_20slag_1',['🚀 Aan de Slag',['../index.html#autotoc_md199',1,'']]],
  ['aannames_2',['Type Aannames',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md256',1,'']]],
  ['abonnementen_3',['Abonnementen',['../md_modules_2network_2network__doc.html#autotoc_md89',1,'']]],
  ['ack_20tracking_4',['Acknowledgement (ACK) Tracking',['../md_modules_2reboot_2reboot__doc.html#autotoc_md152',1,'']]],
  ['acknowledgement_20ack_20tracking_5',['Acknowledgement (ACK) Tracking',['../md_modules_2reboot_2reboot__doc.html#autotoc_md152',1,'']]],
  ['acq_5ftrigger_20flow_6',['ACQ_TRIGGER Flow',['../p_one_doc.html#autotoc_md106',1,'']]],
  ['acquisitie_7',['Gas Meting Acquisitie',['../p_one_doc.html#autotoc_md104',1,'']]],
  ['acquisitie_20buffering_8',['📥 Data Acquisitie &amp;amp; Buffering',['../index.html#autotoc_md186',1,'']]],
  ['acquisitie_20en_20buffering_9',['3.2 Data Acquisitie en Buffering',['../cloud_doc.html#autotoc_md26',1,'']]],
  ['acquisitie_20van_20dsmr_20meters_10',['Data Acquisitie van DSMR Meters',['../p_one_doc.html#autotoc_md98',1,'']]],
  ['afhankelijkheden_11',['Afhankelijkheden',['../md_modules_2network_2network__doc.html#autotoc_md92',1,'']]],
  ['afhankelijkheden_20van_20andere_20modules_12',['10. Afhankelijkheden van Andere Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md373',1,'']]],
  ['afwegingen_20trade_20offs_13',['5. Afwegingen (Trade-offs)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md368',1,'']]],
  ['agent_20documentatie_20verificatie_20protocol_14',['5. AI Agent Documentatie Verificatie Protocol',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md394',1,'']]],
  ['ai_20agent_20documentatie_20verificatie_20protocol_15',['5. AI Agent Documentatie Verificatie Protocol',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md394',1,'']]],
  ['air_16',['3.3 FOTA (Firmware-Over-The-Air)',['../cloud_doc.html#autotoc_md27',1,'']]],
  ['altijd_20compileren_17',['Standaard Pattern (Altijd Compileren)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md301',1,'']]],
  ['analyse_18',['📐 Appendix A: UART Timing Analyse',['../p_one_doc.html#autotoc_md120',1,'']]],
  ['analysis_20commands_20voorbeelden_19',['Code Analysis Commands (Voorbeelden)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md421',1,'']]],
  ['anchor_20mismatch_20',['❗ Anchor Mismatch',['../group__Titel.html#autotoc_md457',1,'']]],
  ['andere_20modules_21',['10. Afhankelijkheden van Andere Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md373',1,'']]],
  ['anti_20patterns_20red_20flags_22',['Fase 4: Documentatie Anti-Patterns (Red Flags)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md413',1,'']]],
  ['api_20elementen_23',['Links naar API Elementen',['../group__Titel.html#autotoc_md448',1,'']]],
  ['api_20referentie_24',['📄 API Referentie',['../index.html#autotoc_md205',1,'']]],
  ['api_20timing_25',['UART Async API &amp;amp; Timing',['../p_one_doc.html#autotoc_md99',1,'']]],
  ['app_20module_20documentatie_26',['App Module - Documentatie',['../app_doc.html',1,'']]],
  ['appendix_20a_3a_20uart_20timing_20analyse_27',['📐 Appendix A: UART Timing Analyse',['../p_one_doc.html#autotoc_md120',1,'']]],
  ['architectuur_28',['Architectuur',['../index.html#autotoc_md179',1,'🏗️ Architectuur'],['../index.html#autotoc_md182',1,'🔄 Data Flow &amp; ZBUS Architectuur'],['../app_doc.html#autotoc_md14',1,'5. Architectuur'],['../p_one_doc.html#autotoc_md108',1,'Architectuur']]],
  ['architectuur_20en_20functionaliteit_29',['3. Architectuur en Functionaliteit',['../cloud_doc.html#autotoc_md24',1,'']]],
  ['architectuur_20en_20gedrag_30',['Architectuur en Gedrag',['../md_modules_2reboot_2reboot__doc.html#autotoc_md150',1,'Architectuur en Gedrag'],['../md_modules_2timing_2timing__doc.html#autotoc_md168',1,'Architectuur en Gedrag']]],
  ['architectuur_20gedrag_31',['Architectuur Gedrag',['../energy_pulse_doc.html#autotoc_md44',1,'Hoe? (Architectuur &amp; Gedrag)'],['../led_doc.html#autotoc_md71',1,'Hoe? (Architectuur &amp; Gedrag)']]],
  ['architectuur_20pattern_20claims_32',['3.1 Architectuur Pattern Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md405',1,'']]],
  ['architectuur_3a_20interrupt_20thread_20scheiding_33',['Architectuur: Interrupt/Thread Scheiding',['../md_modules_2timing_2timing__doc.html#autotoc_md169',1,'']]],
  ['arg_5funused_20macro_34',['ARG_UNUSED Macro',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md356',1,'']]],
  ['argumentaties_35',['4. Argumentaties',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md367',1,'']]],
  ['arithmetic_36',['Pointer Arithmetic',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md257',1,'']]],
  ['arrays_20en_20buffers_37',['Arrays en Buffers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md344',1,'']]],
  ['assertions_38',['Assertions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md225',1,'']]],
  ['async_20api_20timing_39',['UART Async API &amp;amp; Timing',['../p_one_doc.html#autotoc_md99',1,'']]],
  ['asynchrone_20data_20ontvangst_40',['1. UART Callbacks (Asynchrone Data Ontvangst)',['../p_one_doc.html#autotoc_md109',1,'']]]
];
