var searchData=
[
  ['behavior_0',['Watchdog Callback Behavior',['../app_doc.html#autotoc_md14',1,'']]],
  ['behavior_20claims_1',['3.4 Timing &amp;amp; Behavior Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md611',1,'']]],
  ['behavior_20en_20portability_2',['Undefined Behavior en Portability',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md454',1,'']]],
  ['behaviour_3',['6. Intended Behaviour',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md569',1,'']]],
  ['belangrijk_4',['Waarom is dit zo belangrijk?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md590',1,'']]],
  ['belangrijke_20features_5',['⚙️ Belangrijke Features',['../index.html#autotoc_md299',1,'']]],
  ['belangrijke_20links_6',['🔗 Belangrijke Links',['../index.html#autotoc_md315',1,'']]],
  ['benefits_7',['User Experience Benefits',['../led_doc.html#autotoc_md115',1,'']]],
  ['berekening_8',['Timing Berekening',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md446',1,'']]],
  ['beschikbare_20targets_9',['Beschikbare Targets',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md352',1,'']]],
  ['best_20practices_20praktische_20richtlijnen_10',['Best Practices - Praktische Richtlijnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html',1,'']]],
  ['bestanden_20structuur_11',['Bestanden Structuur',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md508',1,'']]],
  ['bestandsnaam_20conventie_12',['Bestandsnaam Conventie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md559',1,'']]],
  ['betrouwbaarheid_13',['Betrouwbaarheid',['../energy_pulse_doc.html#autotoc_md90',1,'Betrouwbaarheid'],['../timing_doc.html#autotoc_md280',1,'Betrouwbaarheid'],['../reboot_doc.html#autotoc_md248',1,'Shutdown Betrouwbaarheid']]],
  ['bewerken_20van_20documentatie_3a_14',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md583',1,'']]],
  ['bij_20errors_15',['Logging Bij Errors',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md423',1,'']]],
  ['bij_20het_20schrijven_20of_20bewerken_20van_20documentatie_3a_16',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md583',1,'']]],
  ['blocking_20led_20control_17',['Non-Blocking LED Control',['../led_doc.html#autotoc_md102',1,'']]],
  ['blokken_20code_18',['2. Herhalingen van Blokken Code',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md578',1,'']]],
  ['board_19',['Build voor Specifiek Board',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md339',1,'']]],
  ['board_20definitie_20',['🔧 Custom Board Definitie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md355',1,'']]],
  ['board_20definition_21',['Custom Board Definition',['../index.html#autotoc_md307',1,'']]],
  ['board_20not_20found_22',['&quot;Board not found&quot;',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md363',1,'']]],
  ['bool_20checks_23',['Bool Checks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md554',1,'']]],
  ['boot_20confirmation_24',['Boot Confirmation',['../cloud_doc.html#autotoc_md32',1,'']]],
  ['boot_20confirmation_20window_25',['Boot Confirmation Window',['../cloud_doc.html#autotoc_md58',1,'']]],
  ['boot_20loop_20protection_26',['Boot Loop Protection',['../cloud_doc.html#autotoc_md39',1,'']]],
  ['bouwen_27',['1.4 Modem Shell (MoSh) Bouwen',['../provisioning.html#autotoc_md385',1,'']]],
  ['brace_20style_28',['Brace Style',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md525',1,'']]],
  ['branding_29',['🎨 Styling &amp;amp; Branding',['../doxygen_guidelines.html#autotoc_md639',1,'']]],
  ['broken_20links_30',['❗ Broken Links',['../group__Titel.html#autotoc_md659',1,'']]],
  ['buffer_20overflow_20prevention_31',['Buffer Overflow Prevention',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md470',1,'']]],
  ['buffer_20size_20constraint_32',['Buffer Size Constraint',['../p_one_doc.html#autotoc_md224',1,'']]],
  ['buffering_33',['Delivery Garanties via Buffering',['../message_queue_doc.html#autotoc_md128',1,'']]],
  ['buffers_34',['Arrays en Buffers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md544',1,'']]],
  ['build_35',['Build',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md337',1,'Clean Build'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md338',1,'Debug Build'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md336',1,'Standard Build']]],
  ['build_20cache_20corrupt_36',['&quot;Build cache corrupt&quot;',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md364',1,'']]],
  ['build_20code_20inventory_20objectieve_20waarheid_37',['Fase 1: Build Code Inventory (Objectieve Waarheid)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md600',1,'']]],
  ['build_20de_20dinnis_20application_38',['Build de Dinnis Application',['../provisioning.html#autotoc_md403',1,'']]],
  ['build_20instructies_39',['🏗️ Build Instructies',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md335',1,'']]],
  ['build_20systeem_40',['Build Systeem',['../index.html#autotoc_md306',1,'']]],
  ['build_20system_41',['🛠️ Build System',['../group__Titel.html#autotoc_md652',1,'']]],
  ['build_20targets_42',['📊 Build Targets',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md351',1,'']]],
  ['build_20troubleshooting_43',['📝 Build Troubleshooting',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md361',1,'']]],
  ['build_20validation_44',['Build Validation',['../cloud_doc.html#autotoc_md51',1,'']]],
  ['build_20voor_20specifiek_20board_45',['Build voor Specifiek Board',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md339',1,'']]],
  ['builds_20mcuboot_20app_46',['Multi-Image Builds (MCUboot + App)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md368',1,'']]],
  ['bulk_20onboarding_47',['Bulk Onboarding',['../provisioning.html#autotoc_md416',1,'']]],
  ['bulk_20onboarding_20naar_20nrf_20cloud_48',['☁️ Fase 3: Bulk Onboarding naar nRF Cloud',['../provisioning.html#autotoc_md406',1,'']]],
  ['byte_20timeout_49',['2. UART RX Timeout (Inter-byte timeout)',['../p_one_doc.html#autotoc_md211',1,'']]],
  ['byte_20timeout_20392_20ms_50',['Inter-byte Timeout (392 ms)',['../p_one_doc.html#autotoc_md215',1,'']]],
  ['byte_20timeout_20trigger_51',['Scenario 3: Inter-byte Timeout Trigger',['../p_one_doc.html#autotoc_md221',1,'']]]
];
