var searchData=
[
  ['machine_0',['Machine',['../cloud_doc.html#autotoc_md25',1,'3.1 Cloud Connectie State Machine'],['../message_queue_module.html#mq_dataflow',1,'Data Flow &amp; State Machine'],['../led_doc.html#autotoc_md72',1,'Network State Machine'],['../md_modules_2network_2network__doc.html#autotoc_md86',1,'State Machine'],['../md_modules_2reboot_2reboot__doc.html#autotoc_md151',1,'State Machine'],['../md_modules_2timing_2timing__doc.html#autotoc_md171',1,'State Machine']]],
  ['machine_20forward_20declarations_1',['State Machine Forward Declarations',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md281',1,'']]],
  ['machine_20patterns_20smf_2',['State Machine Patterns (SMF)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md233',1,'']]],
  ['machine_20setup_3',['State Machine Setup',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md234',1,'']]],
  ['machine_20transities_4',['9. State Machine Transities',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md372',1,'']]],
  ['macro_5',['ARG_UNUSED Macro',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md356',1,'']]],
  ['macro_20s_6',['Macro&apos;s',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md332',1,'']]],
  ['magic_20numbers_20en_20constants_7',['Magic Numbers en Constants',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md347',1,'']]],
  ['management_8',['Resource Management',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md238',1,'']]],
  ['matter_9',['Why These Specific Timeouts Matter',['../p_one_doc.html#autotoc_md127',1,'']]],
  ['maximum_20length_20telegram_10',['Scenario 2: Maximum Length Telegram',['../p_one_doc.html#autotoc_md134',1,'']]],
  ['maximum_20telegram_20transmission_20time_11',['1. Maximum Telegram Transmission Time',['../p_one_doc.html#autotoc_md124',1,'']]],
  ['md_12',['Structuur van &lt;span class=&quot;tt&quot;&gt;&amp;lt;module&amp;gt;_doc.md&lt;/span&gt;',['../doxygen_guidelines.html#autotoc_md444',1,'']]],
  ['mechanisme_13',['Mechanisme',['../md_modules_2timing_2timing__doc.html#autotoc_md164',1,'Het Offset Mechanisme'],['../md_modules_2reboot_2reboot__doc.html#autotoc_md153',1,'Work Queue en Timeout Mechanisme']]],
  ['memory_20usage_14',['Memory Usage',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md265',1,'']]],
  ['message_20flow_20scenarios_15',['Message Flow Scenarios',['../index.html#autotoc_md185',1,'']]],
  ['message_20format_16',['Cloud Message Format',['../message_queue_module.html#mq_cloudformat',1,'']]],
  ['message_20handling_20periodieke_20triggers_17',['2. ZBUS Message Handling (Periodieke Triggers)',['../p_one_doc.html#autotoc_md110',1,'']]],
  ['message_20processing_20in_20thread_18',['Message Processing in Thread',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md231',1,'']]],
  ['message_20queue_20module_19',['Message Queue Module',['../message_queue_module.html',1,'']]],
  ['message_20structs_20',['Message Structs',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md293',1,'']]],
  ['messages_21',['Publishing Messages',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md230',1,'']]],
  ['met_20zbus_20smf_22',['Thread Loop met ZBUS + SMF',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md260',1,'']]],
  ['meters_23',['Data Acquisitie van DSMR Meters',['../p_one_doc.html#autotoc_md98',1,'']]],
  ['meting_20acquisitie_24',['Gas Meting Acquisitie',['../p_one_doc.html#autotoc_md104',1,'']]],
  ['minuten_25',['minuten',['../index.html#autotoc_md189',1,'☁️ Cloud Transmission (elke 30 minuten)'],['../index.html#autotoc_md188',1,'📊 Publish Statistics (elke 10 minuten)']]],
  ['mismatch_26',['❗ Anchor Mismatch',['../group__Titel.html#autotoc_md457',1,'']]],
  ['missing_27',['Missing',['../group__Titel.html#autotoc_md460',1,'❗ Missing @ingroup'],['../group__Titel.html#autotoc_md463',1,'❗ Missing @ingroup']]],
  ['model_28',['5.1 Thread Model',['../app_doc.html#autotoc_md15',1,'']]],
  ['module_29',['Module',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md247',1,'Checklist voor Nieuwe Module'],['../message_queue_module.html',1,'Message Queue Module'],['../md_modules_2network_2network__doc.html#autotoc_md82',1,'Network Module'],['../md_modules_2reboot_2reboot__doc.html#autotoc_md142',1,'Reboot Module'],['../md_modules_2timing_2timing__doc.html#autotoc_md159',1,'Timing Module'],['../md_modules_2reboot_2reboot__doc.html#autotoc_md145',1,'Waarom een Reboot Module?'],['../md_modules_2timing_2timing__doc.html#autotoc_md162',1,'Waarom een Timing Module?']]],
  ['module_20checklist_30',['Module Checklist',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md307',1,'']]],
  ['module_20documentatie_31',['Module Documentatie',['../doxygen_guidelines.html#autotoc_md443',1,'📝 Module Documentatie'],['../app_doc.html',1,'App Module - Documentatie'],['../cloud_doc.html',1,'Cloud Module - Documentatie'],['../energy_pulse_doc.html',1,'Energy Pulse Module - Documentatie'],['../led_doc.html',1,'LED Module - Documentatie'],['../p_one_doc.html',1,'P1 DSMR Module - Documentatie']]],
  ['module_20documentatie_20richtlijnen_32',['Module Documentatie Richtlijnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html',1,'']]],
  ['module_20documenteren_33',['✅ Checklist: Nieuwe Module Documenteren',['../group__Titel.html#autotoc_md454',1,'']]],
  ['module_20eigen_20thread_20heeft_34',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md314',1,'']]],
  ['module_20groepen_20definiëren_35',['Module Groepen Definiëren',['../doxygen_guidelines.html#autotoc_md447',1,'']]],
  ['module_20initialisatie_36',['Module Initialisatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md296',1,'Module Initialisatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md311',1,'Module Initialisatie']]],
  ['module_20readme_20s_37',['📁 Module README&apos;s',['../index.html#autotoc_md207',1,'']]],
  ['module_20setup_20pattern_38',['Module Setup Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md245',1,'']]],
  ['modules_39',['Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md373',1,'10. Afhankelijkheden van Andere Modules'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md300',1,'CMakeLists.txt voor Modules'],['../md_modules_2timing_2timing__doc.html#autotoc_md176',1,'Gerelateerde Modules'],['../md_modules_2reboot_2reboot__doc.html#autotoc_md157',1,'Implementatie Vereisten voor Modules'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md318',1,'Referentie Modules']]],
  ['moet_40',['moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md363',1,'✅ Wat ER WEL in moet'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md376',1,'❗ Wat ER NIET in moet']]],
  ['monitor_41',['3.2 ZBUS Monitor',['../app_doc.html#autotoc_md7',1,'']]],
  ['motivatie_42',['Waarom? (Probleem &amp;amp; Motivatie)',['../led_doc.html#autotoc_md62',1,'']]],
  ['ms_43',['ms',['../p_one_doc.html#autotoc_md129',1,'Inter-byte Timeout (392 ms)'],['../p_one_doc.html#autotoc_md130',1,'Telegram Timeout (784 ms)']]],
  ['msg_5fsubscriber_20pattern_44',['MSG_SUBSCRIBER Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md228',1,'']]],
  ['multi_20layer_20timeout_20strategy_45',['Multi-Layer Timeout Strategy',['../p_one_doc.html#autotoc_md140',1,'']]],
  ['multiple_20source_20files_46',['Multiple Source Files',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md303',1,'']]],
  ['mutex_20usage_47',['Mutex Usage',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md240',1,'']]]
];
