var searchData=
[
  ['c_20files_0',['Include Order (in .c files)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md277',1,'']]],
  ['c_20template_1',['Source File (.c) Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md288',1,'']]],
  ['calculations_2',['Critical Timing Calculations',['../p_one_doc.html#autotoc_md123',1,'']]],
  ['calculations_20fundamentals_3',['UART Timing Calculations - Fundamentals',['../p_one_doc.html#autotoc_md100',1,'']]],
  ['call_20graphs_4',['📊 Call Graphs',['../index.html#autotoc_md206',1,'']]],
  ['callback_20behavior_5',['Watchdog Callback Behavior',['../app_doc.html#autotoc_md17',1,'']]],
  ['callback_20pattern_6',['Callback Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md262',1,'']]],
  ['callbacks_7',['GPIO Callbacks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md251',1,'']]],
  ['callbacks_20asynchrone_20data_20ontvangst_8',['1. UART Callbacks (Asynchrone Data Ontvangst)',['../p_one_doc.html#autotoc_md109',1,'']]],
  ['case_20scenarios_9',['Edge Case Scenarios',['../p_one_doc.html#autotoc_md132',1,'']]],
  ['cases_10',['3. Edge Cases',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md366',1,'']]],
  ['cases_20robuustheid_11',['Edge Cases &amp;amp; Robuustheid',['../p_one_doc.html#autotoc_md115',1,'']]],
  ['channel_20declarations_20vs_20definitions_12',['Channel Declarations vs Definitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md294',1,'']]],
  ['channel_20naming_13',['Channel Naming',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md292',1,'']]],
  ['channel_20overzicht_14',['ZBUS Channel Overzicht',['../index.html#autotoc_md184',1,'']]],
  ['checklist_15',['Module Checklist',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md307',1,'']]],
  ['checklist_20voor_20elke_20documentatie_20wijziging_3a_16',['Checklist voor elke documentatie wijziging:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md389',1,'']]],
  ['checklist_20voor_20nieuwe_20module_17',['Checklist voor Nieuwe Module',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md247',1,'']]],
  ['checklist_3a_20nieuwe_20module_20documenteren_18',['✅ Checklist: Nieuwe Module Documenteren',['../group__Titel.html#autotoc_md454',1,'']]],
  ['checklist_3a_20voor_20documentatie_20review_20sessie_19',['5.6 Checklist: Voor Documentatie Review Sessie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md425',1,'']]],
  ['checks_20',['Checks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md354',1,'Bool Checks'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md250',1,'Device Readiness Checks']]],
  ['checks_20en_20validatie_21',['NULL Checks en Validatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md352',1,'']]],
  ['claim_20type_22',['Fase 3: Systematische Verificatie Per Claim Type',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md404',1,'']]],
  ['claims_23',['Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md405',1,'3.1 Architectuur Pattern Claims'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md407',1,'3.2 Communication Pattern Claims'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md409',1,'3.3 Configuration &amp; Constants Claims'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md411',1,'3.4 Timing &amp; Behavior Claims']]],
  ['claims_20extraction_24',['Fase 2: Documentation Claims Extraction',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md402',1,'']]],
  ['cloud_25',['� Data Verzending naar de Cloud',['../index.html#autotoc_md187',1,'']]],
  ['cloud_20connectie_20state_20machine_26',['3.1 Cloud Connectie State Machine',['../cloud_doc.html#autotoc_md25',1,'']]],
  ['cloud_20integratie_27',['☁️ Cloud Integratie',['../index.html#autotoc_md196',1,'']]],
  ['cloud_20message_20format_28',['Cloud Message Format',['../message_queue_module.html#mq_cloudformat',1,'']]],
  ['cloud_20module_20documentatie_29',['Cloud Module - Documentatie',['../cloud_doc.html',1,'']]],
  ['cloud_20transmission_20elke_2030_20minuten_30',['☁️ Cloud Transmission (elke 30 minuten)',['../index.html#autotoc_md189',1,'']]],
  ['cmakelists_31',['Integration in Parent CMakeLists',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md305',1,'']]],
  ['cmakelists_20txt_32',['CMakeLists.txt',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md312',1,'']]],
  ['cmakelists_20txt_20voor_20modules_33',['CMakeLists.txt voor Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md300',1,'']]],
  ['code_34',['2. Herhalingen van Blokken Code',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md378',1,'']]],
  ['code_20analysis_20commands_20voorbeelden_35',['Code Analysis Commands (Voorbeelden)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md421',1,'']]],
  ['code_20first_20investigation_36',['5.2 Fundamenteel Principe: Code-First Investigation',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md397',1,'']]],
  ['code_20implementatie_20voorbeelden_37',['1. Code Implementatie Voorbeelden',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md377',1,'']]],
  ['code_20inventory_20objectieve_20waarheid_38',['Fase 1: Build Code Inventory (Objectieve Waarheid)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md400',1,'']]],
  ['code_20structure_20organisatie_20en_20volgorde_39',['Code Structure - Organisatie en Volgorde',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html',1,'']]],
  ['code_20structuur_40',['Code Structuur',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md309',1,'']]],
  ['code_20style_20formattering_20regels_41',['Code Style - Formattering Regels',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html',1,'']]],
  ['code_20verificatie_20en_20synchronisatie_20kritiek_20⚠️_42',['4. Code Verificatie en Synchronisatie (KRITIEK! ⚠️)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md381',1,'']]],
  ['commands_43',['5.5 Practical Tools &amp;amp; Commands',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md420',1,'']]],
  ['commands_20context_44',['Git History Commands (Context)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md422',1,'']]],
  ['commands_20voorbeelden_45',['Code Analysis Commands (Voorbeelden)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md421',1,'']]],
  ['comment_20style_46',['Comment Style',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md338',1,'']]],
  ['comments_20en_20documentatie_47',['Comments en Documentatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md337',1,'']]],
  ['common_20patterns_48',['Common Patterns',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md259',1,'']]],
  ['common_20pitfalls_49',['🚨 Common Pitfalls',['../group__Titel.html#autotoc_md456',1,'']]],
  ['communication_20pattern_20claims_50',['3.2 Communication Pattern Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md407',1,'']]],
  ['compilatie_20pattern_51',['Conditionele Compilatie Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md302',1,'']]],
  ['compileren_52',['Standaard Pattern (Altijd Compileren)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md301',1,'']]],
  ['complete_20systeem_20tijdlijn_53',['Complete Systeem Tijdlijn',['../md_modules_2timing_2timing__doc.html#autotoc_md167',1,'']]],
  ['componenten_20diagram_54',['Componenten Diagram',['../md_modules_2network_2network__doc.html#autotoc_md85',1,'']]],
  ['conditionele_20compilatie_20pattern_55',['Conditionele Compilatie Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md302',1,'']]],
  ['configuratie_56',['Configuratie',['../doxygen_guidelines.html#autotoc_md437',1,'⚙️ Doxyfile Configuratie'],['../cloud_doc.html#autotoc_md33',1,'5. Configuratie'],['../app_doc.html#autotoc_md16',1,'5.2 Configuratie'],['../p_one_doc.html#autotoc_md117',1,'Configuratie'],['../index.html#autotoc_md202',1,'Configuratie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md244',1,'Configuratie'],['../energy_pulse_doc.html#autotoc_md40',1,'Kanaal Configuratie'],['../md_modules_2timing_2timing__doc.html#autotoc_md170',1,'Timer Configuratie']]],
  ['configuratie_20kconfig_57',['Configuratie Kconfig',['../energy_pulse_doc.html#autotoc_md48',1,'Configuratie (Kconfig)'],['../md_modules_2timing_2timing__doc.html#autotoc_md172',1,'Configuratie (Kconfig)']]],
  ['configuration_20constants_20claims_58',['3.3 Configuration &amp;amp; Constants Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md409',1,'']]],
  ['connectie_20state_20machine_59',['3.1 Cloud Connectie State Machine',['../cloud_doc.html#autotoc_md25',1,'']]],
  ['consistency_20red_20flags_60',['4.3 Feature Consistency Red Flags',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md416',1,'']]],
  ['constanten_20en_20defines_61',['Constanten en Defines',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md331',1,'']]],
  ['constants_62',['Constants',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md349',1,'Gebruik Named Constants'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md347',1,'Magic Numbers en Constants']]],
  ['constants_20claims_63',['3.3 Configuration &amp;amp; Constants Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md409',1,'']]],
  ['constraint_64',['Buffer Size Constraint',['../p_one_doc.html#autotoc_md138',1,'']]],
  ['contact_65',['📞 Contact',['../index.html#autotoc_md213',1,'']]],
  ['content_20_3a_66',['❗ FOUT (verzonnen content):',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md387',1,'']]],
  ['context_67',['Git History Commands (Context)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md422',1,'']]],
  ['control_68',['Non-Blocking LED Control',['../led_doc.html#autotoc_md64',1,'']]],
  ['control_20patterns_69',['LED Control Patterns',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md252',1,'']]],
  ['conventie_70',['Bestandsnaam Conventie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md359',1,'']]],
  ['conventies_71',['Conventies',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md222',1,'Return Value Conventies'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md291',1,'ZBUS Conventies']]],
  ['conventions_72',['Naming Conventions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md328',1,'']]],
  ['conversie_73',['OBIS Parsing &amp;amp; Data Conversie',['../p_one_doc.html#autotoc_md102',1,'']]],
  ['core_20firmware_20documentatie_74',['SolarResult Energy Core - Firmware Documentatie',['../index.html',1,'']]],
  ['correct_20geverifieerd_20_3a_75',['✅ CORRECT (geverifieerd):',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md388',1,'']]],
  ['crc16_20validatie_76',['CRC16 Validatie',['../p_one_doc.html#autotoc_md114',1,'']]],
  ['critical_20dependencies_77',['Critical Dependencies',['../p_one_doc.html#autotoc_md136',1,'']]],
  ['critical_20timing_20calculations_78',['Critical Timing Calculations',['../p_one_doc.html#autotoc_md123',1,'']]],
  ['cross_20referencing_79',['🔗 Cross-Referencing',['../doxygen_guidelines.html#autotoc_md446',1,'']]],
  ['css_80',['Custom CSS (&lt;span class=&quot;tt&quot;&gt;docs/doxygen-custom.css&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md440',1,'']]],
  ['css_20docs_20doxygen_20custom_20css_81',['Custom CSS (&lt;span class=&quot;tt&quot;&gt;docs/doxygen-custom.css&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md440',1,'']]],
  ['custom_20board_20definition_82',['Custom Board Definition',['../index.html#autotoc_md201',1,'']]],
  ['custom_20css_83',['Custom CSS (&lt;span class=&quot;tt&quot;&gt;docs/doxygen-custom.css&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md440',1,'']]],
  ['custom_20css_20docs_20doxygen_20custom_20css_84',['Custom CSS (&lt;span class=&quot;tt&quot;&gt;docs/doxygen-custom.css&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md440',1,'']]]
];
