var searchData=
[
  ['edge_20case_20scenarios_0',['Edge Case Scenarios',['../p_one_doc.html#autotoc_md218',1,'']]],
  ['edge_20cases_1',['Edge Cases',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md515',1,'3. Edge Cases'],['../cloud_doc.html#autotoc_md35',1,'Edge Cases']]],
  ['edge_20cases_20robuustheid_2',['Edge Cases &amp;amp; Robuustheid',['../p_one_doc.html#autotoc_md201',1,'']]],
  ['eenmalige_20setup_3',['Eenmalige Setup',['../provisioning.html#autotoc_md326',1,'🛠️ Fase 1: Eenmalige Setup'],['../provisioning.html#autotoc_md363',1,'Eenmalige Setup']]],
  ['eigen_20thread_20heeft_4',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md463',1,'']]],
  ['elementen_5',['Links naar API Elementen',['../group__Titel.html#autotoc_md597',1,'']]],
  ['elke_2010_20minuten_6',['📊 Publish Statistics (elke 10 minuten)',['../index.html#autotoc_md294',1,'']]],
  ['elke_2030_20minuten_7',['☁️ Cloud Transmission (elke 30 minuten)',['../index.html#autotoc_md295',1,'']]],
  ['elke_2030_20seconden_8',['📥 Normal Data Collection (elke 30 seconden)',['../index.html#autotoc_md293',1,'']]],
  ['elke_20documentatie_20wijziging_3a_9',['Checklist voor elke documentatie wijziging:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md538',1,'']]],
  ['en_20buffers_10',['Arrays en Buffers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md493',1,'']]],
  ['en_20constants_11',['Magic Numbers en Constants',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md496',1,'']]],
  ['en_20defines_12',['Constanten en Defines',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md480',1,'']]],
  ['en_20documentatie_13',['Comments en Documentatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md486',1,'']]],
  ['en_20formattering_14',['Indentatie en Formattering',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md471',1,'']]],
  ['en_20headers_15',['Include Guards en Headers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md424',1,'']]],
  ['en_20optimization_16',['Performance en Optimization',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md413',1,'']]],
  ['en_20portability_17',['Undefined Behavior en Portability',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md403',1,'']]],
  ['en_20return_20values_18',['Error Handling en Return Values',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md368',1,'']]],
  ['en_20safety_19',['Security en Safety',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md417',1,'']]],
  ['en_20static_20',['Scope en Static',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md492',1,'']]],
  ['en_20synchronisatie_20kritiek_20⚠️_21',['4. Code Verificatie en Synchronisatie (KRITIEK! ⚠️)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md530',1,'']]],
  ['en_20validatie_22',['NULL Checks en Validatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md501',1,'']]],
  ['en_20volgorde_23',['Code Structure - Organisatie en Volgorde',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html',1,'']]],
  ['en_20voor_20na_20vergelijkingen_24',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md528',1,'']]],
  ['end_20test_25',['FOTA End-to-End Test',['../cloud_doc.html#autotoc_md52',1,'']]],
  ['end_20to_20end_20test_26',['FOTA End-to-End Test',['../cloud_doc.html#autotoc_md52',1,'']]],
  ['energietellers_27',['Persistente Energietellers',['../energy_pulse_doc.html#autotoc_md74',1,'']]],
  ['energy_20pulse_20module_20documentatie_28',['Energy Pulse Module - Documentatie',['../energy_pulse_doc.html',1,'']]],
  ['enum_20vs_20define_29',['enum vs define',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md497',1,'']]],
  ['enums_30',['Enums',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md482',1,'Enums'],['../network_doc.html#autotoc_md168',1,'Network Status Enums']]],
  ['environment_31',['1.1 Development Environment',['../provisioning.html#autotoc_md327',1,'']]],
  ['environment_20activeren_32',['1.2 nRF Connect Environment Activeren',['../provisioning.html#autotoc_md328',1,'']]],
  ['er_20niet_20in_20moet_33',['❗ Wat ER NIET in moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md525',1,'']]],
  ['er_20wel_20in_20moet_34',['✅ Wat ER WEL in moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md512',1,'']]],
  ['error_20handling_35',['Error Handling',['../energy_pulse_doc.html#autotoc_md85',1,'']]],
  ['error_20handling_20en_20return_20values_36',['Error Handling en Return Values',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md368',1,'']]],
  ['error_20variable_20declaratie_37',['Error Variable Declaratie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md369',1,'']]],
  ['errors_38',['Logging Bij Errors',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md372',1,'']]],
  ['evaluatievolgorde_39',['Evaluatievolgorde',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md404',1,'']]],
  ['event_20driven_20network_20management_40',['Event-Driven Network Management',['../network_doc.html#autotoc_md162',1,'']]],
  ['event_20flow_41',['FOTA Event Flow',['../cloud_doc.html#autotoc_md28',1,'']]],
  ['experience_20benefits_42',['User Experience Benefits',['../led_doc.html#autotoc_md115',1,'']]],
  ['external_20flash_20support_43',['Priority 1: External Flash Support',['../cloud_doc.html#autotoc_md61',1,'']]],
  ['external_20interface_20contract_44',['External Interface Contract',['../message_queue_doc.html#autotoc_md141',1,'']]],
  ['externe_20resources_45',['🌐 Externe Resources',['../index.html#autotoc_md317',1,'']]],
  ['extraction_46',['Fase 2: Documentation Claims Extraction',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md551',1,'']]]
];
