var searchData=
[
  ['edge_20case_20scenarios_0',['Edge Case Scenarios',['../p_one_doc.html#autotoc_md132',1,'']]],
  ['edge_20cases_1',['3. Edge Cases',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md366',1,'']]],
  ['edge_20cases_20robuustheid_2',['Edge Cases &amp;amp; Robuustheid',['../p_one_doc.html#autotoc_md115',1,'']]],
  ['een_20reboot_20module_3',['Waarom een Reboot Module?',['../md_modules_2reboot_2reboot__doc.html#autotoc_md145',1,'']]],
  ['een_20timing_20module_4',['Waarom een Timing Module?',['../md_modules_2timing_2timing__doc.html#autotoc_md162',1,'']]],
  ['eigen_20thread_20heeft_5',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md314',1,'']]],
  ['elementen_6',['Links naar API Elementen',['../group__Titel.html#autotoc_md448',1,'']]],
  ['elke_2010_20minuten_7',['📊 Publish Statistics (elke 10 minuten)',['../index.html#autotoc_md188',1,'']]],
  ['elke_2030_20minuten_8',['☁️ Cloud Transmission (elke 30 minuten)',['../index.html#autotoc_md189',1,'']]],
  ['elke_20documentatie_20wijziging_3a_9',['Checklist voor elke documentatie wijziging:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md389',1,'']]],
  ['en_20buffering_10',['3.2 Data Acquisitie en Buffering',['../cloud_doc.html#autotoc_md26',1,'']]],
  ['en_20buffers_11',['Arrays en Buffers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md344',1,'']]],
  ['en_20constants_12',['Magic Numbers en Constants',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md347',1,'']]],
  ['en_20data_20flow_13',['Functionaliteit en Data Flow',['../md_modules_2timing_2timing__doc.html#autotoc_md165',1,'']]],
  ['en_20defines_14',['Constanten en Defines',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md331',1,'']]],
  ['en_20documentatie_15',['Comments en Documentatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md337',1,'']]],
  ['en_20formattering_16',['Indentatie en Formattering',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md322',1,'']]],
  ['en_20functionaliteit_17',['3. Architectuur en Functionaliteit',['../cloud_doc.html#autotoc_md24',1,'']]],
  ['en_20gedrag_18',['en Gedrag',['../md_modules_2reboot_2reboot__doc.html#autotoc_md150',1,'Architectuur en Gedrag'],['../md_modules_2timing_2timing__doc.html#autotoc_md168',1,'Architectuur en Gedrag']]],
  ['en_20headers_19',['Include Guards en Headers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md275',1,'']]],
  ['en_20impact_20',['Resultaten en Impact',['../md_modules_2timing_2timing__doc.html#autotoc_md173',1,'']]],
  ['en_20optimization_21',['Performance en Optimization',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md264',1,'']]],
  ['en_20performance_22',['Geheugen en Performance',['../md_modules_2timing_2timing__doc.html#autotoc_md174',1,'']]],
  ['en_20portability_23',['Undefined Behavior en Portability',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md254',1,'']]],
  ['en_20return_20values_24',['Error Handling en Return Values',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md219',1,'']]],
  ['en_20robuustheid_25',['Foutafhandeling en Robuustheid',['../md_modules_2network_2network__doc.html#autotoc_md90',1,'']]],
  ['en_20safety_26',['Security en Safety',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md268',1,'']]],
  ['en_20static_27',['Scope en Static',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md343',1,'']]],
  ['en_20synchronisatie_20kritiek_20⚠️_28',['4. Code Verificatie en Synchronisatie (KRITIEK! ⚠️)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md381',1,'']]],
  ['en_20timeout_20mechanisme_29',['Work Queue en Timeout Mechanisme',['../md_modules_2reboot_2reboot__doc.html#autotoc_md153',1,'']]],
  ['en_20validatie_30',['NULL Checks en Validatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md352',1,'']]],
  ['en_20verantwoordelijkheden_31',['2. Doel en Verantwoordelijkheden',['../app_doc.html#autotoc_md3',1,'']]],
  ['en_20volgorde_32',['Code Structure - Organisatie en Volgorde',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html',1,'']]],
  ['en_20voor_20na_20vergelijkingen_33',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md379',1,'']]],
  ['en_20wachtrij_34',['Buffering en Wachtrij',['../message_queue_module.html#mq_buffering',1,'']]],
  ['energy_20core_20firmware_20documentatie_35',['SolarResult Energy Core - Firmware Documentatie',['../index.html',1,'']]],
  ['energy_20pulse_20module_20documentatie_36',['Energy Pulse Module - Documentatie',['../energy_pulse_doc.html',1,'']]],
  ['enum_20vs_20define_37',['enum vs define',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md348',1,'']]],
  ['enums_38',['Enums',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md333',1,'']]],
  ['er_20niet_20in_20moet_39',['❗ Wat ER NIET in moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md376',1,'']]],
  ['er_20wel_20in_20moet_40',['✅ Wat ER WEL in moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md363',1,'']]],
  ['error_20handling_41',['Error Handling',['../energy_pulse_doc.html#autotoc_md47',1,'']]],
  ['error_20handling_20en_20return_20values_42',['Error Handling en Return Values',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md219',1,'']]],
  ['error_20variable_20declaratie_43',['Error Variable Declaratie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md220',1,'']]],
  ['errors_44',['Logging Bij Errors',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md223',1,'']]],
  ['evaluatievolgorde_45',['Evaluatievolgorde',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md255',1,'']]],
  ['experience_20benefits_46',['User Experience Benefits',['../led_doc.html#autotoc_md75',1,'']]],
  ['externe_20resources_47',['🌐 Externe Resources',['../index.html#autotoc_md211',1,'']]],
  ['extraction_48',['Fase 2: Documentation Claims Extraction',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md402',1,'']]]
];
