var searchData=
[
  ['fase_201_3a_20build_20code_20inventory_20objectieve_20waarheid_0',['Fase 1: Build Code Inventory (Objectieve Waarheid)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md600',1,'']]],
  ['fase_201_3a_20eenmalige_20setup_1',['🛠️ Fase 1: Eenmalige Setup',['../provisioning.html#autotoc_md377',1,'']]],
  ['fase_202_3a_20documentation_20claims_20extraction_2',['Fase 2: Documentation Claims Extraction',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md602',1,'']]],
  ['fase_202_3a_20per_20device_20provisioneren_3',['🔧 Fase 2: Per Device Provisioneren',['../provisioning.html#autotoc_md391',1,'']]],
  ['fase_203_3a_20bulk_20onboarding_20naar_20nrf_20cloud_4',['☁️ Fase 3: Bulk Onboarding naar nRF Cloud',['../provisioning.html#autotoc_md406',1,'']]],
  ['fase_203_3a_20systematische_20verificatie_20per_20claim_20type_5',['Fase 3: Systematische Verificatie Per Claim Type',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md604',1,'']]],
  ['fase_204_3a_20documentatie_20anti_20patterns_20red_20flags_6',['Fase 4: Documentatie Anti-Patterns (Red Flags)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md613',1,'']]],
  ['fasen_7',['5.4 Verification Workflow (5 Fasen)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md618',1,'']]],
  ['feature_20consistency_20red_20flags_8',['4.3 Feature Consistency Red Flags',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md616',1,'']]],
  ['features_9',['Features',['../index.html#autotoc_md299',1,'⚙️ Belangrijke Features'],['../index.html#autotoc_md303',1,'🛡️ Robustness Features']]],
  ['feedback_20voor_20iot_20device_10',['Visuele Feedback voor IoT Device',['../led_doc.html#autotoc_md101',1,'']]],
  ['feedback_20waarde_11',['LED Feedback Waarde',['../led_doc.html#autotoc_md114',1,'']]],
  ['field_20definitions_12',['Field Definitions',['../message_queue_doc.html#autotoc_md143',1,'']]],
  ['file_20c_20template_13',['Source File (.c) Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md488',1,'']]],
  ['file_20h_20template_14',['Header File (.h) Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md489',1,'']]],
  ['file_20structuur_15',['File Structuur',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md487',1,'']]],
  ['files_16',['Multiple Source Files',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md503',1,'']]],
  ['files_17',['Include Order (in .c files)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md477',1,'']]],
  ['files_20h_18',['Header Files (.h)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md476',1,'']]],
  ['filosofie_19',['📋 Filosofie',['../doxygen_guidelines.html#autotoc_md631',1,'']]],
  ['firmware_20',['Firmware',['../provisioning.html#autotoc_md399',1,'Stap 1: Flash Productie Modem Firmware'],['../provisioning.html#autotoc_md393',1,'Stap 1: Flash PTI Modem Firmware']]],
  ['firmware_20documentatie_21',['SolarResult Dinnis Core - Firmware Documentatie',['../index.html',1,'']]],
  ['firmware_20downloaden_22',['1.3 Modem Firmware Downloaden',['../provisioning.html#autotoc_md381',1,'']]],
  ['firmware_20image_23',['Corrupte Firmware Image',['../cloud_doc.html#autotoc_md37',1,'']]],
  ['firmware_20v2_200_203_24',['Download Modem Firmware v2.0.3',['../provisioning.html#autotoc_md382',1,'']]],
  ['firmware_20v2_203_208_25',['Download PTI Modem Firmware v2.3.8',['../provisioning.html#autotoc_md383',1,'']]],
  ['first_20investigation_26',['5.2 Fundamenteel Principe: Code-First Investigation',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md597',1,'']]],
  ['fixed_20point_27',['Waarom Integer Fixed-Point?',['../p_one_doc.html#autotoc_md199',1,'']]],
  ['flags_28',['Flags',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md614',1,'4.1 Taalgebruik Red Flags'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md615',1,'4.2 Structurele Red Flags'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md616',1,'4.3 Feature Consistency Red Flags'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md613',1,'Fase 4: Documentatie Anti-Patterns (Red Flags)']]],
  ['flash_20capacity_29',['Flash Capacity',['../cloud_doc.html#autotoc_md38',1,'']]],
  ['flash_20instructies_30',['📦 Flash Instructies',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md341',1,'']]],
  ['flash_20met_20custom_20runner_31',['Flash met Custom Runner',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md344',1,'']]],
  ['flash_20modem_20shell_32',['Stap 3: Flash Modem Shell',['../provisioning.html#autotoc_md395',1,'']]],
  ['flash_20naar_20device_33',['Flash naar Device',['../provisioning.html#autotoc_md404',1,'']]],
  ['flash_20productie_20modem_20firmware_34',['Stap 1: Flash Productie Modem Firmware',['../provisioning.html#autotoc_md399',1,'']]],
  ['flash_20pti_20modem_20firmware_35',['Stap 1: Flash PTI Modem Firmware',['../provisioning.html#autotoc_md393',1,'']]],
  ['flash_20ram_36',['&quot;Out of Flash/RAM&quot;',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md365',1,'']]],
  ['flash_20support_37',['Priority 1: External Flash Support',['../cloud_doc.html#autotoc_md61',1,'']]],
  ['flashen_38',['2.3 User Applicatie Flashen',['../provisioning.html#autotoc_md402',1,'']]],
  ['flow_39',['Flow',['../p_one_doc.html#autotoc_md192',1,'ACQ_TRIGGER Flow'],['../energy_pulse_doc.html#autotoc_md79',1,'Data Flow'],['../cloud_doc.html#autotoc_md28',1,'FOTA Event Flow'],['../message_queue_doc.html#autotoc_md131',1,'Gecoördineerde Data Collectie Flow'],['../network_doc.html#autotoc_md166',1,'Network Status Flow'],['../p_one_doc.html#autotoc_md193',1,'PUBLISH Flow'],['../energy_pulse_doc.html#autotoc_md77',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../led_doc.html#autotoc_md104',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../message_queue_doc.html#autotoc_md130',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../network_doc.html#autotoc_md165',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../reboot_doc.html#autotoc_md236',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../timing_doc.html#autotoc_md266',1,'Wat? (Functionaliteit &amp; Data Flow)']]],
  ['flow_20module_20interacties_40',['🔄 Data Flow &amp;amp; Module Interacties',['../index.html#autotoc_md289',1,'']]],
  ['flow_20scenarios_41',['Message Flow Scenarios',['../index.html#autotoc_md292',1,'']]],
  ['format_42',['Format',['../message_queue_doc.html#autotoc_md140',1,'Cloud Message Format'],['../message_queue_doc.html#autotoc_md133',1,'Message Format']]],
  ['formaten_43',['❗ Inconsistente Titel Formaten',['../group__Titel.html#autotoc_md658',1,'']]],
  ['formattering_44',['Indentatie en Formattering',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md522',1,'']]],
  ['formattering_20regels_45',['Code Style - Formattering Regels',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html',1,'']]],
  ['forward_20declarations_46',['Forward Declarations',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md479',1,'Forward Declarations'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md481',1,'State Machine Forward Declarations']]],
  ['fota_47',['FOTA',['../cloud_doc.html#autotoc_md36',1,'Netwerk Loss During FOTA'],['../cloud_doc.html#autotoc_md43',1,'Outbound (Using FOTA)']]],
  ['fota_20channel_20publishing_48',['FOTA Channel Publishing',['../cloud_doc.html#autotoc_md33',1,'']]],
  ['fota_20end_20to_20end_20test_49',['FOTA End-to-End Test',['../cloud_doc.html#autotoc_md52',1,'']]],
  ['fota_20event_20flow_50',['FOTA Event Flow',['../cloud_doc.html#autotoc_md28',1,'']]],
  ['fota_20image_20generatie_51',['FOTA Image Generatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md369',1,'']]],
  ['fota_20orchestratie_52',['FOTA Orchestratie',['../cloud_doc.html#autotoc_md24',1,'']]],
  ['fota_20requires_53',['Inbound (FOTA Requires)',['../cloud_doc.html#autotoc_md42',1,'']]],
  ['fota_20windows_54',['Priority 2: Scheduled FOTA Windows',['../cloud_doc.html#autotoc_md62',1,'']]],
  ['found_55',['found',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md363',1,'"Board not found"'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md362',1,'"West command not found"']]],
  ['fout_20verzonnen_20content_20_3a_56',['❗ FOUT (verzonnen content):',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md587',1,'']]],
  ['fouten_20door_20niet_20te_20verifiëren_3a_57',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md586',1,'']]],
  ['frame_20level_20timing_2087_20µs_58',['Frame-Level Timing (87 µs)',['../p_one_doc.html#autotoc_md214',1,'']]],
  ['frame_20timing_20fundamentals_59',['UART Frame Timing Fundamentals',['../p_one_doc.html#autotoc_md208',1,'']]],
  ['functies_60',['Functies',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md529',1,'']]],
  ['functionaliteit_61',['Functionaliteit',['../app_doc.html#autotoc_md7',1,'Functionaliteit'],['../p_one_doc.html#autotoc_md184',1,'Functionaliteit'],['../cloud_doc.html#autotoc_md26',1,'Wat? (Functionaliteit)']]],
  ['functionaliteit_20data_20flow_62',['Functionaliteit Data Flow',['../energy_pulse_doc.html#autotoc_md77',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../led_doc.html#autotoc_md104',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../message_queue_doc.html#autotoc_md130',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../network_doc.html#autotoc_md165',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../reboot_doc.html#autotoc_md236',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../timing_doc.html#autotoc_md266',1,'Wat? (Functionaliteit &amp; Data Flow)']]],
  ['functions_63',['State Handler Functions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md435',1,'']]],
  ['fundamentals_64',['Fundamentals',['../p_one_doc.html#autotoc_md208',1,'UART Frame Timing Fundamentals'],['../p_one_doc.html#autotoc_md187',1,'UART Timing Calculations - Fundamentals']]],
  ['fundamenteel_20principe_3a_20code_20first_20investigation_65',['5.2 Fundamenteel Principe: Code-First Investigation',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md597',1,'']]],
  ['future_20uitbreidingen_66',['Future Uitbreidingen',['../led_doc.html#autotoc_md117',1,'']]]
];
