var searchData=
[
  ['h_0',['Header Files (.h)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md276',1,'']]],
  ['h_20template_1',['Header File (.h) Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md289',1,'']]],
  ['handleidingen_2',['📚 Handleidingen',['../index.html#autotoc_md210',1,'']]],
  ['handler_20functions_3',['State Handler Functions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md235',1,'']]],
  ['handlers_4',['Work Queue Handlers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md241',1,'']]],
  ['handling_5',['Handling',['../energy_pulse_doc.html#autotoc_md47',1,'Error Handling'],['../app_doc.html#autotoc_md18',1,'Native Sim Handling']]],
  ['handling_20en_20return_20values_6',['Error Handling en Return Values',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md219',1,'']]],
  ['handling_20periodieke_20triggers_7',['2. ZBUS Message Handling (Periodieke Triggers)',['../p_one_doc.html#autotoc_md110',1,'']]],
  ['hardware_20interaction_8',['Hardware Interaction',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md249',1,'']]],
  ['hardware_20ondersteuning_9',['🔌 Hardware Ondersteuning',['../index.html#autotoc_md194',1,'']]],
  ['hardware_20watchdog_10',['3.1 Hardware Watchdog',['../app_doc.html#autotoc_md6',1,'']]],
  ['header_20file_20h_20template_11',['Header File (.h) Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md289',1,'']]],
  ['header_20files_20h_12',['Header Files (.h)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md276',1,'']]],
  ['header_20html_13',['Header HTML (&lt;span class=&quot;tt&quot;&gt;docs/header.html&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md441',1,'']]],
  ['header_20html_20docs_20header_20html_14',['Header HTML (&lt;span class=&quot;tt&quot;&gt;docs/header.html&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md441',1,'']]],
  ['header_20visibility_15',['Header Visibility',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md304',1,'']]],
  ['headers_16',['Headers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md275',1,'Include Guards en Headers'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md284',1,'Sectie Headers']]],
  ['heeft_17',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md314',1,'']]],
  ['herhalingen_20van_20blokken_20code_18',['2. Herhalingen van Blokken Code',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md378',1,'']]],
  ['het_20offset_20mechanisme_19',['Het Offset Mechanisme',['../md_modules_2timing_2timing__doc.html#autotoc_md164',1,'']]],
  ['het_20schrijven_20of_20bewerken_20van_20documentatie_3a_20',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md383',1,'']]],
  ['historische_20referenties_20en_20voor_20na_20vergelijkingen_21',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md379',1,'']]],
  ['history_20commands_20context_22',['Git History Commands (Context)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md422',1,'']]],
  ['hoe_20architectuur_20gedrag_23',['Hoe Architectuur Gedrag',['../energy_pulse_doc.html#autotoc_md44',1,'Hoe? (Architectuur &amp; Gedrag)'],['../led_doc.html#autotoc_md71',1,'Hoe? (Architectuur &amp; Gedrag)']]],
  ['html_24',['Header HTML (&lt;span class=&quot;tt&quot;&gt;docs/header.html&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md441',1,'']]],
  ['html_20docs_20header_20html_25',['Header HTML (&lt;span class=&quot;tt&quot;&gt;docs/header.html&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md441',1,'']]]
];
