var searchData=
[
  ['taalgebruik_20red_20flags_0',['4.1 Taalgebruik Red Flags',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md414',1,'']]],
  ['tabs_1',['Spaties (GEEN Tabs)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md323',1,'']]],
  ['task_20watchdog_2',['Task Watchdog',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md243',1,'']]],
  ['task_20watchdog_20indien_20module_20eigen_20thread_20heeft_3',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md314',1,'']]],
  ['te_20verifiëren_3a_4',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md386',1,'']]],
  ['technische_20diepgang_5',['Technische Diepgang',['../p_one_doc.html#autotoc_md112',1,'']]],
  ['telegram_6',['Scenario 2: Maximum Length Telegram',['../p_one_doc.html#autotoc_md134',1,'']]],
  ['telegram_20timeout_20784_20ms_7',['Telegram Timeout (784 ms)',['../p_one_doc.html#autotoc_md130',1,'']]],
  ['telegram_20transmission_20time_8',['1. Maximum Telegram Transmission Time',['../p_one_doc.html#autotoc_md124',1,'']]],
  ['template_9',['Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md289',1,'Header File (.h) Template'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md288',1,'Source File (.c) Template']]],
  ['testing_10',['Testing',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md315',1,'']]],
  ['the_20air_11',['3.3 FOTA (Firmware-Over-The-Air)',['../cloud_doc.html#autotoc_md27',1,'']]],
  ['these_20specific_20timeouts_20matter_12',['Why These Specific Timeouts Matter',['../p_one_doc.html#autotoc_md127',1,'']]],
  ['thread_13',['Message Processing in Thread',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md231',1,'']]],
  ['thread_20heeft_14',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md314',1,'']]],
  ['thread_20loop_20met_20zbus_20smf_15',['Thread Loop met ZBUS + SMF',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md260',1,'']]],
  ['thread_20loop_20structuur_16',['Thread Loop Structuur',['../p_one_doc.html#autotoc_md111',1,'']]],
  ['thread_20model_17',['5.1 Thread Model',['../app_doc.html#autotoc_md15',1,'']]],
  ['thread_20scheiding_18',['Architectuur: Interrupt/Thread Scheiding',['../md_modules_2timing_2timing__doc.html#autotoc_md169',1,'']]],
  ['tijdlijn_19',['Complete Systeem Tijdlijn',['../md_modules_2timing_2timing__doc.html#autotoc_md167',1,'']]],
  ['time_20',['1. Maximum Telegram Transmission Time',['../p_one_doc.html#autotoc_md124',1,'']]],
  ['timeout_21',['3. Total Response Timeout',['../p_one_doc.html#autotoc_md126',1,'']]],
  ['timeout_22',['2. UART RX Timeout (Inter-byte timeout)',['../p_one_doc.html#autotoc_md125',1,'']]],
  ['timeout_2010_208s_23',['Response Timeout (10.8s)',['../p_one_doc.html#autotoc_md131',1,'']]],
  ['timeout_20392_20ms_24',['Inter-byte Timeout (392 ms)',['../p_one_doc.html#autotoc_md129',1,'']]],
  ['timeout_20784_20ms_25',['Telegram Timeout (784 ms)',['../p_one_doc.html#autotoc_md130',1,'']]],
  ['timeout_20inter_20byte_20timeout_26',['2. UART RX Timeout (Inter-byte timeout)',['../p_one_doc.html#autotoc_md125',1,'']]],
  ['timeout_20mechanisme_27',['Work Queue en Timeout Mechanisme',['../md_modules_2reboot_2reboot__doc.html#autotoc_md153',1,'']]],
  ['timeout_20strategy_28',['Multi-Layer Timeout Strategy',['../p_one_doc.html#autotoc_md140',1,'']]],
  ['timeout_20trigger_29',['Scenario 3: Inter-byte Timeout Trigger',['../p_one_doc.html#autotoc_md135',1,'']]],
  ['timeouts_20matter_30',['Why These Specific Timeouts Matter',['../p_one_doc.html#autotoc_md127',1,'']]],
  ['timer_20configuratie_31',['Timer Configuratie',['../md_modules_2timing_2timing__doc.html#autotoc_md170',1,'']]],
  ['timestamp_20strategie_32',['Timestamp Strategie',['../message_queue_module.html#mq_timestamp',1,'']]],
  ['timing_33',['Timing',['../md_modules_2timing_2timing__doc.html#autotoc_md163',1,'Gecoördineerde Timing'],['../p_one_doc.html#autotoc_md99',1,'UART Async API &amp; Timing']]],
  ['timing_2087_20µs_34',['Frame-Level Timing (87 µs)',['../p_one_doc.html#autotoc_md128',1,'']]],
  ['timing_20analyse_35',['📐 Appendix A: UART Timing Analyse',['../p_one_doc.html#autotoc_md120',1,'']]],
  ['timing_20behavior_20claims_36',['3.4 Timing &amp;amp; Behavior Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md411',1,'']]],
  ['timing_20berekening_37',['Timing Berekening',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md246',1,'']]],
  ['timing_20calculations_38',['Critical Timing Calculations',['../p_one_doc.html#autotoc_md123',1,'']]],
  ['timing_20calculations_20fundamentals_39',['UART Timing Calculations - Fundamentals',['../p_one_doc.html#autotoc_md100',1,'']]],
  ['timing_20diagrammen_40',['8. Timing Diagrammen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md371',1,'']]],
  ['timing_20fundamentals_41',['UART Frame Timing Fundamentals',['../p_one_doc.html#autotoc_md122',1,'']]],
  ['timing_20module_42',['Timing Module',['../md_modules_2timing_2timing__doc.html#autotoc_md159',1,'Timing Module'],['../md_modules_2timing_2timing__doc.html#autotoc_md162',1,'Waarom een Timing Module?']]],
  ['timing_20parameters_20summary_43',['Key Timing Parameters Summary',['../p_one_doc.html#autotoc_md139',1,'']]],
  ['timing_20uitleg_44',['7. Timing Uitleg',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md370',1,'']]],
  ['timing_20watchdog_45',['Timing &amp;amp; Watchdog',['../p_one_doc.html#autotoc_md116',1,'']]],
  ['timingnauwkeurigheid_46',['Timingnauwkeurigheid',['../md_modules_2timing_2timing__doc.html#autotoc_md175',1,'']]],
  ['titel_20formaten_47',['❗ Inconsistente Titel Formaten',['../group__Titel.html#autotoc_md458',1,'']]],
  ['toekomstige_20uitbreidingen_48',['Toekomstige Uitbreidingen',['../energy_pulse_doc.html#autotoc_md54',1,'']]],
  ['toelichting_49',['Toelichting',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md274',1,'']]],
  ['tools_20commands_50',['5.5 Practical Tools &amp;amp; Commands',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md420',1,'']]],
  ['total_20response_20timeout_51',['3. Total Response Timeout',['../p_one_doc.html#autotoc_md126',1,'']]],
  ['tracking_52',['Acknowledgement (ACK) Tracking',['../md_modules_2reboot_2reboot__doc.html#autotoc_md152',1,'']]],
  ['trade_20offs_53',['Trade offs',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md368',1,'5. Afwegingen (Trade-offs)'],['../energy_pulse_doc.html#autotoc_md53',1,'Design Trade-offs']]],
  ['transities_54',['9. State Machine Transities',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md372',1,'']]],
  ['transitions_55',['State Transitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md236',1,'']]],
  ['transmission_20elke_2030_20minuten_56',['☁️ Cloud Transmission (elke 30 minuten)',['../index.html#autotoc_md189',1,'']]],
  ['transmission_20time_57',['1. Maximum Telegram Transmission Time',['../p_one_doc.html#autotoc_md124',1,'']]],
  ['trigger_58',['Scenario 3: Inter-byte Timeout Trigger',['../p_one_doc.html#autotoc_md135',1,'']]],
  ['triggers_59',['2. ZBUS Message Handling (Periodieke Triggers)',['../p_one_doc.html#autotoc_md110',1,'']]],
  ['txt_60',['CMakeLists.txt',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md312',1,'']]],
  ['txt_20voor_20modules_61',['CMakeLists.txt voor Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md300',1,'']]],
  ['type_62',['Fase 3: Systematische Verificatie Per Claim Type',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md404',1,'']]],
  ['type_20aannames_63',['Type Aannames',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md256',1,'']]],
  ['types_64',['Types',['../doxygen_guidelines.html#autotoc_md433',1,'📚 Documentatie Types'],['../md_modules_2reboot_2reboot__doc.html#autotoc_md147',1,'Reboot Types']]],
  ['typische_20scenario_20s_65',['Typische Scenario&apos;s',['../led_doc.html#autotoc_md69',1,'']]]
];
