var searchData=
[
  ['data_20acquisitie_20buffering_0',['📥 Data Acquisitie &amp;amp; Buffering',['../index.html#autotoc_md186',1,'']]],
  ['data_20acquisitie_20en_20buffering_1',['3.2 Data Acquisitie en Buffering',['../cloud_doc.html#autotoc_md26',1,'']]],
  ['data_20acquisitie_20van_20dsmr_20meters_2',['Data Acquisitie van DSMR Meters',['../p_one_doc.html#autotoc_md98',1,'']]],
  ['data_20conversie_3',['OBIS Parsing &amp;amp; Data Conversie',['../p_one_doc.html#autotoc_md102',1,'']]],
  ['data_20flow_4',['Data Flow',['../energy_pulse_doc.html#autotoc_md41',1,'Data Flow'],['../md_modules_2timing_2timing__doc.html#autotoc_md165',1,'Functionaliteit en Data Flow'],['../energy_pulse_doc.html#autotoc_md39',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../led_doc.html#autotoc_md66',1,'Wat? (Functionaliteit &amp; Data Flow)']]],
  ['data_20flow_20state_20machine_5',['Data Flow &amp;amp; State Machine',['../message_queue_module.html#mq_dataflow',1,'']]],
  ['data_20flow_20zbus_20architectuur_6',['🔄 Data Flow &amp;amp; ZBUS Architectuur',['../index.html#autotoc_md182',1,'']]],
  ['data_20ontvangst_7',['1. UART Callbacks (Asynchrone Data Ontvangst)',['../p_one_doc.html#autotoc_md109',1,'']]],
  ['data_20output_8',['Data Output',['../p_one_doc.html#autotoc_md118',1,'']]],
  ['data_20request_20pin_20inverterende_20buffer_9',['GPIO Data Request Pin &amp;amp; Inverterende Buffer',['../p_one_doc.html#autotoc_md101',1,'']]],
  ['data_20verwerking_10',['📊 Data Verwerking',['../index.html#autotoc_md195',1,'']]],
  ['data_20verzending_20naar_20de_20cloud_11',['� Data Verzending naar de Cloud',['../index.html#autotoc_md187',1,'']]],
  ['de_20cloud_12',['� Data Verzending naar de Cloud',['../index.html#autotoc_md187',1,'']]],
  ['de_20slag_13',['🚀 Aan de Slag',['../index.html#autotoc_md199',1,'']]],
  ['declaratie_14',['Error Variable Declaratie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md220',1,'']]],
  ['declarations_15',['Declarations',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md279',1,'Forward Declarations'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md281',1,'State Machine Forward Declarations'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md341',1,'Variable Declarations']]],
  ['declarations_20vs_20definitions_16',['Channel Declarations vs Definitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md294',1,'']]],
  ['define_17',['enum vs define',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md348',1,'']]],
  ['defines_18',['Constanten en Defines',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md331',1,'']]],
  ['definiëren_19',['Module Groepen Definiëren',['../doxygen_guidelines.html#autotoc_md447',1,'']]],
  ['definition_20',['Custom Board Definition',['../index.html#autotoc_md201',1,'']]],
  ['definitions_21',['Channel Declarations vs Definitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md294',1,'']]],
  ['dependencies_22',['Critical Dependencies',['../p_one_doc.html#autotoc_md136',1,'']]],
  ['design_23',['Design',['../md_modules_2network_2network__doc.html#autotoc_md81',1,'grand_parent: Design'],['../md_modules_2reboot_2reboot__doc.html#autotoc_md141',1,'grand_parent: Design'],['../md_modules_2timing_2timing__doc.html#autotoc_md158',1,'grand_parent: Design']]],
  ['design_20rationale_24',['2. Implementatie Design Rationale',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md365',1,'']]],
  ['design_20trade_20offs_25',['Design Trade-offs',['../energy_pulse_doc.html#autotoc_md53',1,'']]],
  ['device_26',['Visuele Feedback voor IoT Device',['../led_doc.html#autotoc_md63',1,'']]],
  ['device_20readiness_20checks_27',['Device Readiness Checks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md250',1,'']]],
  ['device_20response_28',['Scenario 1: Slow P1 Device Response',['../p_one_doc.html#autotoc_md133',1,'']]],
  ['diagram_29',['Componenten Diagram',['../md_modules_2network_2network__doc.html#autotoc_md85',1,'']]],
  ['diagrammen_30',['8. Timing Diagrammen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md371',1,'']]],
  ['diepgang_31',['Technische Diepgang',['../p_one_doc.html#autotoc_md112',1,'']]],
  ['dit_20protocol_32',['5.1 Waarom dit Protocol?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md395',1,'']]],
  ['dit_20zo_20belangrijk_33',['Waarom is dit zo belangrijk?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md390',1,'']]],
  ['docs_20doxygen_20custom_20css_34',['Custom CSS (&lt;span class=&quot;tt&quot;&gt;docs/doxygen-custom.css&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md440',1,'']]],
  ['docs_20header_20html_35',['Header HTML (&lt;span class=&quot;tt&quot;&gt;docs/header.html&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md441',1,'']]],
  ['documentatie_36',['Documentatie',['../doxygen_guidelines.html#autotoc_md443',1,'📝 Module Documentatie'],['../app_doc.html',1,'App Module - Documentatie'],['../cloud_doc.html',1,'Cloud Module - Documentatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md337',1,'Comments en Documentatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md316',1,'Documentatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md339',1,'Doxygen Documentatie'],['../energy_pulse_doc.html',1,'Energy Pulse Module - Documentatie'],['../led_doc.html',1,'LED Module - Documentatie'],['../p_one_doc.html',1,'P1 DSMR Module - Documentatie'],['../index.html',1,'SolarResult Energy Core - Firmware Documentatie']]],
  ['documentatie_20anti_20patterns_20red_20flags_37',['Fase 4: Documentatie Anti-Patterns (Red Flags)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md413',1,'']]],
  ['documentatie_20guidelines_38',['Doxygen Documentatie Guidelines',['../doxygen_guidelines.html',1,'']]],
  ['documentatie_20niveau_39',['Documentatie Niveau',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md361',1,'']]],
  ['documentatie_20review_20sessie_40',['5.6 Checklist: Voor Documentatie Review Sessie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md425',1,'']]],
  ['documentatie_20richtlijnen_41',['Module Documentatie Richtlijnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html',1,'']]],
  ['documentatie_20structuur_42',['📚 Documentatie Structuur',['../index.html#autotoc_md204',1,'']]],
  ['documentatie_20types_43',['📚 Documentatie Types',['../doxygen_guidelines.html#autotoc_md433',1,'']]],
  ['documentatie_20verificatie_20protocol_44',['5. AI Agent Documentatie Verificatie Protocol',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md394',1,'']]],
  ['documentatie_20wijziging_3a_45',['Checklist voor elke documentatie wijziging:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md389',1,'']]],
  ['documentatie_3a_46',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md383',1,'']]],
  ['documentation_20claims_20extraction_47',['Fase 2: Documentation Claims Extraction',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md402',1,'']]],
  ['documenteren_48',['✅ Checklist: Nieuwe Module Documenteren',['../group__Titel.html#autotoc_md454',1,'']]],
  ['doel_20en_20verantwoordelijkheden_49',['2. Doel en Verantwoordelijkheden',['../app_doc.html#autotoc_md3',1,'']]],
  ['door_20niet_20te_20verifiëren_3a_50',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md386',1,'']]],
  ['doxyfile_20configuratie_51',['⚙️ Doxyfile Configuratie',['../doxygen_guidelines.html#autotoc_md437',1,'']]],
  ['doxygen_20custom_20css_52',['Custom CSS (&lt;span class=&quot;tt&quot;&gt;docs/doxygen-custom.css&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md440',1,'']]],
  ['doxygen_20documentatie_53',['Doxygen Documentatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md339',1,'']]],
  ['doxygen_20documentatie_20guidelines_54',['Doxygen Documentatie Guidelines',['../doxygen_guidelines.html',1,'']]],
  ['dsmr_20meters_55',['Data Acquisitie van DSMR Meters',['../p_one_doc.html#autotoc_md98',1,'']]],
  ['dsmr_20module_20documentatie_56',['P1 DSMR Module - Documentatie',['../p_one_doc.html',1,'']]]
];
