var searchData=
[
  ['a_3a_20uart_20timing_20analyse_0',['📐 Appendix A: UART Timing Analyse',['../p_one_doc.html#autotoc_md206',1,'']]],
  ['aan_20de_20slag_1',['🚀 Aan de Slag',['../index.html#autotoc_md305',1,'']]],
  ['aannames_2',['Type Aannames',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md405',1,'']]],
  ['accuracy_3',['Timing Accuracy',['../timing_doc.html#autotoc_md279',1,'']]],
  ['acknowledgement_20tracking_4',['Acknowledgement Tracking',['../reboot_doc.html#autotoc_md244',1,'']]],
  ['acq_5ftrigger_20flow_5',['ACQ_TRIGGER Flow',['../p_one_doc.html#autotoc_md192',1,'']]],
  ['acquisitie_6',['Gas Meting Acquisitie',['../p_one_doc.html#autotoc_md190',1,'']]],
  ['acquisitie_20van_20dsmr_20meters_7',['Data Acquisitie van DSMR Meters',['../p_one_doc.html#autotoc_md185',1,'']]],
  ['activeren_8',['1.2 nRF Connect Environment Activeren',['../provisioning.html#autotoc_md328',1,'']]],
  ['afhankelijkheden_20van_20andere_20modules_9',['10. Afhankelijkheden van Andere Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md522',1,'']]],
  ['afwegingen_20trade_20offs_10',['5. Afwegingen (Trade-offs)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md517',1,'']]],
  ['agent_20documentatie_20verificatie_20protocol_11',['5. AI Agent Documentatie Verificatie Protocol',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md543',1,'']]],
  ['ai_20agent_20documentatie_20verificatie_20protocol_12',['5. AI Agent Documentatie Verificatie Protocol',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md543',1,'']]],
  ['alle_20devices_20onboarden_13',['3.1 Alle Devices Onboarden',['../provisioning.html#autotoc_md356',1,'']]],
  ['als_20coördinatie_20mechanisme_14',['TRIGGER_CHAN als Coördinatie Mechanisme',['../app_doc.html#autotoc_md5',1,'']]],
  ['als_20safety_20mechanism_15',['Hardware Watchdog als Safety Mechanism',['../app_doc.html#autotoc_md4',1,'']]],
  ['altijd_20compileren_16',['Standaard Pattern (Altijd Compileren)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md450',1,'']]],
  ['analyse_17',['📐 Appendix A: UART Timing Analyse',['../p_one_doc.html#autotoc_md206',1,'']]],
  ['analysis_20commands_20voorbeelden_18',['Code Analysis Commands (Voorbeelden)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md570',1,'']]],
  ['anchor_20mismatch_19',['❗ Anchor Mismatch',['../group__Titel.html#autotoc_md606',1,'']]],
  ['and_20onboarding_20',['Provisioning and Onboarding',['../provisioning.html',1,'']]],
  ['andere_20modules_21',['10. Afhankelijkheden van Andere Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md522',1,'']]],
  ['anti_20patterns_20red_20flags_22',['Fase 4: Documentatie Anti-Patterns (Red Flags)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md562',1,'']]],
  ['api_20elementen_23',['Links naar API Elementen',['../group__Titel.html#autotoc_md597',1,'']]],
  ['api_20key_24',['nRF Cloud API Key',['../provisioning.html#autotoc_md357',1,'']]],
  ['api_20referentie_25',['📄 API Referentie',['../index.html#autotoc_md311',1,'']]],
  ['api_20timing_26',['UART Async API &amp;amp; Timing',['../p_one_doc.html#autotoc_md186',1,'']]],
  ['app_20module_20documentatie_27',['App Module - Documentatie',['../app_doc.html',1,'']]],
  ['appendix_20a_3a_20uart_20timing_20analyse_28',['📐 Appendix A: UART Timing Analyse',['../p_one_doc.html#autotoc_md206',1,'']]],
  ['applicatie_20flashen_29',['2.3 User Applicatie Flashen',['../provisioning.html#autotoc_md351',1,'']]],
  ['application_30',['Build de Dinnis Application',['../provisioning.html#autotoc_md352',1,'']]],
  ['architectuur_31',['Architectuur',['../index.html#autotoc_md286',1,'🏗️ Architectuur'],['../app_doc.html#autotoc_md10',1,'Architectuur'],['../p_one_doc.html#autotoc_md194',1,'Architectuur'],['../timing_doc.html#autotoc_md272',1,'Architectuur']]],
  ['architectuur_20gedrag_32',['Architectuur Gedrag',['../energy_pulse_doc.html#autotoc_md82',1,'Hoe? (Architectuur &amp; Gedrag)'],['../led_doc.html#autotoc_md109',1,'Hoe? (Architectuur &amp; Gedrag)'],['../message_queue_doc.html#autotoc_md135',1,'Hoe? (Architectuur &amp; Gedrag)'],['../network_doc.html#autotoc_md170',1,'Hoe? (Architectuur &amp; Gedrag)'],['../reboot_doc.html#autotoc_md242',1,'Hoe? (Architectuur &amp; Gedrag)'],['../timing_doc.html#autotoc_md271',1,'Hoe? (Architectuur &amp; Gedrag)']]],
  ['architectuur_20pattern_20claims_33',['3.1 Architectuur Pattern Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md554',1,'']]],
  ['arg_5funused_20macro_34',['ARG_UNUSED Macro',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md505',1,'']]],
  ['argumentaties_35',['4. Argumentaties',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md516',1,'']]],
  ['arithmetic_36',['Pointer Arithmetic',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md406',1,'']]],
  ['arrays_20en_20buffers_37',['Arrays en Buffers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md493',1,'']]],
  ['assertions_38',['Assertions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md374',1,'']]],
  ['async_20api_20timing_39',['UART Async API &amp;amp; Timing',['../p_one_doc.html#autotoc_md186',1,'']]],
  ['asynchrone_20data_20ontvangst_40',['1. UART Callbacks (Asynchrone Data Ontvangst)',['../p_one_doc.html#autotoc_md195',1,'']]]
];
