var searchData=
[
  ['waarde_0',['LED Feedback Waarde',['../led_doc.html#autotoc_md74',1,'']]],
  ['waarheid_1',['Fase 1: Build Code Inventory (Objectieve Waarheid)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md400',1,'']]],
  ['waarom_20dit_20protocol_2',['5.1 Waarom dit Protocol?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md395',1,'']]],
  ['waarom_20een_20reboot_20module_3',['Waarom een Reboot Module?',['../md_modules_2reboot_2reboot__doc.html#autotoc_md145',1,'']]],
  ['waarom_20een_20timing_20module_4',['Waarom een Timing Module?',['../md_modules_2timing_2timing__doc.html#autotoc_md162',1,'']]],
  ['waarom_20integer_20fixed_20point_5',['Waarom Integer Fixed-Point?',['../p_one_doc.html#autotoc_md113',1,'']]],
  ['waarom_20is_20dit_20zo_20belangrijk_6',['Waarom is dit zo belangrijk?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md390',1,'']]],
  ['waarom_20probleem_20motivatie_7',['Waarom? (Probleem &amp;amp; Motivatie)',['../led_doc.html#autotoc_md62',1,'']]],
  ['wachtrij_8',['Buffering en Wachtrij',['../message_queue_module.html#mq_buffering',1,'']]],
  ['wanneer_20gebruiken_9',['Wanneer Gebruiken',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md280',1,'']]],
  ['wat_20er_20niet_20in_20moet_10',['❗ Wat ER NIET in moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md376',1,'']]],
  ['wat_20er_20wel_20in_20moet_11',['✅ Wat ER WEL in moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md363',1,'']]],
  ['wat_20functionaliteit_20data_20flow_12',['Wat Functionaliteit Data Flow',['../energy_pulse_doc.html#autotoc_md39',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../led_doc.html#autotoc_md66',1,'Wat? (Functionaliteit &amp; Data Flow)']]],
  ['watchdog_13',['Watchdog',['../app_doc.html#autotoc_md6',1,'3.1 Hardware Watchdog'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md243',1,'Task Watchdog'],['../p_one_doc.html#autotoc_md116',1,'Timing &amp; Watchdog']]],
  ['watchdog_20callback_20behavior_14',['Watchdog Callback Behavior',['../app_doc.html#autotoc_md17',1,'']]],
  ['watchdog_20indien_20module_20eigen_20thread_20heeft_15',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md314',1,'']]],
  ['watchdog_20relationship_16',['Watchdog Relationship',['../p_one_doc.html#autotoc_md137',1,'']]],
  ['wel_20in_20moet_17',['✅ Wat ER WEL in moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md363',1,'']]],
  ['why_20these_20specific_20timeouts_20matter_18',['Why These Specific Timeouts Matter',['../p_one_doc.html#autotoc_md127',1,'']]],
  ['wijziging_3a_19',['Checklist voor elke documentatie wijziging:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md389',1,'']]],
  ['work_20pattern_20',['Periodic Work Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md261',1,'']]],
  ['work_20queue_20en_20timeout_20mechanisme_21',['Work Queue en Timeout Mechanisme',['../md_modules_2reboot_2reboot__doc.html#autotoc_md153',1,'']]],
  ['work_20queue_20handlers_22',['Work Queue Handlers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md241',1,'']]],
  ['workflow_205_20fasen_23',['5.4 Verification Workflow (5 Fasen)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md418',1,'']]]
];
