var searchData=
[
  ['validatie_0',['Validatie',['../p_one_doc.html#autotoc_md114',1,'CRC16 Validatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md352',1,'NULL Checks en Validatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md353',1,'Pointer Validatie']]],
  ['validation_1',['Input Validation',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md269',1,'']]],
  ['value_20conventies_2',['Return Value Conventies',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md222',1,'']]],
  ['values_3',['Error Handling en Return Values',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md219',1,'']]],
  ['van_20_5fdoc_20md_4',['Structuur van &lt;span class=&quot;tt&quot;&gt;&amp;lt;module&amp;gt;_doc.md&lt;/span&gt;',['../doxygen_guidelines.html#autotoc_md444',1,'']]],
  ['van_20andere_20modules_5',['10. Afhankelijkheden van Andere Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md373',1,'']]],
  ['van_20blokken_20code_6',['2. Herhalingen van Blokken Code',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md378',1,'']]],
  ['van_20documentatie_3a_7',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md383',1,'']]],
  ['van_20dsmr_20meters_8',['Data Acquisitie van DSMR Meters',['../p_one_doc.html#autotoc_md98',1,'']]],
  ['van_20fouten_20door_20niet_20te_20verifiëren_3a_9',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md386',1,'']]],
  ['variabelen_10',['Variabelen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md330',1,'']]],
  ['variable_20declaratie_11',['Error Variable Declaratie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md220',1,'']]],
  ['variable_20declarations_12',['Variable Declarations',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md341',1,'']]],
  ['verantwoordelijkheden_13',['2. Doel en Verantwoordelijkheden',['../app_doc.html#autotoc_md3',1,'']]],
  ['verboden_3a_14',['❗ VERBODEN:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md385',1,'']]],
  ['vereisten_20voor_20modules_15',['Implementatie Vereisten voor Modules',['../md_modules_2reboot_2reboot__doc.html#autotoc_md157',1,'']]],
  ['vergelijkingen_16',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md379',1,'']]],
  ['verifiëren_3a_17',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md386',1,'']]],
  ['verificatie_20en_20synchronisatie_20kritiek_20⚠️_18',['4. Code Verificatie en Synchronisatie (KRITIEK! ⚠️)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md381',1,'']]],
  ['verificatie_20per_20claim_20type_19',['Fase 3: Systematische Verificatie Per Claim Type',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md404',1,'']]],
  ['verificatie_20protocol_20',['5. AI Agent Documentatie Verificatie Protocol',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md394',1,'']]],
  ['verificatie_20strategie_21',['5.3 Systematische Verificatie Strategie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md399',1,'']]],
  ['verification_20shortcuts_22',['Verification Shortcuts',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md423',1,'']]],
  ['verification_20workflow_205_20fasen_23',['5.4 Verification Workflow (5 Fasen)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md418',1,'']]],
  ['verplichte_20stappen_3a_24',['✅ VERPLICHTE STAPPEN:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md384',1,'']]],
  ['verwerking_25',['📊 Data Verwerking',['../index.html#autotoc_md195',1,'']]],
  ['verzending_20naar_20de_20cloud_26',['� Data Verzending naar de Cloud',['../index.html#autotoc_md187',1,'']]],
  ['verzinnen_27',['Principe: NOOIT iets verzinnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md382',1,'']]],
  ['verzonnen_20content_20_3a_28',['❗ FOUT (verzonnen content):',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md387',1,'']]],
  ['visibility_29',['Header Visibility',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md304',1,'']]],
  ['visueel_20overzicht_30',['Visueel Overzicht',['../index.html#autotoc_md183',1,'']]],
  ['visuele_20feedback_20voor_20iot_20device_31',['Visuele Feedback voor IoT Device',['../led_doc.html#autotoc_md63',1,'']]],
  ['void_20vs_20int_20return_32',['Void vs Int Return',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md224',1,'']]],
  ['volgorde_33',['Volgorde',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html',1,'Code Structure - Organisatie en Volgorde'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md282',1,'Volgorde']]],
  ['volgorde_34',['Standaard Secties (in volgorde)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md285',1,'']]],
  ['voor_20documentatie_20review_20sessie_35',['5.6 Checklist: Voor Documentatie Review Sessie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md425',1,'']]],
  ['voor_20elke_20documentatie_20wijziging_3a_36',['Checklist voor elke documentatie wijziging:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md389',1,'']]],
  ['voor_20immediate_20scheduling_37',['K_NO_WAIT voor Immediate Scheduling',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md239',1,'']]],
  ['voor_20iot_20device_38',['Visuele Feedback voor IoT Device',['../led_doc.html#autotoc_md63',1,'']]],
  ['voor_20modules_39',['voor Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md300',1,'CMakeLists.txt voor Modules'],['../md_modules_2reboot_2reboot__doc.html#autotoc_md157',1,'Implementatie Vereisten voor Modules']]],
  ['voor_20na_20vergelijkingen_40',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md379',1,'']]],
  ['voor_20nieuwe_20module_41',['Checklist voor Nieuwe Module',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md247',1,'']]],
  ['voorbeelden_42',['Voorbeelden',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md377',1,'1. Code Implementatie Voorbeelden'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md421',1,'Code Analysis Commands (Voorbeelden)']]],
  ['voorbeelden_20van_20fouten_20door_20niet_20te_20verifiëren_3a_43',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md386',1,'']]],
  ['voordelen_44',['Remote Support Voordelen',['../led_doc.html#autotoc_md76',1,'']]],
  ['vs_20define_45',['enum vs define',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md348',1,'']]],
  ['vs_20definitions_46',['Channel Declarations vs Definitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md294',1,'']]],
  ['vs_20geforceerde_20shutdown_47',['Graceful vs. Geforceerde Shutdown',['../md_modules_2reboot_2reboot__doc.html#autotoc_md156',1,'']]],
  ['vs_20int_20return_48',['Void vs Int Return',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md224',1,'']]]
];
