var searchData=
[
  ['waarde_0',['LED Feedback Waarde',['../led_doc.html#autotoc_md118',1,'']]],
  ['waarheid_1',['Fase 1: Build Code Inventory (Objectieve Waarheid)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md553',1,'']]],
  ['waarom_2',['Waarom',['../app_doc.html#autotoc_md3',1,'']]],
  ['waarom_20design_20rationale_3',['Waarom Design Rationale',['../message_queue_doc.html#autotoc_md130',1,'Waarom? (Design Rationale)'],['../network_doc.html#autotoc_md165',1,'Waarom? (Design Rationale)']]],
  ['waarom_20dit_20protocol_4',['5.1 Waarom dit Protocol?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md548',1,'']]],
  ['waarom_20integer_20fixed_20point_5',['Waarom Integer Fixed-Point?',['../p_one_doc.html#autotoc_md203',1,'']]],
  ['waarom_20is_20dit_20zo_20belangrijk_6',['Waarom is dit zo belangrijk?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md543',1,'']]],
  ['waarom_20motivatie_7',['Waarom? (Motivatie)',['../cloud_doc.html#autotoc_md22',1,'']]],
  ['waarom_20probleem_20motivatie_8',['Waarom Probleem Motivatie',['../energy_pulse_doc.html#autotoc_md73',1,'Waarom? (Probleem &amp; Motivatie)'],['../led_doc.html#autotoc_md100',1,'Waarom? (Probleem &amp; Motivatie)'],['../reboot_doc.html#autotoc_md236',1,'Waarom? (Probleem &amp; Motivatie)'],['../timing_doc.html#autotoc_md266',1,'Waarom? (Probleem &amp; Motivatie)']]],
  ['wanneer_20gebruiken_9',['Wanneer Gebruiken',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md433',1,'']]],
  ['warning_3a_20intentional_20crash_10',['Rollback Test (Warning: Intentional Crash)',['../cloud_doc.html#autotoc_md53',1,'']]],
  ['wat_11',['Wat',['../app_doc.html#autotoc_md6',1,'']]],
  ['wat_20er_20niet_20in_20moet_12',['❗ Wat ER NIET in moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md529',1,'']]],
  ['wat_20er_20wel_20in_20moet_13',['✅ Wat ER WEL in moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md516',1,'']]],
  ['wat_20functionaliteit_14',['Wat? (Functionaliteit)',['../cloud_doc.html#autotoc_md26',1,'']]],
  ['wat_20functionaliteit_20data_20flow_15',['Wat Functionaliteit Data Flow',['../energy_pulse_doc.html#autotoc_md77',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../led_doc.html#autotoc_md104',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../message_queue_doc.html#autotoc_md134',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../network_doc.html#autotoc_md169',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../reboot_doc.html#autotoc_md240',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../timing_doc.html#autotoc_md270',1,'Wat? (Functionaliteit &amp; Data Flow)']]],
  ['watchdog_16',['Watchdog',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md396',1,'Task Watchdog'],['../p_one_doc.html#autotoc_md206',1,'Timing &amp; Watchdog']]],
  ['watchdog_20als_20safety_20mechanism_17',['Hardware Watchdog als Safety Mechanism',['../app_doc.html#autotoc_md4',1,'']]],
  ['watchdog_20callback_20behavior_18',['Watchdog Callback Behavior',['../app_doc.html#autotoc_md14',1,'']]],
  ['watchdog_20indien_20module_20eigen_20thread_20heeft_19',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md467',1,'']]],
  ['watchdog_20relationship_20',['Watchdog Relationship',['../p_one_doc.html#autotoc_md227',1,'']]],
  ['wel_20in_20moet_21',['✅ Wat ER WEL in moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md516',1,'']]],
  ['why_20these_20specific_20timeouts_20matter_22',['Why These Specific Timeouts Matter',['../p_one_doc.html#autotoc_md217',1,'']]],
  ['wijziging_3a_23',['Checklist voor elke documentatie wijziging:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md542',1,'']]],
  ['window_24',['Boot Confirmation Window',['../cloud_doc.html#autotoc_md58',1,'']]],
  ['windows_25',['Priority 2: Scheduled FOTA Windows',['../cloud_doc.html#autotoc_md62',1,'']]],
  ['work_20pattern_26',['Periodic Work Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md414',1,'']]],
  ['work_20queue_20handlers_27',['Work Queue Handlers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md394',1,'']]],
  ['work_20queue_20pattern_28',['Work Queue Pattern',['../reboot_doc.html#autotoc_md250',1,'']]],
  ['workflow_205_20fasen_29',['5.4 Verification Workflow (5 Fasen)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md571',1,'']]]
];
