var searchData=
[
  ['rationale_0',['2. Implementatie Design Rationale',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md365',1,'']]],
  ['readiness_20checks_1',['Device Readiness Checks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md250',1,'']]],
  ['readme_20s_2',['📁 Module README&apos;s',['../index.html#autotoc_md207',1,'']]],
  ['reboot_20module_3',['Reboot Module',['../md_modules_2reboot_2reboot__doc.html#autotoc_md142',1,'Reboot Module'],['../md_modules_2reboot_2reboot__doc.html#autotoc_md145',1,'Waarom een Reboot Module?']]],
  ['reboot_20types_4',['Reboot Types',['../md_modules_2reboot_2reboot__doc.html#autotoc_md147',1,'']]],
  ['red_20flags_5',['Red Flags',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md414',1,'4.1 Taalgebruik Red Flags'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md415',1,'4.2 Structurele Red Flags'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md416',1,'4.3 Feature Consistency Red Flags'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md413',1,'Fase 4: Documentatie Anti-Patterns (Red Flags)']]],
  ['referencing_6',['🔗 Cross-Referencing',['../doxygen_guidelines.html#autotoc_md446',1,'']]],
  ['referentie_7',['📄 API Referentie',['../index.html#autotoc_md205',1,'']]],
  ['referentie_20modules_8',['Referentie Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md318',1,'']]],
  ['referenties_20en_20voor_20na_20vergelijkingen_9',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md379',1,'']]],
  ['regels_10',['Regels',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html',1,'Code Style - Formattering Regels'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md324',1,'Lege Regels']]],
  ['related_20pages_11',['📚 Related Pages',['../group__Titel.html#autotoc_md450',1,'']]],
  ['relationship_12',['Watchdog Relationship',['../p_one_doc.html#autotoc_md137',1,'']]],
  ['remote_20support_20voordelen_13',['Remote Support Voordelen',['../led_doc.html#autotoc_md76',1,'']]],
  ['request_20pin_20inverterende_20buffer_14',['GPIO Data Request Pin &amp;amp; Inverterende Buffer',['../p_one_doc.html#autotoc_md101',1,'']]],
  ['resource_20management_15',['Resource Management',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md238',1,'']]],
  ['resources_16',['Resources',['../index.html#autotoc_md211',1,'🌐 Externe Resources'],['../group__Titel.html#autotoc_md462',1,'📚 Resources'],['../group__Titel.html#autotoc_md465',1,'📚 Resources']]],
  ['response_17',['Scenario 1: Slow P1 Device Response',['../p_one_doc.html#autotoc_md133',1,'']]],
  ['response_20timeout_18',['3. Total Response Timeout',['../p_one_doc.html#autotoc_md126',1,'']]],
  ['response_20timeout_2010_208s_19',['Response Timeout (10.8s)',['../p_one_doc.html#autotoc_md131',1,'']]],
  ['resultaten_20en_20impact_20',['Resultaten en Impact',['../md_modules_2timing_2timing__doc.html#autotoc_md173',1,'']]],
  ['resultaten_20impact_21',['Resultaten &amp;amp; Impact',['../energy_pulse_doc.html#autotoc_md50',1,'']]],
  ['return_22',['Void vs Int Return',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md224',1,'']]],
  ['return_20patterns_23',['Return Patterns',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md221',1,'']]],
  ['return_20value_20conventies_24',['Return Value Conventies',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md222',1,'']]],
  ['return_20values_25',['Error Handling en Return Values',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md219',1,'']]],
  ['review_20sessie_26',['5.6 Checklist: Voor Documentatie Review Sessie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md425',1,'']]],
  ['richtlijnen_27',['Richtlijnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html',1,'Best Practices - Praktische Richtlijnen'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html',1,'Module Documentatie Richtlijnen']]],
  ['robustness_20features_28',['🛡️ Robustness Features',['../index.html#autotoc_md197',1,'']]],
  ['robuustheid_29',['Robuustheid',['../p_one_doc.html#autotoc_md115',1,'Edge Cases &amp; Robuustheid'],['../md_modules_2network_2network__doc.html#autotoc_md90',1,'Foutafhandeling en Robuustheid']]],
  ['rolling_20statistics_20sampling_30',['Rolling Statistics &amp;amp; Sampling',['../p_one_doc.html#autotoc_md103',1,'']]],
  ['runtime_20gedrag_31',['Runtime Gedrag',['../energy_pulse_doc.html#autotoc_md46',1,'']]],
  ['rx_20timeout_20inter_20byte_20timeout_32',['2. UART RX Timeout (Inter-byte timeout)',['../p_one_doc.html#autotoc_md125',1,'']]]
];
