var searchData=
[
  ['p1_20device_20response_0',['Scenario 1: Slow P1 Device Response',['../p_one_doc.html#autotoc_md219',1,'']]],
  ['p1_20dsmr_20module_20documentatie_1',['P1 DSMR Module - Documentatie',['../p_one_doc.html',1,'']]],
  ['pages_2',['📚 Related Pages',['../group__Titel.html#autotoc_md599',1,'']]],
  ['parameters_20summary_3',['Key Timing Parameters Summary',['../p_one_doc.html#autotoc_md225',1,'']]],
  ['parent_20cmakelists_4',['Integration in Parent CMakeLists',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md454',1,'']]],
  ['parsing_20data_20conversie_5',['OBIS Parsing &amp;amp; Data Conversie',['../p_one_doc.html#autotoc_md188',1,'']]],
  ['partition_20layout_20pm_5fstatic_20yml_6',['Partition Layout (pm_static.yml)',['../cloud_doc.html#autotoc_md48',1,'']]],
  ['patronen_7',['LED Status Patronen',['../led_doc.html#autotoc_md105',1,'']]],
  ['pattern_8',['Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md411',1,'Callback Pattern'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md451',1,'Conditionele Compilatie Pattern'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md378',1,'LISTENER Pattern'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md394',1,'Module Setup Pattern'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md377',1,'MSG_SUBSCRIBER Pattern'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md410',1,'Periodic Work Pattern'],['../reboot_doc.html#autotoc_md246',1,'Work Queue Pattern']]],
  ['pattern_20altijd_20compileren_9',['Standaard Pattern (Altijd Compileren)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md450',1,'']]],
  ['pattern_20claims_10',['Pattern Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md554',1,'3.1 Architectuur Pattern Claims'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md556',1,'3.2 Communication Pattern Claims']]],
  ['pattern_20implementation_11',['Pattern Implementation',['../led_doc.html#autotoc_md111',1,'']]],
  ['patterns_12',['Patterns',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md408',1,'Common Patterns'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md401',1,'LED Control Patterns'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md370',1,'Return Patterns'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md376',1,'ZBUS Patterns']]],
  ['patterns_20red_20flags_13',['Fase 4: Documentatie Anti-Patterns (Red Flags)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md562',1,'']]],
  ['patterns_20smf_14',['State Machine Patterns (SMF)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md382',1,'']]],
  ['per_20claim_20type_15',['Fase 3: Systematische Verificatie Per Claim Type',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md553',1,'']]],
  ['per_20device_16',['Per Device',['../provisioning.html#autotoc_md364',1,'']]],
  ['per_20device_20provisioneren_17',['🔧 Fase 2: Per Device Provisioneren',['../provisioning.html#autotoc_md340',1,'']]],
  ['performance_18',['Performance',['../energy_pulse_doc.html#autotoc_md89',1,'Geheugen &amp; Performance'],['../timing_doc.html#autotoc_md278',1,'Geheugen &amp; Performance'],['../cloud_doc.html#autotoc_md55',1,'Timing &amp; Performance']]],
  ['performance_20en_20optimization_19',['Performance en Optimization',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md413',1,'']]],
  ['periodic_20work_20pattern_20',['Periodic Work Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md410',1,'']]],
  ['periodieke_20triggers_21',['2. ZBUS Message Handling (Periodieke Triggers)',['../p_one_doc.html#autotoc_md196',1,'']]],
  ['persistente_20energietellers_22',['Persistente Energietellers',['../energy_pulse_doc.html#autotoc_md74',1,'']]],
  ['pitfalls_23',['🚨 Common Pitfalls',['../group__Titel.html#autotoc_md605',1,'']]],
  ['pm_5fstatic_20yml_24',['Partition Layout (pm_static.yml)',['../cloud_doc.html#autotoc_md48',1,'']]],
  ['point_25',['Waarom Integer Fixed-Point?',['../p_one_doc.html#autotoc_md199',1,'']]],
  ['pointer_20arithmetic_26',['Pointer Arithmetic',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md406',1,'']]],
  ['pointer_20validatie_27',['Pointer Validatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md502',1,'']]],
  ['pointers_28',['Pointers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md484',1,'']]],
  ['portability_29',['Undefined Behavior en Portability',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md403',1,'']]],
  ['practical_20tools_20commands_30',['5.5 Practical Tools &amp;amp; Commands',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md569',1,'']]],
  ['practices_20praktische_20richtlijnen_31',['Best Practices - Praktische Richtlijnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html',1,'']]],
  ['praktische_20richtlijnen_32',['Best Practices - Praktische Richtlijnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html',1,'']]],
  ['presence_20scenarios_33',['Message Presence Scenarios',['../message_queue_doc.html#autotoc_md145',1,'']]],
  ['prevention_34',['Buffer Overflow Prevention',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md419',1,'']]],
  ['principe_3a_20code_20first_20investigation_35',['5.2 Fundamenteel Principe: Code-First Investigation',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md546',1,'']]],
  ['principe_3a_20nooit_20iets_20verzinnen_36',['Principe: NOOIT iets verzinnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md531',1,'']]],
  ['priority_201_3a_20external_20flash_20support_37',['Priority 1: External Flash Support',['../cloud_doc.html#autotoc_md61',1,'']]],
  ['priority_202_3a_20scheduled_20fota_20windows_38',['Priority 2: Scheduled FOTA Windows',['../cloud_doc.html#autotoc_md62',1,'']]],
  ['priority_203_3a_20delta_20updates_39',['Priority 3: Delta Updates',['../cloud_doc.html#autotoc_md63',1,'']]],
  ['prj_20conf_40',['Kconfig (prj.conf)',['../cloud_doc.html#autotoc_md46',1,'']]],
  ['probleem_20motivatie_41',['Probleem Motivatie',['../energy_pulse_doc.html#autotoc_md73',1,'Waarom? (Probleem &amp; Motivatie)'],['../led_doc.html#autotoc_md100',1,'Waarom? (Probleem &amp; Motivatie)'],['../reboot_doc.html#autotoc_md232',1,'Waarom? (Probleem &amp; Motivatie)'],['../timing_doc.html#autotoc_md262',1,'Waarom? (Probleem &amp; Motivatie)']]],
  ['processing_20in_20thread_42',['Message Processing in Thread',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md380',1,'']]],
  ['productie_20modem_20firmware_43',['Stap 1: Flash Productie Modem Firmware',['../provisioning.html#autotoc_md348',1,'']]],
  ['programmeren_44',['Programmeren',['../provisioning.html#autotoc_md341',1,'2.1 IMEI Programmeren'],['../provisioning.html#autotoc_md349',1,'Stap 2: Certificaten Programmeren']]],
  ['project_20layout_45',['🏗️ Project Layout',['../doxygen_guidelines.html#autotoc_md584',1,'']]],
  ['protection_46',['Boot Loop Protection',['../cloud_doc.html#autotoc_md39',1,'']]],
  ['protocol_47',['Protocol',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md543',1,'5. AI Agent Documentatie Verificatie Protocol'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md544',1,'5.1 Waarom dit Protocol?'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md578',1,'5.8 Samenvatting Protocol'],['../reboot_doc.html#autotoc_md239',1,'ZBUS Protocol']]],
  ['provisioneren_48',['🔧 Fase 2: Per Device Provisioneren',['../provisioning.html#autotoc_md340',1,'']]],
  ['provisioning_20and_20onboarding_49',['Provisioning and Onboarding',['../provisioning.html',1,'']]],
  ['pti_20modem_20firmware_50',['Stap 1: Flash PTI Modem Firmware',['../provisioning.html#autotoc_md342',1,'']]],
  ['pti_20modem_20firmware_20v2_203_208_51',['Download PTI Modem Firmware v2.3.8',['../provisioning.html#autotoc_md332',1,'']]],
  ['publish_20flow_52',['PUBLISH Flow',['../p_one_doc.html#autotoc_md193',1,'']]],
  ['publish_20statistics_20elke_2010_20minuten_53',['📊 Publish Statistics (elke 10 minuten)',['../index.html#autotoc_md294',1,'']]],
  ['published_54',['ZBUS Channels (Published)',['../timing_doc.html#autotoc_md267',1,'']]],
  ['publishing_55',['FOTA Channel Publishing',['../cloud_doc.html#autotoc_md33',1,'']]],
  ['publishing_20messages_56',['Publishing Messages',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md379',1,'']]],
  ['pulse_20module_20documentatie_57',['Energy Pulse Module - Documentatie',['../energy_pulse_doc.html',1,'']]]
];
