var searchData=
[
  ['c_20files_0',['Include Order (in .c files)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md430',1,'']]],
  ['c_20template_1',['Source File (.c) Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md441',1,'']]],
  ['calculations_2',['Critical Timing Calculations',['../p_one_doc.html#autotoc_md213',1,'']]],
  ['calculations_20fundamentals_3',['UART Timing Calculations - Fundamentals',['../p_one_doc.html#autotoc_md191',1,'']]],
  ['call_20graphs_4',['📊 Call Graphs',['../index.html#autotoc_md316',1,'']]],
  ['callback_20behavior_5',['Watchdog Callback Behavior',['../app_doc.html#autotoc_md14',1,'']]],
  ['callback_20pattern_6',['Callback Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md415',1,'']]],
  ['callbacks_7',['GPIO Callbacks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md404',1,'']]],
  ['callbacks_20asynchrone_20data_20ontvangst_8',['1. UART Callbacks (Asynchrone Data Ontvangst)',['../p_one_doc.html#autotoc_md199',1,'']]],
  ['capacity_9',['Flash Capacity',['../cloud_doc.html#autotoc_md38',1,'']]],
  ['case_20scenarios_10',['Edge Case Scenarios',['../p_one_doc.html#autotoc_md222',1,'']]],
  ['case_3a_20typische_20dag_11',['Use Case: Typische Dag',['../timing_doc.html#autotoc_md273',1,'']]],
  ['cases_12',['Cases',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md519',1,'3. Edge Cases'],['../cloud_doc.html#autotoc_md35',1,'Edge Cases']]],
  ['cases_20robuustheid_13',['Edge Cases &amp;amp; Robuustheid',['../p_one_doc.html#autotoc_md205',1,'']]],
  ['certificaten_20genereren_14',['1.5 Certificaten Genereren',['../provisioning.html#autotoc_md340',1,'']]],
  ['certificaten_20installeren_15',['2.2 Certificaten Installeren',['../provisioning.html#autotoc_md351',1,'']]],
  ['certificaten_20programmeren_16',['Stap 2: Certificaten Programmeren',['../provisioning.html#autotoc_md353',1,'']]],
  ['channel_20declarations_20vs_20definitions_17',['Channel Declarations vs Definitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md447',1,'']]],
  ['channel_20naming_18',['Channel Naming',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md445',1,'']]],
  ['channel_20overzicht_19',['ZBUS Channel Overzicht',['../index.html#autotoc_md295',1,'']]],
  ['channel_20publishing_20',['FOTA Channel Publishing',['../cloud_doc.html#autotoc_md33',1,'']]],
  ['channels_21',['ZBUS Channels',['../cloud_doc.html#autotoc_md20',1,'']]],
  ['channels_20published_22',['ZBUS Channels (Published)',['../timing_doc.html#autotoc_md271',1,'']]],
  ['checklist_23',['Checklist',['../provisioning.html#autotoc_md366',1,'✅ Checklist'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md460',1,'Module Checklist']]],
  ['checklist_20voor_20elke_20documentatie_20wijziging_3a_24',['Checklist voor elke documentatie wijziging:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md542',1,'']]],
  ['checklist_20voor_20nieuwe_20module_25',['Checklist voor Nieuwe Module',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md400',1,'']]],
  ['checklist_3a_20nieuwe_20module_20documenteren_26',['✅ Checklist: Nieuwe Module Documenteren',['../group__Titel.html#autotoc_md607',1,'']]],
  ['checklist_3a_20voor_20documentatie_20review_20sessie_27',['5.6 Checklist: Voor Documentatie Review Sessie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md578',1,'']]],
  ['checks_28',['Checks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md507',1,'Bool Checks'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md403',1,'Device Readiness Checks']]],
  ['checks_20en_20validatie_29',['NULL Checks en Validatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md505',1,'']]],
  ['claim_20type_30',['Fase 3: Systematische Verificatie Per Claim Type',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md557',1,'']]],
  ['claims_31',['Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md558',1,'3.1 Architectuur Pattern Claims'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md560',1,'3.2 Communication Pattern Claims'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md562',1,'3.3 Configuration &amp; Constants Claims'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md564',1,'3.4 Timing &amp; Behavior Claims']]],
  ['claims_20extraction_32',['Fase 2: Documentation Claims Extraction',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md555',1,'']]],
  ['clarification_33',['Gas Unit Clarification',['../message_queue_doc.html#autotoc_md151',1,'']]],
  ['cloud_34',['☁️ Fase 3: Bulk Onboarding naar nRF Cloud',['../provisioning.html#autotoc_md359',1,'']]],
  ['cloud_20api_20key_35',['nRF Cloud API Key',['../provisioning.html#autotoc_md361',1,'']]],
  ['cloud_20connectie_20state_20machine_36',['Cloud Connectie State Machine',['../cloud_doc.html#autotoc_md27',1,'']]],
  ['cloud_20connectiviteit_37',['Cloud Connectiviteit',['../cloud_doc.html#autotoc_md23',1,'']]],
  ['cloud_20integratie_38',['☁️ Cloud Integratie',['../index.html#autotoc_md306',1,'']]],
  ['cloud_20message_20format_39',['Cloud Message Format',['../message_queue_doc.html#autotoc_md144',1,'']]],
  ['cloud_20module_20documentatie_40',['Cloud Module - Documentatie',['../cloud_doc.html',1,'']]],
  ['cloud_20transmission_20elke_2030_20minuten_41',['☁️ Cloud Transmission (elke 30 minuten)',['../index.html#autotoc_md299',1,'']]],
  ['cmakelists_42',['Integration in Parent CMakeLists',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md458',1,'']]],
  ['cmakelists_20txt_43',['CMakeLists.txt',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md465',1,'']]],
  ['cmakelists_20txt_20voor_20modules_44',['CMakeLists.txt voor Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md453',1,'']]],
  ['coördinatie_20mechanisme_45',['TRIGGER_CHAN als Coördinatie Mechanisme',['../app_doc.html#autotoc_md5',1,'']]],
  ['code_46',['2. Herhalingen van Blokken Code',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md531',1,'']]],
  ['code_20analysis_20commands_20voorbeelden_47',['Code Analysis Commands (Voorbeelden)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md574',1,'']]],
  ['code_20first_20investigation_48',['5.2 Fundamenteel Principe: Code-First Investigation',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md550',1,'']]],
  ['code_20implementatie_20voorbeelden_49',['1. Code Implementatie Voorbeelden',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md530',1,'']]],
  ['code_20inventory_20objectieve_20waarheid_50',['Fase 1: Build Code Inventory (Objectieve Waarheid)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md553',1,'']]],
  ['code_20structure_20organisatie_20en_20volgorde_51',['Code Structure - Organisatie en Volgorde',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html',1,'']]],
  ['code_20structuur_52',['Code Structuur',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md462',1,'']]],
  ['code_20style_20formattering_20regels_53',['Code Style - Formattering Regels',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html',1,'']]],
  ['code_20verificatie_20en_20synchronisatie_20kritiek_20⚠️_54',['4. Code Verificatie en Synchronisatie (KRITIEK! ⚠️)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md534',1,'']]],
  ['collectie_55',['Gecoördineerde Data Collectie',['../message_queue_doc.html#autotoc_md131',1,'']]],
  ['collectie_20flow_56',['Gecoördineerde Data Collectie Flow',['../message_queue_doc.html#autotoc_md135',1,'']]],
  ['collection_20elke_2030_20seconden_57',['📥 Normal Data Collection (elke 30 seconden)',['../index.html#autotoc_md297',1,'']]],
  ['commands_58',['5.5 Practical Tools &amp;amp; Commands',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md573',1,'']]],
  ['commands_20context_59',['Git History Commands (Context)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md575',1,'']]],
  ['commands_20voorbeelden_60',['Code Analysis Commands (Voorbeelden)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md574',1,'']]],
  ['comment_20style_61',['Comment Style',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md491',1,'']]],
  ['comments_20en_20documentatie_62',['Comments en Documentatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md490',1,'']]],
  ['common_20patterns_63',['Common Patterns',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md412',1,'']]],
  ['common_20pitfalls_64',['🚨 Common Pitfalls',['../group__Titel.html#autotoc_md609',1,'']]],
  ['communication_20pattern_20claims_65',['3.2 Communication Pattern Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md560',1,'']]],
  ['compilatie_20pattern_66',['Conditionele Compilatie Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md455',1,'']]],
  ['compileren_67',['Standaard Pattern (Altijd Compileren)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md454',1,'']]],
  ['complete_20system_20timeline_68',['Complete System Timeline',['../timing_doc.html#autotoc_md272',1,'']]],
  ['conditionele_20compilatie_20pattern_69',['Conditionele Compilatie Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md455',1,'']]],
  ['conf_70',['conf',['../cloud_doc.html#autotoc_md46',1,'Kconfig (prj.conf)'],['../cloud_doc.html#autotoc_md47',1,'Sysbuild (sysbuild.conf)']]],
  ['configuratie_71',['Configuratie',['../doxygen_guidelines.html#autotoc_md590',1,'⚙️ Doxyfile Configuratie'],['../app_doc.html#autotoc_md13',1,'Configuratie'],['../cloud_doc.html#autotoc_md45',1,'Configuratie'],['../message_queue_doc.html#autotoc_md155',1,'Configuratie'],['../network_doc.html#autotoc_md179',1,'Configuratie'],['../p_one_doc.html#autotoc_md207',1,'Configuratie'],['../index.html#autotoc_md312',1,'Configuratie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md397',1,'Configuratie'],['../energy_pulse_doc.html#autotoc_md78',1,'Kanaal Configuratie'],['../timing_doc.html#autotoc_md277',1,'Timer Configuratie']]],
  ['configuratie_20kconfig_72',['Configuratie Kconfig',['../energy_pulse_doc.html#autotoc_md86',1,'Configuratie (Kconfig)'],['../timing_doc.html#autotoc_md279',1,'Configuratie (Kconfig)']]],
  ['configuration_20constants_20claims_73',['3.3 Configuration &amp;amp; Constants Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md562',1,'']]],
  ['confirmation_74',['Boot Confirmation',['../cloud_doc.html#autotoc_md32',1,'']]],
  ['confirmation_20window_75',['Boot Confirmation Window',['../cloud_doc.html#autotoc_md58',1,'']]],
  ['connect_20environment_20activeren_76',['1.2 nRF Connect Environment Activeren',['../provisioning.html#autotoc_md332',1,'']]],
  ['connectie_20state_20machine_77',['Cloud Connectie State Machine',['../cloud_doc.html#autotoc_md27',1,'']]],
  ['connection_20manager_20integration_78',['Zephyr Connection Manager Integration',['../network_doc.html#autotoc_md176',1,'']]],
  ['connectiviteit_79',['Cloud Connectiviteit',['../cloud_doc.html#autotoc_md23',1,'']]],
  ['consistency_20red_20flags_80',['4.3 Feature Consistency Red Flags',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md569',1,'']]],
  ['constanten_20en_20defines_81',['Constanten en Defines',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md484',1,'']]],
  ['constants_82',['Constants',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md502',1,'Gebruik Named Constants'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md500',1,'Magic Numbers en Constants']]],
  ['constants_20claims_83',['3.3 Configuration &amp;amp; Constants Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md562',1,'']]],
  ['constraint_84',['Buffer Size Constraint',['../p_one_doc.html#autotoc_md228',1,'']]],
  ['contact_85',['📞 Contact',['../index.html#autotoc_md323',1,'']]],
  ['content_20_3a_86',['❗ FOUT (verzonnen content):',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md540',1,'']]],
  ['context_87',['Git History Commands (Context)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md575',1,'']]],
  ['contract_88',['External Interface Contract',['../message_queue_doc.html#autotoc_md145',1,'']]],
  ['control_89',['Non-Blocking LED Control',['../led_doc.html#autotoc_md102',1,'']]],
  ['control_20patterns_90',['LED Control Patterns',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md405',1,'']]],
  ['conventie_91',['Bestandsnaam Conventie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md512',1,'']]],
  ['conventies_92',['Conventies',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md375',1,'Return Value Conventies'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md444',1,'ZBUS Conventies']]],
  ['conventions_93',['Naming Conventions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md481',1,'']]],
  ['conversie_94',['OBIS Parsing &amp;amp; Data Conversie',['../p_one_doc.html#autotoc_md192',1,'']]],
  ['core_20firmware_20documentatie_95',['SolarResult Dinnis Core - Firmware Documentatie',['../index.html',1,'']]],
  ['correct_20geverifieerd_20_3a_96',['✅ CORRECT (geverifieerd):',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md541',1,'']]],
  ['corrupte_20firmware_20image_97',['Corrupte Firmware Image',['../cloud_doc.html#autotoc_md37',1,'']]],
  ['crash_98',['Rollback Test (Warning: Intentional Crash)',['../cloud_doc.html#autotoc_md53',1,'']]],
  ['crc16_20validatie_99',['CRC16 Validatie',['../p_one_doc.html#autotoc_md204',1,'']]],
  ['critical_20dependencies_100',['Critical Dependencies',['../p_one_doc.html#autotoc_md226',1,'']]],
  ['critical_20timing_20calculations_101',['Critical Timing Calculations',['../p_one_doc.html#autotoc_md213',1,'']]],
  ['cross_20referencing_102',['🔗 Cross-Referencing',['../doxygen_guidelines.html#autotoc_md599',1,'']]],
  ['css_103',['Custom CSS (&lt;span class=&quot;tt&quot;&gt;docs/doxygen-custom.css&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md593',1,'']]],
  ['css_20docs_20doxygen_20custom_20css_104',['Custom CSS (&lt;span class=&quot;tt&quot;&gt;docs/doxygen-custom.css&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md593',1,'']]],
  ['custom_20board_20definition_105',['Custom Board Definition',['../index.html#autotoc_md311',1,'']]],
  ['custom_20css_106',['Custom CSS (&lt;span class=&quot;tt&quot;&gt;docs/doxygen-custom.css&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md593',1,'']]],
  ['custom_20css_20docs_20doxygen_20custom_20css_107',['Custom CSS (&lt;span class=&quot;tt&quot;&gt;docs/doxygen-custom.css&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md593',1,'']]]
];
