var searchData=
[
  ['obis_20parsing_20data_20conversie_0',['OBIS Parsing &amp;amp; Data Conversie',['../p_one_doc.html#autotoc_md188',1,'']]],
  ['objectieve_20waarheid_1',['Fase 1: Build Code Inventory (Objectieve Waarheid)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md600',1,'']]],
  ['of_20bewerken_20van_20documentatie_3a_2',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md583',1,'']]],
  ['of_20flash_20ram_3',['&quot;Out of Flash/RAM&quot;',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md365',1,'']]],
  ['offs_4',['offs',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md568',1,'5. Afwegingen (Trade-offs)'],['../energy_pulse_doc.html#autotoc_md91',1,'Design Trade-offs']]],
  ['offset_20mechanisme_5',['Offset Mechanisme',['../timing_doc.html#autotoc_md264',1,'']]],
  ['onboarden_6',['3.1 Alle Devices Onboarden',['../provisioning.html#autotoc_md407',1,'']]],
  ['onboarding_7',['Onboarding',['../provisioning.html#autotoc_md416',1,'Bulk Onboarding'],['../provisioning.html',1,'Provisioning and Onboarding']]],
  ['onboarding_20naar_20nrf_20cloud_8',['☁️ Fase 3: Bulk Onboarding naar nRF Cloud',['../provisioning.html#autotoc_md406',1,'']]],
  ['onboarding_20uit_9',['Voer Onboarding Uit',['../provisioning.html#autotoc_md409',1,'']]],
  ['ondersteuning_10',['🔌 Hardware Ondersteuning',['../index.html#autotoc_md300',1,'']]],
  ['ontvangst_11',['1. UART Callbacks (Asynchrone Data Ontvangst)',['../p_one_doc.html#autotoc_md195',1,'']]],
  ['ook_12',['Ook',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md372',1,'📚 Zie Ook'],['../cloud_doc.html#autotoc_md65',1,'Zie Ook'],['../cloud_doc.html#autotoc_md67',1,'Zie Ook'],['../energy_pulse_doc.html#autotoc_md94',1,'Zie Ook'],['../led_doc.html#autotoc_md120',1,'Zie Ook'],['../message_queue_doc.html#autotoc_md155',1,'Zie Ook'],['../network_doc.html#autotoc_md179',1,'Zie Ook'],['../reboot_doc.html#autotoc_md256',1,'Zie Ook'],['../timing_doc.html#autotoc_md283',1,'Zie Ook']]],
  ['operator_13',['sizeof Operator',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md545',1,'']]],
  ['optimization_14',['Performance en Optimization',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md464',1,'']]],
  ['orchestratie_15',['FOTA Orchestratie',['../cloud_doc.html#autotoc_md24',1,'']]],
  ['order_20in_20c_20files_16',['Include Order (in .c files)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md477',1,'']]],
  ['organisatie_20en_20volgorde_17',['Code Structure - Organisatie en Volgorde',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html',1,'']]],
  ['out_20of_20flash_20ram_18',['&quot;Out of Flash/RAM&quot;',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md365',1,'']]],
  ['outbound_20using_20fota_19',['Outbound (Using FOTA)',['../cloud_doc.html#autotoc_md43',1,'']]],
  ['output_20',['Data Output',['../p_one_doc.html#autotoc_md204',1,'']]],
  ['overflow_20gedrag_21',['Queue Overflow Gedrag',['../message_queue_doc.html#autotoc_md149',1,'']]],
  ['overflow_20prevention_22',['Buffer Overflow Prevention',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md470',1,'']]],
  ['overlays_23',['Custom Overlays',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md370',1,'']]],
  ['overzicht_24',['Overzicht',['../index.html#autotoc_md284',1,'📋 Overzicht'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md325',1,'📋 Overzicht'],['../provisioning.html#autotoc_md375',1,'📋 Overzicht'],['../cloud_doc.html#autotoc_md19',1,'Overzicht'],['../energy_pulse_doc.html#autotoc_md71',1,'Overzicht'],['../led_doc.html#autotoc_md98',1,'Overzicht'],['../message_queue_doc.html#autotoc_md124',1,'Overzicht'],['../network_doc.html#autotoc_md159',1,'Overzicht'],['../p_one_doc.html#autotoc_md183',1,'Overzicht'],['../p_one_doc.html#autotoc_md207',1,'Overzicht'],['../reboot_doc.html#autotoc_md230',1,'Overzicht'],['../timing_doc.html#autotoc_md260',1,'Overzicht'],['../index.html#autotoc_md290',1,'Visueel Overzicht'],['../index.html#autotoc_md291',1,'ZBUS Channel Overzicht']]]
];
