var searchData=
[
  ['dag_0',['Use Case: Typische Dag',['../timing_doc.html#autotoc_md269',1,'']]],
  ['data_20acquisitie_20van_20dsmr_20meters_1',['Data Acquisitie van DSMR Meters',['../p_one_doc.html#autotoc_md185',1,'']]],
  ['data_20collectie_2',['Gecoördineerde Data Collectie',['../message_queue_doc.html#autotoc_md127',1,'']]],
  ['data_20collectie_20flow_3',['Gecoördineerde Data Collectie Flow',['../message_queue_doc.html#autotoc_md131',1,'']]],
  ['data_20collection_20elke_2030_20seconden_4',['📥 Normal Data Collection (elke 30 seconden)',['../index.html#autotoc_md293',1,'']]],
  ['data_20conversie_5',['OBIS Parsing &amp;amp; Data Conversie',['../p_one_doc.html#autotoc_md188',1,'']]],
  ['data_20flow_6',['Data Flow',['../energy_pulse_doc.html#autotoc_md79',1,'Data Flow'],['../energy_pulse_doc.html#autotoc_md77',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../led_doc.html#autotoc_md104',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../message_queue_doc.html#autotoc_md130',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../network_doc.html#autotoc_md165',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../reboot_doc.html#autotoc_md236',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../timing_doc.html#autotoc_md266',1,'Wat? (Functionaliteit &amp; Data Flow)']]],
  ['data_20flow_20module_20interacties_7',['🔄 Data Flow &amp;amp; Module Interacties',['../index.html#autotoc_md289',1,'']]],
  ['data_20ontvangst_8',['1. UART Callbacks (Asynchrone Data Ontvangst)',['../p_one_doc.html#autotoc_md195',1,'']]],
  ['data_20output_9',['Data Output',['../p_one_doc.html#autotoc_md204',1,'']]],
  ['data_20verwerking_10',['📊 Data Verwerking',['../index.html#autotoc_md301',1,'']]],
  ['de_20dinnis_20application_11',['Build de Dinnis Application',['../provisioning.html#autotoc_md352',1,'']]],
  ['de_20slag_12',['🚀 Aan de Slag',['../index.html#autotoc_md305',1,'']]],
  ['declaratie_13',['Error Variable Declaratie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md369',1,'']]],
  ['declarations_14',['Declarations',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md428',1,'Forward Declarations'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md430',1,'State Machine Forward Declarations'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md490',1,'Variable Declarations']]],
  ['declarations_20vs_20definitions_15',['Channel Declarations vs Definitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md443',1,'']]],
  ['define_16',['enum vs define',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md497',1,'']]],
  ['defines_17',['Constanten en Defines',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md480',1,'']]],
  ['definiëren_18',['Module Groepen Definiëren',['../doxygen_guidelines.html#autotoc_md596',1,'']]],
  ['definition_19',['Custom Board Definition',['../index.html#autotoc_md307',1,'']]],
  ['definitions_20',['Definitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md443',1,'Channel Declarations vs Definitions'],['../message_queue_doc.html#autotoc_md143',1,'Field Definitions']]],
  ['delivery_20garanties_20via_20buffering_21',['Delivery Garanties via Buffering',['../message_queue_doc.html#autotoc_md128',1,'']]],
  ['delta_20updates_22',['Priority 3: Delta Updates',['../cloud_doc.html#autotoc_md63',1,'']]],
  ['dependencies_23',['Dependencies',['../p_one_doc.html#autotoc_md222',1,'Critical Dependencies'],['../cloud_doc.html#autotoc_md41',1,'Dependencies']]],
  ['design_20rationale_24',['Design Rationale',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md514',1,'2. Implementatie Design Rationale'],['../message_queue_doc.html#autotoc_md126',1,'Waarom? (Design Rationale)'],['../network_doc.html#autotoc_md161',1,'Waarom? (Design Rationale)']]],
  ['design_20rationale_3a_20short_20key_20names_25',['Design Rationale: Short Key Names',['../message_queue_doc.html#autotoc_md144',1,'']]],
  ['design_20trade_20offs_26',['Design Trade-offs',['../energy_pulse_doc.html#autotoc_md91',1,'']]],
  ['details_27',['Details',['../network_doc.html#autotoc_md173',1,'Modem Initialization Details'],['../message_queue_doc.html#autotoc_md146',1,'Transport Details']]],
  ['development_20environment_28',['1.1 Development Environment',['../provisioning.html#autotoc_md327',1,'']]],
  ['device_29',['Device',['../provisioning.html#autotoc_md353',1,'Flash naar Device'],['../provisioning.html#autotoc_md364',1,'Per Device'],['../led_doc.html#autotoc_md101',1,'Visuele Feedback voor IoT Device']]],
  ['device_20provisioneren_30',['🔧 Fase 2: Per Device Provisioneren',['../provisioning.html#autotoc_md340',1,'']]],
  ['device_20readiness_20checks_31',['Device Readiness Checks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md399',1,'']]],
  ['device_20recoveren_32',['Stap 2: Device Recoveren',['../provisioning.html#autotoc_md343',1,'']]],
  ['device_20response_33',['Scenario 1: Slow P1 Device Response',['../p_one_doc.html#autotoc_md219',1,'']]],
  ['devices_20onboarden_34',['3.1 Alle Devices Onboarden',['../provisioning.html#autotoc_md356',1,'']]],
  ['diagrammen_35',['8. Timing Diagrammen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md520',1,'']]],
  ['diepgang_36',['Technische Diepgang',['../p_one_doc.html#autotoc_md198',1,'']]],
  ['dinnis_20application_37',['Build de Dinnis Application',['../provisioning.html#autotoc_md352',1,'']]],
  ['dinnis_20core_20firmware_20documentatie_38',['SolarResult Dinnis Core - Firmware Documentatie',['../index.html',1,'']]],
  ['dit_20protocol_39',['5.1 Waarom dit Protocol?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md544',1,'']]],
  ['dit_20zo_20belangrijk_40',['Waarom is dit zo belangrijk?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md539',1,'']]],
  ['docs_20doxygen_20custom_20css_41',['Custom CSS (&lt;span class=&quot;tt&quot;&gt;docs/doxygen-custom.css&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md589',1,'']]],
  ['docs_20header_20html_42',['Header HTML (&lt;span class=&quot;tt&quot;&gt;docs/header.html&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md590',1,'']]],
  ['documentatie_43',['Documentatie',['../doxygen_guidelines.html#autotoc_md592',1,'📝 Module Documentatie'],['../app_doc.html',1,'App Module - Documentatie'],['../cloud_doc.html',1,'Cloud Module - Documentatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md486',1,'Comments en Documentatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md465',1,'Documentatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md488',1,'Doxygen Documentatie'],['../energy_pulse_doc.html',1,'Energy Pulse Module - Documentatie'],['../led_doc.html',1,'LED Module - Documentatie'],['../message_queue_doc.html',1,'Message Queue Module - Documentatie'],['../network_doc.html',1,'Network Module - Documentatie'],['../p_one_doc.html',1,'P1 DSMR Module - Documentatie'],['../reboot_doc.html',1,'Reboot Module - Documentatie'],['../index.html',1,'SolarResult Dinnis Core - Firmware Documentatie'],['../timing_doc.html',1,'Timing Module - Documentatie']]],
  ['documentatie_20anti_20patterns_20red_20flags_44',['Fase 4: Documentatie Anti-Patterns (Red Flags)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md562',1,'']]],
  ['documentatie_20guidelines_45',['Doxygen Documentatie Guidelines',['../doxygen_guidelines.html',1,'']]],
  ['documentatie_20niveau_46',['Documentatie Niveau',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md510',1,'']]],
  ['documentatie_20review_20sessie_47',['5.6 Checklist: Voor Documentatie Review Sessie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md574',1,'']]],
  ['documentatie_20richtlijnen_48',['Module Documentatie Richtlijnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html',1,'']]],
  ['documentatie_20structuur_49',['📚 Documentatie Structuur',['../index.html#autotoc_md310',1,'']]],
  ['documentatie_20types_50',['📚 Documentatie Types',['../doxygen_guidelines.html#autotoc_md582',1,'']]],
  ['documentatie_20verificatie_20protocol_51',['5. AI Agent Documentatie Verificatie Protocol',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md543',1,'']]],
  ['documentatie_20wijziging_3a_52',['Checklist voor elke documentatie wijziging:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md538',1,'']]],
  ['documentatie_3a_53',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md532',1,'']]],
  ['documentation_20claims_20extraction_54',['Fase 2: Documentation Claims Extraction',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md551',1,'']]],
  ['documenteren_55',['✅ Checklist: Nieuwe Module Documenteren',['../group__Titel.html#autotoc_md603',1,'']]],
  ['door_20niet_20te_20verifiëren_3a_56',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md535',1,'']]],
  ['download_20duration_57',['Download Duration',['../cloud_doc.html#autotoc_md56',1,'']]],
  ['download_20modem_20firmware_20v2_200_203_58',['Download Modem Firmware v2.0.3',['../provisioning.html#autotoc_md331',1,'']]],
  ['download_20pti_20modem_20firmware_20v2_203_208_59',['Download PTI Modem Firmware v2.3.8',['../provisioning.html#autotoc_md332',1,'']]],
  ['downloaden_60',['1.3 Modem Firmware Downloaden',['../provisioning.html#autotoc_md330',1,'']]],
  ['doxyfile_20configuratie_61',['⚙️ Doxyfile Configuratie',['../doxygen_guidelines.html#autotoc_md586',1,'']]],
  ['doxygen_20custom_20css_62',['Custom CSS (&lt;span class=&quot;tt&quot;&gt;docs/doxygen-custom.css&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md589',1,'']]],
  ['doxygen_20documentatie_63',['Doxygen Documentatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md488',1,'']]],
  ['doxygen_20documentatie_20guidelines_64',['Doxygen Documentatie Guidelines',['../doxygen_guidelines.html',1,'']]],
  ['driven_20network_20management_65',['Event-Driven Network Management',['../network_doc.html#autotoc_md162',1,'']]],
  ['dsmr_20meters_66',['Data Acquisitie van DSMR Meters',['../p_one_doc.html#autotoc_md185',1,'']]],
  ['dsmr_20module_20documentatie_67',['P1 DSMR Module - Documentatie',['../p_one_doc.html',1,'']]],
  ['duration_68',['Duration',['../cloud_doc.html#autotoc_md56',1,'Download Duration'],['../cloud_doc.html#autotoc_md57',1,'MCUboot Swap Duration']]],
  ['during_20fota_69',['Netwerk Loss During FOTA',['../cloud_doc.html#autotoc_md36',1,'']]]
];
