var searchData=
[
  ['h_0',['Header Files (.h)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md429',1,'']]],
  ['h_20template_1',['Header File (.h) Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md442',1,'']]],
  ['handleidingen_2',['📚 Handleidingen',['../index.html#autotoc_md320',1,'']]],
  ['handler_20functions_3',['State Handler Functions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md388',1,'']]],
  ['handlers_4',['Work Queue Handlers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md394',1,'']]],
  ['handling_5',['Handling',['../energy_pulse_doc.html#autotoc_md85',1,'Error Handling'],['../app_doc.html#autotoc_md15',1,'Native Sim Handling']]],
  ['handling_20en_20return_20values_6',['Error Handling en Return Values',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md372',1,'']]],
  ['handling_20periodieke_20triggers_7',['2. ZBUS Message Handling (Periodieke Triggers)',['../p_one_doc.html#autotoc_md200',1,'']]],
  ['hardware_20interaction_8',['Hardware Interaction',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md402',1,'']]],
  ['hardware_20interface_9',['Hardware Interface',['../led_doc.html#autotoc_md113',1,'']]],
  ['hardware_20ondersteuning_10',['🔌 Hardware Ondersteuning',['../index.html#autotoc_md304',1,'']]],
  ['hardware_20watchdog_20als_20safety_20mechanism_11',['Hardware Watchdog als Safety Mechanism',['../app_doc.html#autotoc_md4',1,'']]],
  ['header_20file_20h_20template_12',['Header File (.h) Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md442',1,'']]],
  ['header_20files_20h_13',['Header Files (.h)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md429',1,'']]],
  ['header_20html_14',['Header HTML (&lt;span class=&quot;tt&quot;&gt;docs/header.html&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md594',1,'']]],
  ['header_20html_20docs_20header_20html_15',['Header HTML (&lt;span class=&quot;tt&quot;&gt;docs/header.html&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md594',1,'']]],
  ['header_20visibility_16',['Header Visibility',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md457',1,'']]],
  ['headers_17',['Headers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md428',1,'Include Guards en Headers'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md437',1,'Sectie Headers']]],
  ['heeft_18',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md467',1,'']]],
  ['herhalingen_20van_20blokken_20code_19',['2. Herhalingen van Blokken Code',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md531',1,'']]],
  ['het_20schrijven_20of_20bewerken_20van_20documentatie_3a_20',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md536',1,'']]],
  ['historische_20referenties_20en_20voor_20na_20vergelijkingen_21',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md532',1,'']]],
  ['history_20commands_20context_22',['Git History Commands (Context)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md575',1,'']]],
  ['hoe_23',['Hoe',['../app_doc.html#autotoc_md9',1,'']]],
  ['hoe_20architectuur_20gedrag_24',['Hoe Architectuur Gedrag',['../energy_pulse_doc.html#autotoc_md82',1,'Hoe? (Architectuur &amp; Gedrag)'],['../led_doc.html#autotoc_md110',1,'Hoe? (Architectuur &amp; Gedrag)'],['../message_queue_doc.html#autotoc_md139',1,'Hoe? (Architectuur &amp; Gedrag)'],['../network_doc.html#autotoc_md174',1,'Hoe? (Architectuur &amp; Gedrag)'],['../reboot_doc.html#autotoc_md246',1,'Hoe? (Architectuur &amp; Gedrag)'],['../timing_doc.html#autotoc_md275',1,'Hoe? (Architectuur &amp; Gedrag)']]],
  ['hook_25',['Modem Initialization Hook',['../network_doc.html#autotoc_md167',1,'']]],
  ['how_20implementatie_26',['How? (Implementatie)',['../cloud_doc.html#autotoc_md31',1,'']]],
  ['html_27',['Header HTML (&lt;span class=&quot;tt&quot;&gt;docs/header.html&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md594',1,'']]],
  ['html_20docs_20header_20html_28',['Header HTML (&lt;span class=&quot;tt&quot;&gt;docs/header.html&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md594',1,'']]]
];
