var searchData=
[
  ['behavior_0',['Watchdog Callback Behavior',['../app_doc.html#autotoc_md17',1,'']]],
  ['behavior_20claims_1',['3.4 Timing &amp;amp; Behavior Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md411',1,'']]],
  ['behavior_20en_20portability_2',['Undefined Behavior en Portability',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md254',1,'']]],
  ['behaviour_3',['6. Intended Behaviour',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md369',1,'']]],
  ['belangrijk_4',['Waarom is dit zo belangrijk?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md390',1,'']]],
  ['belangrijke_20features_5',['⚙️ Belangrijke Features',['../index.html#autotoc_md193',1,'']]],
  ['belangrijke_20links_6',['🔗 Belangrijke Links',['../index.html#autotoc_md209',1,'']]],
  ['benefits_7',['User Experience Benefits',['../led_doc.html#autotoc_md75',1,'']]],
  ['berekening_8',['Timing Berekening',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md246',1,'']]],
  ['best_20practices_20praktische_20richtlijnen_9',['Best Practices - Praktische Richtlijnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html',1,'']]],
  ['bestanden_20structuur_10',['Bestanden Structuur',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md308',1,'']]],
  ['bestandsnaam_20conventie_11',['Bestandsnaam Conventie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md359',1,'']]],
  ['betrouwbaarheid_12',['Betrouwbaarheid',['../energy_pulse_doc.html#autotoc_md52',1,'Betrouwbaarheid'],['../md_modules_2reboot_2reboot__doc.html#autotoc_md154',1,'Betrouwbaarheid']]],
  ['bewerken_20van_20documentatie_3a_13',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md383',1,'']]],
  ['bij_20errors_14',['Logging Bij Errors',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md223',1,'']]],
  ['bij_20het_20schrijven_20of_20bewerken_20van_20documentatie_3a_15',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md383',1,'']]],
  ['blocking_20led_20control_16',['Non-Blocking LED Control',['../led_doc.html#autotoc_md64',1,'']]],
  ['blokken_20code_17',['2. Herhalingen van Blokken Code',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md378',1,'']]],
  ['board_20definition_18',['Custom Board Definition',['../index.html#autotoc_md201',1,'']]],
  ['bool_20checks_19',['Bool Checks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md354',1,'']]],
  ['brace_20style_20',['Brace Style',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md325',1,'']]],
  ['branding_21',['🎨 Styling &amp;amp; Branding',['../doxygen_guidelines.html#autotoc_md439',1,'']]],
  ['broken_20links_22',['❗ Broken Links',['../group__Titel.html#autotoc_md459',1,'']]],
  ['buffer_23',['GPIO Data Request Pin &amp;amp; Inverterende Buffer',['../p_one_doc.html#autotoc_md101',1,'']]],
  ['buffer_20overflow_20prevention_24',['Buffer Overflow Prevention',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md270',1,'']]],
  ['buffer_20size_20constraint_25',['Buffer Size Constraint',['../p_one_doc.html#autotoc_md138',1,'']]],
  ['buffering_26',['Buffering',['../index.html#autotoc_md186',1,'📥 Data Acquisitie &amp; Buffering'],['../cloud_doc.html#autotoc_md26',1,'3.2 Data Acquisitie en Buffering']]],
  ['buffering_20en_20wachtrij_27',['Buffering en Wachtrij',['../message_queue_module.html#mq_buffering',1,'']]],
  ['buffers_28',['Arrays en Buffers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md344',1,'']]],
  ['build_20code_20inventory_20objectieve_20waarheid_29',['Fase 1: Build Code Inventory (Objectieve Waarheid)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md400',1,'']]],
  ['build_20systeem_30',['Build Systeem',['../index.html#autotoc_md200',1,'']]],
  ['build_20system_31',['🛠️ Build System',['../group__Titel.html#autotoc_md452',1,'']]],
  ['byte_20timeout_32',['2. UART RX Timeout (Inter-byte timeout)',['../p_one_doc.html#autotoc_md125',1,'']]],
  ['byte_20timeout_20392_20ms_33',['Inter-byte Timeout (392 ms)',['../p_one_doc.html#autotoc_md129',1,'']]],
  ['byte_20timeout_20trigger_34',['Scenario 3: Inter-byte Timeout Trigger',['../p_one_doc.html#autotoc_md135',1,'']]]
];
