var searchData=
[
  ['obis_20parsing_20data_20conversie_0',['OBIS Parsing &amp;amp; Data Conversie',['../p_one_doc.html#autotoc_md192',1,'']]],
  ['objectieve_20waarheid_1',['Fase 1: Build Code Inventory (Objectieve Waarheid)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md553',1,'']]],
  ['of_20bewerken_20van_20documentatie_3a_2',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md536',1,'']]],
  ['offs_3',['offs',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md521',1,'5. Afwegingen (Trade-offs)'],['../energy_pulse_doc.html#autotoc_md91',1,'Design Trade-offs']]],
  ['offset_20mechanisme_4',['Offset Mechanisme',['../timing_doc.html#autotoc_md268',1,'']]],
  ['onboarden_5',['3.1 Alle Devices Onboarden',['../provisioning.html#autotoc_md360',1,'']]],
  ['onboarding_6',['Onboarding',['../provisioning.html#autotoc_md369',1,'Bulk Onboarding'],['../provisioning.html',1,'Provisioning and Onboarding']]],
  ['onboarding_20naar_20nrf_20cloud_7',['☁️ Fase 3: Bulk Onboarding naar nRF Cloud',['../provisioning.html#autotoc_md359',1,'']]],
  ['onboarding_20uit_8',['Voer Onboarding Uit',['../provisioning.html#autotoc_md362',1,'']]],
  ['ondersteuning_9',['🔌 Hardware Ondersteuning',['../index.html#autotoc_md304',1,'']]],
  ['ontvangst_10',['1. UART Callbacks (Asynchrone Data Ontvangst)',['../p_one_doc.html#autotoc_md199',1,'']]],
  ['ook_11',['Ook',['../cloud_doc.html#autotoc_md65',1,'Zie Ook'],['../cloud_doc.html#autotoc_md67',1,'Zie Ook'],['../energy_pulse_doc.html#autotoc_md94',1,'Zie Ook'],['../led_doc.html#autotoc_md124',1,'Zie Ook'],['../message_queue_doc.html#autotoc_md159',1,'Zie Ook'],['../network_doc.html#autotoc_md183',1,'Zie Ook'],['../reboot_doc.html#autotoc_md260',1,'Zie Ook'],['../timing_doc.html#autotoc_md287',1,'Zie Ook']]],
  ['operator_12',['sizeof Operator',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md498',1,'']]],
  ['optimization_13',['Performance en Optimization',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md417',1,'']]],
  ['orchestratie_14',['FOTA Orchestratie',['../cloud_doc.html#autotoc_md24',1,'']]],
  ['order_20in_20c_20files_15',['Include Order (in .c files)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md430',1,'']]],
  ['organisatie_20en_20volgorde_16',['Code Structure - Organisatie en Volgorde',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html',1,'']]],
  ['outbound_20using_20fota_17',['Outbound (Using FOTA)',['../cloud_doc.html#autotoc_md43',1,'']]],
  ['output_18',['Data Output',['../p_one_doc.html#autotoc_md208',1,'']]],
  ['overflow_20gedrag_19',['Queue Overflow Gedrag',['../message_queue_doc.html#autotoc_md153',1,'']]],
  ['overflow_20prevention_20',['Buffer Overflow Prevention',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md423',1,'']]],
  ['overzicht_21',['Overzicht',['../index.html#autotoc_md288',1,'📋 Overzicht'],['../provisioning.html#autotoc_md328',1,'📋 Overzicht'],['../cloud_doc.html#autotoc_md19',1,'Overzicht'],['../energy_pulse_doc.html#autotoc_md71',1,'Overzicht'],['../led_doc.html#autotoc_md98',1,'Overzicht'],['../message_queue_doc.html#autotoc_md128',1,'Overzicht'],['../network_doc.html#autotoc_md163',1,'Overzicht'],['../p_one_doc.html#autotoc_md187',1,'Overzicht'],['../p_one_doc.html#autotoc_md211',1,'Overzicht'],['../reboot_doc.html#autotoc_md234',1,'Overzicht'],['../timing_doc.html#autotoc_md264',1,'Overzicht'],['../index.html#autotoc_md294',1,'Visueel Overzicht'],['../index.html#autotoc_md295',1,'ZBUS Channel Overzicht']]]
];
