var searchData=
[
  ['iets_20verzinnen_0',['Principe: NOOIT iets verzinnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md582',1,'']]],
  ['image_1',['Corrupte Firmware Image',['../cloud_doc.html#autotoc_md37',1,'']]],
  ['image_20builds_20mcuboot_20app_2',['Multi-Image Builds (MCUboot + App)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md368',1,'']]],
  ['image_20generatie_3',['FOTA Image Generatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md369',1,'']]],
  ['imei_20lijst_20verkrijgen_4',['1.6 IMEI Lijst Verkrijgen',['../provisioning.html#autotoc_md389',1,'']]],
  ['imei_20programmeren_5',['2.1 IMEI Programmeren',['../provisioning.html#autotoc_md392',1,'']]],
  ['imei_20schrijven_20via_20rtt_6',['Stap 4: IMEI Schrijven via RTT',['../provisioning.html#autotoc_md396',1,'']]],
  ['immediate_20scheduling_7',['K_NO_WAIT voor Immediate Scheduling',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md439',1,'']]],
  ['impact_8',['Impact',['../energy_pulse_doc.html#autotoc_md88',1,'Resultaten &amp; Impact'],['../timing_doc.html#autotoc_md277',1,'Resultaten &amp; Impact']]],
  ['implementatie_9',['How? (Implementatie)',['../cloud_doc.html#autotoc_md31',1,'']]],
  ['implementatie_20design_20rationale_10',['2. Implementatie Design Rationale',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md565',1,'']]],
  ['implementatie_20vereisten_11',['Module Shutdown Implementatie Vereisten',['../reboot_doc.html#autotoc_md253',1,'']]],
  ['implementatie_20voorbeelden_12',['1. Code Implementatie Voorbeelden',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md577',1,'']]],
  ['implementation_13',['Pattern Implementation',['../led_doc.html#autotoc_md111',1,'']]],
  ['in_20c_20files_14',['Include Order (in .c files)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md477',1,'']]],
  ['in_20moet_15',['in moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md563',1,'✅ Wat ER WEL in moet'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md576',1,'❗ Wat ER NIET in moet']]],
  ['in_20parent_20cmakelists_16',['Integration in Parent CMakeLists',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md505',1,'']]],
  ['in_20thread_17',['Message Processing in Thread',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md431',1,'']]],
  ['in_20volgorde_18',['Standaard Secties (in volgorde)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md485',1,'']]],
  ['inbound_20fota_20requires_19',['Inbound (FOTA Requires)',['../cloud_doc.html#autotoc_md42',1,'']]],
  ['include_20guards_20en_20headers_20',['Include Guards en Headers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md475',1,'']]],
  ['include_20order_20in_20c_20files_21',['Include Order (in .c files)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md477',1,'']]],
  ['inconsistente_20titel_20formaten_22',['❗ Inconsistente Titel Formaten',['../group__Titel.html#autotoc_md658',1,'']]],
  ['indentatie_20en_20formattering_23',['Indentatie en Formattering',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md522',1,'']]],
  ['indien_20module_20eigen_20thread_20heeft_24',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md514',1,'']]],
  ['initialisatie_25',['Initialisatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md496',1,'Module Initialisatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md511',1,'Module Initialisatie']]],
  ['initialisatie_20sequence_26',['Initialisatie Sequence',['../energy_pulse_doc.html#autotoc_md83',1,'']]],
  ['initialisatie_20volgorde_27',['Initialisatie Volgorde',['../app_doc.html#autotoc_md12',1,'']]],
  ['initialization_28',['Initialization',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md542',1,'']]],
  ['initialization_20details_29',['Modem Initialization Details',['../network_doc.html#autotoc_md173',1,'']]],
  ['initialization_20hook_30',['Modem Initialization Hook',['../network_doc.html#autotoc_md163',1,'']]],
  ['input_20validation_31',['Input Validation',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md469',1,'']]],
  ['insights_20lessons_20learned_32',['5.7 Key Insights &amp;amp; Lessons Learned',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md627',1,'']]],
  ['installeren_33',['2.2 Certificaten Installeren',['../provisioning.html#autotoc_md398',1,'']]],
  ['instructies_34',['Instructies',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md335',1,'🏗️ Build Instructies'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md341',1,'📦 Flash Instructies']]],
  ['int_20return_35',['Void vs Int Return',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md424',1,'']]],
  ['integer_20fixed_20point_36',['Waarom Integer Fixed-Point?',['../p_one_doc.html#autotoc_md199',1,'']]],
  ['integratie_37',['Integratie',['../index.html#autotoc_md302',1,'☁️ Cloud Integratie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md498',1,'Kconfig Integratie'],['../p_one_doc.html#autotoc_md191',1,'ZBUS Integratie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md510',1,'ZBUS Integratie']]],
  ['integration_38',['Integration',['../cloud_doc.html#autotoc_md29',1,'LED Integration'],['../network_doc.html#autotoc_md172',1,'Zephyr Connection Manager Integration']]],
  ['integration_20in_20parent_20cmakelists_39',['Integration in Parent CMakeLists',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md505',1,'']]],
  ['integration_20tests_40',['Integration Tests',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md359',1,'']]],
  ['intended_20behaviour_41',['6. Intended Behaviour',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md569',1,'']]],
  ['intentional_20crash_42',['Rollback Test (Warning: Intentional Crash)',['../cloud_doc.html#autotoc_md53',1,'']]],
  ['inter_20byte_20timeout_43',['2. UART RX Timeout (Inter-byte timeout)',['../p_one_doc.html#autotoc_md211',1,'']]],
  ['inter_20byte_20timeout_20392_20ms_44',['Inter-byte Timeout (392 ms)',['../p_one_doc.html#autotoc_md215',1,'']]],
  ['inter_20byte_20timeout_20trigger_45',['Scenario 3: Inter-byte Timeout Trigger',['../p_one_doc.html#autotoc_md221',1,'']]],
  ['interacties_46',['🔄 Data Flow &amp;amp; Module Interacties',['../index.html#autotoc_md289',1,'']]],
  ['interaction_47',['Hardware Interaction',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md449',1,'']]],
  ['interface_48',['Interface',['../led_doc.html#autotoc_md110',1,'Hardware Interface'],['../app_doc.html#autotoc_md8',1,'ZBUS Interface']]],
  ['interface_20contract_49',['External Interface Contract',['../message_queue_doc.html#autotoc_md141',1,'']]],
  ['interfaces_50',['Interfaces',['../energy_pulse_doc.html#autotoc_md80',1,'ZBUS Interfaces'],['../led_doc.html#autotoc_md106',1,'ZBUS Interfaces'],['../message_queue_doc.html#autotoc_md132',1,'ZBUS Interfaces'],['../network_doc.html#autotoc_md167',1,'ZBUS Interfaces']]],
  ['interrupt_20gedreven_51',['GPIO Interrupt Gedreven',['../energy_pulse_doc.html#autotoc_md75',1,'']]],
  ['inventory_20objectieve_20waarheid_52',['Fase 1: Build Code Inventory (Objectieve Waarheid)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md600',1,'']]],
  ['investigation_53',['5.2 Fundamenteel Principe: Code-First Investigation',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md597',1,'']]],
  ['iot_20device_54',['Visuele Feedback voor IoT Device',['../led_doc.html#autotoc_md101',1,'']]],
  ['is_20dit_20zo_20belangrijk_55',['Waarom is dit zo belangrijk?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md590',1,'']]]
];
