var searchData=
[
  ['dag_0',['Use Case: Typische Dag',['../timing_doc.html#autotoc_md269',1,'']]],
  ['data_20acquisitie_20van_20dsmr_20meters_1',['Data Acquisitie van DSMR Meters',['../p_one_doc.html#autotoc_md185',1,'']]],
  ['data_20collectie_2',['Gecoördineerde Data Collectie',['../message_queue_doc.html#autotoc_md127',1,'']]],
  ['data_20collectie_20flow_3',['Gecoördineerde Data Collectie Flow',['../message_queue_doc.html#autotoc_md131',1,'']]],
  ['data_20collection_20elke_2030_20seconden_4',['📥 Normal Data Collection (elke 30 seconden)',['../index.html#autotoc_md293',1,'']]],
  ['data_20conversie_5',['OBIS Parsing &amp;amp; Data Conversie',['../p_one_doc.html#autotoc_md188',1,'']]],
  ['data_20flow_6',['Data Flow',['../energy_pulse_doc.html#autotoc_md79',1,'Data Flow'],['../energy_pulse_doc.html#autotoc_md77',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../led_doc.html#autotoc_md104',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../message_queue_doc.html#autotoc_md130',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../network_doc.html#autotoc_md165',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../reboot_doc.html#autotoc_md236',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../timing_doc.html#autotoc_md266',1,'Wat? (Functionaliteit &amp; Data Flow)']]],
  ['data_20flow_20module_20interacties_7',['🔄 Data Flow &amp;amp; Module Interacties',['../index.html#autotoc_md289',1,'']]],
  ['data_20ontvangst_8',['1. UART Callbacks (Asynchrone Data Ontvangst)',['../p_one_doc.html#autotoc_md195',1,'']]],
  ['data_20output_9',['Data Output',['../p_one_doc.html#autotoc_md204',1,'']]],
  ['data_20verwerking_10',['📊 Data Verwerking',['../index.html#autotoc_md301',1,'']]],
  ['de_20dinnis_20application_11',['Build de Dinnis Application',['../provisioning.html#autotoc_md403',1,'']]],
  ['de_20slag_12',['🚀 Aan de Slag',['../index.html#autotoc_md305',1,'']]],
  ['debug_20build_13',['Debug Build',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md338',1,'']]],
  ['debug_20procedures_14',['🐛 Debug Procedures',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md346',1,'']]],
  ['debugging_15',['GDB Debugging',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md348',1,'']]],
  ['declaratie_16',['Error Variable Declaratie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md420',1,'']]],
  ['declarations_17',['Declarations',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md479',1,'Forward Declarations'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md481',1,'State Machine Forward Declarations'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md541',1,'Variable Declarations']]],
  ['declarations_20vs_20definitions_18',['Channel Declarations vs Definitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md494',1,'']]],
  ['define_19',['enum vs define',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md548',1,'']]],
  ['defines_20',['Constanten en Defines',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md531',1,'']]],
  ['definiëren_21',['Module Groepen Definiëren',['../doxygen_guidelines.html#autotoc_md647',1,'']]],
  ['definitie_22',['🔧 Custom Board Definitie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md355',1,'']]],
  ['definition_23',['Custom Board Definition',['../index.html#autotoc_md307',1,'']]],
  ['definitions_24',['Definitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md494',1,'Channel Declarations vs Definitions'],['../message_queue_doc.html#autotoc_md143',1,'Field Definitions']]],
  ['delivery_20garanties_20via_20buffering_25',['Delivery Garanties via Buffering',['../message_queue_doc.html#autotoc_md128',1,'']]],
  ['delta_20updates_26',['Priority 3: Delta Updates',['../cloud_doc.html#autotoc_md63',1,'']]],
  ['dependencies_27',['Dependencies',['../p_one_doc.html#autotoc_md222',1,'Critical Dependencies'],['../cloud_doc.html#autotoc_md41',1,'Dependencies']]],
  ['design_20rationale_28',['Design Rationale',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md565',1,'2. Implementatie Design Rationale'],['../message_queue_doc.html#autotoc_md126',1,'Waarom? (Design Rationale)'],['../network_doc.html#autotoc_md161',1,'Waarom? (Design Rationale)']]],
  ['design_20rationale_3a_20short_20key_20names_29',['Design Rationale: Short Key Names',['../message_queue_doc.html#autotoc_md144',1,'']]],
  ['design_20trade_20offs_30',['Design Trade-offs',['../energy_pulse_doc.html#autotoc_md91',1,'']]],
  ['details_31',['Details',['../network_doc.html#autotoc_md173',1,'Modem Initialization Details'],['../message_queue_doc.html#autotoc_md146',1,'Transport Details']]],
  ['development_20environment_32',['1.1 Development Environment',['../provisioning.html#autotoc_md378',1,'']]],
  ['development_20guide_33',['Development Guide',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html',1,'']]],
  ['device_34',['Device',['../provisioning.html#autotoc_md404',1,'Flash naar Device'],['../provisioning.html#autotoc_md415',1,'Per Device'],['../led_doc.html#autotoc_md101',1,'Visuele Feedback voor IoT Device']]],
  ['device_20provisioneren_35',['🔧 Fase 2: Per Device Provisioneren',['../provisioning.html#autotoc_md391',1,'']]],
  ['device_20readiness_20checks_36',['Device Readiness Checks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md450',1,'']]],
  ['device_20recoveren_37',['Stap 2: Device Recoveren',['../provisioning.html#autotoc_md394',1,'']]],
  ['device_20response_38',['Scenario 1: Slow P1 Device Response',['../p_one_doc.html#autotoc_md219',1,'']]],
  ['devices_20onboarden_39',['3.1 Alle Devices Onboarden',['../provisioning.html#autotoc_md407',1,'']]],
  ['diagrammen_40',['8. Timing Diagrammen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md571',1,'']]],
  ['diepgang_41',['Technische Diepgang',['../p_one_doc.html#autotoc_md198',1,'']]],
  ['dinnis_20application_42',['Build de Dinnis Application',['../provisioning.html#autotoc_md403',1,'']]],
  ['dinnis_20core_20firmware_20documentatie_43',['SolarResult Dinnis Core - Firmware Documentatie',['../index.html',1,'']]],
  ['direct_44',['Via nrfjprog (Direct)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md343',1,'']]],
  ['dit_20protocol_45',['5.1 Waarom dit Protocol?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md595',1,'']]],
  ['dit_20zo_20belangrijk_46',['Waarom is dit zo belangrijk?',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md590',1,'']]],
  ['docs_20doxygen_20custom_20css_47',['Custom CSS (&lt;span class=&quot;tt&quot;&gt;docs/doxygen-custom.css&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md640',1,'']]],
  ['docs_20header_20html_48',['Header HTML (&lt;span class=&quot;tt&quot;&gt;docs/header.html&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md641',1,'']]],
  ['documentatie_49',['Documentatie',['../doxygen_guidelines.html#autotoc_md643',1,'📝 Module Documentatie'],['../app_doc.html',1,'App Module - Documentatie'],['../cloud_doc.html',1,'Cloud Module - Documentatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md537',1,'Comments en Documentatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md516',1,'Documentatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md539',1,'Doxygen Documentatie'],['../energy_pulse_doc.html',1,'Energy Pulse Module - Documentatie'],['../led_doc.html',1,'LED Module - Documentatie'],['../message_queue_doc.html',1,'Message Queue Module - Documentatie'],['../network_doc.html',1,'Network Module - Documentatie'],['../p_one_doc.html',1,'P1 DSMR Module - Documentatie'],['../reboot_doc.html',1,'Reboot Module - Documentatie'],['../index.html',1,'SolarResult Dinnis Core - Firmware Documentatie'],['../timing_doc.html',1,'Timing Module - Documentatie']]],
  ['documentatie_20anti_20patterns_20red_20flags_50',['Fase 4: Documentatie Anti-Patterns (Red Flags)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md613',1,'']]],
  ['documentatie_20guidelines_51',['Doxygen Documentatie Guidelines',['../doxygen_guidelines.html',1,'']]],
  ['documentatie_20niveau_52',['Documentatie Niveau',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md561',1,'']]],
  ['documentatie_20review_20sessie_53',['5.6 Checklist: Voor Documentatie Review Sessie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md625',1,'']]],
  ['documentatie_20richtlijnen_54',['Module Documentatie Richtlijnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html',1,'']]],
  ['documentatie_20structuur_55',['📚 Documentatie Structuur',['../index.html#autotoc_md310',1,'']]],
  ['documentatie_20types_56',['📚 Documentatie Types',['../doxygen_guidelines.html#autotoc_md633',1,'']]],
  ['documentatie_20verificatie_20protocol_57',['5. AI Agent Documentatie Verificatie Protocol',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md594',1,'']]],
  ['documentatie_20wijziging_3a_58',['Checklist voor elke documentatie wijziging:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md589',1,'']]],
  ['documentatie_3a_59',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md583',1,'']]],
  ['documentation_20claims_20extraction_60',['Fase 2: Documentation Claims Extraction',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md602',1,'']]],
  ['documenteren_61',['✅ Checklist: Nieuwe Module Documenteren',['../group__Titel.html#autotoc_md654',1,'']]],
  ['door_20niet_20te_20verifiëren_3a_62',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md586',1,'']]],
  ['download_20duration_63',['Download Duration',['../cloud_doc.html#autotoc_md56',1,'']]],
  ['download_20modem_20firmware_20v2_200_203_64',['Download Modem Firmware v2.0.3',['../provisioning.html#autotoc_md382',1,'']]],
  ['download_20pti_20modem_20firmware_20v2_203_208_65',['Download PTI Modem Firmware v2.3.8',['../provisioning.html#autotoc_md383',1,'']]],
  ['downloaden_66',['1.3 Modem Firmware Downloaden',['../provisioning.html#autotoc_md381',1,'']]],
  ['doxyfile_20configuratie_67',['⚙️ Doxyfile Configuratie',['../doxygen_guidelines.html#autotoc_md637',1,'']]],
  ['doxygen_20custom_20css_68',['Custom CSS (&lt;span class=&quot;tt&quot;&gt;docs/doxygen-custom.css&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md640',1,'']]],
  ['doxygen_20documentatie_69',['Doxygen Documentatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md539',1,'']]],
  ['doxygen_20documentatie_20guidelines_70',['Doxygen Documentatie Guidelines',['../doxygen_guidelines.html',1,'']]],
  ['driven_20network_20management_71',['Event-Driven Network Management',['../network_doc.html#autotoc_md162',1,'']]],
  ['dsmr_20meters_72',['Data Acquisitie van DSMR Meters',['../p_one_doc.html#autotoc_md185',1,'']]],
  ['dsmr_20module_20documentatie_73',['P1 DSMR Module - Documentatie',['../p_one_doc.html',1,'']]],
  ['duration_74',['Duration',['../cloud_doc.html#autotoc_md56',1,'Download Duration'],['../cloud_doc.html#autotoc_md57',1,'MCUboot Swap Duration']]],
  ['during_20fota_75',['Netwerk Loss During FOTA',['../cloud_doc.html#autotoc_md36',1,'']]]
];
