var searchData=
[
  ['na_20vergelijkingen_0',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md579',1,'']]],
  ['naar_20api_20elementen_1',['Links naar API Elementen',['../group__Titel.html#autotoc_md648',1,'']]],
  ['naar_20device_2',['Flash naar Device',['../provisioning.html#autotoc_md404',1,'']]],
  ['naar_20nrf_20cloud_3',['☁️ Fase 3: Bulk Onboarding naar nRF Cloud',['../provisioning.html#autotoc_md406',1,'']]],
  ['named_20constants_4',['Gebruik Named Constants',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md549',1,'']]],
  ['names_5',['Design Rationale: Short Key Names',['../message_queue_doc.html#autotoc_md144',1,'']]],
  ['naming_6',['Channel Naming',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md492',1,'']]],
  ['naming_20conventions_7',['Naming Conventions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md528',1,'']]],
  ['native_20sim_20handling_8',['Native Sim Handling',['../app_doc.html#autotoc_md15',1,'']]],
  ['navigatie_9',['Navigatie',['../app_doc.html#autotoc_md1',1,'🔗 Navigatie'],['../cloud_doc.html#autotoc_md17',1,'🔗 Navigatie'],['../energy_pulse_doc.html#autotoc_md69',1,'🔗 Navigatie'],['../led_doc.html#autotoc_md96',1,'🔗 Navigatie'],['../message_queue_doc.html#autotoc_md122',1,'🔗 Navigatie'],['../network_doc.html#autotoc_md157',1,'🔗 Navigatie'],['../p_one_doc.html#autotoc_md181',1,'🔗 Navigatie'],['../reboot_doc.html#autotoc_md228',1,'🔗 Navigatie'],['../timing_doc.html#autotoc_md258',1,'🔗 Navigatie']]],
  ['netwerk_20loss_20during_20fota_10',['Netwerk Loss During FOTA',['../cloud_doc.html#autotoc_md36',1,'']]],
  ['network_20management_11',['Event-Driven Network Management',['../network_doc.html#autotoc_md162',1,'']]],
  ['network_20module_20documentatie_12',['Network Module - Documentatie',['../network_doc.html',1,'']]],
  ['network_20status_20enums_13',['Network Status Enums',['../network_doc.html#autotoc_md168',1,'']]],
  ['network_20status_20flow_14',['Network Status Flow',['../network_doc.html#autotoc_md166',1,'']]],
  ['niet_20in_20moet_15',['❗ Wat ER NIET in moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md576',1,'']]],
  ['niet_20te_20verifiëren_3a_16',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md586',1,'']]],
  ['nieuwe_20module_17',['Checklist voor Nieuwe Module',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md447',1,'']]],
  ['nieuwe_20module_20documenteren_18',['✅ Checklist: Nieuwe Module Documenteren',['../group__Titel.html#autotoc_md654',1,'']]],
  ['niveau_19',['Documentatie Niveau',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md561',1,'']]],
  ['non_20blocking_20led_20control_20',['Non-Blocking LED Control',['../led_doc.html#autotoc_md102',1,'']]],
  ['nooit_20iets_20verzinnen_21',['Principe: NOOIT iets verzinnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md582',1,'']]],
  ['normal_20data_20collection_20elke_2030_20seconden_22',['📥 Normal Data Collection (elke 30 seconden)',['../index.html#autotoc_md293',1,'']]],
  ['not_20found_23',['not found',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md363',1,'"Board not found"'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md362',1,'"West command not found"']]],
  ['nrf_20cloud_24',['☁️ Fase 3: Bulk Onboarding naar nRF Cloud',['../provisioning.html#autotoc_md406',1,'']]],
  ['nrf_20cloud_20api_20key_25',['nRF Cloud API Key',['../provisioning.html#autotoc_md408',1,'']]],
  ['nrf_20connect_20environment_20activeren_26',['1.2 nRF Connect Environment Activeren',['../provisioning.html#autotoc_md379',1,'']]],
  ['nrfjprog_20direct_27',['Via nrfjprog (Direct)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md343',1,'']]],
  ['null_20checks_20en_20validatie_28',['NULL Checks en Validatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md552',1,'']]],
  ['numbers_20en_20constants_29',['Magic Numbers en Constants',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md547',1,'']]]
];
