var searchData=
[
  ['fase_201_3a_20build_20code_20inventory_20objectieve_20waarheid_0',['Fase 1: Build Code Inventory (Objectieve Waarheid)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md557',1,'']]],
  ['fase_201_3a_20eenmalige_20setup_1',['🛠️ Fase 1: Eenmalige Setup',['../provisioning.html#autotoc_md334',1,'']]],
  ['fase_202_3a_20documentation_20claims_20extraction_2',['Fase 2: Documentation Claims Extraction',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md559',1,'']]],
  ['fase_202_3a_20per_20device_20provisioneren_3',['🔧 Fase 2: Per Device Provisioneren',['../provisioning.html#autotoc_md348',1,'']]],
  ['fase_203_3a_20bulk_20onboarding_20naar_20nrf_20cloud_4',['☁️ Fase 3: Bulk Onboarding naar nRF Cloud',['../provisioning.html#autotoc_md363',1,'']]],
  ['fase_203_3a_20systematische_20verificatie_20per_20claim_20type_5',['Fase 3: Systematische Verificatie Per Claim Type',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md561',1,'']]],
  ['fase_204_3a_20documentatie_20anti_20patterns_20red_20flags_6',['Fase 4: Documentatie Anti-Patterns (Red Flags)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md570',1,'']]],
  ['fasen_7',['5.4 Verification Workflow (5 Fasen)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md575',1,'']]],
  ['feature_20consistency_20red_20flags_8',['4.3 Feature Consistency Red Flags',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md573',1,'']]],
  ['features_9',['Features',['../index.html#autotoc_md307',1,'⚙️ Belangrijke Features'],['../index.html#autotoc_md311',1,'🛡️ Robustness Features']]],
  ['feedback_20voor_20iot_20device_10',['Visuele Feedback voor IoT Device',['../led_doc.html#autotoc_md101',1,'']]],
  ['feedback_20waarde_11',['LED Feedback Waarde',['../led_doc.html#autotoc_md118',1,'']]],
  ['field_20definitions_12',['Field Definitions',['../message_queue_doc.html#autotoc_md151',1,'']]],
  ['file_20c_20template_13',['Source File (.c) Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md445',1,'']]],
  ['file_20h_20template_14',['Header File (.h) Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md446',1,'']]],
  ['file_20structuur_15',['File Structuur',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md444',1,'']]],
  ['files_16',['Multiple Source Files',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md460',1,'']]],
  ['files_17',['Include Order (in .c files)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md434',1,'']]],
  ['files_20h_18',['Header Files (.h)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md433',1,'']]],
  ['filosofie_19',['📋 Filosofie',['../doxygen_guidelines.html#autotoc_md588',1,'']]],
  ['firmware_20',['Firmware',['../provisioning.html#autotoc_md356',1,'Stap 1: Flash Productie Modem Firmware'],['../provisioning.html#autotoc_md350',1,'Stap 1: Flash PTI Modem Firmware']]],
  ['firmware_20documentatie_21',['SolarResult Dinnis Core - Firmware Documentatie',['../index.html',1,'']]],
  ['firmware_20downloaden_22',['1.3 Modem Firmware Downloaden',['../provisioning.html#autotoc_md338',1,'']]],
  ['firmware_20image_23',['Corrupte Firmware Image',['../cloud_doc.html#autotoc_md37',1,'']]],
  ['firmware_20v2_200_203_24',['Download Modem Firmware v2.0.3',['../provisioning.html#autotoc_md339',1,'']]],
  ['firmware_20v2_203_208_25',['Download PTI Modem Firmware v2.3.8',['../provisioning.html#autotoc_md340',1,'']]],
  ['first_20investigation_26',['5.2 Fundamenteel Principe: Code-First Investigation',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md554',1,'']]],
  ['fixed_20point_27',['Waarom Integer Fixed-Point?',['../p_one_doc.html#autotoc_md207',1,'']]],
  ['flags_28',['Flags',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md571',1,'4.1 Taalgebruik Red Flags'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md572',1,'4.2 Structurele Red Flags'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md573',1,'4.3 Feature Consistency Red Flags'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md570',1,'Fase 4: Documentatie Anti-Patterns (Red Flags)']]],
  ['flash_20capacity_29',['Flash Capacity',['../cloud_doc.html#autotoc_md38',1,'']]],
  ['flash_20modem_20shell_30',['Stap 3: Flash Modem Shell',['../provisioning.html#autotoc_md352',1,'']]],
  ['flash_20naar_20device_31',['Flash naar Device',['../provisioning.html#autotoc_md361',1,'']]],
  ['flash_20productie_20modem_20firmware_32',['Stap 1: Flash Productie Modem Firmware',['../provisioning.html#autotoc_md356',1,'']]],
  ['flash_20pti_20modem_20firmware_33',['Stap 1: Flash PTI Modem Firmware',['../provisioning.html#autotoc_md350',1,'']]],
  ['flash_20support_34',['Priority 1: External Flash Support',['../cloud_doc.html#autotoc_md61',1,'']]],
  ['flashen_35',['2.3 User Applicatie Flashen',['../provisioning.html#autotoc_md359',1,'']]],
  ['flow_36',['Flow',['../p_one_doc.html#autotoc_md200',1,'ACQ_TRIGGER Flow'],['../energy_pulse_doc.html#autotoc_md79',1,'Data Flow'],['../cloud_doc.html#autotoc_md28',1,'FOTA Event Flow'],['../message_queue_doc.html#autotoc_md135',1,'Gecoördineerde Data Collectie Flow'],['../network_doc.html#autotoc_md174',1,'Network Status Flow'],['../p_one_doc.html#autotoc_md201',1,'PUBLISH Flow'],['../energy_pulse_doc.html#autotoc_md77',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../led_doc.html#autotoc_md104',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../message_queue_doc.html#autotoc_md134',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../network_doc.html#autotoc_md173',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../reboot_doc.html#autotoc_md244',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../timing_doc.html#autotoc_md274',1,'Wat? (Functionaliteit &amp; Data Flow)']]],
  ['flow_20module_20interacties_37',['🔄 Data Flow &amp;amp; Module Interacties',['../index.html#autotoc_md297',1,'']]],
  ['flow_20scenarios_38',['Message Flow Scenarios',['../index.html#autotoc_md300',1,'']]],
  ['format_39',['Format',['../message_queue_doc.html#autotoc_md148',1,'Cloud Message Format'],['../message_queue_doc.html#autotoc_md137',1,'Message Format']]],
  ['formaten_40',['❗ Inconsistente Titel Formaten',['../group__Titel.html#autotoc_md615',1,'']]],
  ['formattering_41',['Indentatie en Formattering',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md479',1,'']]],
  ['formattering_20regels_42',['Code Style - Formattering Regels',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html',1,'']]],
  ['forward_20declarations_43',['Forward Declarations',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md436',1,'Forward Declarations'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md438',1,'State Machine Forward Declarations']]],
  ['fota_44',['FOTA',['../cloud_doc.html#autotoc_md36',1,'Netwerk Loss During FOTA'],['../cloud_doc.html#autotoc_md43',1,'Outbound (Using FOTA)']]],
  ['fota_20channel_20publishing_45',['FOTA Channel Publishing',['../cloud_doc.html#autotoc_md33',1,'']]],
  ['fota_20end_20to_20end_20test_46',['FOTA End-to-End Test',['../cloud_doc.html#autotoc_md52',1,'']]],
  ['fota_20event_20flow_47',['FOTA Event Flow',['../cloud_doc.html#autotoc_md28',1,'']]],
  ['fota_20orchestratie_48',['FOTA Orchestratie',['../cloud_doc.html#autotoc_md24',1,'']]],
  ['fota_20requires_49',['Inbound (FOTA Requires)',['../cloud_doc.html#autotoc_md42',1,'']]],
  ['fota_20windows_50',['Priority 2: Scheduled FOTA Windows',['../cloud_doc.html#autotoc_md62',1,'']]],
  ['fout_20verzonnen_20content_20_3a_51',['❗ FOUT (verzonnen content):',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md544',1,'']]],
  ['fouten_20door_20niet_20te_20verifiëren_3a_52',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md543',1,'']]],
  ['frame_20level_20timing_2087_20µs_53',['Frame-Level Timing (87 µs)',['../p_one_doc.html#autotoc_md222',1,'']]],
  ['frame_20timing_20fundamentals_54',['UART Frame Timing Fundamentals',['../p_one_doc.html#autotoc_md216',1,'']]],
  ['functies_55',['Functies',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md486',1,'']]],
  ['functionaliteit_56',['Functionaliteit',['../app_doc.html#autotoc_md7',1,'Functionaliteit'],['../p_one_doc.html#autotoc_md192',1,'Functionaliteit'],['../cloud_doc.html#autotoc_md26',1,'Wat? (Functionaliteit)']]],
  ['functionaliteit_20data_20flow_57',['Functionaliteit Data Flow',['../energy_pulse_doc.html#autotoc_md77',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../led_doc.html#autotoc_md104',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../message_queue_doc.html#autotoc_md134',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../network_doc.html#autotoc_md173',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../reboot_doc.html#autotoc_md244',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../timing_doc.html#autotoc_md274',1,'Wat? (Functionaliteit &amp; Data Flow)']]],
  ['functions_58',['State Handler Functions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md392',1,'']]],
  ['fundamentals_59',['Fundamentals',['../p_one_doc.html#autotoc_md216',1,'UART Frame Timing Fundamentals'],['../p_one_doc.html#autotoc_md195',1,'UART Timing Calculations - Fundamentals']]],
  ['fundamenteel_20principe_3a_20code_20first_20investigation_60',['5.2 Fundamenteel Principe: Code-First Investigation',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md554',1,'']]],
  ['future_20uitbreidingen_61',['Future Uitbreidingen',['../led_doc.html#autotoc_md121',1,'']]]
];
