var searchData=
[
  ['c_20files_0',['Include Order (in .c files)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md477',1,'']]],
  ['c_20template_1',['Source File (.c) Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md488',1,'']]],
  ['cache_20corrupt_2',['&quot;Build cache corrupt&quot;',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md364',1,'']]],
  ['calculations_3',['Critical Timing Calculations',['../p_one_doc.html#autotoc_md209',1,'']]],
  ['calculations_20fundamentals_4',['UART Timing Calculations - Fundamentals',['../p_one_doc.html#autotoc_md187',1,'']]],
  ['call_20graphs_5',['📊 Call Graphs',['../index.html#autotoc_md312',1,'']]],
  ['callback_20behavior_6',['Watchdog Callback Behavior',['../app_doc.html#autotoc_md14',1,'']]],
  ['callback_20pattern_7',['Callback Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md462',1,'']]],
  ['callbacks_8',['GPIO Callbacks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md451',1,'']]],
  ['callbacks_20asynchrone_20data_20ontvangst_9',['1. UART Callbacks (Asynchrone Data Ontvangst)',['../p_one_doc.html#autotoc_md195',1,'']]],
  ['capacity_10',['Flash Capacity',['../cloud_doc.html#autotoc_md38',1,'']]],
  ['case_20scenarios_11',['Edge Case Scenarios',['../p_one_doc.html#autotoc_md218',1,'']]],
  ['case_3a_20typische_20dag_12',['Use Case: Typische Dag',['../timing_doc.html#autotoc_md269',1,'']]],
  ['cases_13',['Cases',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md566',1,'3. Edge Cases'],['../cloud_doc.html#autotoc_md35',1,'Edge Cases']]],
  ['cases_20robuustheid_14',['Edge Cases &amp;amp; Robuustheid',['../p_one_doc.html#autotoc_md201',1,'']]],
  ['certificaten_20genereren_15',['1.5 Certificaten Genereren',['../provisioning.html#autotoc_md387',1,'']]],
  ['certificaten_20installeren_16',['2.2 Certificaten Installeren',['../provisioning.html#autotoc_md398',1,'']]],
  ['certificaten_20programmeren_17',['Stap 2: Certificaten Programmeren',['../provisioning.html#autotoc_md400',1,'']]],
  ['channel_20declarations_20vs_20definitions_18',['Channel Declarations vs Definitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md494',1,'']]],
  ['channel_20naming_19',['Channel Naming',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md492',1,'']]],
  ['channel_20overzicht_20',['ZBUS Channel Overzicht',['../index.html#autotoc_md291',1,'']]],
  ['channel_20publishing_21',['FOTA Channel Publishing',['../cloud_doc.html#autotoc_md33',1,'']]],
  ['channels_22',['ZBUS Channels',['../cloud_doc.html#autotoc_md20',1,'']]],
  ['channels_20published_23',['ZBUS Channels (Published)',['../timing_doc.html#autotoc_md267',1,'']]],
  ['checklist_24',['Checklist',['../provisioning.html#autotoc_md413',1,'✅ Checklist'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md507',1,'Module Checklist']]],
  ['checklist_20voor_20elke_20documentatie_20wijziging_3a_25',['Checklist voor elke documentatie wijziging:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md589',1,'']]],
  ['checklist_20voor_20nieuwe_20module_26',['Checklist voor Nieuwe Module',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md447',1,'']]],
  ['checklist_3a_20nieuwe_20module_20documenteren_27',['✅ Checklist: Nieuwe Module Documenteren',['../group__Titel.html#autotoc_md654',1,'']]],
  ['checklist_3a_20voor_20documentatie_20review_20sessie_28',['5.6 Checklist: Voor Documentatie Review Sessie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md625',1,'']]],
  ['checks_29',['Checks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md554',1,'Bool Checks'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md450',1,'Device Readiness Checks']]],
  ['checks_20en_20validatie_30',['NULL Checks en Validatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md552',1,'']]],
  ['claim_20type_31',['Fase 3: Systematische Verificatie Per Claim Type',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md604',1,'']]],
  ['claims_32',['Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md605',1,'3.1 Architectuur Pattern Claims'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md607',1,'3.2 Communication Pattern Claims'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md609',1,'3.3 Configuration &amp; Constants Claims'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md611',1,'3.4 Timing &amp; Behavior Claims']]],
  ['claims_20extraction_33',['Fase 2: Documentation Claims Extraction',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md602',1,'']]],
  ['clarification_34',['Gas Unit Clarification',['../message_queue_doc.html#autotoc_md147',1,'']]],
  ['clean_20build_35',['Clean Build',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md337',1,'']]],
  ['cloud_36',['☁️ Fase 3: Bulk Onboarding naar nRF Cloud',['../provisioning.html#autotoc_md406',1,'']]],
  ['cloud_20api_20key_37',['nRF Cloud API Key',['../provisioning.html#autotoc_md408',1,'']]],
  ['cloud_20connectie_20state_20machine_38',['Cloud Connectie State Machine',['../cloud_doc.html#autotoc_md27',1,'']]],
  ['cloud_20connectiviteit_39',['Cloud Connectiviteit',['../cloud_doc.html#autotoc_md23',1,'']]],
  ['cloud_20integratie_40',['☁️ Cloud Integratie',['../index.html#autotoc_md302',1,'']]],
  ['cloud_20message_20format_41',['Cloud Message Format',['../message_queue_doc.html#autotoc_md140',1,'']]],
  ['cloud_20module_20documentatie_42',['Cloud Module - Documentatie',['../cloud_doc.html',1,'']]],
  ['cloud_20transmission_20elke_2030_20minuten_43',['☁️ Cloud Transmission (elke 30 minuten)',['../index.html#autotoc_md295',1,'']]],
  ['cmakelists_44',['Integration in Parent CMakeLists',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md505',1,'']]],
  ['cmakelists_20txt_45',['CMakeLists.txt',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md512',1,'']]],
  ['cmakelists_20txt_20voor_20modules_46',['CMakeLists.txt voor Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md500',1,'']]],
  ['coördinatie_20mechanisme_47',['TRIGGER_CHAN als Coördinatie Mechanisme',['../app_doc.html#autotoc_md5',1,'']]],
  ['code_48',['2. Herhalingen van Blokken Code',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md578',1,'']]],
  ['code_20analysis_20commands_20voorbeelden_49',['Code Analysis Commands (Voorbeelden)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md621',1,'']]],
  ['code_20first_20investigation_50',['5.2 Fundamenteel Principe: Code-First Investigation',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md597',1,'']]],
  ['code_20implementatie_20voorbeelden_51',['1. Code Implementatie Voorbeelden',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md577',1,'']]],
  ['code_20inventory_20objectieve_20waarheid_52',['Fase 1: Build Code Inventory (Objectieve Waarheid)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md600',1,'']]],
  ['code_20structure_20organisatie_20en_20volgorde_53',['Code Structure - Organisatie en Volgorde',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html',1,'']]],
  ['code_20structuur_54',['Code Structuur',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md509',1,'']]],
  ['code_20style_20formattering_20regels_55',['Code Style - Formattering Regels',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html',1,'']]],
  ['code_20verificatie_20en_20synchronisatie_20kritiek_20⚠️_56',['4. Code Verificatie en Synchronisatie (KRITIEK! ⚠️)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md581',1,'']]],
  ['collectie_57',['Gecoördineerde Data Collectie',['../message_queue_doc.html#autotoc_md127',1,'']]],
  ['collectie_20flow_58',['Gecoördineerde Data Collectie Flow',['../message_queue_doc.html#autotoc_md131',1,'']]],
  ['collection_20elke_2030_20seconden_59',['📥 Normal Data Collection (elke 30 seconden)',['../index.html#autotoc_md293',1,'']]],
  ['command_20not_20found_60',['&quot;West command not found&quot;',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md362',1,'']]],
  ['commands_61',['5.5 Practical Tools &amp;amp; Commands',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md620',1,'']]],
  ['commands_20context_62',['Git History Commands (Context)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md622',1,'']]],
  ['commands_20voorbeelden_63',['Code Analysis Commands (Voorbeelden)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md621',1,'']]],
  ['comment_20style_64',['Comment Style',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md538',1,'']]],
  ['comments_20en_20documentatie_65',['Comments en Documentatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md537',1,'']]],
  ['common_20patterns_66',['Common Patterns',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md459',1,'']]],
  ['common_20pitfalls_67',['🚨 Common Pitfalls',['../group__Titel.html#autotoc_md656',1,'']]],
  ['communication_20pattern_20claims_68',['3.2 Communication Pattern Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md607',1,'']]],
  ['compilatie_20pattern_69',['Conditionele Compilatie Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md502',1,'']]],
  ['compileren_70',['Standaard Pattern (Altijd Compileren)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md501',1,'']]],
  ['complete_20system_20timeline_71',['Complete System Timeline',['../timing_doc.html#autotoc_md268',1,'']]],
  ['conditionele_20compilatie_20pattern_72',['Conditionele Compilatie Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md502',1,'']]],
  ['conf_73',['conf',['../cloud_doc.html#autotoc_md46',1,'Kconfig (prj.conf)'],['../cloud_doc.html#autotoc_md47',1,'Sysbuild (sysbuild.conf)']]],
  ['configuratie_74',['Configuratie',['../doxygen_guidelines.html#autotoc_md637',1,'⚙️ Doxyfile Configuratie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md331',1,'⚙️ West Configuratie'],['../app_doc.html#autotoc_md13',1,'Configuratie'],['../cloud_doc.html#autotoc_md45',1,'Configuratie'],['../message_queue_doc.html#autotoc_md151',1,'Configuratie'],['../network_doc.html#autotoc_md175',1,'Configuratie'],['../p_one_doc.html#autotoc_md203',1,'Configuratie'],['../index.html#autotoc_md308',1,'Configuratie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md444',1,'Configuratie'],['../energy_pulse_doc.html#autotoc_md78',1,'Kanaal Configuratie'],['../timing_doc.html#autotoc_md273',1,'Timer Configuratie']]],
  ['configuratie_20kconfig_75',['Configuratie Kconfig',['../energy_pulse_doc.html#autotoc_md86',1,'Configuratie (Kconfig)'],['../timing_doc.html#autotoc_md275',1,'Configuratie (Kconfig)']]],
  ['configuration_20constants_20claims_76',['3.3 Configuration &amp;amp; Constants Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md609',1,'']]],
  ['confirmation_77',['Boot Confirmation',['../cloud_doc.html#autotoc_md32',1,'']]],
  ['confirmation_20window_78',['Boot Confirmation Window',['../cloud_doc.html#autotoc_md58',1,'']]],
  ['connect_20environment_20activeren_79',['1.2 nRF Connect Environment Activeren',['../provisioning.html#autotoc_md379',1,'']]],
  ['connectie_20state_20machine_80',['Cloud Connectie State Machine',['../cloud_doc.html#autotoc_md27',1,'']]],
  ['connection_20manager_20integration_81',['Zephyr Connection Manager Integration',['../network_doc.html#autotoc_md172',1,'']]],
  ['connectiviteit_82',['Cloud Connectiviteit',['../cloud_doc.html#autotoc_md23',1,'']]],
  ['consistency_20red_20flags_83',['4.3 Feature Consistency Red Flags',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md616',1,'']]],
  ['console_84',['Serial Console',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md347',1,'']]],
  ['constanten_20en_20defines_85',['Constanten en Defines',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md531',1,'']]],
  ['constants_86',['Constants',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md549',1,'Gebruik Named Constants'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md547',1,'Magic Numbers en Constants']]],
  ['constants_20claims_87',['3.3 Configuration &amp;amp; Constants Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md609',1,'']]],
  ['constraint_88',['Buffer Size Constraint',['../p_one_doc.html#autotoc_md224',1,'']]],
  ['contact_89',['📞 Contact',['../index.html#autotoc_md319',1,'']]],
  ['content_20_3a_90',['❗ FOUT (verzonnen content):',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md587',1,'']]],
  ['context_91',['Git History Commands (Context)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md622',1,'']]],
  ['contract_92',['External Interface Contract',['../message_queue_doc.html#autotoc_md141',1,'']]],
  ['control_93',['Non-Blocking LED Control',['../led_doc.html#autotoc_md102',1,'']]],
  ['control_20patterns_94',['LED Control Patterns',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md452',1,'']]],
  ['conventie_95',['Bestandsnaam Conventie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md559',1,'']]],
  ['conventies_96',['Conventies',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md422',1,'Return Value Conventies'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md491',1,'ZBUS Conventies']]],
  ['conventions_97',['Naming Conventions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md528',1,'']]],
  ['conversie_98',['OBIS Parsing &amp;amp; Data Conversie',['../p_one_doc.html#autotoc_md188',1,'']]],
  ['core_20firmware_20documentatie_99',['SolarResult Dinnis Core - Firmware Documentatie',['../index.html',1,'']]],
  ['correct_20geverifieerd_20_3a_100',['✅ CORRECT (geverifieerd):',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md588',1,'']]],
  ['corrupt_101',['&quot;Build cache corrupt&quot;',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md364',1,'']]],
  ['corrupte_20firmware_20image_102',['Corrupte Firmware Image',['../cloud_doc.html#autotoc_md37',1,'']]],
  ['crash_103',['Rollback Test (Warning: Intentional Crash)',['../cloud_doc.html#autotoc_md53',1,'']]],
  ['crc16_20validatie_104',['CRC16 Validatie',['../p_one_doc.html#autotoc_md200',1,'']]],
  ['critical_20dependencies_105',['Critical Dependencies',['../p_one_doc.html#autotoc_md222',1,'']]],
  ['critical_20timing_20calculations_106',['Critical Timing Calculations',['../p_one_doc.html#autotoc_md209',1,'']]],
  ['cross_20referencing_107',['🔗 Cross-Referencing',['../doxygen_guidelines.html#autotoc_md646',1,'']]],
  ['css_108',['Custom CSS (&lt;span class=&quot;tt&quot;&gt;docs/doxygen-custom.css&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md640',1,'']]],
  ['css_20docs_20doxygen_20custom_20css_109',['Custom CSS (&lt;span class=&quot;tt&quot;&gt;docs/doxygen-custom.css&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md640',1,'']]],
  ['custom_20board_20definitie_110',['🔧 Custom Board Definitie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md355',1,'']]],
  ['custom_20board_20definition_111',['Custom Board Definition',['../index.html#autotoc_md307',1,'']]],
  ['custom_20css_112',['Custom CSS (&lt;span class=&quot;tt&quot;&gt;docs/doxygen-custom.css&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md640',1,'']]],
  ['custom_20css_20docs_20doxygen_20custom_20css_113',['Custom CSS (&lt;span class=&quot;tt&quot;&gt;docs/doxygen-custom.css&lt;/span&gt;)',['../doxygen_guidelines.html#autotoc_md640',1,'']]],
  ['custom_20overlays_114',['Custom Overlays',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md370',1,'']]],
  ['custom_20runner_115',['Flash met Custom Runner',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md344',1,'']]]
];
