var searchData=
[
  ['taalgebruik_20red_20flags_0',['4.1 Taalgebruik Red Flags',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md567',1,'']]],
  ['tabs_1',['Spaties (GEEN Tabs)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md476',1,'']]],
  ['task_20watchdog_2',['Task Watchdog',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md396',1,'']]],
  ['task_20watchdog_20indien_20module_20eigen_20thread_20heeft_3',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md467',1,'']]],
  ['te_20verifiëren_3a_4',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md539',1,'']]],
  ['technische_20diepgang_5',['Technische Diepgang',['../p_one_doc.html#autotoc_md202',1,'']]],
  ['telegram_6',['Scenario 2: Maximum Length Telegram',['../p_one_doc.html#autotoc_md224',1,'']]],
  ['telegram_20timeout_20784_20ms_7',['Telegram Timeout (784 ms)',['../p_one_doc.html#autotoc_md220',1,'']]],
  ['telegram_20transmission_20time_8',['1. Maximum Telegram Transmission Time',['../p_one_doc.html#autotoc_md214',1,'']]],
  ['template_9',['Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md442',1,'Header File (.h) Template'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md441',1,'Source File (.c) Template']]],
  ['test_10',['FOTA End-to-End Test',['../cloud_doc.html#autotoc_md52',1,'']]],
  ['test_20warning_3a_20intentional_20crash_11',['Rollback Test (Warning: Intentional Crash)',['../cloud_doc.html#autotoc_md53',1,'']]],
  ['testing_12',['Testing',['../cloud_doc.html#autotoc_md50',1,'Testing'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md468',1,'Testing']]],
  ['these_20specific_20timeouts_20matter_13',['Why These Specific Timeouts Matter',['../p_one_doc.html#autotoc_md217',1,'']]],
  ['thread_14',['Message Processing in Thread',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md384',1,'']]],
  ['thread_20heeft_15',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md467',1,'']]],
  ['thread_20loop_20met_20zbus_20smf_16',['Thread Loop met ZBUS + SMF',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md413',1,'']]],
  ['thread_20loop_20structuur_17',['Thread Loop Structuur',['../p_one_doc.html#autotoc_md201',1,'']]],
  ['thread_20model_18',['Thread Model',['../app_doc.html#autotoc_md11',1,'']]],
  ['time_19',['Time',['../p_one_doc.html#autotoc_md214',1,'1. Maximum Telegram Transmission Time'],['../led_doc.html#autotoc_md115',1,'Minimum Display Time']]],
  ['timeline_20',['Complete System Timeline',['../timing_doc.html#autotoc_md272',1,'']]],
  ['timeout_21',['3. Total Response Timeout',['../p_one_doc.html#autotoc_md216',1,'']]],
  ['timeout_22',['2. UART RX Timeout (Inter-byte timeout)',['../p_one_doc.html#autotoc_md215',1,'']]],
  ['timeout_2010_208s_23',['Response Timeout (10.8s)',['../p_one_doc.html#autotoc_md221',1,'']]],
  ['timeout_20392_20ms_24',['Inter-byte Timeout (392 ms)',['../p_one_doc.html#autotoc_md219',1,'']]],
  ['timeout_20784_20ms_25',['Telegram Timeout (784 ms)',['../p_one_doc.html#autotoc_md220',1,'']]],
  ['timeout_20inter_20byte_20timeout_26',['2. UART RX Timeout (Inter-byte timeout)',['../p_one_doc.html#autotoc_md215',1,'']]],
  ['timeout_20mechanisme_27',['Timeout Mechanisme',['../reboot_doc.html#autotoc_md249',1,'']]],
  ['timeout_20strategy_28',['Multi-Layer Timeout Strategy',['../p_one_doc.html#autotoc_md230',1,'']]],
  ['timeout_20trigger_29',['Scenario 3: Inter-byte Timeout Trigger',['../p_one_doc.html#autotoc_md225',1,'']]],
  ['timeouts_20matter_30',['Why These Specific Timeouts Matter',['../p_one_doc.html#autotoc_md217',1,'']]],
  ['timer_20configuratie_31',['Timer Configuratie',['../timing_doc.html#autotoc_md277',1,'']]],
  ['timing_32',['Timing',['../timing_doc.html#autotoc_md267',1,'Gecoördineerde Timing'],['../p_one_doc.html#autotoc_md190',1,'UART Async API &amp; Timing']]],
  ['timing_2087_20µs_33',['Frame-Level Timing (87 µs)',['../p_one_doc.html#autotoc_md218',1,'']]],
  ['timing_20accuracy_34',['Timing Accuracy',['../timing_doc.html#autotoc_md283',1,'']]],
  ['timing_20analyse_35',['📐 Appendix A: UART Timing Analyse',['../p_one_doc.html#autotoc_md210',1,'']]],
  ['timing_20behavior_20claims_36',['3.4 Timing &amp;amp; Behavior Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md564',1,'']]],
  ['timing_20berekening_37',['Timing Berekening',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md399',1,'']]],
  ['timing_20calculations_38',['Critical Timing Calculations',['../p_one_doc.html#autotoc_md213',1,'']]],
  ['timing_20calculations_20fundamentals_39',['UART Timing Calculations - Fundamentals',['../p_one_doc.html#autotoc_md191',1,'']]],
  ['timing_20diagrammen_40',['8. Timing Diagrammen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md524',1,'']]],
  ['timing_20fundamentals_41',['UART Frame Timing Fundamentals',['../p_one_doc.html#autotoc_md212',1,'']]],
  ['timing_20module_20documentatie_42',['Timing Module - Documentatie',['../timing_doc.html',1,'']]],
  ['timing_20parameters_20summary_43',['Key Timing Parameters Summary',['../p_one_doc.html#autotoc_md229',1,'']]],
  ['timing_20performance_44',['Timing &amp;amp; Performance',['../cloud_doc.html#autotoc_md55',1,'']]],
  ['timing_20uitleg_45',['7. Timing Uitleg',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md523',1,'']]],
  ['timing_20watchdog_46',['Timing &amp;amp; Watchdog',['../p_one_doc.html#autotoc_md206',1,'']]],
  ['titel_20formaten_47',['❗ Inconsistente Titel Formaten',['../group__Titel.html#autotoc_md611',1,'']]],
  ['to_20end_20test_48',['FOTA End-to-End Test',['../cloud_doc.html#autotoc_md52',1,'']]],
  ['toekomstige_20uitbreidingen_49',['Toekomstige Uitbreidingen',['../cloud_doc.html#autotoc_md60',1,'Toekomstige Uitbreidingen'],['../energy_pulse_doc.html#autotoc_md92',1,'Toekomstige Uitbreidingen'],['../message_queue_doc.html#autotoc_md157',1,'Toekomstige Uitbreidingen'],['../network_doc.html#autotoc_md181',1,'Toekomstige Uitbreidingen'],['../reboot_doc.html#autotoc_md255',1,'Toekomstige Uitbreidingen'],['../timing_doc.html#autotoc_md285',1,'Toekomstige Uitbreidingen']]],
  ['toelichting_50',['Toelichting',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md427',1,'']]],
  ['tools_20commands_51',['5.5 Practical Tools &amp;amp; Commands',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md573',1,'']]],
  ['total_20response_20timeout_52',['3. Total Response Timeout',['../p_one_doc.html#autotoc_md216',1,'']]],
  ['tracking_53',['Tracking',['../reboot_doc.html#autotoc_md248',1,'Acknowledgement Tracking'],['../reboot_doc.html#autotoc_md238',1,'Reboot Reason Tracking']]],
  ['trade_20offs_54',['Trade offs',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md521',1,'5. Afwegingen (Trade-offs)'],['../energy_pulse_doc.html#autotoc_md91',1,'Design Trade-offs']]],
  ['transities_55',['9. State Machine Transities',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md525',1,'']]],
  ['transitions_56',['State Transitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md389',1,'']]],
  ['transmission_20elke_2030_20minuten_57',['☁️ Cloud Transmission (elke 30 minuten)',['../index.html#autotoc_md299',1,'']]],
  ['transmission_20time_58',['1. Maximum Telegram Transmission Time',['../p_one_doc.html#autotoc_md214',1,'']]],
  ['transport_20details_59',['Transport Details',['../message_queue_doc.html#autotoc_md150',1,'']]],
  ['trigger_60',['Scenario 3: Inter-byte Timeout Trigger',['../p_one_doc.html#autotoc_md225',1,'']]],
  ['trigger_5fchan_20als_20coördinatie_20mechanisme_61',['TRIGGER_CHAN als Coördinatie Mechanisme',['../app_doc.html#autotoc_md5',1,'']]],
  ['triggers_62',['2. ZBUS Message Handling (Periodieke Triggers)',['../p_one_doc.html#autotoc_md200',1,'']]],
  ['txt_63',['CMakeLists.txt',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md465',1,'']]],
  ['txt_20voor_20modules_64',['CMakeLists.txt voor Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md453',1,'']]],
  ['type_65',['Fase 3: Systematische Verificatie Per Claim Type',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md557',1,'']]],
  ['type_20aannames_66',['Type Aannames',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md409',1,'']]],
  ['types_67',['Types',['../doxygen_guidelines.html#autotoc_md586',1,'📚 Documentatie Types'],['../reboot_doc.html#autotoc_md241',1,'Reboot Types']]],
  ['typische_20dag_68',['Use Case: Typische Dag',['../timing_doc.html#autotoc_md273',1,'']]],
  ['typische_20scenario_20s_69',['Typische Scenario s',['../led_doc.html#autotoc_md107',1,'Typische Scenario's'],['../led_doc.html#autotoc_md108',1,'Typische Scenario's']]]
];
