var searchData=
[
  ['s_0',['s',['../index.html#autotoc_md313',1,'📁 Module README's'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md481',1,'Macro's'],['../led_doc.html#autotoc_md107',1,'Typische Scenario's']]],
  ['safety_1',['Security en Safety',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md417',1,'']]],
  ['safety_20mechanism_2',['Hardware Watchdog als Safety Mechanism',['../app_doc.html#autotoc_md4',1,'']]],
  ['samenvatting_3',['Samenvatting',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md541',1,'']]],
  ['samenvatting_20protocol_4',['5.8 Samenvatting Protocol',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md578',1,'']]],
  ['sampling_5',['Rolling Statistics &amp;amp; Sampling',['../p_one_doc.html#autotoc_md189',1,'']]],
  ['scenario_201_3a_20slow_20p1_20device_20response_6',['Scenario 1: Slow P1 Device Response',['../p_one_doc.html#autotoc_md219',1,'']]],
  ['scenario_202_3a_20maximum_20length_20telegram_7',['Scenario 2: Maximum Length Telegram',['../p_one_doc.html#autotoc_md220',1,'']]],
  ['scenario_203_3a_20inter_20byte_20timeout_20trigger_8',['Scenario 3: Inter-byte Timeout Trigger',['../p_one_doc.html#autotoc_md221',1,'']]],
  ['scenario_20s_9',['Typische Scenario&apos;s',['../led_doc.html#autotoc_md107',1,'']]],
  ['scenarios_10',['Scenarios',['../p_one_doc.html#autotoc_md218',1,'Edge Case Scenarios'],['../index.html#autotoc_md292',1,'Message Flow Scenarios'],['../message_queue_doc.html#autotoc_md145',1,'Message Presence Scenarios']]],
  ['scheduled_20fota_20windows_11',['Priority 2: Scheduled FOTA Windows',['../cloud_doc.html#autotoc_md62',1,'']]],
  ['scheduling_12',['K_NO_WAIT voor Immediate Scheduling',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md388',1,'']]],
  ['schrijven_20of_20bewerken_20van_20documentatie_3a_13',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md532',1,'']]],
  ['schrijven_20via_20rtt_14',['Stap 4: IMEI Schrijven via RTT',['../provisioning.html#autotoc_md345',1,'']]],
  ['scope_20en_20static_15',['Scope en Static',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md492',1,'']]],
  ['seconden_16',['📥 Normal Data Collection (elke 30 seconden)',['../index.html#autotoc_md293',1,'']]],
  ['sectie_20headers_17',['Sectie Headers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md433',1,'']]],
  ['secties_20in_20volgorde_18',['Standaard Secties (in volgorde)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md434',1,'']]],
  ['security_20en_20safety_19',['Security en Safety',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md417',1,'']]],
  ['sequence_20',['Sequence',['../index.html#autotoc_md296',1,'🔄 Startup Sequence'],['../energy_pulse_doc.html#autotoc_md83',1,'Initialisatie Sequence'],['../reboot_doc.html#autotoc_md240',1,'Shutdown Sequence']]],
  ['sessie_21',['5.6 Checklist: Voor Documentatie Review Sessie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md574',1,'']]],
  ['setup_22',['Setup',['../provisioning.html#autotoc_md326',1,'🛠️ Fase 1: Eenmalige Setup'],['../provisioning.html#autotoc_md363',1,'Eenmalige Setup'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md383',1,'State Machine Setup']]],
  ['setup_20pattern_23',['Module Setup Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md394',1,'']]],
  ['shell_24',['Stap 3: Flash Modem Shell',['../provisioning.html#autotoc_md344',1,'']]],
  ['shell_20mosh_20bouwen_25',['1.4 Modem Shell (MoSh) Bouwen',['../provisioning.html#autotoc_md334',1,'']]],
  ['short_20key_20names_26',['Design Rationale: Short Key Names',['../message_queue_doc.html#autotoc_md144',1,'']]],
  ['shortcuts_27',['Verification Shortcuts',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md572',1,'']]],
  ['shutdown_28',['Shutdown',['../index.html#autotoc_md297',1,'🛑 Graceful Shutdown'],['../reboot_doc.html#autotoc_md233',1,'Graceful Shutdown']]],
  ['shutdown_20betrouwbaarheid_29',['Shutdown Betrouwbaarheid',['../reboot_doc.html#autotoc_md248',1,'']]],
  ['shutdown_20gedrag_30',['Graceful Shutdown Gedrag',['../reboot_doc.html#autotoc_md249',1,'']]],
  ['shutdown_20implementatie_20vereisten_31',['Module Shutdown Implementatie Vereisten',['../reboot_doc.html#autotoc_md253',1,'']]],
  ['shutdown_20sequence_32',['Shutdown Sequence',['../reboot_doc.html#autotoc_md240',1,'']]],
  ['sim_20handling_33',['Native Sim Handling',['../app_doc.html#autotoc_md15',1,'']]],
  ['size_20constraint_34',['Buffer Size Constraint',['../p_one_doc.html#autotoc_md224',1,'']]],
  ['sizeof_20operator_35',['sizeof Operator',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md494',1,'']]],
  ['slag_36',['🚀 Aan de Slag',['../index.html#autotoc_md305',1,'']]],
  ['slow_20p1_20device_20response_37',['Scenario 1: Slow P1 Device Response',['../p_one_doc.html#autotoc_md219',1,'']]],
  ['smf_38',['SMF',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md382',1,'State Machine Patterns (SMF)'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md409',1,'Thread Loop met ZBUS + SMF']]],
  ['solarresult_20dinnis_20core_20firmware_20documentatie_39',['SolarResult Dinnis Core - Firmware Documentatie',['../index.html',1,'']]],
  ['source_20file_20c_20template_40',['Source File (.c) Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md437',1,'']]],
  ['source_20files_41',['Multiple Source Files',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md452',1,'']]],
  ['spaties_20geen_20tabs_42',['Spaties (GEEN Tabs)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md472',1,'']]],
  ['specific_20timeouts_20matter_43',['Why These Specific Timeouts Matter',['../p_one_doc.html#autotoc_md213',1,'']]],
  ['specificaties_44',['1. Specificaties',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md513',1,'']]],
  ['standaard_20pattern_20altijd_20compileren_45',['Standaard Pattern (Altijd Compileren)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md450',1,'']]],
  ['standaard_20secties_20in_20volgorde_46',['Standaard Secties (in volgorde)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md434',1,'']]],
  ['stap_201_3a_20flash_20productie_20modem_20firmware_47',['Stap 1: Flash Productie Modem Firmware',['../provisioning.html#autotoc_md348',1,'']]],
  ['stap_201_3a_20flash_20pti_20modem_20firmware_48',['Stap 1: Flash PTI Modem Firmware',['../provisioning.html#autotoc_md342',1,'']]],
  ['stap_202_3a_20certificaten_20programmeren_49',['Stap 2: Certificaten Programmeren',['../provisioning.html#autotoc_md349',1,'']]],
  ['stap_202_3a_20device_20recoveren_50',['Stap 2: Device Recoveren',['../provisioning.html#autotoc_md343',1,'']]],
  ['stap_203_3a_20flash_20modem_20shell_51',['Stap 3: Flash Modem Shell',['../provisioning.html#autotoc_md344',1,'']]],
  ['stap_204_3a_20imei_20schrijven_20via_20rtt_52',['Stap 4: IMEI Schrijven via RTT',['../provisioning.html#autotoc_md345',1,'']]],
  ['stappen_3a_53',['✅ VERPLICHTE STAPPEN:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md533',1,'']]],
  ['startup_20sequence_54',['🔄 Startup Sequence',['../index.html#autotoc_md296',1,'']]],
  ['state_20handler_20functions_55',['State Handler Functions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md384',1,'']]],
  ['state_20machine_56',['State Machine',['../cloud_doc.html#autotoc_md27',1,'Cloud Connectie State Machine'],['../message_queue_doc.html#autotoc_md136',1,'State Machine'],['../network_doc.html#autotoc_md171',1,'State Machine'],['../reboot_doc.html#autotoc_md243',1,'State Machine'],['../timing_doc.html#autotoc_md274',1,'State Machine']]],
  ['state_20machine_20forward_20declarations_57',['State Machine Forward Declarations',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md430',1,'']]],
  ['state_20machine_20patterns_20smf_58',['State Machine Patterns (SMF)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md382',1,'']]],
  ['state_20machine_20setup_59',['State Machine Setup',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md383',1,'']]],
  ['state_20machine_20transities_60',['9. State Machine Transities',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md521',1,'']]],
  ['state_20management_61',['State Management',['../led_doc.html#autotoc_md112',1,'']]],
  ['state_20transitions_62',['State Transitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md385',1,'']]],
  ['static_63',['Scope en Static',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md492',1,'']]],
  ['statistics_20elke_2010_20minuten_64',['📊 Publish Statistics (elke 10 minuten)',['../index.html#autotoc_md294',1,'']]],
  ['statistics_20sampling_65',['Rolling Statistics &amp;amp; Sampling',['../p_one_doc.html#autotoc_md189',1,'']]],
  ['status_20enums_66',['Network Status Enums',['../network_doc.html#autotoc_md168',1,'']]],
  ['status_20flow_67',['Network Status Flow',['../network_doc.html#autotoc_md166',1,'']]],
  ['status_20patronen_68',['LED Status Patronen',['../led_doc.html#autotoc_md105',1,'']]],
  ['strategie_69',['5.3 Systematische Verificatie Strategie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md548',1,'']]],
  ['strategy_70',['Multi-Layer Timeout Strategy',['../p_one_doc.html#autotoc_md226',1,'']]],
  ['structs_71',['Structs',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md442',1,'Message Structs'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md483',1,'Structs']]],
  ['structure_72',['Message Structure',['../message_queue_doc.html#autotoc_md142',1,'']]],
  ['structure_20organisatie_20en_20volgorde_73',['Code Structure - Organisatie en Volgorde',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html',1,'']]],
  ['structurele_20red_20flags_74',['4.2 Structurele Red Flags',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md564',1,'']]],
  ['structuur_75',['Structuur',['../index.html#autotoc_md310',1,'📚 Documentatie Structuur'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md457',1,'Bestanden Structuur'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md458',1,'Code Structuur'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md436',1,'File Structuur'],['../p_one_doc.html#autotoc_md197',1,'Thread Loop Structuur']]],
  ['structuur_20van_20_5fdoc_20md_76',['Structuur van &lt;span class=&quot;tt&quot;&gt;&amp;lt;module&amp;gt;_doc.md&lt;/span&gt;',['../doxygen_guidelines.html#autotoc_md593',1,'']]],
  ['style_77',['Style',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md474',1,'Brace Style'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md487',1,'Comment Style']]],
  ['style_20formattering_20regels_78',['Code Style - Formattering Regels',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html',1,'']]],
  ['styling_20branding_79',['🎨 Styling &amp;amp; Branding',['../doxygen_guidelines.html#autotoc_md588',1,'']]],
  ['summary_80',['Key Timing Parameters Summary',['../p_one_doc.html#autotoc_md225',1,'']]],
  ['support_81',['Priority 1: External Flash Support',['../cloud_doc.html#autotoc_md61',1,'']]],
  ['support_20voordelen_82',['Remote Support Voordelen',['../led_doc.html#autotoc_md116',1,'']]],
  ['swap_20duration_83',['MCUboot Swap Duration',['../cloud_doc.html#autotoc_md57',1,'']]],
  ['synchronisatie_20kritiek_20⚠️_84',['4. Code Verificatie en Synchronisatie (KRITIEK! ⚠️)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md530',1,'']]],
  ['sys_5finit_20gebruik_85',['SYS_INIT Gebruik',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md446',1,'']]],
  ['sysbuild_20conf_86',['Sysbuild (sysbuild.conf)',['../cloud_doc.html#autotoc_md47',1,'']]],
  ['sysbuild_20sysbuild_20conf_87',['Sysbuild (sysbuild.conf)',['../cloud_doc.html#autotoc_md47',1,'']]],
  ['systeem_88',['Build Systeem',['../index.html#autotoc_md306',1,'']]],
  ['system_89',['🛠️ Build System',['../group__Titel.html#autotoc_md601',1,'']]],
  ['system_20timeline_90',['Complete System Timeline',['../timing_doc.html#autotoc_md268',1,'']]],
  ['systematische_20verificatie_20per_20claim_20type_91',['Fase 3: Systematische Verificatie Per Claim Type',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md553',1,'']]],
  ['systematische_20verificatie_20strategie_92',['5.3 Systematische Verificatie Strategie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md548',1,'']]]
];
