var searchData=
[
  ['machine_0',['Machine',['../cloud_doc.html#autotoc_md27',1,'Cloud Connectie State Machine'],['../led_doc.html#autotoc_md111',1,'Network State Machine'],['../message_queue_doc.html#autotoc_md140',1,'State Machine'],['../network_doc.html#autotoc_md179',1,'State Machine'],['../reboot_doc.html#autotoc_md251',1,'State Machine'],['../timing_doc.html#autotoc_md282',1,'State Machine']]],
  ['machine_20forward_20declarations_1',['State Machine Forward Declarations',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md438',1,'']]],
  ['machine_20patterns_20smf_2',['State Machine Patterns (SMF)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md390',1,'']]],
  ['machine_20setup_3',['State Machine Setup',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md391',1,'']]],
  ['machine_20transities_4',['9. State Machine Transities',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md529',1,'']]],
  ['macro_5',['ARG_UNUSED Macro',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md513',1,'']]],
  ['macro_20s_6',['Macro&apos;s',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md489',1,'']]],
  ['magic_20numbers_20en_20constants_7',['Magic Numbers en Constants',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md504',1,'']]],
  ['management_8',['Management',['../network_doc.html#autotoc_md170',1,'Event-Driven Network Management'],['../message_queue_doc.html#autotoc_md141',1,'Queue Management'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md395',1,'Resource Management'],['../led_doc.html#autotoc_md116',1,'State Management']]],
  ['manager_20integration_9',['Zephyr Connection Manager Integration',['../network_doc.html#autotoc_md180',1,'']]],
  ['matter_10',['Why These Specific Timeouts Matter',['../p_one_doc.html#autotoc_md221',1,'']]],
  ['maximum_20length_20telegram_11',['Scenario 2: Maximum Length Telegram',['../p_one_doc.html#autotoc_md228',1,'']]],
  ['maximum_20telegram_20transmission_20time_12',['1. Maximum Telegram Transmission Time',['../p_one_doc.html#autotoc_md218',1,'']]],
  ['mcuboot_20swap_20duration_13',['MCUboot Swap Duration',['../cloud_doc.html#autotoc_md57',1,'']]],
  ['md_14',['Structuur van &lt;span class=&quot;tt&quot;&gt;&amp;lt;module&amp;gt;_doc.md&lt;/span&gt;',['../doxygen_guidelines.html#autotoc_md601',1,'']]],
  ['mechanism_15',['Hardware Watchdog als Safety Mechanism',['../app_doc.html#autotoc_md4',1,'']]],
  ['mechanisme_16',['Mechanisme',['../timing_doc.html#autotoc_md272',1,'Offset Mechanisme'],['../reboot_doc.html#autotoc_md253',1,'Timeout Mechanisme'],['../app_doc.html#autotoc_md5',1,'TRIGGER_CHAN als Coördinatie Mechanisme']]],
  ['memory_20usage_17',['Memory Usage',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md422',1,'']]],
  ['message_20flow_20scenarios_18',['Message Flow Scenarios',['../index.html#autotoc_md300',1,'']]],
  ['message_20format_19',['Message Format',['../message_queue_doc.html#autotoc_md148',1,'Cloud Message Format'],['../message_queue_doc.html#autotoc_md137',1,'Message Format']]],
  ['message_20handling_20periodieke_20triggers_20',['2. ZBUS Message Handling (Periodieke Triggers)',['../p_one_doc.html#autotoc_md204',1,'']]],
  ['message_20presence_20scenarios_21',['Message Presence Scenarios',['../message_queue_doc.html#autotoc_md153',1,'']]],
  ['message_20processing_20in_20thread_22',['Message Processing in Thread',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md388',1,'']]],
  ['message_20queue_20module_20documentatie_23',['Message Queue Module - Documentatie',['../message_queue_doc.html',1,'']]],
  ['message_20structs_24',['Message Structs',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md450',1,'']]],
  ['message_20structure_25',['Message Structure',['../message_queue_doc.html#autotoc_md150',1,'']]],
  ['messages_26',['Publishing Messages',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md387',1,'']]],
  ['met_20zbus_20smf_27',['Thread Loop met ZBUS + SMF',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md417',1,'']]],
  ['meters_28',['Data Acquisitie van DSMR Meters',['../p_one_doc.html#autotoc_md193',1,'']]],
  ['meting_20acquisitie_29',['Gas Meting Acquisitie',['../p_one_doc.html#autotoc_md198',1,'']]],
  ['minimum_20display_20time_30',['Minimum Display Time',['../led_doc.html#autotoc_md115',1,'']]],
  ['minuten_31',['minuten',['../index.html#autotoc_md303',1,'☁️ Cloud Transmission (elke 30 minuten)'],['../index.html#autotoc_md302',1,'📊 Publish Statistics (elke 10 minuten)']]],
  ['mismatch_32',['❗ Anchor Mismatch',['../group__Titel.html#autotoc_md614',1,'']]],
  ['missing_33',['Missing',['../group__Titel.html#autotoc_md617',1,'❗ Missing @ingroup'],['../group__Titel.html#autotoc_md620',1,'❗ Missing @ingroup']]],
  ['model_34',['Thread Model',['../app_doc.html#autotoc_md11',1,'']]],
  ['modem_20firmware_35',['Modem Firmware',['../provisioning.html#autotoc_md356',1,'Stap 1: Flash Productie Modem Firmware'],['../provisioning.html#autotoc_md350',1,'Stap 1: Flash PTI Modem Firmware']]],
  ['modem_20firmware_20downloaden_36',['1.3 Modem Firmware Downloaden',['../provisioning.html#autotoc_md338',1,'']]],
  ['modem_20firmware_20v2_200_203_37',['Download Modem Firmware v2.0.3',['../provisioning.html#autotoc_md339',1,'']]],
  ['modem_20firmware_20v2_203_208_38',['Download PTI Modem Firmware v2.3.8',['../provisioning.html#autotoc_md340',1,'']]],
  ['modem_20initialization_20details_39',['Modem Initialization Details',['../network_doc.html#autotoc_md181',1,'']]],
  ['modem_20initialization_20hook_40',['Modem Initialization Hook',['../network_doc.html#autotoc_md171',1,'']]],
  ['modem_20shell_41',['Stap 3: Flash Modem Shell',['../provisioning.html#autotoc_md352',1,'']]],
  ['modem_20shell_20mosh_20bouwen_42',['1.4 Modem Shell (MoSh) Bouwen',['../provisioning.html#autotoc_md342',1,'']]],
  ['module_43',['Checklist voor Nieuwe Module',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md404',1,'']]],
  ['module_20checklist_44',['Module Checklist',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md464',1,'']]],
  ['module_20documentatie_45',['Module Documentatie',['../doxygen_guidelines.html#autotoc_md600',1,'📝 Module Documentatie'],['../app_doc.html',1,'App Module - Documentatie'],['../cloud_doc.html',1,'Cloud Module - Documentatie'],['../energy_pulse_doc.html',1,'Energy Pulse Module - Documentatie'],['../led_doc.html',1,'LED Module - Documentatie'],['../message_queue_doc.html',1,'Message Queue Module - Documentatie'],['../network_doc.html',1,'Network Module - Documentatie'],['../p_one_doc.html',1,'P1 DSMR Module - Documentatie'],['../reboot_doc.html',1,'Reboot Module - Documentatie'],['../timing_doc.html',1,'Timing Module - Documentatie']]],
  ['module_20documentatie_20richtlijnen_46',['Module Documentatie Richtlijnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html',1,'']]],
  ['module_20documenteren_47',['✅ Checklist: Nieuwe Module Documenteren',['../group__Titel.html#autotoc_md611',1,'']]],
  ['module_20eigen_20thread_20heeft_48',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md471',1,'']]],
  ['module_20groepen_20definiëren_49',['Module Groepen Definiëren',['../doxygen_guidelines.html#autotoc_md604',1,'']]],
  ['module_20initialisatie_50',['Module Initialisatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md453',1,'Module Initialisatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md468',1,'Module Initialisatie']]],
  ['module_20interacties_51',['🔄 Data Flow &amp;amp; Module Interacties',['../index.html#autotoc_md297',1,'']]],
  ['module_20readme_20s_52',['📁 Module README&apos;s',['../index.html#autotoc_md321',1,'']]],
  ['module_20setup_20pattern_53',['Module Setup Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md402',1,'']]],
  ['module_20shutdown_20implementatie_20vereisten_54',['Module Shutdown Implementatie Vereisten',['../reboot_doc.html#autotoc_md261',1,'']]],
  ['modules_55',['Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md530',1,'10. Afhankelijkheden van Andere Modules'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md457',1,'CMakeLists.txt voor Modules'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md475',1,'Referentie Modules']]],
  ['moet_56',['moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md520',1,'✅ Wat ER WEL in moet'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md533',1,'❗ Wat ER NIET in moet']]],
  ['mosh_20bouwen_57',['1.4 Modem Shell (MoSh) Bouwen',['../provisioning.html#autotoc_md342',1,'']]],
  ['motivatie_58',['Motivatie',['../cloud_doc.html#autotoc_md22',1,'Waarom? (Motivatie)'],['../energy_pulse_doc.html#autotoc_md73',1,'Waarom? (Probleem &amp; Motivatie)'],['../led_doc.html#autotoc_md100',1,'Waarom? (Probleem &amp; Motivatie)'],['../reboot_doc.html#autotoc_md240',1,'Waarom? (Probleem &amp; Motivatie)'],['../timing_doc.html#autotoc_md270',1,'Waarom? (Probleem &amp; Motivatie)']]],
  ['ms_59',['ms',['../p_one_doc.html#autotoc_md223',1,'Inter-byte Timeout (392 ms)'],['../p_one_doc.html#autotoc_md224',1,'Telegram Timeout (784 ms)']]],
  ['msg_5fsubscriber_20pattern_60',['MSG_SUBSCRIBER Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md385',1,'']]],
  ['multi_20layer_20timeout_20strategy_61',['Multi-Layer Timeout Strategy',['../p_one_doc.html#autotoc_md234',1,'']]],
  ['multiple_20source_20files_62',['Multiple Source Files',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md460',1,'']]],
  ['mutex_20usage_63',['Mutex Usage',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md397',1,'']]]
];
