var searchData=
[
  ['s_0',['s',['../index.html#autotoc_md321',1,'📁 Module README's'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md489',1,'Macro's'],['../led_doc.html#autotoc_md107',1,'Typische Scenario's'],['../led_doc.html#autotoc_md108',1,'Typische Scenario's']]],
  ['safety_1',['Security en Safety',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md425',1,'']]],
  ['safety_20mechanism_2',['Hardware Watchdog als Safety Mechanism',['../app_doc.html#autotoc_md4',1,'']]],
  ['samenvatting_3',['Samenvatting',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md549',1,'']]],
  ['samenvatting_20protocol_4',['5.8 Samenvatting Protocol',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md586',1,'']]],
  ['sampling_5',['Rolling Statistics &amp;amp; Sampling',['../p_one_doc.html#autotoc_md197',1,'']]],
  ['scenario_201_3a_20slow_20p1_20device_20response_6',['Scenario 1: Slow P1 Device Response',['../p_one_doc.html#autotoc_md227',1,'']]],
  ['scenario_202_3a_20maximum_20length_20telegram_7',['Scenario 2: Maximum Length Telegram',['../p_one_doc.html#autotoc_md228',1,'']]],
  ['scenario_203_3a_20inter_20byte_20timeout_20trigger_8',['Scenario 3: Inter-byte Timeout Trigger',['../p_one_doc.html#autotoc_md229',1,'']]],
  ['scenario_20s_9',['Scenario s',['../led_doc.html#autotoc_md107',1,'Typische Scenario's'],['../led_doc.html#autotoc_md108',1,'Typische Scenario's']]],
  ['scenarios_10',['Scenarios',['../p_one_doc.html#autotoc_md226',1,'Edge Case Scenarios'],['../index.html#autotoc_md300',1,'Message Flow Scenarios'],['../message_queue_doc.html#autotoc_md153',1,'Message Presence Scenarios']]],
  ['scheduled_20fota_20windows_11',['Priority 2: Scheduled FOTA Windows',['../cloud_doc.html#autotoc_md62',1,'']]],
  ['scheduling_12',['K_NO_WAIT voor Immediate Scheduling',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md396',1,'']]],
  ['schrijven_20of_20bewerken_20van_20documentatie_3a_13',['Bij het schrijven of bewerken van documentatie:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md540',1,'']]],
  ['schrijven_20via_20rtt_14',['Stap 4: IMEI Schrijven via RTT',['../provisioning.html#autotoc_md353',1,'']]],
  ['scope_20en_20static_15',['Scope en Static',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md500',1,'']]],
  ['seconden_16',['📥 Normal Data Collection (elke 30 seconden)',['../index.html#autotoc_md301',1,'']]],
  ['sectie_20headers_17',['Sectie Headers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md441',1,'']]],
  ['secties_20in_20volgorde_18',['Standaard Secties (in volgorde)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md442',1,'']]],
  ['security_20en_20safety_19',['Security en Safety',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md425',1,'']]],
  ['sequence_20',['Sequence',['../index.html#autotoc_md304',1,'🔄 Startup Sequence'],['../energy_pulse_doc.html#autotoc_md83',1,'Initialisatie Sequence'],['../reboot_doc.html#autotoc_md248',1,'Shutdown Sequence']]],
  ['sessie_21',['5.6 Checklist: Voor Documentatie Review Sessie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md582',1,'']]],
  ['setup_22',['Setup',['../provisioning.html#autotoc_md334',1,'🛠️ Fase 1: Eenmalige Setup'],['../provisioning.html#autotoc_md371',1,'Eenmalige Setup'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md391',1,'State Machine Setup']]],
  ['setup_20pattern_23',['Module Setup Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md402',1,'']]],
  ['shell_24',['Stap 3: Flash Modem Shell',['../provisioning.html#autotoc_md352',1,'']]],
  ['shell_20mosh_20bouwen_25',['1.4 Modem Shell (MoSh) Bouwen',['../provisioning.html#autotoc_md342',1,'']]],
  ['short_20key_20names_26',['Design Rationale: Short Key Names',['../message_queue_doc.html#autotoc_md152',1,'']]],
  ['shortcuts_27',['Verification Shortcuts',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md580',1,'']]],
  ['shutdown_28',['Shutdown',['../index.html#autotoc_md305',1,'🛑 Graceful Shutdown'],['../reboot_doc.html#autotoc_md241',1,'Graceful Shutdown']]],
  ['shutdown_20betrouwbaarheid_29',['Shutdown Betrouwbaarheid',['../reboot_doc.html#autotoc_md256',1,'']]],
  ['shutdown_20gedrag_30',['Graceful Shutdown Gedrag',['../reboot_doc.html#autotoc_md257',1,'']]],
  ['shutdown_20implementatie_20vereisten_31',['Module Shutdown Implementatie Vereisten',['../reboot_doc.html#autotoc_md261',1,'']]],
  ['shutdown_20sequence_32',['Shutdown Sequence',['../reboot_doc.html#autotoc_md248',1,'']]],
  ['sim_20handling_33',['Native Sim Handling',['../app_doc.html#autotoc_md15',1,'']]],
  ['size_20constraint_34',['Buffer Size Constraint',['../p_one_doc.html#autotoc_md232',1,'']]],
  ['sizeof_20operator_35',['sizeof Operator',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md502',1,'']]],
  ['slag_36',['🚀 Aan de Slag',['../index.html#autotoc_md313',1,'']]],
  ['slow_20p1_20device_20response_37',['Scenario 1: Slow P1 Device Response',['../p_one_doc.html#autotoc_md227',1,'']]],
  ['smf_38',['SMF',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md390',1,'State Machine Patterns (SMF)'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md417',1,'Thread Loop met ZBUS + SMF']]],
  ['solarresult_20dinnis_20core_20firmware_20documentatie_39',['SolarResult Dinnis Core - Firmware Documentatie',['../index.html',1,'']]],
  ['source_20file_20c_20template_40',['Source File (.c) Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md445',1,'']]],
  ['source_20files_41',['Multiple Source Files',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md460',1,'']]],
  ['spaties_20geen_20tabs_42',['Spaties (GEEN Tabs)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md480',1,'']]],
  ['specific_20timeouts_20matter_43',['Why These Specific Timeouts Matter',['../p_one_doc.html#autotoc_md221',1,'']]],
  ['specificaties_44',['1. Specificaties',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md521',1,'']]],
  ['standaard_20pattern_20altijd_20compileren_45',['Standaard Pattern (Altijd Compileren)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md458',1,'']]],
  ['standaard_20secties_20in_20volgorde_46',['Standaard Secties (in volgorde)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md442',1,'']]],
  ['stap_201_3a_20flash_20productie_20modem_20firmware_47',['Stap 1: Flash Productie Modem Firmware',['../provisioning.html#autotoc_md356',1,'']]],
  ['stap_201_3a_20flash_20pti_20modem_20firmware_48',['Stap 1: Flash PTI Modem Firmware',['../provisioning.html#autotoc_md350',1,'']]],
  ['stap_202_3a_20certificaten_20programmeren_49',['Stap 2: Certificaten Programmeren',['../provisioning.html#autotoc_md357',1,'']]],
  ['stap_202_3a_20device_20recoveren_50',['Stap 2: Device Recoveren',['../provisioning.html#autotoc_md351',1,'']]],
  ['stap_203_3a_20flash_20modem_20shell_51',['Stap 3: Flash Modem Shell',['../provisioning.html#autotoc_md352',1,'']]],
  ['stap_204_3a_20imei_20schrijven_20via_20rtt_52',['Stap 4: IMEI Schrijven via RTT',['../provisioning.html#autotoc_md353',1,'']]],
  ['stappen_3a_53',['✅ VERPLICHTE STAPPEN:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md541',1,'']]],
  ['startup_20sequence_54',['🔄 Startup Sequence',['../index.html#autotoc_md304',1,'']]],
  ['state_20handler_20functions_55',['State Handler Functions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md392',1,'']]],
  ['state_20machine_56',['State Machine',['../cloud_doc.html#autotoc_md27',1,'Cloud Connectie State Machine'],['../led_doc.html#autotoc_md111',1,'Network State Machine'],['../message_queue_doc.html#autotoc_md140',1,'State Machine'],['../network_doc.html#autotoc_md179',1,'State Machine'],['../reboot_doc.html#autotoc_md251',1,'State Machine'],['../timing_doc.html#autotoc_md282',1,'State Machine']]],
  ['state_20machine_20forward_20declarations_57',['State Machine Forward Declarations',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md438',1,'']]],
  ['state_20machine_20patterns_20smf_58',['State Machine Patterns (SMF)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md390',1,'']]],
  ['state_20machine_20setup_59',['State Machine Setup',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md391',1,'']]],
  ['state_20machine_20transities_60',['9. State Machine Transities',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md529',1,'']]],
  ['state_20management_61',['State Management',['../led_doc.html#autotoc_md116',1,'']]],
  ['state_20transitions_62',['State Transitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md393',1,'']]],
  ['static_63',['Scope en Static',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md500',1,'']]],
  ['statistics_20elke_2010_20minuten_64',['📊 Publish Statistics (elke 10 minuten)',['../index.html#autotoc_md302',1,'']]],
  ['statistics_20sampling_65',['Rolling Statistics &amp;amp; Sampling',['../p_one_doc.html#autotoc_md197',1,'']]],
  ['status_20enums_66',['Network Status Enums',['../network_doc.html#autotoc_md176',1,'']]],
  ['status_20flow_67',['Network Status Flow',['../network_doc.html#autotoc_md174',1,'']]],
  ['status_20patronen_68',['LED Status Patronen',['../led_doc.html#autotoc_md105',1,'']]],
  ['strategie_69',['5.3 Systematische Verificatie Strategie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md556',1,'']]],
  ['strategy_70',['Strategy',['../p_one_doc.html#autotoc_md234',1,'Multi-Layer Timeout Strategy'],['../message_queue_doc.html#autotoc_md144',1,'Timestamp Strategy']]],
  ['structs_71',['Structs',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md450',1,'Message Structs'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md491',1,'Structs']]],
  ['structure_72',['Message Structure',['../message_queue_doc.html#autotoc_md150',1,'']]],
  ['structure_20organisatie_20en_20volgorde_73',['Code Structure - Organisatie en Volgorde',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html',1,'']]],
  ['structurele_20red_20flags_74',['4.2 Structurele Red Flags',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md572',1,'']]],
  ['structuur_75',['Structuur',['../index.html#autotoc_md318',1,'📚 Documentatie Structuur'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md465',1,'Bestanden Structuur'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md466',1,'Code Structuur'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md444',1,'File Structuur'],['../p_one_doc.html#autotoc_md205',1,'Thread Loop Structuur']]],
  ['structuur_20van_20_5fdoc_20md_76',['Structuur van &lt;span class=&quot;tt&quot;&gt;&amp;lt;module&amp;gt;_doc.md&lt;/span&gt;',['../doxygen_guidelines.html#autotoc_md601',1,'']]],
  ['style_77',['Style',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md482',1,'Brace Style'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md495',1,'Comment Style']]],
  ['style_20formattering_20regels_78',['Code Style - Formattering Regels',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html',1,'']]],
  ['styling_20branding_79',['🎨 Styling &amp;amp; Branding',['../doxygen_guidelines.html#autotoc_md596',1,'']]],
  ['summary_80',['Key Timing Parameters Summary',['../p_one_doc.html#autotoc_md233',1,'']]],
  ['support_81',['Priority 1: External Flash Support',['../cloud_doc.html#autotoc_md61',1,'']]],
  ['support_20voordelen_82',['Remote Support Voordelen',['../led_doc.html#autotoc_md120',1,'']]],
  ['swap_20duration_83',['MCUboot Swap Duration',['../cloud_doc.html#autotoc_md57',1,'']]],
  ['synchronisatie_20kritiek_20⚠️_84',['4. Code Verificatie en Synchronisatie (KRITIEK! ⚠️)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md538',1,'']]],
  ['sys_5finit_20gebruik_85',['SYS_INIT Gebruik',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md454',1,'']]],
  ['sysbuild_20conf_86',['Sysbuild (sysbuild.conf)',['../cloud_doc.html#autotoc_md47',1,'']]],
  ['sysbuild_20sysbuild_20conf_87',['Sysbuild (sysbuild.conf)',['../cloud_doc.html#autotoc_md47',1,'']]],
  ['systeem_88',['Build Systeem',['../index.html#autotoc_md314',1,'']]],
  ['system_89',['🛠️ Build System',['../group__Titel.html#autotoc_md609',1,'']]],
  ['system_20timeline_90',['Complete System Timeline',['../timing_doc.html#autotoc_md276',1,'']]],
  ['systematische_20verificatie_20per_20claim_20type_91',['Fase 3: Systematische Verificatie Per Claim Type',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md561',1,'']]],
  ['systematische_20verificatie_20strategie_92',['5.3 Systematische Verificatie Strategie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md556',1,'']]]
];
