var searchData=
[
  ['p1_20device_20response_0',['Scenario 1: Slow P1 Device Response',['../p_one_doc.html#autotoc_md219',1,'']]],
  ['p1_20dsmr_20module_20documentatie_1',['P1 DSMR Module - Documentatie',['../p_one_doc.html',1,'']]],
  ['pages_2',['📚 Related Pages',['../group__Titel.html#autotoc_md650',1,'']]],
  ['parameters_20summary_3',['Key Timing Parameters Summary',['../p_one_doc.html#autotoc_md225',1,'']]],
  ['parent_20cmakelists_4',['Integration in Parent CMakeLists',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md505',1,'']]],
  ['parsing_20data_20conversie_5',['OBIS Parsing &amp;amp; Data Conversie',['../p_one_doc.html#autotoc_md188',1,'']]],
  ['partition_20layout_20pm_5fstatic_20yml_6',['Partition Layout (pm_static.yml)',['../cloud_doc.html#autotoc_md48',1,'']]],
  ['patronen_7',['LED Status Patronen',['../led_doc.html#autotoc_md105',1,'']]],
  ['pattern_8',['Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md462',1,'Callback Pattern'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md502',1,'Conditionele Compilatie Pattern'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md429',1,'LISTENER Pattern'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md445',1,'Module Setup Pattern'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md428',1,'MSG_SUBSCRIBER Pattern'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md461',1,'Periodic Work Pattern'],['../reboot_doc.html#autotoc_md246',1,'Work Queue Pattern']]],
  ['pattern_20altijd_20compileren_9',['Standaard Pattern (Altijd Compileren)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md501',1,'']]],
  ['pattern_20claims_10',['Pattern Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md605',1,'3.1 Architectuur Pattern Claims'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md607',1,'3.2 Communication Pattern Claims']]],
  ['pattern_20implementation_11',['Pattern Implementation',['../led_doc.html#autotoc_md111',1,'']]],
  ['patterns_12',['Patterns',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md459',1,'Common Patterns'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md452',1,'LED Control Patterns'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md421',1,'Return Patterns'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md427',1,'ZBUS Patterns']]],
  ['patterns_20red_20flags_13',['Fase 4: Documentatie Anti-Patterns (Red Flags)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md613',1,'']]],
  ['patterns_20smf_14',['State Machine Patterns (SMF)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md433',1,'']]],
  ['per_20claim_20type_15',['Fase 3: Systematische Verificatie Per Claim Type',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md604',1,'']]],
  ['per_20device_16',['Per Device',['../provisioning.html#autotoc_md415',1,'']]],
  ['per_20device_20provisioneren_17',['🔧 Fase 2: Per Device Provisioneren',['../provisioning.html#autotoc_md391',1,'']]],
  ['performance_18',['Performance',['../energy_pulse_doc.html#autotoc_md89',1,'Geheugen &amp; Performance'],['../timing_doc.html#autotoc_md278',1,'Geheugen &amp; Performance'],['../cloud_doc.html#autotoc_md55',1,'Timing &amp; Performance']]],
  ['performance_20en_20optimization_19',['Performance en Optimization',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md464',1,'']]],
  ['periodic_20work_20pattern_20',['Periodic Work Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md461',1,'']]],
  ['periodieke_20triggers_21',['2. ZBUS Message Handling (Periodieke Triggers)',['../p_one_doc.html#autotoc_md196',1,'']]],
  ['persistente_20energietellers_22',['Persistente Energietellers',['../energy_pulse_doc.html#autotoc_md74',1,'']]],
  ['pitfalls_23',['🚨 Common Pitfalls',['../group__Titel.html#autotoc_md656',1,'']]],
  ['pm_5fstatic_20yml_24',['Partition Layout (pm_static.yml)',['../cloud_doc.html#autotoc_md48',1,'']]],
  ['point_25',['Waarom Integer Fixed-Point?',['../p_one_doc.html#autotoc_md199',1,'']]],
  ['pointer_20arithmetic_26',['Pointer Arithmetic',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md457',1,'']]],
  ['pointer_20validatie_27',['Pointer Validatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md553',1,'']]],
  ['pointers_28',['Pointers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md535',1,'']]],
  ['portability_29',['Undefined Behavior en Portability',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md454',1,'']]],
  ['practical_20tools_20commands_30',['5.5 Practical Tools &amp;amp; Commands',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md620',1,'']]],
  ['practices_20praktische_20richtlijnen_31',['Best Practices - Praktische Richtlijnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html',1,'']]],
  ['praktische_20richtlijnen_32',['Best Practices - Praktische Richtlijnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html',1,'']]],
  ['prerequisites_33',['Prerequisites',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md328',1,'']]],
  ['presence_20scenarios_34',['Message Presence Scenarios',['../message_queue_doc.html#autotoc_md145',1,'']]],
  ['prevention_35',['Buffer Overflow Prevention',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md470',1,'']]],
  ['principe_3a_20code_20first_20investigation_36',['5.2 Fundamenteel Principe: Code-First Investigation',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md597',1,'']]],
  ['principe_3a_20nooit_20iets_20verzinnen_37',['Principe: NOOIT iets verzinnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md582',1,'']]],
  ['priority_201_3a_20external_20flash_20support_38',['Priority 1: External Flash Support',['../cloud_doc.html#autotoc_md61',1,'']]],
  ['priority_202_3a_20scheduled_20fota_20windows_39',['Priority 2: Scheduled FOTA Windows',['../cloud_doc.html#autotoc_md62',1,'']]],
  ['priority_203_3a_20delta_20updates_40',['Priority 3: Delta Updates',['../cloud_doc.html#autotoc_md63',1,'']]],
  ['prj_20conf_41',['Kconfig (prj.conf)',['../cloud_doc.html#autotoc_md46',1,'']]],
  ['probleem_20motivatie_42',['Probleem Motivatie',['../energy_pulse_doc.html#autotoc_md73',1,'Waarom? (Probleem &amp; Motivatie)'],['../led_doc.html#autotoc_md100',1,'Waarom? (Probleem &amp; Motivatie)'],['../reboot_doc.html#autotoc_md232',1,'Waarom? (Probleem &amp; Motivatie)'],['../timing_doc.html#autotoc_md262',1,'Waarom? (Probleem &amp; Motivatie)']]],
  ['procedures_43',['🐛 Debug Procedures',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md346',1,'']]],
  ['processing_20in_20thread_44',['Message Processing in Thread',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md431',1,'']]],
  ['productie_20modem_20firmware_45',['Stap 1: Flash Productie Modem Firmware',['../provisioning.html#autotoc_md399',1,'']]],
  ['programmeren_46',['Programmeren',['../provisioning.html#autotoc_md392',1,'2.1 IMEI Programmeren'],['../provisioning.html#autotoc_md400',1,'Stap 2: Certificaten Programmeren']]],
  ['project_20layout_47',['🏗️ Project Layout',['../doxygen_guidelines.html#autotoc_md635',1,'']]],
  ['protection_48',['Boot Loop Protection',['../cloud_doc.html#autotoc_md39',1,'']]],
  ['protocol_49',['Protocol',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md594',1,'5. AI Agent Documentatie Verificatie Protocol'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md595',1,'5.1 Waarom dit Protocol?'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md629',1,'5.8 Samenvatting Protocol'],['../reboot_doc.html#autotoc_md239',1,'ZBUS Protocol']]],
  ['provisioneren_50',['🔧 Fase 2: Per Device Provisioneren',['../provisioning.html#autotoc_md391',1,'']]],
  ['provisioning_20and_20onboarding_51',['Provisioning and Onboarding',['../provisioning.html',1,'']]],
  ['pti_20modem_20firmware_52',['Stap 1: Flash PTI Modem Firmware',['../provisioning.html#autotoc_md393',1,'']]],
  ['pti_20modem_20firmware_20v2_203_208_53',['Download PTI Modem Firmware v2.3.8',['../provisioning.html#autotoc_md383',1,'']]],
  ['publish_20flow_54',['PUBLISH Flow',['../p_one_doc.html#autotoc_md193',1,'']]],
  ['publish_20statistics_20elke_2010_20minuten_55',['📊 Publish Statistics (elke 10 minuten)',['../index.html#autotoc_md294',1,'']]],
  ['published_56',['ZBUS Channels (Published)',['../timing_doc.html#autotoc_md267',1,'']]],
  ['publishing_57',['FOTA Channel Publishing',['../cloud_doc.html#autotoc_md33',1,'']]],
  ['publishing_20messages_58',['Publishing Messages',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md430',1,'']]],
  ['pulse_20module_20documentatie_59',['Energy Pulse Module - Documentatie',['../energy_pulse_doc.html',1,'']]]
];
