var searchData=
[
  ['a_3a_20uart_20timing_20analyse_0',['📐 Appendix A: UART Timing Analyse',['../p_one_doc.html#autotoc_md214',1,'']]],
  ['aan_20de_20slag_1',['🚀 Aan de Slag',['../index.html#autotoc_md313',1,'']]],
  ['aannames_2',['Type Aannames',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md413',1,'']]],
  ['accuracy_3',['Timing Accuracy',['../timing_doc.html#autotoc_md287',1,'']]],
  ['acknowledgement_20tracking_4',['Acknowledgement Tracking',['../reboot_doc.html#autotoc_md252',1,'']]],
  ['acq_5ftrigger_20flow_5',['ACQ_TRIGGER Flow',['../p_one_doc.html#autotoc_md200',1,'']]],
  ['acquisitie_6',['Gas Meting Acquisitie',['../p_one_doc.html#autotoc_md198',1,'']]],
  ['acquisitie_20van_20dsmr_20meters_7',['Data Acquisitie van DSMR Meters',['../p_one_doc.html#autotoc_md193',1,'']]],
  ['acquisitie_3a_20uptime_20timestamps_8',['1. Acquisitie: Uptime Timestamps',['../message_queue_doc.html#autotoc_md145',1,'']]],
  ['activeren_9',['1.2 nRF Connect Environment Activeren',['../provisioning.html#autotoc_md336',1,'']]],
  ['afhankelijkheden_20van_20andere_20modules_10',['10. Afhankelijkheden van Andere Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md530',1,'']]],
  ['afwegingen_20trade_20offs_11',['5. Afwegingen (Trade-offs)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md525',1,'']]],
  ['agent_20documentatie_20verificatie_20protocol_12',['5. AI Agent Documentatie Verificatie Protocol',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md551',1,'']]],
  ['ai_20agent_20documentatie_20verificatie_20protocol_13',['5. AI Agent Documentatie Verificatie Protocol',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md551',1,'']]],
  ['alle_20devices_20onboarden_14',['3.1 Alle Devices Onboarden',['../provisioning.html#autotoc_md364',1,'']]],
  ['als_20coördinatie_20mechanisme_15',['TRIGGER_CHAN als Coördinatie Mechanisme',['../app_doc.html#autotoc_md5',1,'']]],
  ['als_20safety_20mechanism_16',['Hardware Watchdog als Safety Mechanism',['../app_doc.html#autotoc_md4',1,'']]],
  ['altijd_20compileren_17',['Standaard Pattern (Altijd Compileren)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md458',1,'']]],
  ['analyse_18',['📐 Appendix A: UART Timing Analyse',['../p_one_doc.html#autotoc_md214',1,'']]],
  ['analysis_20commands_20voorbeelden_19',['Code Analysis Commands (Voorbeelden)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md578',1,'']]],
  ['anchor_20mismatch_20',['❗ Anchor Mismatch',['../group__Titel.html#autotoc_md614',1,'']]],
  ['and_20onboarding_21',['Provisioning and Onboarding',['../provisioning.html',1,'']]],
  ['andere_20modules_22',['10. Afhankelijkheden van Andere Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md530',1,'']]],
  ['anti_20patterns_20red_20flags_23',['Fase 4: Documentatie Anti-Patterns (Red Flags)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md570',1,'']]],
  ['api_20elementen_24',['Links naar API Elementen',['../group__Titel.html#autotoc_md605',1,'']]],
  ['api_20key_25',['nRF Cloud API Key',['../provisioning.html#autotoc_md365',1,'']]],
  ['api_20referentie_26',['📄 API Referentie',['../index.html#autotoc_md319',1,'']]],
  ['api_20timing_27',['UART Async API &amp;amp; Timing',['../p_one_doc.html#autotoc_md194',1,'']]],
  ['app_20module_20documentatie_28',['App Module - Documentatie',['../app_doc.html',1,'']]],
  ['appendix_20a_3a_20uart_20timing_20analyse_29',['📐 Appendix A: UART Timing Analyse',['../p_one_doc.html#autotoc_md214',1,'']]],
  ['applicatie_20flashen_30',['2.3 User Applicatie Flashen',['../provisioning.html#autotoc_md359',1,'']]],
  ['application_31',['Build de Dinnis Application',['../provisioning.html#autotoc_md360',1,'']]],
  ['architectuur_32',['Architectuur',['../index.html#autotoc_md294',1,'🏗️ Architectuur'],['../app_doc.html#autotoc_md10',1,'Architectuur'],['../p_one_doc.html#autotoc_md202',1,'Architectuur'],['../timing_doc.html#autotoc_md280',1,'Architectuur']]],
  ['architectuur_20gedrag_33',['Architectuur Gedrag',['../energy_pulse_doc.html#autotoc_md82',1,'Hoe? (Architectuur &amp; Gedrag)'],['../led_doc.html#autotoc_md110',1,'Hoe? (Architectuur &amp; Gedrag)'],['../message_queue_doc.html#autotoc_md139',1,'Hoe? (Architectuur &amp; Gedrag)'],['../network_doc.html#autotoc_md178',1,'Hoe? (Architectuur &amp; Gedrag)'],['../reboot_doc.html#autotoc_md250',1,'Hoe? (Architectuur &amp; Gedrag)'],['../timing_doc.html#autotoc_md279',1,'Hoe? (Architectuur &amp; Gedrag)']]],
  ['architectuur_20pattern_20claims_34',['3.1 Architectuur Pattern Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md562',1,'']]],
  ['arg_5funused_20macro_35',['ARG_UNUSED Macro',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md513',1,'']]],
  ['argumentaties_36',['4. Argumentaties',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md524',1,'']]],
  ['arithmetic_37',['Pointer Arithmetic',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md414',1,'']]],
  ['arrays_20en_20buffers_38',['Arrays en Buffers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md501',1,'']]],
  ['assertions_39',['Assertions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md382',1,'']]],
  ['async_20api_20timing_40',['UART Async API &amp;amp; Timing',['../p_one_doc.html#autotoc_md194',1,'']]],
  ['asynchrone_20data_20ontvangst_41',['1. UART Callbacks (Asynchrone Data Ontvangst)',['../p_one_doc.html#autotoc_md203',1,'']]]
];
