var searchData=
[
  ['rationale_0',['Rationale',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md514',1,'2. Implementatie Design Rationale'],['../message_queue_doc.html#autotoc_md126',1,'Waarom? (Design Rationale)'],['../network_doc.html#autotoc_md161',1,'Waarom? (Design Rationale)']]],
  ['rationale_3a_20short_20key_20names_1',['Design Rationale: Short Key Names',['../message_queue_doc.html#autotoc_md144',1,'']]],
  ['readiness_20checks_2',['Device Readiness Checks',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md399',1,'']]],
  ['readme_20s_3',['📁 Module README&apos;s',['../index.html#autotoc_md313',1,'']]],
  ['reason_20tracking_4',['Reboot Reason Tracking',['../reboot_doc.html#autotoc_md234',1,'']]],
  ['reboot_20module_20documentatie_5',['Reboot Module - Documentatie',['../reboot_doc.html',1,'']]],
  ['reboot_20reason_20tracking_6',['Reboot Reason Tracking',['../reboot_doc.html#autotoc_md234',1,'']]],
  ['reboot_20redenen_7',['Reboot Redenen',['../reboot_doc.html#autotoc_md238',1,'']]],
  ['reboot_20types_8',['Reboot Types',['../reboot_doc.html#autotoc_md237',1,'']]],
  ['recoveren_9',['Stap 2: Device Recoveren',['../provisioning.html#autotoc_md343',1,'']]],
  ['red_20flags_10',['Red Flags',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md563',1,'4.1 Taalgebruik Red Flags'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md564',1,'4.2 Structurele Red Flags'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md565',1,'4.3 Feature Consistency Red Flags'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md562',1,'Fase 4: Documentatie Anti-Patterns (Red Flags)']]],
  ['redenen_11',['Reboot Redenen',['../reboot_doc.html#autotoc_md238',1,'']]],
  ['referencing_12',['🔗 Cross-Referencing',['../doxygen_guidelines.html#autotoc_md595',1,'']]],
  ['referentie_13',['📄 API Referentie',['../index.html#autotoc_md311',1,'']]],
  ['referentie_20modules_14',['Referentie Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md467',1,'']]],
  ['referenties_15',['📚 Referenties',['../provisioning.html#autotoc_md360',1,'']]],
  ['referenties_20en_20voor_20na_20vergelijkingen_16',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md528',1,'']]],
  ['regels_17',['Regels',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html',1,'Code Style - Formattering Regels'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md473',1,'Lege Regels']]],
  ['related_20pages_18',['📚 Related Pages',['../group__Titel.html#autotoc_md599',1,'']]],
  ['relationship_19',['Watchdog Relationship',['../p_one_doc.html#autotoc_md223',1,'']]],
  ['remote_20support_20voordelen_20',['Remote Support Voordelen',['../led_doc.html#autotoc_md116',1,'']]],
  ['requires_21',['Inbound (FOTA Requires)',['../cloud_doc.html#autotoc_md42',1,'']]],
  ['resource_20management_22',['Resource Management',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md387',1,'']]],
  ['resources_23',['Resources',['../index.html#autotoc_md317',1,'🌐 Externe Resources'],['../group__Titel.html#autotoc_md611',1,'📚 Resources'],['../group__Titel.html#autotoc_md614',1,'📚 Resources']]],
  ['response_24',['Scenario 1: Slow P1 Device Response',['../p_one_doc.html#autotoc_md219',1,'']]],
  ['response_20timeout_25',['3. Total Response Timeout',['../p_one_doc.html#autotoc_md212',1,'']]],
  ['response_20timeout_2010_208s_26',['Response Timeout (10.8s)',['../p_one_doc.html#autotoc_md217',1,'']]],
  ['resultaten_20impact_27',['Resultaten Impact',['../energy_pulse_doc.html#autotoc_md88',1,'Resultaten &amp; Impact'],['../timing_doc.html#autotoc_md277',1,'Resultaten &amp; Impact']]],
  ['return_28',['Void vs Int Return',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md373',1,'']]],
  ['return_20patterns_29',['Return Patterns',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md370',1,'']]],
  ['return_20value_20conventies_30',['Return Value Conventies',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md371',1,'']]],
  ['return_20values_31',['Error Handling en Return Values',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md368',1,'']]],
  ['review_20sessie_32',['5.6 Checklist: Voor Documentatie Review Sessie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md574',1,'']]],
  ['richtlijnen_33',['Richtlijnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html',1,'Best Practices - Praktische Richtlijnen'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html',1,'Module Documentatie Richtlijnen']]],
  ['robustness_20features_34',['🛡️ Robustness Features',['../index.html#autotoc_md303',1,'']]],
  ['robuustheid_35',['Edge Cases &amp;amp; Robuustheid',['../p_one_doc.html#autotoc_md201',1,'']]],
  ['rollback_20test_20warning_3a_20intentional_20crash_36',['Rollback Test (Warning: Intentional Crash)',['../cloud_doc.html#autotoc_md53',1,'']]],
  ['rolling_20statistics_20sampling_37',['Rolling Statistics &amp;amp; Sampling',['../p_one_doc.html#autotoc_md189',1,'']]],
  ['rtt_38',['Stap 4: IMEI Schrijven via RTT',['../provisioning.html#autotoc_md345',1,'']]],
  ['runtime_20gedrag_39',['Runtime Gedrag',['../energy_pulse_doc.html#autotoc_md84',1,'']]],
  ['rx_20timeout_20inter_20byte_20timeout_40',['2. UART RX Timeout (Inter-byte timeout)',['../p_one_doc.html#autotoc_md211',1,'']]]
];
