var searchData=
[
  ['taalgebruik_20red_20flags_0',['4.1 Taalgebruik Red Flags',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md571',1,'']]],
  ['tabs_1',['Spaties (GEEN Tabs)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md480',1,'']]],
  ['task_20watchdog_2',['Task Watchdog',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md400',1,'']]],
  ['task_20watchdog_20indien_20module_20eigen_20thread_20heeft_3',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md471',1,'']]],
  ['te_20verifiëren_3a_4',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md543',1,'']]],
  ['technische_20diepgang_5',['Technische Diepgang',['../p_one_doc.html#autotoc_md206',1,'']]],
  ['telegram_6',['Scenario 2: Maximum Length Telegram',['../p_one_doc.html#autotoc_md228',1,'']]],
  ['telegram_20timeout_20784_20ms_7',['Telegram Timeout (784 ms)',['../p_one_doc.html#autotoc_md224',1,'']]],
  ['telegram_20transmission_20time_8',['1. Maximum Telegram Transmission Time',['../p_one_doc.html#autotoc_md218',1,'']]],
  ['template_9',['Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md446',1,'Header File (.h) Template'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md445',1,'Source File (.c) Template']]],
  ['test_10',['FOTA End-to-End Test',['../cloud_doc.html#autotoc_md52',1,'']]],
  ['test_20warning_3a_20intentional_20crash_11',['Rollback Test (Warning: Intentional Crash)',['../cloud_doc.html#autotoc_md53',1,'']]],
  ['testing_12',['Testing',['../cloud_doc.html#autotoc_md50',1,'Testing'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md472',1,'Testing']]],
  ['these_20specific_20timeouts_20matter_13',['Why These Specific Timeouts Matter',['../p_one_doc.html#autotoc_md221',1,'']]],
  ['thread_14',['Message Processing in Thread',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md388',1,'']]],
  ['thread_20heeft_15',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md471',1,'']]],
  ['thread_20loop_20met_20zbus_20smf_16',['Thread Loop met ZBUS + SMF',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md417',1,'']]],
  ['thread_20loop_20structuur_17',['Thread Loop Structuur',['../p_one_doc.html#autotoc_md205',1,'']]],
  ['thread_20model_18',['Thread Model',['../app_doc.html#autotoc_md11',1,'']]],
  ['time_19',['Time',['../p_one_doc.html#autotoc_md218',1,'1. Maximum Telegram Transmission Time'],['../led_doc.html#autotoc_md115',1,'Minimum Display Time']]],
  ['timeline_20',['Complete System Timeline',['../timing_doc.html#autotoc_md276',1,'']]],
  ['timeout_21',['3. Total Response Timeout',['../p_one_doc.html#autotoc_md220',1,'']]],
  ['timeout_22',['2. UART RX Timeout (Inter-byte timeout)',['../p_one_doc.html#autotoc_md219',1,'']]],
  ['timeout_2010_208s_23',['Response Timeout (10.8s)',['../p_one_doc.html#autotoc_md225',1,'']]],
  ['timeout_20392_20ms_24',['Inter-byte Timeout (392 ms)',['../p_one_doc.html#autotoc_md223',1,'']]],
  ['timeout_20784_20ms_25',['Telegram Timeout (784 ms)',['../p_one_doc.html#autotoc_md224',1,'']]],
  ['timeout_20inter_20byte_20timeout_26',['2. UART RX Timeout (Inter-byte timeout)',['../p_one_doc.html#autotoc_md219',1,'']]],
  ['timeout_20mechanisme_27',['Timeout Mechanisme',['../reboot_doc.html#autotoc_md253',1,'']]],
  ['timeout_20strategy_28',['Multi-Layer Timeout Strategy',['../p_one_doc.html#autotoc_md234',1,'']]],
  ['timeout_20trigger_29',['Scenario 3: Inter-byte Timeout Trigger',['../p_one_doc.html#autotoc_md229',1,'']]],
  ['timeouts_20matter_30',['Why These Specific Timeouts Matter',['../p_one_doc.html#autotoc_md221',1,'']]],
  ['timer_20configuratie_31',['Timer Configuratie',['../timing_doc.html#autotoc_md281',1,'']]],
  ['timestamp_20strategy_32',['Timestamp Strategy',['../message_queue_doc.html#autotoc_md144',1,'']]],
  ['timestamps_33',['1. Acquisitie: Uptime Timestamps',['../message_queue_doc.html#autotoc_md145',1,'']]],
  ['timing_34',['Timing',['../timing_doc.html#autotoc_md271',1,'Gecoördineerde Timing'],['../p_one_doc.html#autotoc_md194',1,'UART Async API &amp; Timing']]],
  ['timing_2087_20µs_35',['Frame-Level Timing (87 µs)',['../p_one_doc.html#autotoc_md222',1,'']]],
  ['timing_20accuracy_36',['Timing Accuracy',['../timing_doc.html#autotoc_md287',1,'']]],
  ['timing_20analyse_37',['📐 Appendix A: UART Timing Analyse',['../p_one_doc.html#autotoc_md214',1,'']]],
  ['timing_20behavior_20claims_38',['3.4 Timing &amp;amp; Behavior Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md568',1,'']]],
  ['timing_20berekening_39',['Timing Berekening',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md403',1,'']]],
  ['timing_20calculations_40',['Critical Timing Calculations',['../p_one_doc.html#autotoc_md217',1,'']]],
  ['timing_20calculations_20fundamentals_41',['UART Timing Calculations - Fundamentals',['../p_one_doc.html#autotoc_md195',1,'']]],
  ['timing_20diagrammen_42',['8. Timing Diagrammen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md528',1,'']]],
  ['timing_20fundamentals_43',['UART Frame Timing Fundamentals',['../p_one_doc.html#autotoc_md216',1,'']]],
  ['timing_20module_20documentatie_44',['Timing Module - Documentatie',['../timing_doc.html',1,'']]],
  ['timing_20parameters_20summary_45',['Key Timing Parameters Summary',['../p_one_doc.html#autotoc_md233',1,'']]],
  ['timing_20performance_46',['Timing &amp;amp; Performance',['../cloud_doc.html#autotoc_md55',1,'']]],
  ['timing_20uitleg_47',['7. Timing Uitleg',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md527',1,'']]],
  ['timing_20watchdog_48',['Timing &amp;amp; Watchdog',['../p_one_doc.html#autotoc_md210',1,'']]],
  ['titel_20formaten_49',['❗ Inconsistente Titel Formaten',['../group__Titel.html#autotoc_md615',1,'']]],
  ['to_20end_20test_50',['FOTA End-to-End Test',['../cloud_doc.html#autotoc_md52',1,'']]],
  ['toekomstige_20uitbreidingen_51',['Toekomstige Uitbreidingen',['../cloud_doc.html#autotoc_md60',1,'Toekomstige Uitbreidingen'],['../energy_pulse_doc.html#autotoc_md92',1,'Toekomstige Uitbreidingen'],['../message_queue_doc.html#autotoc_md161',1,'Toekomstige Uitbreidingen'],['../network_doc.html#autotoc_md185',1,'Toekomstige Uitbreidingen'],['../reboot_doc.html#autotoc_md259',1,'Toekomstige Uitbreidingen'],['../timing_doc.html#autotoc_md289',1,'Toekomstige Uitbreidingen']]],
  ['toelichting_52',['Toelichting',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md431',1,'']]],
  ['tools_20commands_53',['5.5 Practical Tools &amp;amp; Commands',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md577',1,'']]],
  ['total_20response_20timeout_54',['3. Total Response Timeout',['../p_one_doc.html#autotoc_md220',1,'']]],
  ['tracking_55',['Tracking',['../reboot_doc.html#autotoc_md252',1,'Acknowledgement Tracking'],['../reboot_doc.html#autotoc_md242',1,'Reboot Reason Tracking']]],
  ['trade_20offs_56',['Trade offs',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md525',1,'5. Afwegingen (Trade-offs)'],['../energy_pulse_doc.html#autotoc_md91',1,'Design Trade-offs']]],
  ['transities_57',['9. State Machine Transities',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md529',1,'']]],
  ['transitions_58',['State Transitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md393',1,'']]],
  ['transmission_20elke_2030_20minuten_59',['☁️ Cloud Transmission (elke 30 minuten)',['../index.html#autotoc_md303',1,'']]],
  ['transmission_20time_60',['1. Maximum Telegram Transmission Time',['../p_one_doc.html#autotoc_md218',1,'']]],
  ['transport_20details_61',['Transport Details',['../message_queue_doc.html#autotoc_md154',1,'']]],
  ['trigger_62',['Scenario 3: Inter-byte Timeout Trigger',['../p_one_doc.html#autotoc_md229',1,'']]],
  ['trigger_5fchan_20als_20coördinatie_20mechanisme_63',['TRIGGER_CHAN als Coördinatie Mechanisme',['../app_doc.html#autotoc_md5',1,'']]],
  ['triggers_64',['2. ZBUS Message Handling (Periodieke Triggers)',['../p_one_doc.html#autotoc_md204',1,'']]],
  ['txt_65',['CMakeLists.txt',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md469',1,'']]],
  ['txt_20voor_20modules_66',['CMakeLists.txt voor Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md457',1,'']]],
  ['type_67',['Fase 3: Systematische Verificatie Per Claim Type',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md561',1,'']]],
  ['type_20aannames_68',['Type Aannames',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md413',1,'']]],
  ['types_69',['Types',['../doxygen_guidelines.html#autotoc_md590',1,'📚 Documentatie Types'],['../reboot_doc.html#autotoc_md245',1,'Reboot Types']]],
  ['typische_20dag_70',['Use Case: Typische Dag',['../timing_doc.html#autotoc_md277',1,'']]],
  ['typische_20scenario_20s_71',['Typische Scenario s',['../led_doc.html#autotoc_md107',1,'Typische Scenario's'],['../led_doc.html#autotoc_md108',1,'Typische Scenario's']]]
];
