var searchData=
[
  ['machine_0',['Machine',['../cloud_doc.html#autotoc_md27',1,'Cloud Connectie State Machine'],['../message_queue_doc.html#autotoc_md136',1,'State Machine'],['../network_doc.html#autotoc_md171',1,'State Machine'],['../reboot_doc.html#autotoc_md243',1,'State Machine'],['../timing_doc.html#autotoc_md274',1,'State Machine']]],
  ['machine_20forward_20declarations_1',['State Machine Forward Declarations',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md481',1,'']]],
  ['machine_20patterns_20smf_2',['State Machine Patterns (SMF)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md433',1,'']]],
  ['machine_20setup_3',['State Machine Setup',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md434',1,'']]],
  ['machine_20transities_4',['9. State Machine Transities',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md572',1,'']]],
  ['macro_5',['ARG_UNUSED Macro',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md556',1,'']]],
  ['macro_20s_6',['Macro&apos;s',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md532',1,'']]],
  ['magic_20numbers_20en_20constants_7',['Magic Numbers en Constants',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md547',1,'']]],
  ['management_8',['Management',['../network_doc.html#autotoc_md162',1,'Event-Driven Network Management'],['../message_queue_doc.html#autotoc_md137',1,'Queue Management'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md438',1,'Resource Management'],['../led_doc.html#autotoc_md112',1,'State Management']]],
  ['manager_20integration_9',['Zephyr Connection Manager Integration',['../network_doc.html#autotoc_md172',1,'']]],
  ['matter_10',['Why These Specific Timeouts Matter',['../p_one_doc.html#autotoc_md213',1,'']]],
  ['maximum_20length_20telegram_11',['Scenario 2: Maximum Length Telegram',['../p_one_doc.html#autotoc_md220',1,'']]],
  ['maximum_20telegram_20transmission_20time_12',['1. Maximum Telegram Transmission Time',['../p_one_doc.html#autotoc_md210',1,'']]],
  ['mcuboot_20app_13',['Multi-Image Builds (MCUboot + App)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md368',1,'']]],
  ['mcuboot_20swap_20duration_14',['MCUboot Swap Duration',['../cloud_doc.html#autotoc_md57',1,'']]],
  ['md_15',['Structuur van &lt;span class=&quot;tt&quot;&gt;&amp;lt;module&amp;gt;_doc.md&lt;/span&gt;',['../doxygen_guidelines.html#autotoc_md644',1,'']]],
  ['mechanism_16',['Hardware Watchdog als Safety Mechanism',['../app_doc.html#autotoc_md4',1,'']]],
  ['mechanisme_17',['Mechanisme',['../timing_doc.html#autotoc_md264',1,'Offset Mechanisme'],['../reboot_doc.html#autotoc_md245',1,'Timeout Mechanisme'],['../app_doc.html#autotoc_md5',1,'TRIGGER_CHAN als Coördinatie Mechanisme']]],
  ['memory_20usage_18',['Memory Usage',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md465',1,'']]],
  ['message_20flow_20scenarios_19',['Message Flow Scenarios',['../index.html#autotoc_md292',1,'']]],
  ['message_20format_20',['Message Format',['../message_queue_doc.html#autotoc_md140',1,'Cloud Message Format'],['../message_queue_doc.html#autotoc_md133',1,'Message Format']]],
  ['message_20handling_20periodieke_20triggers_21',['2. ZBUS Message Handling (Periodieke Triggers)',['../p_one_doc.html#autotoc_md196',1,'']]],
  ['message_20presence_20scenarios_22',['Message Presence Scenarios',['../message_queue_doc.html#autotoc_md145',1,'']]],
  ['message_20processing_20in_20thread_23',['Message Processing in Thread',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md431',1,'']]],
  ['message_20queue_20module_20documentatie_24',['Message Queue Module - Documentatie',['../message_queue_doc.html',1,'']]],
  ['message_20structs_25',['Message Structs',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md493',1,'']]],
  ['message_20structure_26',['Message Structure',['../message_queue_doc.html#autotoc_md142',1,'']]],
  ['messages_27',['Publishing Messages',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md430',1,'']]],
  ['met_20custom_20runner_28',['Flash met Custom Runner',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md344',1,'']]],
  ['met_20zbus_20smf_29',['Thread Loop met ZBUS + SMF',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md460',1,'']]],
  ['meters_30',['Data Acquisitie van DSMR Meters',['../p_one_doc.html#autotoc_md185',1,'']]],
  ['meting_20acquisitie_31',['Gas Meting Acquisitie',['../p_one_doc.html#autotoc_md190',1,'']]],
  ['minuten_32',['minuten',['../index.html#autotoc_md295',1,'☁️ Cloud Transmission (elke 30 minuten)'],['../index.html#autotoc_md294',1,'📊 Publish Statistics (elke 10 minuten)']]],
  ['mismatch_33',['❗ Anchor Mismatch',['../group__Titel.html#autotoc_md657',1,'']]],
  ['missing_34',['Missing',['../group__Titel.html#autotoc_md660',1,'❗ Missing @ingroup'],['../group__Titel.html#autotoc_md663',1,'❗ Missing @ingroup']]],
  ['model_35',['Thread Model',['../app_doc.html#autotoc_md11',1,'']]],
  ['modem_20firmware_36',['Modem Firmware',['../provisioning.html#autotoc_md399',1,'Stap 1: Flash Productie Modem Firmware'],['../provisioning.html#autotoc_md393',1,'Stap 1: Flash PTI Modem Firmware']]],
  ['modem_20firmware_20downloaden_37',['1.3 Modem Firmware Downloaden',['../provisioning.html#autotoc_md381',1,'']]],
  ['modem_20firmware_20v2_200_203_38',['Download Modem Firmware v2.0.3',['../provisioning.html#autotoc_md382',1,'']]],
  ['modem_20firmware_20v2_203_208_39',['Download PTI Modem Firmware v2.3.8',['../provisioning.html#autotoc_md383',1,'']]],
  ['modem_20initialization_20details_40',['Modem Initialization Details',['../network_doc.html#autotoc_md173',1,'']]],
  ['modem_20initialization_20hook_41',['Modem Initialization Hook',['../network_doc.html#autotoc_md163',1,'']]],
  ['modem_20shell_42',['Stap 3: Flash Modem Shell',['../provisioning.html#autotoc_md395',1,'']]],
  ['modem_20shell_20mosh_20bouwen_43',['1.4 Modem Shell (MoSh) Bouwen',['../provisioning.html#autotoc_md385',1,'']]],
  ['module_44',['Checklist voor Nieuwe Module',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md447',1,'']]],
  ['module_20checklist_45',['Module Checklist',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md507',1,'']]],
  ['module_20documentatie_46',['Module Documentatie',['../doxygen_guidelines.html#autotoc_md643',1,'📝 Module Documentatie'],['../app_doc.html',1,'App Module - Documentatie'],['../cloud_doc.html',1,'Cloud Module - Documentatie'],['../energy_pulse_doc.html',1,'Energy Pulse Module - Documentatie'],['../led_doc.html',1,'LED Module - Documentatie'],['../message_queue_doc.html',1,'Message Queue Module - Documentatie'],['../network_doc.html',1,'Network Module - Documentatie'],['../p_one_doc.html',1,'P1 DSMR Module - Documentatie'],['../reboot_doc.html',1,'Reboot Module - Documentatie'],['../timing_doc.html',1,'Timing Module - Documentatie']]],
  ['module_20documentatie_20richtlijnen_47',['Module Documentatie Richtlijnen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html',1,'']]],
  ['module_20documenteren_48',['✅ Checklist: Nieuwe Module Documenteren',['../group__Titel.html#autotoc_md654',1,'']]],
  ['module_20eigen_20thread_20heeft_49',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md514',1,'']]],
  ['module_20groepen_20definiëren_50',['Module Groepen Definiëren',['../doxygen_guidelines.html#autotoc_md647',1,'']]],
  ['module_20initialisatie_51',['Module Initialisatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md496',1,'Module Initialisatie'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md511',1,'Module Initialisatie']]],
  ['module_20interacties_52',['🔄 Data Flow &amp;amp; Module Interacties',['../index.html#autotoc_md289',1,'']]],
  ['module_20readme_20s_53',['📁 Module README&apos;s',['../index.html#autotoc_md313',1,'']]],
  ['module_20setup_20pattern_54',['Module Setup Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md445',1,'']]],
  ['module_20shutdown_20implementatie_20vereisten_55',['Module Shutdown Implementatie Vereisten',['../reboot_doc.html#autotoc_md253',1,'']]],
  ['modules_56',['Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md573',1,'10. Afhankelijkheden van Andere Modules'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md500',1,'CMakeLists.txt voor Modules'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md518',1,'Referentie Modules']]],
  ['moet_57',['moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md563',1,'✅ Wat ER WEL in moet'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md576',1,'❗ Wat ER NIET in moet']]],
  ['mosh_20bouwen_58',['1.4 Modem Shell (MoSh) Bouwen',['../provisioning.html#autotoc_md385',1,'']]],
  ['motivatie_59',['Motivatie',['../cloud_doc.html#autotoc_md22',1,'Waarom? (Motivatie)'],['../energy_pulse_doc.html#autotoc_md73',1,'Waarom? (Probleem &amp; Motivatie)'],['../led_doc.html#autotoc_md100',1,'Waarom? (Probleem &amp; Motivatie)'],['../reboot_doc.html#autotoc_md232',1,'Waarom? (Probleem &amp; Motivatie)'],['../timing_doc.html#autotoc_md262',1,'Waarom? (Probleem &amp; Motivatie)']]],
  ['ms_60',['ms',['../p_one_doc.html#autotoc_md215',1,'Inter-byte Timeout (392 ms)'],['../p_one_doc.html#autotoc_md216',1,'Telegram Timeout (784 ms)']]],
  ['msg_5fsubscriber_20pattern_61',['MSG_SUBSCRIBER Pattern',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md428',1,'']]],
  ['multi_20image_20builds_20mcuboot_20app_62',['Multi-Image Builds (MCUboot + App)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md368',1,'']]],
  ['multi_20layer_20timeout_20strategy_63',['Multi-Layer Timeout Strategy',['../p_one_doc.html#autotoc_md226',1,'']]],
  ['multiple_20source_20files_64',['Multiple Source Files',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md503',1,'']]],
  ['mutex_20usage_65',['Mutex Usage',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md440',1,'']]]
];
