var searchData=
[
  ['edge_20case_20scenarios_0',['Edge Case Scenarios',['../p_one_doc.html#autotoc_md218',1,'']]],
  ['edge_20cases_1',['Edge Cases',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md566',1,'3. Edge Cases'],['../cloud_doc.html#autotoc_md35',1,'Edge Cases']]],
  ['edge_20cases_20robuustheid_2',['Edge Cases &amp;amp; Robuustheid',['../p_one_doc.html#autotoc_md201',1,'']]],
  ['eenmalige_20setup_3',['Eenmalige Setup',['../provisioning.html#autotoc_md377',1,'🛠️ Fase 1: Eenmalige Setup'],['../provisioning.html#autotoc_md414',1,'Eenmalige Setup']]],
  ['eerste_20keer_20setup_4',['Eerste Keer Setup',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md332',1,'']]],
  ['eigen_20thread_20heeft_5',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md514',1,'']]],
  ['elementen_6',['Links naar API Elementen',['../group__Titel.html#autotoc_md648',1,'']]],
  ['elke_2010_20minuten_7',['📊 Publish Statistics (elke 10 minuten)',['../index.html#autotoc_md294',1,'']]],
  ['elke_2030_20minuten_8',['☁️ Cloud Transmission (elke 30 minuten)',['../index.html#autotoc_md295',1,'']]],
  ['elke_2030_20seconden_9',['📥 Normal Data Collection (elke 30 seconden)',['../index.html#autotoc_md293',1,'']]],
  ['elke_20documentatie_20wijziging_3a_10',['Checklist voor elke documentatie wijziging:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md589',1,'']]],
  ['en_20buffers_11',['Arrays en Buffers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md544',1,'']]],
  ['en_20constants_12',['Magic Numbers en Constants',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md547',1,'']]],
  ['en_20defines_13',['Constanten en Defines',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md531',1,'']]],
  ['en_20documentatie_14',['Comments en Documentatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md537',1,'']]],
  ['en_20formattering_15',['Indentatie en Formattering',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md522',1,'']]],
  ['en_20headers_16',['Include Guards en Headers',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md475',1,'']]],
  ['en_20optimization_17',['Performance en Optimization',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md464',1,'']]],
  ['en_20portability_18',['Undefined Behavior en Portability',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md454',1,'']]],
  ['en_20return_20values_19',['Error Handling en Return Values',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md419',1,'']]],
  ['en_20safety_20',['Security en Safety',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md468',1,'']]],
  ['en_20static_21',['Scope en Static',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md543',1,'']]],
  ['en_20synchronisatie_20kritiek_20⚠️_22',['4. Code Verificatie en Synchronisatie (KRITIEK! ⚠️)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md581',1,'']]],
  ['en_20validatie_23',['NULL Checks en Validatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md552',1,'']]],
  ['en_20volgorde_24',['Code Structure - Organisatie en Volgorde',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html',1,'']]],
  ['en_20voor_20na_20vergelijkingen_25',['3. Historische Referenties en Voor/Na Vergelijkingen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md579',1,'']]],
  ['end_20test_26',['FOTA End-to-End Test',['../cloud_doc.html#autotoc_md52',1,'']]],
  ['end_20to_20end_20test_27',['FOTA End-to-End Test',['../cloud_doc.html#autotoc_md52',1,'']]],
  ['energietellers_28',['Persistente Energietellers',['../energy_pulse_doc.html#autotoc_md74',1,'']]],
  ['energy_20pulse_20module_20documentatie_29',['Energy Pulse Module - Documentatie',['../energy_pulse_doc.html',1,'']]],
  ['enum_20vs_20define_30',['enum vs define',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md548',1,'']]],
  ['enums_31',['Enums',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md533',1,'Enums'],['../network_doc.html#autotoc_md168',1,'Network Status Enums']]],
  ['environment_32',['1.1 Development Environment',['../provisioning.html#autotoc_md378',1,'']]],
  ['environment_20activeren_33',['1.2 nRF Connect Environment Activeren',['../provisioning.html#autotoc_md379',1,'']]],
  ['environment_20setup_34',['🛠️ Environment Setup',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md327',1,'']]],
  ['er_20niet_20in_20moet_35',['❗ Wat ER NIET in moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md576',1,'']]],
  ['er_20wel_20in_20moet_36',['✅ Wat ER WEL in moet',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md563',1,'']]],
  ['error_20handling_37',['Error Handling',['../energy_pulse_doc.html#autotoc_md85',1,'']]],
  ['error_20handling_20en_20return_20values_38',['Error Handling en Return Values',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md419',1,'']]],
  ['error_20variable_20declaratie_39',['Error Variable Declaratie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md420',1,'']]],
  ['errors_40',['Logging Bij Errors',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md423',1,'']]],
  ['evaluatievolgorde_41',['Evaluatievolgorde',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md455',1,'']]],
  ['event_20driven_20network_20management_42',['Event-Driven Network Management',['../network_doc.html#autotoc_md162',1,'']]],
  ['event_20flow_43',['FOTA Event Flow',['../cloud_doc.html#autotoc_md28',1,'']]],
  ['experience_20benefits_44',['User Experience Benefits',['../led_doc.html#autotoc_md115',1,'']]],
  ['external_20flash_20support_45',['Priority 1: External Flash Support',['../cloud_doc.html#autotoc_md61',1,'']]],
  ['external_20interface_20contract_46',['External Interface Contract',['../message_queue_doc.html#autotoc_md141',1,'']]],
  ['externe_20resources_47',['🌐 Externe Resources',['../index.html#autotoc_md317',1,'']]],
  ['extraction_48',['Fase 2: Documentation Claims Extraction',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md602',1,'']]]
];
