var searchData=
[
  ['fase_201_3a_20build_20code_20inventory_20objectieve_20waarheid_0',['Fase 1: Build Code Inventory (Objectieve Waarheid)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md400',1,'']]],
  ['fase_202_3a_20documentation_20claims_20extraction_1',['Fase 2: Documentation Claims Extraction',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md402',1,'']]],
  ['fase_203_3a_20systematische_20verificatie_20per_20claim_20type_2',['Fase 3: Systematische Verificatie Per Claim Type',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md404',1,'']]],
  ['fase_204_3a_20documentatie_20anti_20patterns_20red_20flags_3',['Fase 4: Documentatie Anti-Patterns (Red Flags)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md413',1,'']]],
  ['fasen_4',['5.4 Verification Workflow (5 Fasen)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md418',1,'']]],
  ['fatale_20foutafhandeling_5',['Fatale Foutafhandeling',['../md_modules_2reboot_2reboot__doc.html#autotoc_md155',1,'']]],
  ['feature_20consistency_20red_20flags_6',['4.3 Feature Consistency Red Flags',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md416',1,'']]],
  ['features_7',['Features',['../index.html#autotoc_md193',1,'⚙️ Belangrijke Features'],['../index.html#autotoc_md197',1,'🛡️ Robustness Features']]],
  ['feedback_20voor_20iot_20device_8',['Visuele Feedback voor IoT Device',['../led_doc.html#autotoc_md63',1,'']]],
  ['feedback_20waarde_9',['LED Feedback Waarde',['../led_doc.html#autotoc_md74',1,'']]],
  ['file_20c_20template_10',['Source File (.c) Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md288',1,'']]],
  ['file_20h_20template_11',['Header File (.h) Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md289',1,'']]],
  ['file_20structuur_12',['File Structuur',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md287',1,'']]],
  ['files_13',['Multiple Source Files',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md303',1,'']]],
  ['files_14',['Include Order (in .c files)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md277',1,'']]],
  ['files_20h_15',['Header Files (.h)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md276',1,'']]],
  ['filosofie_16',['📋 Filosofie',['../doxygen_guidelines.html#autotoc_md431',1,'']]],
  ['firmware_20documentatie_17',['SolarResult Energy Core - Firmware Documentatie',['../index.html',1,'']]],
  ['firmware_20over_20the_20air_18',['3.3 FOTA (Firmware-Over-The-Air)',['../cloud_doc.html#autotoc_md27',1,'']]],
  ['first_20investigation_19',['5.2 Fundamenteel Principe: Code-First Investigation',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md397',1,'']]],
  ['fixed_20point_20',['Waarom Integer Fixed-Point?',['../p_one_doc.html#autotoc_md113',1,'']]],
  ['flags_21',['Flags',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md414',1,'4.1 Taalgebruik Red Flags'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md415',1,'4.2 Structurele Red Flags'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md416',1,'4.3 Feature Consistency Red Flags'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md413',1,'Fase 4: Documentatie Anti-Patterns (Red Flags)']]],
  ['flow_22',['Flow',['../p_one_doc.html#autotoc_md106',1,'ACQ_TRIGGER Flow'],['../energy_pulse_doc.html#autotoc_md41',1,'Data Flow'],['../md_modules_2timing_2timing__doc.html#autotoc_md165',1,'Functionaliteit en Data Flow'],['../md_modules_2network_2network__doc.html#autotoc_md91',1,'Initialisatie Flow'],['../p_one_doc.html#autotoc_md107',1,'PUBLISH Flow'],['../energy_pulse_doc.html#autotoc_md39',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../led_doc.html#autotoc_md66',1,'Wat? (Functionaliteit &amp; Data Flow)']]],
  ['flow_20scenarios_23',['Message Flow Scenarios',['../index.html#autotoc_md185',1,'']]],
  ['flow_20state_20machine_24',['Data Flow &amp;amp; State Machine',['../message_queue_module.html#mq_dataflow',1,'']]],
  ['flow_20zbus_20architectuur_25',['🔄 Data Flow &amp;amp; ZBUS Architectuur',['../index.html#autotoc_md182',1,'']]],
  ['format_26',['Cloud Message Format',['../message_queue_module.html#mq_cloudformat',1,'']]],
  ['formaten_27',['❗ Inconsistente Titel Formaten',['../group__Titel.html#autotoc_md458',1,'']]],
  ['formattering_28',['Indentatie en Formattering',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md322',1,'']]],
  ['formattering_20regels_29',['Code Style - Formattering Regels',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html',1,'']]],
  ['forward_20declarations_30',['Forward Declarations',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md279',1,'Forward Declarations'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2structure.html#autotoc_md281',1,'State Machine Forward Declarations']]],
  ['fota_20firmware_20over_20the_20air_31',['3.3 FOTA (Firmware-Over-The-Air)',['../cloud_doc.html#autotoc_md27',1,'']]],
  ['fout_20verzonnen_20content_20_3a_32',['❗ FOUT (verzonnen content):',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md387',1,'']]],
  ['foutafhandeling_33',['Fatale Foutafhandeling',['../md_modules_2reboot_2reboot__doc.html#autotoc_md155',1,'']]],
  ['foutafhandeling_20en_20robuustheid_34',['Foutafhandeling en Robuustheid',['../md_modules_2network_2network__doc.html#autotoc_md90',1,'']]],
  ['fouten_20door_20niet_20te_20verifiëren_3a_35',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md386',1,'']]],
  ['frame_20level_20timing_2087_20µs_36',['Frame-Level Timing (87 µs)',['../p_one_doc.html#autotoc_md128',1,'']]],
  ['frame_20timing_20fundamentals_37',['UART Frame Timing Fundamentals',['../p_one_doc.html#autotoc_md122',1,'']]],
  ['functies_38',['Functies',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2style.html#autotoc_md329',1,'']]],
  ['functionaliteit_39',['Functionaliteit',['../cloud_doc.html#autotoc_md24',1,'3. Architectuur en Functionaliteit'],['../app_doc.html#autotoc_md5',1,'3. Functionaliteit'],['../p_one_doc.html#autotoc_md97',1,'Functionaliteit'],['../md_modules_2reboot_2reboot__doc.html#autotoc_md146',1,'Functionaliteit']]],
  ['functionaliteit_20data_20flow_40',['Functionaliteit Data Flow',['../energy_pulse_doc.html#autotoc_md39',1,'Wat? (Functionaliteit &amp; Data Flow)'],['../led_doc.html#autotoc_md66',1,'Wat? (Functionaliteit &amp; Data Flow)']]],
  ['functionaliteit_20en_20data_20flow_41',['Functionaliteit en Data Flow',['../md_modules_2timing_2timing__doc.html#autotoc_md165',1,'']]],
  ['functions_42',['State Handler Functions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2best-practices.html#autotoc_md235',1,'']]],
  ['fundamentals_43',['Fundamentals',['../p_one_doc.html#autotoc_md122',1,'UART Frame Timing Fundamentals'],['../p_one_doc.html#autotoc_md100',1,'UART Timing Calculations - Fundamentals']]],
  ['fundamenteel_20principe_3a_20code_20first_20investigation_44',['5.2 Fundamenteel Principe: Code-First Investigation',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2fw-energy-core_2guidelines_2documentation.html#autotoc_md397',1,'']]],
  ['future_20uitbreidingen_45',['Future Uitbreidingen',['../led_doc.html#autotoc_md77',1,'']]]
];
