var searchData=
[
  ['taalgebruik_20red_20flags_0',['4.1 Taalgebruik Red Flags',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md614',1,'']]],
  ['tabs_1',['Spaties (GEEN Tabs)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2style.html#autotoc_md523',1,'']]],
  ['targets_2',['Targets',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md351',1,'📊 Build Targets'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md352',1,'Beschikbare Targets']]],
  ['task_20watchdog_3',['Task Watchdog',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md443',1,'']]],
  ['task_20watchdog_20indien_20module_20eigen_20thread_20heeft_4',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md514',1,'']]],
  ['te_20verifiëren_3a_5',['Voorbeelden van FOUTEN door niet te verifiëren:',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md586',1,'']]],
  ['technische_20diepgang_6',['Technische Diepgang',['../p_one_doc.html#autotoc_md198',1,'']]],
  ['telegram_7',['Scenario 2: Maximum Length Telegram',['../p_one_doc.html#autotoc_md220',1,'']]],
  ['telegram_20timeout_20784_20ms_8',['Telegram Timeout (784 ms)',['../p_one_doc.html#autotoc_md216',1,'']]],
  ['telegram_20transmission_20time_9',['1. Maximum Telegram Transmission Time',['../p_one_doc.html#autotoc_md210',1,'']]],
  ['template_10',['Template',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md489',1,'Header File (.h) Template'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md488',1,'Source File (.c) Template']]],
  ['test_11',['FOTA End-to-End Test',['../cloud_doc.html#autotoc_md52',1,'']]],
  ['test_20warning_3a_20intentional_20crash_12',['Rollback Test (Warning: Intentional Crash)',['../cloud_doc.html#autotoc_md53',1,'']]],
  ['testing_13',['Testing',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md357',1,'🧪 Testing'],['../cloud_doc.html#autotoc_md50',1,'Testing'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md515',1,'Testing']]],
  ['tests_14',['Tests',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md359',1,'Integration Tests'],['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md358',1,'Unit Tests']]],
  ['these_20specific_20timeouts_20matter_15',['Why These Specific Timeouts Matter',['../p_one_doc.html#autotoc_md213',1,'']]],
  ['thread_16',['Message Processing in Thread',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md431',1,'']]],
  ['thread_20heeft_17',['Task Watchdog (indien module eigen thread heeft)',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md514',1,'']]],
  ['thread_20loop_20met_20zbus_20smf_18',['Thread Loop met ZBUS + SMF',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md460',1,'']]],
  ['thread_20loop_20structuur_19',['Thread Loop Structuur',['../p_one_doc.html#autotoc_md197',1,'']]],
  ['thread_20model_20',['Thread Model',['../app_doc.html#autotoc_md11',1,'']]],
  ['time_21',['1. Maximum Telegram Transmission Time',['../p_one_doc.html#autotoc_md210',1,'']]],
  ['time_20transfer_20logging_22',['RTT (Real-Time Transfer) Logging',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md349',1,'']]],
  ['timeline_23',['Complete System Timeline',['../timing_doc.html#autotoc_md268',1,'']]],
  ['timeout_24',['3. Total Response Timeout',['../p_one_doc.html#autotoc_md212',1,'']]],
  ['timeout_25',['2. UART RX Timeout (Inter-byte timeout)',['../p_one_doc.html#autotoc_md211',1,'']]],
  ['timeout_2010_208s_26',['Response Timeout (10.8s)',['../p_one_doc.html#autotoc_md217',1,'']]],
  ['timeout_20392_20ms_27',['Inter-byte Timeout (392 ms)',['../p_one_doc.html#autotoc_md215',1,'']]],
  ['timeout_20784_20ms_28',['Telegram Timeout (784 ms)',['../p_one_doc.html#autotoc_md216',1,'']]],
  ['timeout_20inter_20byte_20timeout_29',['2. UART RX Timeout (Inter-byte timeout)',['../p_one_doc.html#autotoc_md211',1,'']]],
  ['timeout_20mechanisme_30',['Timeout Mechanisme',['../reboot_doc.html#autotoc_md245',1,'']]],
  ['timeout_20strategy_31',['Multi-Layer Timeout Strategy',['../p_one_doc.html#autotoc_md226',1,'']]],
  ['timeout_20trigger_32',['Scenario 3: Inter-byte Timeout Trigger',['../p_one_doc.html#autotoc_md221',1,'']]],
  ['timeouts_20matter_33',['Why These Specific Timeouts Matter',['../p_one_doc.html#autotoc_md213',1,'']]],
  ['timer_20configuratie_34',['Timer Configuratie',['../timing_doc.html#autotoc_md273',1,'']]],
  ['timing_35',['Timing',['../timing_doc.html#autotoc_md263',1,'Gecoördineerde Timing'],['../p_one_doc.html#autotoc_md186',1,'UART Async API &amp; Timing']]],
  ['timing_2087_20µs_36',['Frame-Level Timing (87 µs)',['../p_one_doc.html#autotoc_md214',1,'']]],
  ['timing_20accuracy_37',['Timing Accuracy',['../timing_doc.html#autotoc_md279',1,'']]],
  ['timing_20analyse_38',['📐 Appendix A: UART Timing Analyse',['../p_one_doc.html#autotoc_md206',1,'']]],
  ['timing_20behavior_20claims_39',['3.4 Timing &amp;amp; Behavior Claims',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md611',1,'']]],
  ['timing_20berekening_40',['Timing Berekening',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md446',1,'']]],
  ['timing_20calculations_41',['Critical Timing Calculations',['../p_one_doc.html#autotoc_md209',1,'']]],
  ['timing_20calculations_20fundamentals_42',['UART Timing Calculations - Fundamentals',['../p_one_doc.html#autotoc_md187',1,'']]],
  ['timing_20diagrammen_43',['8. Timing Diagrammen',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md571',1,'']]],
  ['timing_20fundamentals_44',['UART Frame Timing Fundamentals',['../p_one_doc.html#autotoc_md208',1,'']]],
  ['timing_20module_20documentatie_45',['Timing Module - Documentatie',['../timing_doc.html',1,'']]],
  ['timing_20parameters_20summary_46',['Key Timing Parameters Summary',['../p_one_doc.html#autotoc_md225',1,'']]],
  ['timing_20performance_47',['Timing &amp;amp; Performance',['../cloud_doc.html#autotoc_md55',1,'']]],
  ['timing_20uitleg_48',['7. Timing Uitleg',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md570',1,'']]],
  ['timing_20watchdog_49',['Timing &amp;amp; Watchdog',['../p_one_doc.html#autotoc_md202',1,'']]],
  ['titel_20formaten_50',['❗ Inconsistente Titel Formaten',['../group__Titel.html#autotoc_md658',1,'']]],
  ['to_20end_20test_51',['FOTA End-to-End Test',['../cloud_doc.html#autotoc_md52',1,'']]],
  ['toekomstige_20uitbreidingen_52',['Toekomstige Uitbreidingen',['../cloud_doc.html#autotoc_md60',1,'Toekomstige Uitbreidingen'],['../energy_pulse_doc.html#autotoc_md92',1,'Toekomstige Uitbreidingen'],['../message_queue_doc.html#autotoc_md153',1,'Toekomstige Uitbreidingen'],['../network_doc.html#autotoc_md177',1,'Toekomstige Uitbreidingen'],['../reboot_doc.html#autotoc_md251',1,'Toekomstige Uitbreidingen'],['../timing_doc.html#autotoc_md281',1,'Toekomstige Uitbreidingen']]],
  ['toelichting_53',['Toelichting',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md474',1,'']]],
  ['toolchain_20verificatie_54',['Toolchain Verificatie',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md329',1,'']]],
  ['tools_20commands_55',['5.5 Practical Tools &amp;amp; Commands',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md620',1,'']]],
  ['topics_56',['🚀 Advanced Topics',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md367',1,'']]],
  ['total_20response_20timeout_57',['3. Total Response Timeout',['../p_one_doc.html#autotoc_md212',1,'']]],
  ['tracking_58',['Tracking',['../reboot_doc.html#autotoc_md244',1,'Acknowledgement Tracking'],['../reboot_doc.html#autotoc_md234',1,'Reboot Reason Tracking']]],
  ['trade_20offs_59',['Trade offs',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md568',1,'5. Afwegingen (Trade-offs)'],['../energy_pulse_doc.html#autotoc_md91',1,'Design Trade-offs']]],
  ['transfer_20logging_60',['RTT (Real-Time Transfer) Logging',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md349',1,'']]],
  ['transities_61',['9. State Machine Transities',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md572',1,'']]],
  ['transitions_62',['State Transitions',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md436',1,'']]],
  ['transmission_20elke_2030_20minuten_63',['☁️ Cloud Transmission (elke 30 minuten)',['../index.html#autotoc_md295',1,'']]],
  ['transmission_20time_64',['1. Maximum Telegram Transmission Time',['../p_one_doc.html#autotoc_md210',1,'']]],
  ['transport_20details_65',['Transport Details',['../message_queue_doc.html#autotoc_md146',1,'']]],
  ['trigger_66',['Scenario 3: Inter-byte Timeout Trigger',['../p_one_doc.html#autotoc_md221',1,'']]],
  ['trigger_5fchan_20als_20coördinatie_20mechanisme_67',['TRIGGER_CHAN als Coördinatie Mechanisme',['../app_doc.html#autotoc_md5',1,'']]],
  ['triggers_68',['2. ZBUS Message Handling (Periodieke Triggers)',['../p_one_doc.html#autotoc_md196',1,'']]],
  ['troubleshooting_69',['📝 Build Troubleshooting',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2docs_2development-guide.html#autotoc_md361',1,'']]],
  ['txt_70',['CMakeLists.txt',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md512',1,'']]],
  ['txt_20voor_20modules_71',['CMakeLists.txt voor Modules',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2structure.html#autotoc_md500',1,'']]],
  ['type_72',['Fase 3: Systematische Verificatie Per Claim Type',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2documentation.html#autotoc_md604',1,'']]],
  ['type_20aannames_73',['Type Aannames',['../md__2home_2ruben_2Documents_2solarresult_2firmware_2dinnis-core_2guidelines_2best-practices.html#autotoc_md456',1,'']]],
  ['types_74',['Types',['../doxygen_guidelines.html#autotoc_md633',1,'📚 Documentatie Types'],['../reboot_doc.html#autotoc_md237',1,'Reboot Types']]],
  ['typische_20dag_75',['Use Case: Typische Dag',['../timing_doc.html#autotoc_md269',1,'']]],
  ['typische_20scenario_20s_76',['Typische Scenario&apos;s',['../led_doc.html#autotoc_md107',1,'']]]
];
