SolarResult Dinnis Core: modules/app/app.c File Reference
app.c File Reference
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/sys/reboot.h>
#include <zephyr/task_wdt/task_wdt.h>
#include <zephyr/zbus/zbus.h>
#include "reboot_zbus.h"
#include "trigger_zbus.h"
Macros
#define HW_WDT_DEV DEVICE_DT_GET(DT_NODELABEL(wdt))
Functions
LOG_MODULE_REGISTER (app, CONFIG_APP_MODULE_LOG_LEVEL)
ZBUS_CHAN_DEFINE (TRIGGER_CHAN, struct trigger_msg, NULL, NULL, ZBUS_OBSERVERS_EMPTY, ZBUS_MSG_INIT(0))
static void zbus_monitor_callback (const struct zbus_channel *chan)
ZBUS listener callback - logs all channel activity.
ZBUS_LISTENER_DEFINE (zbus_monitor, zbus_monitor_callback)
static void task_wdt_callback (int channel_id, void *user_data)
Watchdog timeout callback.
static void app_thread (void)
Main application thread.
K_THREAD_DEFINE (app_thread_id, CONFIG_APP_MODULE_THREAD_STACK_SIZE, app_thread, NULL, NULL, NULL, CONFIG_APP_THREAD_PRIORITY_APP, 0, 0)
static int watchdog_init (void)
Initialize hardware watchdog.
SYS_INIT (watchdog_init, POST_KERNEL, CONFIG_APPLICATION_INIT_PRIORITY)
Variables
static const struct device * hw_wdt_dev = DEVICE_DT_GET(DT_NODELABEL(wdt))
Macro Definition Documentation
HW_WDT_DEV
#define HW_WDT_DEV DEVICE_DT_GET(DT_NODELABEL(wdt))
Definition at line 31 of file app.c.
Function Documentation
app_thread()
void app_thread (void) static
Main application thread.
Simple watchdog feeding loop - no business logic.
Definition at line 110 of file app.c.
References task_wdt_callback().
Referenced by K_THREAD_DEFINE().
K_THREAD_DEFINE()
K_THREAD_DEFINE (app_thread_id , CONFIG_APP_MODULE_THREAD_STACK_SIZE , app_thread , NULL , NULL , NULL , CONFIG_APP_THREAD_PRIORITY_APP , 0 , 0)
References app_thread().
LOG_MODULE_REGISTER()
LOG_MODULE_REGISTER (app , CONFIG_APP_MODULE_LOG_LEVEL)
SYS_INIT()
SYS_INIT (watchdog_init , POST_KERNEL , CONFIG_APPLICATION_INIT_PRIORITY)
References watchdog_init().
task_wdt_callback()
void task_wdt_callback (int channel_id, void * user_data) static
Watchdog timeout callback.
Parameters
channel_id Watchdog channel ID
user_data User data (thread ID)
Definition at line 81 of file app.c.
References reboot_request_publish(), and REBOOT_TYPE_ERROR.
Referenced by app_thread(), cloud_thread(), energy_pulse_thread(), led_thread(), message_queue_thread(), network_thread(), p_one_thread(), reboot_thread(), task_wdt_callback(), and ZBUS_CHAN_DEFINE().
watchdog_init()
int watchdog_init (void) static
Initialize hardware watchdog.
CRITICAL: Watchdog is a safety-critical component. If initialization fails, the system CANNOT run safely and will continuously reboot until the hardware issue is resolved.
Returns
0 on success, does not return on failure (triggers reboot)
Definition at line 158 of file app.c.
References hw_wdt_dev.
Referenced by SYS_INIT().
ZBUS_CHAN_DEFINE()
ZBUS_CHAN_DEFINE (TRIGGER_CHAN , struct trigger_msg , NULL , NULL , ZBUS_OBSERVERS_EMPTY , ZBUS_MSG_INIT(0))
Referenced by ZBUS_CHAN_DEFINE(), ZBUS_CHAN_DEFINE(), and ZBUS_CHAN_DEFINE().
ZBUS_LISTENER_DEFINE()
ZBUS_LISTENER_DEFINE (zbus_monitor , zbus_monitor_callback)
References zbus_monitor_callback().
zbus_monitor_callback()
void zbus_monitor_callback (const struct zbus_channel * chan) static
ZBUS listener callback - logs all channel activity.
This listener observes ALL channels and logs every publish event. Useful for debugging and understanding system-wide message flow.
Parameters
chan The channel that was published to
Definition at line 61 of file app.c.
Referenced by ZBUS_LISTENER_DEFINE().
Variable Documentation
hw_wdt_dev
const struct device* hw_wdt_dev = DEVICE_DT_GET(DT_NODELABEL(wdt)) static
Definition at line 41 of file app.c.
Referenced by watchdog_init().