SolarResult Dinnis Core: modules/cloud/cloud.c File Reference
cloud.c File Reference
#include <app_version.h>
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/smf.h>
#include <zephyr/sys/reboot.h>
#include <zephyr/zbus/zbus.h>
#include <net/nrf_cloud.h>
#include <net/nrf_cloud_codec.h>
#include "cloud_zbus.h"
#include "fota_zbus.h"
#include "modules_common.h"
#include "network_zbus.h"
#include "reboot_zbus.h"
#include "task_wdt_util.h"
Data Structures
struct cloud_state_object
Macros
#define CHANNEL_LIST(X)
#define MAX_MSG_SIZE MAX_MSG_SIZE_FROM_LIST(CHANNEL_LIST)
#define ADD_OBSERVERS(_chan, _type)
Enumerations
enum private_cloud_status {
PRIV_CLOUD_READY_TIMEOUT ,
PRIV_CLOUD_DISCONNECTED
}
enum cloud_module_state {
STATE_OPERATIONAL ,
STATE_WAITING_FOR_MODEM ,
STATE_DISCONNECTED ,
STATE_CONNECTING ,
STATE_CONNECTING_ATTEMPT ,
STATE_CLOUD_READY
}
Functions
LOG_MODULE_REGISTER (cloud, CONFIG_APP_CLOUD_MODULE_LOG_LEVEL)
BUILD_ASSERT (CONFIG_APP_CLOUD_MODULE_WATCHDOG_TIMEOUT_SECONDS > CONFIG_APP_CLOUD_MODULE_MSG_PROCESSING_TIME_SECONDS, "Cloud watchdog timeout must be greater than message processing time")
ZBUS_MSG_SUBSCRIBER_DEFINE (cloud_subscriber)
ZBUS_CHAN_ADD_OBS (NETWORK_CHAN, cloud_subscriber, 0)
ZBUS_CHAN_ADD_OBS (CLOUD_CHAN, cloud_subscriber, 0)
ZBUS_CHAN_ADD_OBS (REBOOT_CHAN, cloud_subscriber, 0)
ZBUS_CHAN_DEFINE (PRIV_CLOUD_CHAN, enum private_cloud_status, NULL, NULL, ZBUS_OBSERVERS(cloud_subscriber), ZBUS_MSG_INIT(0))
ZBUS_CHAN_DEFINE (CLOUD_CHAN, struct cloud_msg, NULL, NULL, ZBUS_OBSERVERS_EMPTY, ZBUS_MSG_INIT(0))
ZBUS_CHAN_DEFINE (FOTA_CHAN, struct fota_msg, NULL, NULL, ZBUS_OBSERVERS_EMPTY, ZBUS_MSG_INIT(0))
static void state_operational_entry (void *o)
static void state_operational_run (void *o)
static void state_waiting_for_modem_entry (void *o)
static void state_waiting_for_modem_run (void *o)
static void state_disconnected_entry (void *o)
static void state_disconnected_run (void *o)
static void state_connecting_entry (void *o)
static void state_connecting_run (void *o)
static void state_connecting_exit (void *o)
static void state_connecting_attempt_entry (void *o)
static void state_cloud_ready_entry (void *o)
static void state_cloud_ready_run (void *o)
static void state_cloud_ready_exit (void *o)
static void cloud_readiness_check_work_fn (struct k_work *work)
static K_WORK_DELAYABLE_DEFINE (cloud_readiness_check_work, cloud_readiness_check_work_fn)
static K_THREAD_STACK_DEFINE (stack_area, CONFIG_APP_CLOUD_MODULE_WORKQUEUE_STACK_SIZE)
static void connect_to_cloud (void)
static void disconnect_from_cloud (void)
static bool priv_internal_cloud_is_ready_timeout (const enum private_cloud_status *status)
static bool priv_internal_cloud_is_disconnected (const enum private_cloud_status *status)
static const char * private_cloud_status_to_str (const enum private_cloud_status status)
static void private_cloud_status_publish (const enum private_cloud_status status, const k_timeout_t timeout)
static const char * cloud_status_to_str (const enum cloud_status status)
static void cloud_status_publish (const enum cloud_status status, const k_timeout_t timeout)
static const char * fota_type_to_str (enum nrf_cloud_fota_type type)
static void on_fota_downloaded (enum nrf_cloud_fota_type fota_type)
Handle FOTA download completion.
static void fota_boot_confirm (void)
Confirm successful boot after FOTA update.
static void task_wdt_callback (int channel_id, void *user_data)
static uint32_t calculate_backoff_time (uint32_t attempts)
static void nrf_cloud_event_handler (const struct nrf_cloud_evt *nrf_cloud_evt)
static int cloud_setup (void)
static void cloud_thread (void)
K_THREAD_DEFINE (cloud_thread_id, CONFIG_APP_CLOUD_MODULE_THREAD_STACK_SIZE, cloud_thread, NULL, NULL, NULL, CONFIG_APP_THREAD_PRIORITY_CLOUD, 0, 0)
Variables
static const struct smf_state states []
static struct k_work_q cloud_workqueue
Macro Definition Documentation
ADD_OBSERVERS
#define ADD_OBSERVERS (_chan, _type)
Value:
    ZBUS_CHAN_ADD_OBS(_chan, cloud_subscriber, 0);
Definition at line 74 of file cloud.c.
Referenced by ZBUS_CHAN_ADD_OBS(), ZBUS_CHAN_ADD_OBS(), ZBUS_CHAN_ADD_OBS(), ZBUS_CHAN_ADD_OBS(), ZBUS_CHAN_ADD_OBS(), ZBUS_CHAN_ADD_OBS(), and ZBUS_CHAN_ADD_OBS().
CHANNEL_LIST
#define CHANNEL_LIST (X)
Value:
    X(NETWORK_CHAN, struct network_msg) \
    X(CLOUD_CHAN, struct cloud_msg)     \
    X(REBOOT_CHAN, struct reboot_msg)
Definition at line 65 of file cloud.c.
MAX_MSG_SIZE
#define MAX_MSG_SIZE MAX_MSG_SIZE_FROM_LIST(CHANNEL_LIST)
Definition at line 71 of file cloud.c.
Referenced by energy_pulse_thread(), led_thread(), and p_one_thread().
Enumeration Type Documentation
cloud_module_state
enum cloud_module_state
Enumerator
STATE_OPERATIONAL
STATE_WAITING_FOR_MODEM
STATE_DISCONNECTED
STATE_CONNECTING
STATE_CONNECTING_ATTEMPT
STATE_CLOUD_READY
Definition at line 163 of file cloud.c.
private_cloud_status
enum private_cloud_status
Enumerator
PRIV_CLOUD_READY_TIMEOUT
PRIV_CLOUD_DISCONNECTED
Definition at line 90 of file cloud.c.
Function Documentation
BUILD_ASSERT()
BUILD_ASSERT (CONFIG_APP_CLOUD_MODULE_WATCHDOG_TIMEOUT_SECONDS , CONFIG_APP_CLOUD_MODULE_MSG_PROCESSING_TIME_SECONDS , "Cloud watchdog timeout must be greater than message processing time")
calculate_backoff_time()
uint32_t calculate_backoff_time (uint32_t attempts) static
Definition at line 463 of file cloud.c.
Referenced by state_connecting_attempt_entry().
cloud_readiness_check_work_fn()
void cloud_readiness_check_work_fn (struct k_work * work) static
Definition at line 487 of file cloud.c.
References disconnect_from_cloud(), PRIV_CLOUD_READY_TIMEOUT, and private_cloud_status_publish().
Referenced by K_WORK_DELAYABLE_DEFINE().
cloud_setup()
int cloud_setup (void) static
Definition at line 607 of file cloud.c.
References nrf_cloud_event_handler().
Referenced by state_waiting_for_modem_run().
cloud_status_publish()
void cloud_status_publish (const enum cloud_status status, const k_timeout_t timeout) static
Definition at line 322 of file cloud.c.
References CLOUD_STATUS, cloud_status_to_str(), reboot_request_publish(), REBOOT_TYPE_ERROR, and cloud_msg::status.
Referenced by nrf_cloud_event_handler(), and state_cloud_ready_exit().
cloud_status_to_str()
const char * cloud_status_to_str (const enum cloud_status status) static
Definition at line 301 of file cloud.c.
References CLOUD_NOT_READY, and CLOUD_READY.
Referenced by cloud_status_publish().
cloud_thread()
void cloud_thread (void) static
Definition at line 893 of file cloud.c.
References cloud_state_object::chan, cloud_state_object::msg_buf, reboot_request_publish(), REBOOT_TYPE_ERROR, STATE_OPERATIONAL, states, task_wdt_callback(), and task_wdt_util_setup().
Referenced by K_THREAD_DEFINE().
connect_to_cloud()
void connect_to_cloud (void) static
Definition at line 627 of file cloud.c.
Referenced by state_connecting_attempt_entry().
disconnect_from_cloud()
void disconnect_from_cloud (void) static
Definition at line 641 of file cloud.c.
Referenced by cloud_readiness_check_work_fn(), and state_cloud_ready_exit().
fota_boot_confirm()
void fota_boot_confirm (void) static
Confirm successful boot after FOTA update.
Tells MCUboot that the current firmware image is good and should be kept. Must be called after successful boot to prevent rollback. Called once when cloud connection is ready (indicates system is stable).
Definition at line 412 of file cloud.c.
Referenced by nrf_cloud_event_handler().
fota_type_to_str()
const char * fota_type_to_str (enum nrf_cloud_fota_type type) static
Definition at line 348 of file cloud.c.
References cloud_msg::type.
Referenced by nrf_cloud_event_handler(), and on_fota_downloaded().
K_THREAD_DEFINE()
K_THREAD_DEFINE (cloud_thread_id , CONFIG_APP_CLOUD_MODULE_THREAD_STACK_SIZE , cloud_thread , NULL , NULL , NULL , CONFIG_APP_THREAD_PRIORITY_CLOUD , 0 , 0)
References cloud_thread().
K_THREAD_STACK_DEFINE()
K_THREAD_STACK_DEFINE (stack_area , CONFIG_APP_CLOUD_MODULE_WORKQUEUE_STACK_SIZE) static
K_WORK_DELAYABLE_DEFINE()
K_WORK_DELAYABLE_DEFINE (cloud_readiness_check_work , cloud_readiness_check_work_fn) static
References cloud_readiness_check_work_fn().
LOG_MODULE_REGISTER()
LOG_MODULE_REGISTER (cloud , CONFIG_APP_CLOUD_MODULE_LOG_LEVEL)
nrf_cloud_event_handler()
void nrf_cloud_event_handler (const struct nrf_cloud_evt * nrf_cloud_evt) static
Definition at line 505 of file cloud.c.
References CLOUD_READY, cloud_status_publish(), fota_boot_confirm(), FOTA_STATUS_DOWNLOADING, FOTA_STATUS_ERROR, fota_type_to_str(), on_fota_downloaded(), PRIV_CLOUD_DISCONNECTED, and private_cloud_status_publish().
Referenced by cloud_setup().
on_fota_downloaded()
void on_fota_downloaded (enum nrf_cloud_fota_type fota_type) static
Handle FOTA download completion.
Called when FOTA download completes successfully. Publishes final status to LED module and triggers graceful reboot via reboot module.
Parameters
fota_type Type of FOTA update (APP/MODEM/BOOTLOADER)
Definition at line 372 of file cloud.c.
References FOTA_STATUS_ERROR, FOTA_STATUS_READY, fota_type_to_str(), reboot_request_publish(), and REBOOT_TYPE_FOTA.
Referenced by nrf_cloud_event_handler().
priv_internal_cloud_is_disconnected()
bool priv_internal_cloud_is_disconnected (const enum private_cloud_status * status) inline static
Definition at line 261 of file cloud.c.
References PRIV_CLOUD_DISCONNECTED.
Referenced by state_cloud_ready_run(), and state_connecting_run().
priv_internal_cloud_is_ready_timeout()
bool priv_internal_cloud_is_ready_timeout (const enum private_cloud_status * status) inline static
Definition at line 254 of file cloud.c.
References PRIV_CLOUD_READY_TIMEOUT.
Referenced by state_connecting_run().
private_cloud_status_publish()
void private_cloud_status_publish (const enum private_cloud_status status, const k_timeout_t timeout) static
Definition at line 281 of file cloud.c.
References private_cloud_status_to_str(), reboot_request_publish(), and REBOOT_TYPE_ERROR.
Referenced by cloud_readiness_check_work_fn(), and nrf_cloud_event_handler().
private_cloud_status_to_str()
const char * private_cloud_status_to_str (const enum private_cloud_status status) static
Definition at line 268 of file cloud.c.
References PRIV_CLOUD_DISCONNECTED, and PRIV_CLOUD_READY_TIMEOUT.
Referenced by private_cloud_status_publish().
state_cloud_ready_entry()
void state_cloud_ready_entry (void * o) static
Definition at line 822 of file cloud.c.
state_cloud_ready_exit()
void state_cloud_ready_exit (void * o) static
Definition at line 873 of file cloud.c.
References CLOUD_NOT_READY, cloud_status_publish(), and disconnect_from_cloud().
state_cloud_ready_run()
void state_cloud_ready_run (void * o) static
Definition at line 830 of file cloud.c.
References cloud_state_object::chan, cloud_state_object::msg_buf, MSG_TO_REBOOT_MSG_PTR, priv_internal_cloud_is_disconnected(), shutdown_acknowledge_publish(), SHUTDOWN_REQ, STATE_CONNECTING, states, and reboot_msg::type.
state_connecting_attempt_entry()
void state_connecting_attempt_entry (void * o) static
Definition at line 803 of file cloud.c.
References calculate_backoff_time(), cloud_workqueue, connect_to_cloud(), and cloud_state_object::connection_attempts.
state_connecting_entry()
void state_connecting_entry (void * o) static
Definition at line 747 of file cloud.c.
References cloud_state_object::connection_attempts.
state_connecting_exit()
void state_connecting_exit (void * o) static
Definition at line 792 of file cloud.c.
state_connecting_run()
void state_connecting_run (void * o) static
Definition at line 757 of file cloud.c.
References cloud_state_object::chan, cloud_is_ready(), cloud_state_object::msg_buf, MSG_TO_CLOUD_MSG_PTR, priv_internal_cloud_is_disconnected(), priv_internal_cloud_is_ready_timeout(), STATE_CLOUD_READY, STATE_CONNECTING_ATTEMPT, states, and cloud_msg::status.
state_disconnected_entry()
void state_disconnected_entry (void * o) static
Definition at line 722 of file cloud.c.
Referenced by ZBUS_CHAN_DEFINE().
state_disconnected_run()
void state_disconnected_run (void * o) static
Definition at line 730 of file cloud.c.
References cloud_state_object::chan, cloud_state_object::msg_buf, MSG_TO_NETWORK_MSG_PTR, network_is_connected(), STATE_CONNECTING, and states.
Referenced by ZBUS_CHAN_DEFINE().
state_operational_entry()
void state_operational_entry (void * o) static
Definition at line 661 of file cloud.c.
References cloud_workqueue.
Referenced by ZBUS_CHAN_DEFINE().
state_operational_run()
void state_operational_run (void * o) static
Definition at line 674 of file cloud.c.
References cloud_state_object::chan, cloud_state_object::msg_buf, MSG_TO_NETWORK_MSG_PTR, network_is_disconnected(), STATE_DISCONNECTED, and states.
Referenced by ZBUS_CHAN_DEFINE().
state_waiting_for_modem_entry()
void state_waiting_for_modem_entry (void * o) static
Definition at line 691 of file cloud.c.
state_waiting_for_modem_run()
void state_waiting_for_modem_run (void * o) static
Definition at line 699 of file cloud.c.
References cloud_state_object::chan, cloud_setup(), cloud_state_object::msg_buf, MSG_TO_NETWORK_MSG_PTR, network_is_modem_initialized(), reboot_request_publish(), REBOOT_TYPE_ERROR, STATE_DISCONNECTED, and states.
task_wdt_callback()
void task_wdt_callback (int channel_id, void * user_data) static
Definition at line 443 of file cloud.c.
References reboot_request_publish(), and REBOOT_TYPE_ERROR.
ZBUS_CHAN_ADD_OBS() [1/3]
ZBUS_CHAN_ADD_OBS (CLOUD_CHAN , cloud_subscriber , 0)
ZBUS_CHAN_ADD_OBS() [2/3]
ZBUS_CHAN_ADD_OBS (NETWORK_CHAN , cloud_subscriber , 0)
References ADD_OBSERVERS.
ZBUS_CHAN_ADD_OBS() [3/3]
ZBUS_CHAN_ADD_OBS (REBOOT_CHAN , cloud_subscriber , 0)
ZBUS_CHAN_DEFINE() [1/3]
ZBUS_CHAN_DEFINE (CLOUD_CHAN , struct cloud_msg , NULL , NULL , ZBUS_OBSERVERS_EMPTY , ZBUS_MSG_INIT(0))
ZBUS_CHAN_DEFINE() [2/3]
ZBUS_CHAN_DEFINE (FOTA_CHAN , struct fota_msg , NULL , NULL , ZBUS_OBSERVERS_EMPTY , ZBUS_MSG_INIT(0))
ZBUS_CHAN_DEFINE() [3/3]
ZBUS_CHAN_DEFINE (PRIV_CLOUD_CHAN , enum private_cloud_status, NULL , NULL , ZBUS_OBSERVERS(cloud_subscriber) , ZBUS_MSG_INIT(0))
ZBUS_MSG_SUBSCRIBER_DEFINE()
ZBUS_MSG_SUBSCRIBER_DEFINE (cloud_subscriber)
Variable Documentation
cloud_workqueue
struct k_work_q cloud_workqueue static
Definition at line 233 of file cloud.c.
Referenced by state_connecting_attempt_entry(), and state_operational_entry().
states
const struct smf_state states[] static
Initial value:
= {
    [STATE_OPERATIONAL] = SMF_CREATE_STATE(
            state_operational_entry, state_operational_run, NULL,
            NULL,
            &states[STATE_WAITING_FOR_MODEM]),
    [STATE_WAITING_FOR_MODEM] = SMF_CREATE_STATE(
            state_waiting_for_modem_entry, state_waiting_for_modem_run, NULL,
            &states[STATE_OPERATIONAL],
            NULL),
    [STATE_DISCONNECTED] = SMF_CREATE_STATE(
            state_disconnected_entry, state_disconnected_run, NULL,
            &states[STATE_OPERATIONAL],
            NULL),
    [STATE_CONNECTING] = SMF_CREATE_STATE(
            state_connecting_entry, state_connecting_run, state_connecting_exit,
            &states[STATE_OPERATIONAL],
            &states[STATE_CONNECTING_ATTEMPT]),
    [STATE_CONNECTING_ATTEMPT] =
            SMF_CREATE_STATE(state_connecting_attempt_entry, NULL, NULL,
                             &states[STATE_CONNECTING],
                             NULL),
    [STATE_CLOUD_READY] =
            SMF_CREATE_STATE(state_cloud_ready_entry, state_cloud_ready_run,
                             state_cloud_ready_exit,
                             &states[STATE_OPERATIONAL],
                             NULL),
}
Definition at line 173 of file cloud.c.
Referenced by cloud_thread(), message_queue_thread(), network_thread(), reboot_thread(), state_cloud_ready_run(), state_collecting_data_run(), state_connected_run(), state_connecting_run(), state_disconnected_run(), state_disconnected_run(), state_operational_run(), state_operational_run(), state_operational_run(), state_send_msg_attempt_entry(), and state_waiting_for_modem_run().