SolarResult Dinnis Core: modules/energy_pulse/energy_pulse.c File Reference
energy_pulse.c File Reference
#include <zephyr/drivers/gpio.h>
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/settings/settings.h>
#include <zephyr/sys/atomic.h>
#include <zephyr/task_wdt/task_wdt.h>
#include <zephyr/zbus/zbus.h>
#include "energy_pulse_zbus.h"
#include "modules_common.h"
#include "reboot_zbus.h"
#include "task_wdt_util.h"
#include "timing_zbus.h"
Macros
#define ENERGY_PULSE_CH1_KEY CONFIG_APP_ENERGY_PULSE_SETTINGS_SUBTREE "/ch1"
#define ENERGY_PULSE_CH2_KEY CONFIG_APP_ENERGY_PULSE_SETTINGS_SUBTREE "/ch2"
#define ENERGY_PULSE_WH_PER_PULSE 1 /* 0.001 kWh = 1 Wh per pulse */
#define PULSE_CH1_GPIO_NODE DT_PATH(pulses, pulse_one)
#define PULSE_CH2_GPIO_NODE DT_PATH(pulses, pulse_two)
#define CHANNEL_LIST(X)
#define MAX_MSG_SIZE MAX_MSG_SIZE_FROM_LIST(CHANNEL_LIST)
#define ADD_OBSERVERS(_chan, _type)
Functions
LOG_MODULE_REGISTER (energy_pulse, CONFIG_APP_ENERGY_PULSE_MODULE_LOG_LEVEL)
BUILD_ASSERT (CONFIG_APP_ENERGY_PULSE_MODULE_WATCHDOG_TIMEOUT_SECONDS > CONFIG_APP_ENERGY_PULSE_MODULE_MSG_PROCESSING_TIME_SECONDS, "Watchdog timeout must be greater than message processing time")
ZBUS_MSG_SUBSCRIBER_DEFINE (energy_pulse_subscriber)
ZBUS_CHAN_ADD_OBS (DATA_PUBLISH_REQUEST_CHAN, energy_pulse_subscriber, 0)
ZBUS_CHAN_ADD_OBS (REBOOT_CHAN, energy_pulse_subscriber, 0)
ZBUS_CHAN_DEFINE (ENERGY_PULSE_CHAN, struct energy_pulse_msg, NULL, NULL, ZBUS_OBSERVERS_EMPTY, ZBUS_MSG_INIT(0))
static void pulse_gpio_callback (const struct device *dev, struct gpio_callback *cb, uint32_t pins)
GPIO callback for pulse counting.
static void task_wdt_callback (int channel_id, void *user_data)
Watchdog timeout callback.
static int setup_pulse_gpio (const struct gpio_dt_spec *gpio_spec, struct gpio_callback *gpio_cb)
Initialize GPIO for pulse input.
static int energy_pulse_gpio_init (void)
Initialize GPIO for both pulse input channels.
static void energy_pulse_msg_publish (void)
Publish energy pulse data to ZBUS.
static int energy_pulse_settings_set (const char *name, size_t len, settings_read_cb read_cb, void *cb_arg)
Settings handler callback for loading energy pulse data.
SETTINGS_STATIC_HANDLER_DEFINE (energy_pulse, CONFIG_APP_ENERGY_PULSE_SETTINGS_SUBTREE, NULL, energy_pulse_settings_set, NULL, NULL)
static int save_energy_channel (const char *key, const atomic_val_t value)
Save a single energy channel to persistent storage.
static int save_energy_counters (void)
Save energy counters to persistent storage.
static int energy_pulse_load_settings (void)
Initialize energy pulse data from persistent storage.
static void energy_pulse_thread (void)
Main energy pulse thread.
K_THREAD_DEFINE (energy_pulse_thread_id, CONFIG_APP_ENERGY_PULSE_MODULE_THREAD_STACK_SIZE, energy_pulse_thread, NULL, NULL, NULL, CONFIG_APP_THREAD_PRIORITY_ENERGY_PULSE, 0, 0)
Variables
static const struct gpio_dt_spec pulse_ch1_gpio
static const struct gpio_dt_spec pulse_ch2_gpio
static atomic_t pulse_energy_ch1 = ATOMIC_INIT(0)
static atomic_t pulse_energy_ch2 = ATOMIC_INIT(0)
static atomic_t has_new_pulses_since_save = ATOMIC_INIT(0)
static struct gpio_callback gpio_cb
Macro Definition Documentation
ADD_OBSERVERS
#define ADD_OBSERVERS (_chan, _type)
Value:
    ZBUS_CHAN_ADD_OBS(_chan, energy_pulse_subscriber, 0);
Definition at line 67 of file energy_pulse.c.
CHANNEL_LIST
#define CHANNEL_LIST (X)
Value:
    X(DATA_PUBLISH_REQUEST_CHAN, struct timing_event_msg) \
    X(REBOOT_CHAN, struct reboot_msg)
Definition at line 59 of file energy_pulse.c.
ENERGY_PULSE_CH1_KEY
#define ENERGY_PULSE_CH1_KEY CONFIG_APP_ENERGY_PULSE_SETTINGS_SUBTREE "/ch1"
Definition at line 39 of file energy_pulse.c.
Referenced by save_energy_counters().
ENERGY_PULSE_CH2_KEY
#define ENERGY_PULSE_CH2_KEY CONFIG_APP_ENERGY_PULSE_SETTINGS_SUBTREE "/ch2"
Definition at line 40 of file energy_pulse.c.
Referenced by save_energy_counters().
ENERGY_PULSE_WH_PER_PULSE
#define ENERGY_PULSE_WH_PER_PULSE 1 /* 0.001 kWh = 1 Wh per pulse */
Definition at line 43 of file energy_pulse.c.
Referenced by energy_pulse_msg_publish().
MAX_MSG_SIZE
#define MAX_MSG_SIZE MAX_MSG_SIZE_FROM_LIST(CHANNEL_LIST)
Definition at line 64 of file energy_pulse.c.
PULSE_CH1_GPIO_NODE
#define PULSE_CH1_GPIO_NODE DT_PATH(pulses, pulse_one)
Definition at line 46 of file energy_pulse.c.
PULSE_CH2_GPIO_NODE
#define PULSE_CH2_GPIO_NODE DT_PATH(pulses, pulse_two)
Definition at line 47 of file energy_pulse.c.
Function Documentation
BUILD_ASSERT()
BUILD_ASSERT (CONFIG_APP_ENERGY_PULSE_MODULE_WATCHDOG_TIMEOUT_SECONDS , CONFIG_APP_ENERGY_PULSE_MODULE_MSG_PROCESSING_TIME_SECONDS , "Watchdog timeout must be greater than message processing time")
energy_pulse_gpio_init()
int energy_pulse_gpio_init (void) static
Initialize GPIO for both pulse input channels.
Returns
0 on success, negative errno on error
Definition at line 158 of file energy_pulse.c.
References gpio_cb, pulse_ch1_gpio, pulse_ch2_gpio, pulse_gpio_callback(), and setup_pulse_gpio().
Referenced by energy_pulse_thread().
energy_pulse_load_settings()
int energy_pulse_load_settings (void) static
Initialize energy pulse data from persistent storage.
Initializes the settings subsystem and loads energy pulse counters from persistent storage using the registered settings handler.
Returns
0 on success, negative errno on error
Definition at line 427 of file energy_pulse.c.
References has_new_pulses_since_save, pulse_energy_ch1, and pulse_energy_ch2.
Referenced by energy_pulse_thread().
energy_pulse_msg_publish()
void energy_pulse_msg_publish (void) static
Publish energy pulse data to ZBUS.
Atomically reads the pulse counters, converts to Wh (int32_t, no FPU!), and publishes the data with current timestamp to the ENERGY_PULSE_CHAN.
Definition at line 191 of file energy_pulse.c.
References ENERGY_PULSE_WH_PER_PULSE, pulse_energy_ch1, energy_pulse_msg::pulse_energy_ch1_wh, pulse_energy_ch2, energy_pulse_msg::pulse_energy_ch2_wh, and energy_pulse_msg::uptime_ms.
Referenced by energy_pulse_thread().
energy_pulse_settings_set()
int energy_pulse_settings_set (const char * name, size_t len, settings_read_cb read_cb, void * cb_arg) static
Settings handler callback for loading energy pulse data.
Called by settings_load() when restoring data from persistent storage. Parses the key name and loads the corresponding channel data.
Parameters
name Setting name (without subtree prefix, e.g., "ch1" or "ch2")
len Length of data to read
read_cb Callback function to read data from backend
cb_arg Argument to pass to read_cb
Returns
0 on success, -ENOENT if key not found, negative errno on error
Definition at line 304 of file energy_pulse.c.
References pulse_energy_ch1, pulse_energy_ch2, and value.
Referenced by SETTINGS_STATIC_HANDLER_DEFINE().
energy_pulse_thread()
void energy_pulse_thread (void) static
Main energy pulse thread.
Initializes the module, monitors trigger messages and feeds watchdog timer.
Definition at line 465 of file energy_pulse.c.
References energy_pulse_gpio_init(), energy_pulse_load_settings(), energy_pulse_msg_publish(), MAX_MSG_SIZE, MSG_TO_REBOOT_MSG_PTR, MSG_TO_TIMING_EVENT_MSG_PTR, save_energy_counters(), shutdown_acknowledge_publish(), SHUTDOWN_REQ, task_wdt_callback(), task_wdt_util_setup(), reboot_msg::type, and timing_event_msg::uptime_ms.
Referenced by K_THREAD_DEFINE().
K_THREAD_DEFINE()
K_THREAD_DEFINE (energy_pulse_thread_id , CONFIG_APP_ENERGY_PULSE_MODULE_THREAD_STACK_SIZE , energy_pulse_thread , NULL , NULL , NULL , CONFIG_APP_THREAD_PRIORITY_ENERGY_PULSE , 0 , 0)
References energy_pulse_thread().
LOG_MODULE_REGISTER()
LOG_MODULE_REGISTER (energy_pulse , CONFIG_APP_ENERGY_PULSE_MODULE_LOG_LEVEL)
pulse_gpio_callback()
void pulse_gpio_callback (const struct device * dev, struct gpio_callback * cb, uint32_t pins) static
GPIO callback for pulse counting.
Triggered on rising edge of pulse input pins. Atomically increments the pulse counter for the corresponding channel.
Parameters
dev GPIO device (unused)
cb GPIO callback structure
pins Pin mask indicating which pins triggered the interrupt
Definition at line 242 of file energy_pulse.c.
References has_new_pulses_since_save, pulse_ch1_gpio, pulse_ch2_gpio, pulse_energy_ch1, and pulse_energy_ch2.
Referenced by energy_pulse_gpio_init(), and ZBUS_CHAN_DEFINE().
save_energy_channel()
int save_energy_channel (const char * key, const atomic_val_t value) static
Save a single energy channel to persistent storage.
Parameters
key Settings key
value Pulse count value
Returns
0 on success, negative errno on error
Definition at line 367 of file energy_pulse.c.
References value.
Referenced by save_energy_counters().
save_energy_counters()
int save_energy_counters (void) static
Save energy counters to persistent storage.
Only saves if there are new pulses since the last save operation. This prevents unnecessary flash writes and extends flash lifetime.
Returns
0 on success, negative errno on error
Definition at line 388 of file energy_pulse.c.
References ENERGY_PULSE_CH1_KEY, ENERGY_PULSE_CH2_KEY, has_new_pulses_since_save, pulse_energy_ch1, pulse_energy_ch2, and save_energy_channel().
Referenced by energy_pulse_thread().
SETTINGS_STATIC_HANDLER_DEFINE()
SETTINGS_STATIC_HANDLER_DEFINE (energy_pulse , CONFIG_APP_ENERGY_PULSE_SETTINGS_SUBTREE , NULL , energy_pulse_settings_set , NULL , NULL)
References energy_pulse_settings_set().
setup_pulse_gpio()
int setup_pulse_gpio (const struct gpio_dt_spec * gpio_spec, struct gpio_callback * gpio_cb) static
Initialize GPIO for pulse input.
Parameters
gpio_spec GPIO device tree specification
gpio_cb GPIO callback structure
Returns
0 on success, negative errno on error
Definition at line 122 of file energy_pulse.c.
References gpio_cb, and setup_pulse_gpio().
Referenced by energy_pulse_gpio_init(), and setup_pulse_gpio().
task_wdt_callback()
void task_wdt_callback (int channel_id, void * user_data) static
Watchdog timeout callback.
Parameters
channel_id Watchdog channel ID
user_data User data (thread ID)
Definition at line 273 of file energy_pulse.c.
ZBUS_CHAN_ADD_OBS() [1/2]
ZBUS_CHAN_ADD_OBS (DATA_PUBLISH_REQUEST_CHAN , energy_pulse_subscriber , 0)
References ADD_OBSERVERS.
ZBUS_CHAN_ADD_OBS() [2/2]
ZBUS_CHAN_ADD_OBS (REBOOT_CHAN , energy_pulse_subscriber , 0)
ZBUS_CHAN_DEFINE()
ZBUS_CHAN_DEFINE (ENERGY_PULSE_CHAN , struct energy_pulse_msg , NULL , NULL , ZBUS_OBSERVERS_EMPTY , ZBUS_MSG_INIT(0))
References pulse_gpio_callback(), task_wdt_callback(), and ZBUS_CHAN_DEFINE().
ZBUS_MSG_SUBSCRIBER_DEFINE()
ZBUS_MSG_SUBSCRIBER_DEFINE (energy_pulse_subscriber)
Variable Documentation
gpio_cb
struct gpio_callback gpio_cb static
Definition at line 107 of file energy_pulse.c.
Referenced by energy_pulse_gpio_init(), and setup_pulse_gpio().
has_new_pulses_since_save
atomic_t has_new_pulses_since_save = ATOMIC_INIT(0) static
Definition at line 104 of file energy_pulse.c.
Referenced by energy_pulse_load_settings(), pulse_gpio_callback(), and save_energy_counters().
pulse_ch1_gpio
const struct gpio_dt_spec pulse_ch1_gpio static
Initial value:
=
        GPIO_DT_SPEC_GET( DT_PATH(pulses, pulse_one) , gpios)
Definition at line 94 of file energy_pulse.c.
Referenced by energy_pulse_gpio_init(), and pulse_gpio_callback().
pulse_ch2_gpio
const struct gpio_dt_spec pulse_ch2_gpio static
Initial value:
=
        GPIO_DT_SPEC_GET( DT_PATH(pulses, pulse_two) , gpios)
Definition at line 96 of file energy_pulse.c.
Referenced by energy_pulse_gpio_init(), and pulse_gpio_callback().
pulse_energy_ch1
atomic_t pulse_energy_ch1 = ATOMIC_INIT(0) static
Definition at line 100 of file energy_pulse.c.
Referenced by energy_pulse_load_settings(), energy_pulse_msg_publish(), energy_pulse_settings_set(), pulse_gpio_callback(), and save_energy_counters().
pulse_energy_ch2
atomic_t pulse_energy_ch2 = ATOMIC_INIT(0) static
Definition at line 101 of file energy_pulse.c.
Referenced by energy_pulse_load_settings(), energy_pulse_msg_publish(), energy_pulse_settings_set(), pulse_gpio_callback(), and save_energy_counters().