SolarResult Dinnis Core: Cloud - API Referentie
Cloud - API Referentie
nRF Cloud connectivity and data transmission.
Data Structures
struct cloud_msg
Macros
#define MSG_TO_CLOUD_MSG_PTR(_msg)
Enumerations
enum cloud_msg_type { CLOUD_STATUS = 0x1 }
enum cloud_status {
CLOUD_NOT_READY = 0x1 ,
CLOUD_READY
}
Functions
ZBUS_CHAN_DECLARE (CLOUD_CHAN)
static bool cloud_is_ready (const struct cloud_msg *msg)
static bool cloud_is_not_ready (const struct cloud_msg *msg)
Detailed Description
nRF Cloud connectivity and data transmission.
For complete documentation, see Cloud Module - Documentatie
Macro Definition Documentation
MSG_TO_CLOUD_MSG_PTR
#define MSG_TO_CLOUD_MSG_PTR (_msg)
Value:
((const struct cloud_msg *)(_msg))
Definition at line 24 of file cloud_zbus.h.
Referenced by led_thread(), state_connecting_run(), and state_operational_run().
Enumeration Type Documentation
cloud_msg_type
enum cloud_msg_type
Enumerator
CLOUD_STATUS
Definition at line 26 of file cloud_zbus.h.
cloud_status
enum cloud_status
Enumerator
CLOUD_NOT_READY
CLOUD_READY
Definition at line 31 of file cloud_zbus.h.
Function Documentation
cloud_is_not_ready()
bool cloud_is_not_ready (const struct cloud_msg * msg) inline static
Definition at line 53 of file cloud_zbus.h.
References CLOUD_NOT_READY, CLOUD_STATUS, cloud_msg::status, and cloud_msg::type.
Referenced by process_cloud_msg().
cloud_is_ready()
bool cloud_is_ready (const struct cloud_msg * msg) inline static
Definition at line 48 of file cloud_zbus.h.
References CLOUD_READY, CLOUD_STATUS, cloud_msg::status, and cloud_msg::type.
Referenced by process_cloud_msg(), state_connecting_run(), and update_cloud_status().
ZBUS_CHAN_DECLARE()
ZBUS_CHAN_DECLARE (CLOUD_CHAN)