SolarResult Dinnis Core: Network - API Referentie
Network - API Referentie
Cellular modem and LTE connectivity management.
Data Structures
struct network_msg
Macros
#define MSG_TO_NETWORK_MSG_PTR(_msg)
Enumerations
enum network_msg_type { NETWORK_STATUS = 0x1 }
enum network_status {
NETWORK_MODEM_INIT = 0x1 ,
NETWORK_DISCONNECTED ,
NETWORK_CONNECTED
}
Functions
ZBUS_CHAN_DECLARE (NETWORK_CHAN)
static bool network_is_connected (const struct network_msg *msg)
static bool network_is_disconnected (const struct network_msg *msg)
static bool network_is_modem_initialized (const struct network_msg *msg)
Detailed Description
Cellular modem and LTE connectivity management.
For complete documentation, see Network Module - Documentatie
Macro Definition Documentation
MSG_TO_NETWORK_MSG_PTR
#define MSG_TO_NETWORK_MSG_PTR (_msg)
Value:
((const struct network_msg *)(_msg))
Definition at line 24 of file network_zbus.h.
Referenced by led_thread(), state_connected_run(), state_disconnected_run(), state_disconnected_run(), state_operational_run(), state_operational_run(), and state_waiting_for_modem_run().
Enumeration Type Documentation
network_msg_type
enum network_msg_type
Enumerator
NETWORK_STATUS
Definition at line 26 of file network_zbus.h.
network_status
enum network_status
Enumerator
NETWORK_MODEM_INIT
NETWORK_DISCONNECTED
NETWORK_CONNECTED
Definition at line 31 of file network_zbus.h.
Function Documentation
network_is_connected()
bool network_is_connected (const struct network_msg * msg) inline static
Definition at line 51 of file network_zbus.h.
References NETWORK_CONNECTED, NETWORK_STATUS, network_msg::status, and network_msg::type.
Referenced by process_network_msg(), state_disconnected_run(), state_disconnected_run(), and state_operational_run().
network_is_disconnected()
bool network_is_disconnected (const struct network_msg * msg) inline static
Definition at line 56 of file network_zbus.h.
References NETWORK_DISCONNECTED, NETWORK_STATUS, network_msg::status, and network_msg::type.
Referenced by process_network_msg(), state_connected_run(), state_disconnected_run(), state_operational_run(), and state_operational_run().
network_is_modem_initialized()
bool network_is_modem_initialized (const struct network_msg * msg) inline static
Definition at line 61 of file network_zbus.h.
References NETWORK_MODEM_INIT, NETWORK_STATUS, network_msg::status, and network_msg::type.
Referenced by process_network_msg(), and state_waiting_for_modem_run().
ZBUS_CHAN_DECLARE()
ZBUS_CHAN_DECLARE (NETWORK_CHAN)