SolarResult Dinnis Core: Reboot - API Referentie
Reboot - API Referentie
Coordinated system shutdown and reboot management.
Data Structures
struct reboot_msg
Reboot message structure.
Macros
#define ZBUS_REBOOT_CHAN_FATAL_ERROR_HANDLE()
#define MSG_TO_REBOOT_MSG_PTR(_msg)
Enumerations
enum reboot_msg_type {
REBOOT_REQ = 0x1 ,
SHUTDOWN_REQ ,
SHUTDOWN_ACK
}
Reboot message types.
enum reboot_type {
REBOOT_TYPE_FOTA = 0x1 ,
REBOOT_TYPE_ERROR
}
Reboot types.
Functions
ZBUS_CHAN_DECLARE (REBOOT_CHAN)
void reboot_request_publish (const enum reboot_type type)
Publish reboot request to ZBUS.
void shutdown_acknowledge_publish (const struct zbus_observer *observer)
Publish shutdown acknowledgment to ZBUS.
void shutdown_request_publish (void)
Publish shutdown request to ZBUS.
Detailed Description
Coordinated system shutdown and reboot management.
For complete documentation, see reboot_doc
Macro Definition Documentation
MSG_TO_REBOOT_MSG_PTR
#define MSG_TO_REBOOT_MSG_PTR (_msg)
Value:
((const struct reboot_msg *)(_msg))
Definition at line 48 of file reboot_zbus.h.
Referenced by energy_pulse_thread(), state_cloud_ready_run(), and state_operational_run().
ZBUS_REBOOT_CHAN_FATAL_ERROR_HANDLE
#define ZBUS_REBOOT_CHAN_FATAL_ERROR_HANDLE ()
Value:
    do {                                                                        \
        LOG_ERR("Fatal error in reboot channel, forcing reboot in 10 seconds"); \
        LOG_PANIC();                                                            \
        k_sleep(K_SECONDS(10));                                                 \
        __ASSERT(false, "ZBUS_REBOOT_CHAN_FATAL_ERROR_HANDLE macro called");    \
        sys_reboot(SYS_REBOOT_WARM);                                            \
        CODE_UNREACHABLE;                                                       \
    } while (0)
Definition at line 36 of file reboot_zbus.h.
Referenced by reboot_request_publish().
Enumeration Type Documentation
reboot_msg_type
enum reboot_msg_type
Reboot message types.
Enumerator
REBOOT_REQ
SHUTDOWN_REQ
SHUTDOWN_ACK
Definition at line 53 of file reboot_zbus.h.
reboot_type
enum reboot_type
Reboot types.
Enumerator
REBOOT_TYPE_FOTA
REBOOT_TYPE_ERROR
Definition at line 62 of file reboot_zbus.h.
Function Documentation
reboot_request_publish()
void reboot_request_publish (const enum reboot_type type)
Publish reboot request to ZBUS.
Parameters
type Type of reboot requested
Definition at line 63 of file reboot_zbus.c.
References get_reboot_type_str(), REBOOT_REQ, reboot_msg::type, and ZBUS_REBOOT_CHAN_FATAL_ERROR_HANDLE.
Referenced by cloud_status_publish(), cloud_thread(), connectivity_event_handler(), message_queue_thread(), modem_lib_init_callback(), network_status_publish(), network_thread(), on_fota_downloaded(), p_one_thread(), private_cloud_status_publish(), state_operational_entry(), state_waiting_for_modem_run(), task_wdt_callback(), task_wdt_callback(), task_wdt_callback(), task_wdt_callback(), task_wdt_callback(), and task_wdt_callback().
shutdown_acknowledge_publish()
void shutdown_acknowledge_publish (const struct zbus_observer * observer)
Publish shutdown acknowledgment to ZBUS.
Parameters
observer Observer acknowledging shutdown
Definition at line 88 of file reboot_zbus.c.
References reboot_msg::observer, and SHUTDOWN_ACK.
Referenced by energy_pulse_thread(), and state_cloud_ready_run().
shutdown_request_publish()
void shutdown_request_publish (void)
Publish shutdown request to ZBUS.
Definition at line 116 of file reboot_zbus.c.
References SHUTDOWN_REQ.
Referenced by handle_reboot_request().
ZBUS_CHAN_DECLARE()
ZBUS_CHAN_DECLARE (REBOOT_CHAN)