SolarResult Dinnis Core: modules/led/led.c File Reference
led.c File Reference
#include <zephyr/device.h>
#include <zephyr/drivers/led.h>
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/zbus/zbus.h>
#include "cloud_zbus.h"
#include "fota_zbus.h"
#include "led.h"
#include "modules_common.h"
#include "network_zbus.h"
#include "task_wdt_util.h"
#include "trigger_zbus.h"
Data Structures
struct led_pattern
struct led_module_state
Macros
#define LED_PWM_NODE_ID DT_COMPAT_GET_ANY_STATUS_OKAY(pwm_leds)
#define CHANNEL_LIST(X)
#define MAX_MSG_SIZE MAX_MSG_SIZE_FROM_LIST(CHANNEL_LIST)
#define ADD_OBSERVERS(_chan, _type)
Enumerations
enum led_channel {
LED_COLOR_RED = DT_NODE_CHILD_IDX(DT_CHILD(DT_COMPAT_GET_ANY_STATUS_OKAY(pwm_leds) , red_led)) ,
LED_COLOR_GRN = DT_NODE_CHILD_IDX(DT_CHILD(DT_COMPAT_GET_ANY_STATUS_OKAY(pwm_leds) , green_led)) ,
LED_COLOR_BLU = DT_NODE_CHILD_IDX(DT_CHILD(DT_COMPAT_GET_ANY_STATUS_OKAY(pwm_leds) , blue_led))
}
Functions
LOG_MODULE_REGISTER (led, CONFIG_LED_MODULE_LOG_LEVEL)
BUILD_ASSERT (CONFIG_LED_MODULE_WATCHDOG_TIMEOUT_SECONDS > CONFIG_LED_MODULE_MSG_PROCESSING_TIME_SECONDS, "LED watchdog timeout must be greater than message processing time")
ZBUS_MSG_SUBSCRIBER_DEFINE (led_subscriber)
ZBUS_CHAN_ADD_OBS (NETWORK_CHAN, led_subscriber, 0)
ZBUS_CHAN_ADD_OBS (CLOUD_CHAN, led_subscriber, 0)
ZBUS_CHAN_ADD_OBS (FOTA_CHAN, led_subscriber, 0)
ZBUS_CHAN_ADD_OBS (TRIGGER_CHAN, led_subscriber, 0)
static void task_wdt_callback (int channel_id, void *user_data)
static void ledblink_handler (struct k_work *work)
LED blink work handler.
static void acquiring_timeout_handler (struct k_work *work)
Acquiring timeout handler.
static void update_led_pattern (struct led_module_state *state)
Update LED pattern based on current system state.
static K_WORK_DELAYABLE_DEFINE (work_ledblink, ledblink_handler)
static void set_led_color (uint8_t red, uint8_t green, uint8_t blue)
Set LED hardware to specific colors.
static void apply_led_pattern (const struct led_pattern *pattern)
Apply LED pattern.
static enum led_status_priority determine_led_status (const struct led_module_state *state)
Determine LED status based on current system state.
static void process_network_msg (struct led_module_state *state, const struct network_msg *msg)
Process network status message.
static void process_cloud_msg (struct led_module_state *state, const struct cloud_msg *msg)
Process cloud status message.
static void process_trigger_msg (struct led_module_state *state, const struct trigger_msg *trigger)
Process trigger message.
static void process_fota_msg (struct led_module_state *state, const struct fota_msg *fota)
Process FOTA message.
static void led_thread (void)
Main LED thread.
K_THREAD_DEFINE (led_thread_id, CONFIG_LED_MODULE_THREAD_STACK_SIZE, led_thread, NULL, NULL, NULL, CONFIG_APP_THREAD_PRIORITY_LED, 0, 0)
static int led_init (void)
Initialize LED module.
SYS_INIT (led_init, APPLICATION, CONFIG_LED_MODULE_INIT_PRIORITY)
Variables
static const struct led_pattern led_patterns []
static const struct device * led_pwm = DEVICE_DT_GET(DT_COMPAT_GET_ANY_STATUS_OKAY(pwm_leds))
static bool led_on_state = false
static enum led_status_priority current_status = LED_STATUS_WAIT
Macro Definition Documentation
ADD_OBSERVERS
#define ADD_OBSERVERS (_chan, _type)
Value:
ZBUS_CHAN_ADD_OBS(_chan, led_subscriber, 0);
Definition at line 127 of file led.c.
CHANNEL_LIST
#define CHANNEL_LIST (X)
Value:
    X(NETWORK_CHAN, struct network_msg) \
    X(CLOUD_CHAN, struct cloud_msg)     \
    X(FOTA_CHAN, struct fota_msg)       \
    X(TRIGGER_CHAN, struct trigger_msg)
Definition at line 117 of file led.c.
LED_PWM_NODE_ID
#define LED_PWM_NODE_ID DT_COMPAT_GET_ANY_STATUS_OKAY(pwm_leds)
Definition at line 38 of file led.c.
MAX_MSG_SIZE
#define MAX_MSG_SIZE MAX_MSG_SIZE_FROM_LIST(CHANNEL_LIST)
Definition at line 124 of file led.c.
Enumeration Type Documentation
led_channel
enum led_channel
Enumerator
LED_COLOR_RED
LED_COLOR_GRN
LED_COLOR_BLU
Definition at line 41 of file led.c.
Function Documentation
acquiring_timeout_handler()
void acquiring_timeout_handler (struct k_work * work) static
Acquiring timeout handler.
Called when acquisition timeout expires (10 seconds). Returns to appropriate LED pattern based on system status.
Parameters
work Pointer to work item
Definition at line 346 of file led.c.
References led_module_state::acquiring, led_module_state::acquiring_timeout, and update_led_pattern().
Referenced by led_thread().
apply_led_pattern()
void apply_led_pattern (const struct led_pattern * pattern) static
Apply LED pattern.
Starts displaying the given LED pattern.
Parameters
pattern Pointer to LED pattern to display
Definition at line 218 of file led.c.
References led_pattern::blue, led_pattern::green, led_on_state, led_pattern::period, led_pattern::red, and set_led_color().
Referenced by led_thread(), and update_led_pattern().
BUILD_ASSERT()
BUILD_ASSERT (CONFIG_LED_MODULE_WATCHDOG_TIMEOUT_SECONDS , CONFIG_LED_MODULE_MSG_PROCESSING_TIME_SECONDS , "LED watchdog timeout must be greater than message processing time")
determine_led_status()
enum led_status_priority determine_led_status (const struct led_module_state * state) static
Determine LED status based on current system state.
Parameters
state Pointer to module state
Returns
LED status priority to display
Definition at line 245 of file led.c.
References led_module_state::acquiring, led_module_state::cloud_ready, led_module_state::fota_active, led_module_state::fota_error, LED_STATUS_ACQUIRING, LED_STATUS_CLOUD_ERROR, LED_STATUS_FOTA, LED_STATUS_FOTA_ERROR, LED_STATUS_IDLE, LED_STATUS_NETWORK_ERROR, LED_STATUS_WAIT, led_module_state::modem_initialized, and led_module_state::network_connected.
Referenced by update_led_pattern().
K_THREAD_DEFINE()
K_THREAD_DEFINE (led_thread_id , CONFIG_LED_MODULE_THREAD_STACK_SIZE , led_thread , NULL , NULL , NULL , CONFIG_APP_THREAD_PRIORITY_LED , 0 , 0)
References led_thread().
K_WORK_DELAYABLE_DEFINE()
K_WORK_DELAYABLE_DEFINE (work_ledblink , ledblink_handler) static
References ledblink_handler().
led_init()
int led_init (void) static
Initialize LED module.
Verifies LED PWM device is ready.
Returns
0 on success, negative errno on error
Definition at line 576 of file led.c.
References led_pwm.
Referenced by SYS_INIT().
led_thread()
void led_thread (void) static
Main LED thread.
Processes ZBUS messages and updates LED pattern based on system state.
Definition at line 482 of file led.c.
References led_module_state::acquiring_timeout, acquiring_timeout_handler(), apply_led_pattern(), current_status, led_patterns, MAX_MSG_SIZE, MSG_TO_CLOUD_MSG_PTR, MSG_TO_FOTA_MSG_PTR, MSG_TO_NETWORK_MSG_PTR, MSG_TO_TRIGGER_MSG_PTR, process_cloud_msg(), process_fota_msg(), process_network_msg(), process_trigger_msg(), task_wdt_callback(), task_wdt_util_setup(), and update_led_pattern().
Referenced by K_THREAD_DEFINE().
ledblink_handler()
void ledblink_handler (struct k_work * work) static
LED blink work handler.
Toggles LED state according to current pattern period.
Parameters
work Pointer to work item (unused)
Definition at line 315 of file led.c.
References led_pattern::blue, current_status, led_pattern::green, led_on_state, led_patterns, led_pattern::period, led_pattern::red, and set_led_color().
Referenced by K_WORK_DELAYABLE_DEFINE().
LOG_MODULE_REGISTER()
LOG_MODULE_REGISTER (led , CONFIG_LED_MODULE_LOG_LEVEL)
process_cloud_msg()
void process_cloud_msg (struct led_module_state * state, const struct cloud_msg * msg) static
Process cloud status message.
Parameters
state Pointer to module state
msg Pointer to cloud message
Definition at line 395 of file led.c.
References cloud_is_not_ready(), cloud_is_ready(), and led_module_state::cloud_ready.
Referenced by led_thread().
process_fota_msg()
void process_fota_msg (struct led_module_state * state, const struct fota_msg * fota) static
Process FOTA message.
Updates LED pattern based on FOTA download status.
Parameters
state Pointer to module state
fota FOTA message with status
Definition at line 438 of file led.c.
References led_module_state::fota_active, led_module_state::fota_error, FOTA_STATUS_DOWNLOADING, FOTA_STATUS_ERROR, FOTA_STATUS_IDLE, FOTA_STATUS_READY, and fota_msg::status.
Referenced by led_thread().
process_network_msg()
void process_network_msg (struct led_module_state * state, const struct network_msg * msg) static
Process network status message.
Parameters
state Pointer to module state
msg Pointer to network message
Definition at line 370 of file led.c.
References led_module_state::acquiring, led_module_state::acquiring_timeout, led_module_state::modem_initialized, led_module_state::network_connected, network_is_connected(), network_is_disconnected(), and network_is_modem_initialized().
Referenced by led_thread().
process_trigger_msg()
void process_trigger_msg (struct led_module_state * state, const struct trigger_msg * trigger) static
Process trigger message.
Starts acquisition indication for 10 seconds.
Parameters
state Pointer to module state
trigger Trigger message with timestamp
Definition at line 413 of file led.c.
References led_module_state::acquiring, led_module_state::acquiring_timeout, and trigger_msg::timestamp_ms.
Referenced by led_thread().
set_led_color()
void set_led_color (uint8_t red, uint8_t green, uint8_t blue) static
Set LED hardware to specific colors.
Parameters
red Red brightness (0-100)
green Green brightness (0-100)
blue Blue brightness (0-100)
Definition at line 204 of file led.c.
References LED_COLOR_BLU, LED_COLOR_GRN, LED_COLOR_RED, and led_pwm.
Referenced by apply_led_pattern(), and ledblink_handler().
SYS_INIT()
SYS_INIT (led_init , APPLICATION , CONFIG_LED_MODULE_INIT_PRIORITY)
References led_init().
task_wdt_callback()
void task_wdt_callback (int channel_id, void * user_data) static
Definition at line 139 of file led.c.
References task_wdt_callback().
update_led_pattern()
void update_led_pattern (struct led_module_state * state) static
Update LED pattern based on current system state.
Determines the appropriate LED pattern and applies it if changed.
Parameters
state Pointer to module state
Definition at line 290 of file led.c.
References apply_led_pattern(), current_status, determine_led_status(), and led_patterns.
Referenced by acquiring_timeout_handler(), and led_thread().
ZBUS_CHAN_ADD_OBS() [1/4]
ZBUS_CHAN_ADD_OBS (CLOUD_CHAN , led_subscriber , 0)
ZBUS_CHAN_ADD_OBS() [2/4]
ZBUS_CHAN_ADD_OBS (FOTA_CHAN , led_subscriber , 0)
ZBUS_CHAN_ADD_OBS() [3/4]
ZBUS_CHAN_ADD_OBS (NETWORK_CHAN , led_subscriber , 0)
References ADD_OBSERVERS.
ZBUS_CHAN_ADD_OBS() [4/4]
ZBUS_CHAN_ADD_OBS (TRIGGER_CHAN , led_subscriber , 0)
ZBUS_MSG_SUBSCRIBER_DEFINE()
ZBUS_MSG_SUBSCRIBER_DEFINE (led_subscriber)
Variable Documentation
current_status
enum led_status_priority current_status = LED_STATUS_WAIT static
Definition at line 189 of file led.c.
Referenced by led_thread(), ledblink_handler(), and update_led_pattern().
led_on_state
bool led_on_state = false static
Definition at line 188 of file led.c.
Referenced by apply_led_pattern(), and ledblink_handler().
led_patterns
const struct led_pattern led_patterns[] static
Definition at line 56 of file led.c.
Referenced by led_thread(), ledblink_handler(), and update_led_pattern().
led_pwm
const struct device* led_pwm = DEVICE_DT_GET(DT_COMPAT_GET_ANY_STATUS_OKAY(pwm_leds)) static
Definition at line 182 of file led.c.
Referenced by led_init(), and set_led_color().