SolarResult Dinnis Core: modules/message_queue/message_queue.c File Reference
message_queue.c File Reference
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/smf.h>
#include <zephyr/sys/reboot.h>
#include <zephyr/task_wdt/task_wdt.h>
#include <zephyr/zbus/zbus.h>
#include <net/nrf_cloud.h>
#include <net/nrf_cloud_codec.h>
#include <net/nrf_cloud_defs.h>
#include <modem/lte_lc.h>
#include <date_time.h>
#include "cloud_zbus.h"
#include "energy_pulse_zbus.h"
#include "message_queue_zbus.h"
#include "modules_common.h"
#include "network_zbus.h"
#include "p_one_zbus.h"
#include "reboot_zbus.h"
#include "task_wdt_util.h"
#include "timing_zbus.h"
Data Structures
struct message_queue_state_object
Macros
#define CHANNEL_LIST(X)
#define MAX_MSG_SIZE MAX_MSG_SIZE_FROM_LIST(CHANNEL_LIST)
#define ADD_OBSERVERS(_chan, _type)
#define TIME_RESYNC_INTERVAL_MS (6 * 60 * 60 * 1000)
#define COLLECTION_TIMEOUT_MS 1000
#define MAX_MSGS_PER_CYCLE 10
Enumerations
enum message_queue_state {
STATE_OPERATIONAL ,
STATE_COLLECTING_DATA ,
STATE_SEND_MSG_ATTEMPT
}
Functions
LOG_MODULE_REGISTER (message_queue, CONFIG_APP_MESSAGE_QUEUE_MODULE_LOG_LEVEL)
BUILD_ASSERT (CONFIG_APP_MESSAGE_QUEUE_MODULE_WATCHDOG_TIMEOUT_SECONDS > CONFIG_APP_MESSAGE_QUEUE_MODULE_MSG_PROCESSING_TIME_SECONDS, "Watchdog timeout must be greater than message processing time")
ZBUS_MSG_SUBSCRIBER_DEFINE (message_queue_subscriber)
ZBUS_CHAN_ADD_OBS (CLOUD_CHAN, message_queue_subscriber, 0)
ZBUS_CHAN_ADD_OBS (NETWORK_CHAN, message_queue_subscriber, 0)
ZBUS_CHAN_ADD_OBS (P_ONE_CHAN, message_queue_subscriber, 0)
ZBUS_CHAN_ADD_OBS (ENERGY_PULSE_CHAN, message_queue_subscriber, 0)
ZBUS_CHAN_ADD_OBS (DATA_PUBLISH_REQUEST_CHAN, message_queue_subscriber, 0)
ZBUS_CHAN_ADD_OBS (DATA_SEND_REQUEST_CHAN, message_queue_subscriber, 0)
static void state_operational_entry (void *o)
Entry function for OPERATIONAL state.
static void state_operational_run (void *o)
Run function for OPERATIONAL state.
static void state_collecting_data_entry (void *o)
Entry function for COLLECTING_DATA state.
static void state_collecting_data_run (void *o)
Run function for COLLECTING_DATA state.
static void state_send_msg_attempt_entry (void *o)
Entry function for SEND_MSG_ATTEMPT state.
static void update_cloud_status (const struct cloud_msg *msg)
Update cloud readiness status.
static void combine_and_queue_data (void)
Combine collected data and queue the result.
static void collection_timeout_handler (struct k_timer *timer)
Collection timeout handler.
static int queue_combined_message (const struct combined_energy_msg *msg)
Queue a combined energy message with FIFO drop-oldest strategy.
static void task_wdt_callback (int channel_id, void *user_data)
Task watchdog timeout callback.
static int64_t uptime_to_unix_epoch (int64_t uptime_ms)
Convert uptime to Unix epoch timestamp.
static void sync_time (int64_t current_uptime_ms, bool force)
Synchronize time with external unix epoch source.
static bool time_needs_resync (void)
Check if time re-sync is needed (periodic drift compensation)
static void date_time_evt_handler (const struct date_time_evt *evt)
Date/time event handler callback.
K_TIMER_DEFINE (collection_timer, collection_timeout_handler, NULL)
K_MSGQ_DEFINE (combined_energy_msgq, sizeof(struct combined_energy_msg), CONFIG_APP_MESSAGE_QUEUE_MODULE_QUEUE_SIZE, 1)
static uint32_t get_queue_usage (void)
Get number of messages currently in queue.
static bool is_queue_empty (void)
Check if queue is empty.
static int build_combined_energy_json (const struct combined_energy_msg *msg, struct nrf_cloud_obj *const obj)
Build nRF Cloud JSON object from combined energy message.
static void message_queue_thread (void)
Main message queue thread.
K_THREAD_DEFINE (message_queue_thread_id, CONFIG_APP_MESSAGE_QUEUE_MODULE_THREAD_STACK_SIZE, message_queue_thread, NULL, NULL, NULL, CONFIG_APP_THREAD_PRIORITY_MESSAGE_QUEUE, 0, 0)
Variables
static const struct smf_state states []
struct {
bool has_data
struct p_one_msg data
} collected_p1
struct {
bool has_data
struct energy_pulse_msg data
} collected_pulse
static atomic_t collection_timeout_expired = ATOMIC_INIT(0)
static bool is_cloud_ready = false
struct {
bool time_synced
int64_t unix_epoch_offset_ms
int64_t last_sync_uptime_ms
} time_sync_state
Macro Definition Documentation
ADD_OBSERVERS
#define ADD_OBSERVERS (_chan, _type)
Value:
    ZBUS_CHAN_ADD_OBS(_chan, message_queue_subscriber, 0);
Definition at line 70 of file message_queue.c.
CHANNEL_LIST
#define CHANNEL_LIST (X)
Value:
    X(CLOUD_CHAN, struct cloud_msg)                       \
    X(NETWORK_CHAN, struct network_msg)                   \
    X(P_ONE_CHAN, struct p_one_msg)                       \
    X(ENERGY_PULSE_CHAN, struct energy_pulse_msg)         \
    X(DATA_PUBLISH_REQUEST_CHAN, struct timing_event_msg) \
    X(DATA_SEND_REQUEST_CHAN, struct timing_event_msg)
Definition at line 58 of file message_queue.c.
COLLECTION_TIMEOUT_MS
#define COLLECTION_TIMEOUT_MS 1000
Definition at line 306 of file message_queue.c.
Referenced by state_collecting_data_entry().
MAX_MSG_SIZE
#define MAX_MSG_SIZE MAX_MSG_SIZE_FROM_LIST(CHANNEL_LIST)
Definition at line 67 of file message_queue.c.
MAX_MSGS_PER_CYCLE
#define MAX_MSGS_PER_CYCLE 10
Referenced by state_send_msg_attempt_entry().
TIME_RESYNC_INTERVAL_MS
#define TIME_RESYNC_INTERVAL_MS (6 * 60 * 60 * 1000)
Definition at line 187 of file message_queue.c.
Referenced by time_needs_resync().
Enumeration Type Documentation
message_queue_state
enum message_queue_state
Enumerator
STATE_OPERATIONAL
STATE_COLLECTING_DATA
STATE_SEND_MSG_ATTEMPT
Definition at line 83 of file message_queue.c.
Function Documentation
BUILD_ASSERT()
BUILD_ASSERT (CONFIG_APP_MESSAGE_QUEUE_MODULE_WATCHDOG_TIMEOUT_SECONDS , CONFIG_APP_MESSAGE_QUEUE_MODULE_MSG_PROCESSING_TIME_SECONDS , "Watchdog timeout must be greater than message processing time")
build_combined_energy_json()
int build_combined_energy_json (const struct combined_energy_msg * msg, struct nrf_cloud_obj *const obj) static
Build nRF Cloud JSON object from combined energy message.
Creates a JSON object with board-specific appId containing P1 and/or Pulse data. Structure follows nRF Cloud device message format with timestamp and data sections. Uses short key names for bandwidth optimization.
Converts uptime timestamps to Unix epoch before adding to JSON. If time is not synced, timestamps will be 0 (invalid).
Parameters
msg Combined energy message with P1 and/or Pulse data
obj Output object to be encoded (must be initialized)
Returns
0 on success, negative errno on error
Definition at line 562 of file message_queue.c.
References p_one_msg::energy_consumed_wh_tariff1, p_one_msg::energy_consumed_wh_tariff2, p_one_msg::energy_delivered_wh_tariff1, p_one_msg::energy_delivered_wh_tariff2, p_one_msg::gas_consumed_dm3, combined_energy_msg::has_p1_data, combined_energy_msg::has_pulse_data, combined_energy_msg::p1_data, p_one_msg::power_consumed_avg_w, p_one_msg::power_consumed_max_timestamp_epoch_ms, p_one_msg::power_consumed_max_w, p_one_msg::power_consumed_min_w, p_one_msg::power_delivered_avg_w, p_one_msg::power_delivered_max_timestamp_epoch_ms, p_one_msg::power_delivered_max_w, p_one_msg::power_delivered_min_w, combined_energy_msg::pulse_data, energy_pulse_msg::pulse_energy_ch1_wh, energy_pulse_msg::pulse_energy_ch2_wh, time_sync_state, p_one_msg::timestamp_epoch_ms, combined_energy_msg::uptime_ms, energy_pulse_msg::uptime_ms, and uptime_to_unix_epoch().
Referenced by state_send_msg_attempt_entry().
collection_timeout_handler()
void collection_timeout_handler (struct k_timer * timer) static
Collection timeout handler.
Called when collection window times out. Sets an atomic flag that will be checked by the state machine in the main thread. Uses atomic operations for safe cross-thread communication.
Parameters
timer Timer that expired (unused)
Definition at line 438 of file message_queue.c.
References collection_timeout_expired.
Referenced by K_TIMER_DEFINE().
combine_and_queue_data()
void combine_and_queue_data (void) static
Combine collected data and queue the result.
Called when collection window closes (either all data received or timeout). Combines whatever data was collected and queues it with flags indicating which data sources were available.
Definition at line 370 of file message_queue.c.
References collected_p1, collected_pulse, combined_energy_msg::has_p1_data, combined_energy_msg::has_pulse_data, combined_energy_msg::p1_data, combined_energy_msg::pulse_data, queue_combined_message(), and combined_energy_msg::uptime_ms.
Referenced by state_collecting_data_run().
date_time_evt_handler()
void date_time_evt_handler (const struct date_time_evt * evt) static
Date/time event handler callback.
Called by date_time library when NTP sync completes. Triggers time synchronization using the obtained Unix timestamp.
Parameters
evt Date/time event
Definition at line 280 of file message_queue.c.
References sync_time().
Referenced by message_queue_thread().
get_queue_usage()
uint32_t get_queue_usage (void) inline static
Get number of messages currently in queue.
Returns
Number of messages in queue
Definition at line 480 of file message_queue.c.
Referenced by state_operational_run().
is_queue_empty()
bool is_queue_empty (void) inline static
Check if queue is empty.
Returns
true if queue is empty, false otherwise
Definition at line 490 of file message_queue.c.
K_MSGQ_DEFINE()
K_MSGQ_DEFINE (combined_energy_msgq , sizeof(struct combined_energy_msg) , CONFIG_APP_MESSAGE_QUEUE_MODULE_QUEUE_SIZE , 1)
K_THREAD_DEFINE()
K_THREAD_DEFINE (message_queue_thread_id , CONFIG_APP_MESSAGE_QUEUE_MODULE_THREAD_STACK_SIZE , message_queue_thread , NULL , NULL , NULL , CONFIG_APP_THREAD_PRIORITY_MESSAGE_QUEUE , 0 , 0)
References message_queue_thread().
K_TIMER_DEFINE()
K_TIMER_DEFINE (collection_timer , collection_timeout_handler , NULL)
References collection_timeout_handler().
LOG_MODULE_REGISTER()
LOG_MODULE_REGISTER (message_queue , CONFIG_APP_MESSAGE_QUEUE_MODULE_LOG_LEVEL)
message_queue_thread()
void message_queue_thread (void) static
Main message queue thread.
Processes ZBUS messages, manages state machine, and feeds task watchdog. Combines P1 and Pulse data, queues messages, and sends them to cloud.
Definition at line 1108 of file message_queue.c.
References message_queue_state_object::chan, date_time_evt_handler(), message_queue_state_object::msg_buf, reboot_request_publish(), REBOOT_TYPE_ERROR, STATE_OPERATIONAL, states, task_wdt_callback(), and task_wdt_util_setup().
Referenced by K_THREAD_DEFINE().
queue_combined_message()
int queue_combined_message (const struct combined_energy_msg * msg) static
Queue a combined energy message with FIFO drop-oldest strategy.
If queue is full, drops the oldest message to make room for new one.
Parameters
msg Combined energy message to queue
Returns
0 on success, negative errno on error
Definition at line 503 of file message_queue.c.
References combined_energy_msg::uptime_ms.
Referenced by combine_and_queue_data().
state_collecting_data_entry()
void state_collecting_data_entry (void * o) static
Entry function for COLLECTING_DATA state.
Starts the collection window and timer.
Parameters
o State object (unused)
Definition at line 897 of file message_queue.c.
References collected_p1, collected_pulse, collection_timeout_expired, and COLLECTION_TIMEOUT_MS.
state_collecting_data_run()
void state_collecting_data_run (void * o) static
Run function for COLLECTING_DATA state.
Collects P1 and Pulse data. When both received or timeout occurs, combines and queues the data.
Parameters
o State object
Definition at line 920 of file message_queue.c.
References message_queue_state_object::chan, collected_p1, collected_pulse, collection_timeout_expired, combine_and_queue_data(), message_queue_state_object::msg_buf, MSG_TO_ENERGY_PULSE_MSG_PTR, MSG_TO_P_ONE_MSG_PTR, STATE_OPERATIONAL, and states.
state_operational_entry()
void state_operational_entry (void * o) static
Entry function for OPERATIONAL state.
Parameters
o State object (unused)
Definition at line 816 of file message_queue.c.
state_operational_run()
void state_operational_run (void * o) static
Run function for OPERATIONAL state.
Waits for DATA_PUBLISH_REQUEST to start data collection. Cloud status is tracked but doesn't block data collection. Network status is tracked for periodic time re-sync (drift compensation).
Parameters
o State object
Definition at line 832 of file message_queue.c.
References message_queue_state_object::chan, get_queue_usage(), is_cloud_ready, message_queue_state_object::msg_buf, MSG_TO_CLOUD_MSG_PTR, MSG_TO_NETWORK_MSG_PTR, network_is_connected(), STATE_COLLECTING_DATA, STATE_SEND_MSG_ATTEMPT, states, sync_time(), time_needs_resync(), and update_cloud_status().
state_send_msg_attempt_entry()
void state_send_msg_attempt_entry (void * o) static
Entry function for SEND_MSG_ATTEMPT state.
Attempts to send as many queued messages as possible to the cloud. Runs in entry function only - immediately transitions back to OPERATIONAL.
Strategy:
Double-check cloud readiness (defense in depth)
Send up to MAX_MSGS_PER_CYCLE messages
Stop on first error (queue remains intact)
Always return to OPERATIONAL (never block)
Parameters
o State object
Definition at line 1005 of file message_queue.c.
References build_combined_energy_json(), is_cloud_ready, MAX_MSGS_PER_CYCLE, STATE_OPERATIONAL, states, and combined_energy_msg::uptime_ms.
sync_time()
void sync_time (int64_t current_uptime_ms, bool force) static
Synchronize time with external unix epoch source.
Called when DATE_TIME_OBTAINED event is received (after NTP sync completes), or periodically to compensate for clock drift (RC oscillator 250 ppm).
Uses date_time library which is updated via nRF Cloud's NTP sync.
Parameters
current_uptime_ms Current system uptime in milliseconds
force Force re-sync even if already synced (for periodic updates)
Definition at line 226 of file message_queue.c.
References time_sync_state.
Referenced by date_time_evt_handler(), and state_operational_run().
task_wdt_callback()
void task_wdt_callback (int channel_id, void * user_data) static
Task watchdog timeout callback.
Called when the task watchdog times out. Requests a system reboot to recover from the watchdog timeout condition.
Parameters
channel_id Task watchdog channel ID
user_data User data (unused)
Definition at line 336 of file message_queue.c.
References reboot_request_publish(), and REBOOT_TYPE_ERROR.
time_needs_resync()
bool time_needs_resync (void) static
Check if time re-sync is needed (periodic drift compensation)
Returns
true if re-sync needed, false otherwise
Definition at line 260 of file message_queue.c.
References TIME_RESYNC_INTERVAL_MS, and time_sync_state.
Referenced by state_operational_run().
update_cloud_status()
void update_cloud_status (const struct cloud_msg * msg) static
Update cloud readiness status.
Tracks changes in cloud connection state and logs transitions.
Parameters
msg Cloud status message
Definition at line 453 of file message_queue.c.
References cloud_is_ready(), and is_cloud_ready.
Referenced by state_operational_run().
uptime_to_unix_epoch()
int64_t uptime_to_unix_epoch (int64_t uptime_ms) static
Convert uptime to Unix epoch timestamp.
Parameters
uptime_ms Uptime in milliseconds
Returns
Unix epoch timestamp in milliseconds, or 0 if not synced
Definition at line 206 of file message_queue.c.
References time_sync_state.
Referenced by build_combined_energy_json().
ZBUS_CHAN_ADD_OBS() [1/6]
ZBUS_CHAN_ADD_OBS (CLOUD_CHAN , message_queue_subscriber , 0)
References ADD_OBSERVERS.
ZBUS_CHAN_ADD_OBS() [2/6]
ZBUS_CHAN_ADD_OBS (DATA_PUBLISH_REQUEST_CHAN , message_queue_subscriber , 0)
ZBUS_CHAN_ADD_OBS() [3/6]
ZBUS_CHAN_ADD_OBS (DATA_SEND_REQUEST_CHAN , message_queue_subscriber , 0)
ZBUS_CHAN_ADD_OBS() [4/6]
ZBUS_CHAN_ADD_OBS (ENERGY_PULSE_CHAN , message_queue_subscriber , 0)
ZBUS_CHAN_ADD_OBS() [5/6]
ZBUS_CHAN_ADD_OBS (NETWORK_CHAN , message_queue_subscriber , 0)
ZBUS_CHAN_ADD_OBS() [6/6]
ZBUS_CHAN_ADD_OBS (P_ONE_CHAN , message_queue_subscriber , 0)
ZBUS_MSG_SUBSCRIBER_DEFINE()
ZBUS_MSG_SUBSCRIBER_DEFINE (message_queue_subscriber)
Variable Documentation
[struct]
struct { ... } collected_p1
Initial value:
= {
    .has_data = false,
}
Referenced by combine_and_queue_data(), state_collecting_data_entry(), and state_collecting_data_run().
[struct]
struct { ... } collected_pulse
Initial value:
= {
    .has_data = false,
}
Referenced by combine_and_queue_data(), state_collecting_data_entry(), and state_collecting_data_run().
collection_timeout_expired
atomic_t collection_timeout_expired = ATOMIC_INIT(0) static
Definition at line 175 of file message_queue.c.
Referenced by collection_timeout_handler(), state_collecting_data_entry(), and state_collecting_data_run().
data
struct energy_pulse_msg data
Definition at line 159 of file message_queue.c.
Referenced by uart_event_handler().
has_data
bool has_data
Definition at line 158 of file message_queue.c.
is_cloud_ready
bool is_cloud_ready = false static
Definition at line 178 of file message_queue.c.
Referenced by state_operational_run(), state_send_msg_attempt_entry(), and update_cloud_status().
last_sync_uptime_ms
int64_t last_sync_uptime_ms
Definition at line 193 of file message_queue.c.
states
const struct smf_state states[] static
Initial value:
= {
    [STATE_OPERATIONAL] = SMF_CREATE_STATE(
            state_operational_entry, state_operational_run, NULL,
            NULL,
            NULL),
    [STATE_COLLECTING_DATA] = SMF_CREATE_STATE(
            state_collecting_data_entry, state_collecting_data_run, NULL,
            &states[STATE_OPERATIONAL],
            NULL),
    [STATE_SEND_MSG_ATTEMPT] = SMF_CREATE_STATE(
            state_send_msg_attempt_entry, NULL, NULL,
            &states[STATE_OPERATIONAL],
            NULL),
}
Definition at line 130 of file message_queue.c.
[struct]
struct { ... } time_sync_state
Initial value:
= {
    .time_synced = false,
    .unix_epoch_offset_ms = 0,
    .last_sync_uptime_ms = 0,
}
Referenced by build_combined_energy_json(), sync_time(), time_needs_resync(), and uptime_to_unix_epoch().
time_synced
bool time_synced
Definition at line 191 of file message_queue.c.
unix_epoch_offset_ms
int64_t unix_epoch_offset_ms
Definition at line 192 of file message_queue.c.