SolarResult Dinnis Core: modules/network/network.c File Reference
network.c File Reference
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/net/conn_mgr_connectivity.h>
#include <zephyr/smf.h>
#include <zephyr/sys/reboot.h>
#include <zephyr/task_wdt/task_wdt.h>
#include <zephyr/zbus/zbus.h>
#include <modem/nrf_modem_lib.h>
#include "modules_common.h"
#include "network_zbus.h"
#include "reboot_zbus.h"
#include "task_wdt_util.h"
Data Structures
struct network_state_object
Macros
#define CHANNEL_LIST(X)
#define MAX_MSG_SIZE MAX_MSG_SIZE_FROM_LIST(CHANNEL_LIST)
#define ADD_OBSERVERS(_chan, _type)
#define L4_EVENT_MASK (NET_EVENT_L4_CONNECTED | NET_EVENT_L4_DISCONNECTED)
#define CONN_LAYER_EVENT_MASK (NET_EVENT_CONN_IF_FATAL_ERROR)
Enumerations
enum network_module_state {
STATE_OPERATIONAL ,
STATE_DISCONNECTED ,
STATE_CONNECTED
}
Functions
LOG_MODULE_REGISTER (network, CONFIG_APP_NETWORK_MODULE_LOG_LEVEL)
BUILD_ASSERT (CONFIG_APP_NETWORK_MODULE_WATCHDOG_TIMEOUT_SECONDS > CONFIG_APP_NETWORK_MODULE_MSG_PROCESSING_TIME_SECONDS, "Watchdog timeout must be greater than message processing time")
ZBUS_MSG_SUBSCRIBER_DEFINE (network_subscriber)
ZBUS_CHAN_ADD_OBS (NETWORK_CHAN, network_subscriber, 0)
ZBUS_CHAN_DEFINE (NETWORK_CHAN, struct network_msg, NULL, NULL, ZBUS_OBSERVERS_EMPTY, ZBUS_MSG_INIT(0))
static void state_operational_entry (void *o)
static void state_operational_run (void *o)
static void state_disconnected_entry (void *o)
static void state_disconnected_run (void *o)
static void state_connected_entry (void *o)
static void state_connected_run (void *o)
K_SEM_DEFINE (nrf_modem_initialized, 0, 1)
NRF_MODEM_LIB_ON_INIT (modem_lib_init_hook, modem_lib_init_callback, NULL)
static void modem_lib_init_callback (int ret, void *ctx)
static void task_wdt_callback (int channel_id, void *user_data)
static const char * network_status_to_str (const enum network_status status)
static void network_status_publish (const enum network_status status, const k_timeout_t timeout)
static void l4_event_handler (struct net_mgmt_event_callback *cb, uint32_t event, struct net_if *iface)
static void connectivity_event_handler (struct net_mgmt_event_callback *cb, uint32_t event, struct net_if *iface)
static void network_thread (void)
K_THREAD_DEFINE (network_thread_id, CONFIG_APP_NETWORK_MODULE_THREAD_STACK_SIZE, network_thread, NULL, NULL, NULL, CONFIG_APP_THREAD_PRIORITY_NETWORK, 0, 0)
Variables
static const struct smf_state states []
static struct net_mgmt_event_callback l4_cb
static struct net_mgmt_event_callback conn_cb
Macro Definition Documentation
ADD_OBSERVERS
#define ADD_OBSERVERS (_chan, _type)
Value:
    ZBUS_CHAN_ADD_OBS(_chan, network_subscriber, 0);
Definition at line 51 of file network.c.
CHANNEL_LIST
#define CHANNEL_LIST (X)
Value:
X(NETWORK_CHAN, struct network_msg)
Definition at line 45 of file network.c.
CONN_LAYER_EVENT_MASK
#define CONN_LAYER_EVENT_MASK (NET_EVENT_CONN_IF_FATAL_ERROR)
Definition at line 131 of file network.c.
Referenced by state_operational_entry().
L4_EVENT_MASK
#define L4_EVENT_MASK (NET_EVENT_L4_CONNECTED | NET_EVENT_L4_DISCONNECTED)
Definition at line 130 of file network.c.
Referenced by state_operational_entry().
MAX_MSG_SIZE
#define MAX_MSG_SIZE MAX_MSG_SIZE_FROM_LIST(CHANNEL_LIST)
Definition at line 48 of file network.c.
Enumeration Type Documentation
network_module_state
enum network_module_state
Enumerator
STATE_OPERATIONAL
STATE_DISCONNECTED
STATE_CONNECTED
Definition at line 82 of file network.c.
Function Documentation
BUILD_ASSERT()
BUILD_ASSERT (CONFIG_APP_NETWORK_MODULE_WATCHDOG_TIMEOUT_SECONDS , CONFIG_APP_NETWORK_MODULE_MSG_PROCESSING_TIME_SECONDS , "Watchdog timeout must be greater than message processing time")
connectivity_event_handler()
void connectivity_event_handler (struct net_mgmt_event_callback * cb, uint32_t event, struct net_if * iface) static
Definition at line 250 of file network.c.
References reboot_request_publish(), and REBOOT_TYPE_ERROR.
Referenced by state_operational_entry().
K_SEM_DEFINE()
K_SEM_DEFINE (nrf_modem_initialized , 0 , 1)
K_THREAD_DEFINE()
K_THREAD_DEFINE (network_thread_id , CONFIG_APP_NETWORK_MODULE_THREAD_STACK_SIZE , network_thread , NULL , NULL , NULL , CONFIG_APP_THREAD_PRIORITY_NETWORK , 0 , 0)
References network_thread().
l4_event_handler()
void l4_event_handler (struct net_mgmt_event_callback * cb, uint32_t event, struct net_if * iface) static
Definition at line 231 of file network.c.
References NETWORK_CONNECTED, NETWORK_DISCONNECTED, and network_status_publish().
Referenced by state_operational_entry().
LOG_MODULE_REGISTER()
LOG_MODULE_REGISTER (network , CONFIG_APP_NETWORK_MODULE_LOG_LEVEL)
modem_lib_init_callback()
void modem_lib_init_callback (int ret, void * ctx) static
Definition at line 152 of file network.c.
References reboot_request_publish(), and REBOOT_TYPE_ERROR.
Referenced by NRF_MODEM_LIB_ON_INIT().
network_status_publish()
void network_status_publish (const enum network_status status, const k_timeout_t timeout) static
Definition at line 209 of file network.c.
References NETWORK_STATUS, network_status_to_str(), reboot_request_publish(), REBOOT_TYPE_ERROR, and network_msg::status.
Referenced by l4_event_handler(), and state_operational_entry().
network_status_to_str()
const char * network_status_to_str (const enum network_status status) static
Definition at line 194 of file network.c.
References NETWORK_CONNECTED, NETWORK_DISCONNECTED, and NETWORK_MODEM_INIT.
Referenced by network_status_publish().
network_thread()
void network_thread (void) static
Definition at line 393 of file network.c.
References network_state_object::chan, network_state_object::msg_buf, reboot_request_publish(), REBOOT_TYPE_ERROR, STATE_OPERATIONAL, states, task_wdt_callback(), and task_wdt_util_setup().
Referenced by K_THREAD_DEFINE().
NRF_MODEM_LIB_ON_INIT()
NRF_MODEM_LIB_ON_INIT (modem_lib_init_hook , modem_lib_init_callback , NULL)
References modem_lib_init_callback().
state_connected_entry()
void state_connected_entry (void * o) static
Definition at line 364 of file network.c.
Referenced by ZBUS_CHAN_DEFINE().
state_connected_run()
void state_connected_run (void * o) static
Definition at line 370 of file network.c.
References network_state_object::chan, network_state_object::msg_buf, MSG_TO_NETWORK_MSG_PTR, network_is_disconnected(), STATE_DISCONNECTED, and states.
Referenced by ZBUS_CHAN_DEFINE().
state_disconnected_entry()
void state_disconnected_entry (void * o) static
Definition at line 334 of file network.c.
state_disconnected_run()
void state_disconnected_run (void * o) static
Definition at line 342 of file network.c.
References network_state_object::chan, network_state_object::msg_buf, MSG_TO_NETWORK_MSG_PTR, network_is_connected(), network_is_disconnected(), STATE_CONNECTED, and states.
state_operational_entry()
void state_operational_entry (void * o) static
Definition at line 269 of file network.c.
References conn_cb, CONN_LAYER_EVENT_MASK, connectivity_event_handler(), l4_cb, l4_event_handler(), L4_EVENT_MASK, NETWORK_MODEM_INIT, network_status_publish(), reboot_request_publish(), and REBOOT_TYPE_ERROR.
state_operational_run()
void state_operational_run (void * o) static
Definition at line 312 of file network.c.
References network_state_object::chan, network_state_object::msg_buf, MSG_TO_NETWORK_MSG_PTR, network_is_connected(), network_is_disconnected(), STATE_CONNECTED, STATE_DISCONNECTED, and states.
task_wdt_callback()
void task_wdt_callback (int channel_id, void * user_data) static
Definition at line 168 of file network.c.
References reboot_request_publish(), and REBOOT_TYPE_ERROR.
ZBUS_CHAN_ADD_OBS()
ZBUS_CHAN_ADD_OBS (NETWORK_CHAN , network_subscriber , 0)
References ADD_OBSERVERS.
ZBUS_CHAN_DEFINE()
ZBUS_CHAN_DEFINE (NETWORK_CHAN , struct network_msg , NULL , NULL , ZBUS_OBSERVERS_EMPTY , ZBUS_MSG_INIT(0))
References state_connected_entry(), state_connected_run(), state_disconnected_entry(), state_disconnected_run(), state_operational_entry(), state_operational_run(), and ZBUS_CHAN_DEFINE().
ZBUS_MSG_SUBSCRIBER_DEFINE()
ZBUS_MSG_SUBSCRIBER_DEFINE (network_subscriber)
Variable Documentation
conn_cb
struct net_mgmt_event_callback conn_cb static
Definition at line 127 of file network.c.
Referenced by state_operational_entry().
l4_cb
struct net_mgmt_event_callback l4_cb static
Definition at line 126 of file network.c.
Referenced by state_operational_entry().
states
const struct smf_state states[] static
Initial value:
= {
    [STATE_OPERATIONAL] = SMF_CREATE_STATE(
            state_operational_entry, state_operational_run, NULL,
            NULL,
            &states[STATE_DISCONNECTED]),
    [STATE_DISCONNECTED] = SMF_CREATE_STATE(
            state_disconnected_entry, state_disconnected_run, NULL,
            &states[STATE_OPERATIONAL],
            NULL),
    [STATE_CONNECTED] =
            SMF_CREATE_STATE(state_connected_entry, state_connected_run, NULL,
                             &states[STATE_OPERATIONAL],
                             NULL),
}
Definition at line 89 of file network.c.