SolarResult Dinnis Core: modules/network/network_shell.c File Reference
network_shell.c File Reference
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/net/conn_mgr_connectivity.h>
#include <zephyr/shell/shell.h>
#include <zephyr/zbus/zbus.h>
#include "network_zbus.h"
Functions
LOG_MODULE_DECLARE (network, CONFIG_APP_NETWORK_MODULE_LOG_LEVEL)
static int cmd_connect (const struct shell *sh, size_t argc, char **argv)
static int cmd_disconnect (const struct shell *sh, size_t argc, char **argv)
SHELL_STATIC_SUBCMD_SET_CREATE (sub_cmds, SHELL_CMD(connect, NULL, "Connect to LTE", cmd_connect), SHELL_CMD(disconnect, NULL, "Disconnect from LTE", cmd_disconnect), SHELL_SUBCMD_SET_END)
SHELL_CMD_REGISTER (app_network, &sub_cmds, "SolarResult Dinnis Firmware Network CMDs", NULL)
Function Documentation
cmd_connect()
int cmd_connect (const struct shell * sh, size_t argc, char ** argv) static
Definition at line 18 of file network_shell.c.
References NETWORK_CONNECTED, and NETWORK_STATUS.
Referenced by SHELL_STATIC_SUBCMD_SET_CREATE().
cmd_disconnect()
int cmd_disconnect (const struct shell * sh, size_t argc, char ** argv) static
Definition at line 36 of file network_shell.c.
References NETWORK_DISCONNECTED, and NETWORK_STATUS.
Referenced by SHELL_STATIC_SUBCMD_SET_CREATE().
LOG_MODULE_DECLARE()
LOG_MODULE_DECLARE (network , CONFIG_APP_NETWORK_MODULE_LOG_LEVEL)
SHELL_CMD_REGISTER()
SHELL_CMD_REGISTER (app_network , & sub_cmds, "SolarResult Dinnis Firmware Network CMDs" , NULL)
SHELL_STATIC_SUBCMD_SET_CREATE()
SHELL_STATIC_SUBCMD_SET_CREATE (sub_cmds , SHELL_CMD(connect, NULL, "Connect to LTE", cmd_connect) , SHELL_CMD(disconnect, NULL, "Disconnect from LTE", cmd_disconnect) , SHELL_SUBCMD_SET_END)
References cmd_connect(), and cmd_disconnect().