SolarResult Dinnis Core: modules/p_one/p_one.c File Reference
p_one.c File Reference
#include <time.h>
#include <zephyr/drivers/gpio.h>
#include <zephyr/drivers/uart.h>
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/sys/reboot.h>
#include <zephyr/sys/timeutil.h>
#include <zephyr/task_wdt/task_wdt.h>
#include <zephyr/zbus/zbus.h>
#include "modules_common.h"
#include "p_one_zbus.h"
#include "reboot_zbus.h"
#include "task_wdt_util.h"
#include "timing_zbus.h"
Data Structures
struct obis_code_entry_t
struct obis_fixed_point_t
struct uart_user_data
Macros
#define P_ONE_UART_MAX_TELEGRAM_SIZE 8191
#define P_ONE_UART_BAUD_RATE DT_PROP(DT_NODELABEL(uart3), current_speed)
#define P_ONE_UART_FRAME_DURATION_USEC
#define P_ONE_UART_MAX_TELEGRAM_TIMEOUT_USEC
#define P_ONE_DATA_REQUEST_RESPONSE_TIMEOUT_MSEC (10000 + P_ONE_UART_MAX_TELEGRAM_TIMEOUT_USEC / 1000)
#define UART_MAX_BUF_SIZE_NRF91 8191
#define UART_RX_BUF_SIZE (UART_MAX_BUF_SIZE_NRF91)
#define DSMR_STR_LINE_END "\r\n"
#define DSMR_STR_LINE_END_LEN 2
#define DSMR_CHAR_HEADER '/'
#define DSMR_CHAR_HEADER_OFFSET (0)
#define DSMR_CHAR_FOOTER '!'
#define DSMR_CHAR_FOOTER_OFFSET_FROM_END (5 + DSMR_STR_LINE_END_LEN)
#define DSMR_STR_CRC_OFFSET_FROM_END (4 + DSMR_STR_LINE_END_LEN)
#define DSMR_STR_CRC_LEN (4)
#define DSMR_STR_START_OF_DATA "\r\n\r\n"
#define DSMR_STR_START_OF_DATA_LEN (4)
#define DSMR_MIN_LEN (1 + DSMR_STR_START_OF_DATA_LEN + DSMR_CHAR_FOOTER_OFFSET_FROM_END)
#define OBIS_TIMESTAMP_LENGTH 13
#define OBIS_LUT_INITIALISER(X)
#define CREATE_STRUCT_ENTRY(name_token, str_lit, value_format)
#define CREATE_ENUM_VALUE(name_token, str_lit, value_format)
#define OBIS_FIND(input_str_ptr, obis_id)
#define CHANNEL_LIST(X)
#define MAX_MSG_SIZE MAX_MSG_SIZE_FROM_LIST(CHANNEL_LIST)
#define ADD_OBSERVERS(_chan, _type)
#define MAX_LINE_BUFFER_SIZE 2048
Enumerations
enum obis_value_format_t {
F3_0_0 ,
F5_3_3 ,
F8_2_2 ,
F8_3_3 ,
F9_3_3 ,
Fn_3_3 ,
S2 ,
S4 ,
S96 ,
TST ,
TST_AND_MBUS_VALUE
}
enum obis_code_id_t {
DSMR_OBIS_P1_VERSION ,
DSMR_OBIS_EQUIPMENT_ID ,
DSMR_OBIS_KWH1_CONSUMED ,
DSMR_OBIS_KWH2_CONSUMED ,
DSMR_OBIS_KWH1_PRODUCED ,
DSMR_OBIS_KWH2_PRODUCED ,
DSMR_OBIS_POWER_DELIVERED ,
DSMR_OBIS_POWER_RECEIVED ,
DSMR_OBIS_TARIFF ,
DSMR_OBIS_P1_DATETIMESTAMP ,
DSMR_OBIS_MBUS_CH1_DEVICE_TYPE ,
DSMR_OBIS_MBUS_CH1_EQUIPMENT_ID ,
DSMR_OBIS_MBUS_CH1_VALUE ,
DSMR_OBIS_MBUS_CH2_DEVICE_TYPE ,
DSMR_OBIS_MBUS_CH2_EQUIPMENT_ID ,
DSMR_OBIS_MBUS_CH2_VALUE ,
DSMR_OBIS_MBUS_CH3_DEVICE_TYPE ,
DSMR_OBIS_MBUS_CH3_EQUIPMENT_ID ,
DSMR_OBIS_MBUS_CH3_VALUE ,
DSMR_OBIS_MBUS_CH4_DEVICE_TYPE ,
DSMR_OBIS_MBUS_CH4_EQUIPMENT_ID ,
DSMR_OBIS_MBUS_CH4_VALUE ,
OBIS_CODE_CNT
}
Functions
LOG_MODULE_REGISTER (p_one, CONFIG_APP_P_ONE_MODULE_LOG_LEVEL)
BUILD_ASSERT (CONFIG_APP_P_ONE_MODULE_WATCHDOG_TIMEOUT_SECONDS > CONFIG_APP_P_ONE_MODULE_MSG_PROCESSING_TIME_SECONDS, "Watchdog timeout must be greater than message processing time")
BUILD_ASSERT (((8191 *(unsigned long)(1000 *1000/(DT_PROP(DT_NODELABEL(uart3), current_speed)/10)+1) *1.1)/1000)<(CONFIG_APP_P_ONE_MODULE_WATCHDOG_TIMEOUT_SECONDS *1000), "UART timeout must be less than watchdog timeout")
ZBUS_MSG_SUBSCRIBER_DEFINE (p_one_subscriber)
ZBUS_CHAN_ADD_OBS (DATA_ACQUISITION_TRIGGER_CHAN, p_one_subscriber, 0)
ZBUS_CHAN_ADD_OBS (DATA_PUBLISH_REQUEST_CHAN, p_one_subscriber, 0)
ZBUS_CHAN_DEFINE (P_ONE_CHAN, struct p_one_msg, NULL, NULL, ZBUS_OBSERVERS_EMPTY, ZBUS_MSG_INIT(0))
K_SEM_DEFINE (p_one_uart_rx_sem, 0, 1)
static void p_one_parse_data (void)
Parse DSMR telegram and extract OBIS values.
static int32_t obis_fixed_point_to_thousandths (obis_fixed_point_t fixed_point)
Convert OBIS fixed-point value to integer (scale by 1/1000)
static void reset_rolling_stats (void)
Reset rolling statistics.
static void update_rolling_stats (void)
Update rolling statistics with new P1 measurement.
static void publish_p1_data (void)
Publish P1 data with rolling statistics to P_ONE_CHAN.
static int obis_sanity_check (obis_code_id_t id, size_t obis_len, size_t max_len)
static int raw_parse_fixed_point (const uint8_t *buf, obis_value_format_t format, obis_fixed_point_t *result)
static int raw_parse_string (const uint8_t *buf, obis_value_format_t format, char *result, size_t result_len)
static int raw_parse_timestamp (const uint8_t *buf, obis_value_format_t format, uint64_t *result)
static int obis_parse_fixed_point (const uint8_t *buf, obis_code_id_t id, size_t max_len, obis_fixed_point_t *result)
static int obis_parse_string (const uint8_t *buf, obis_code_id_t id, size_t max_len, char *result, size_t result_len)
static int obis_parse_timestamp (const uint8_t *buf, obis_code_id_t id, size_t max_len, uint64_t *result)
static int obis_parse_mbus_value (const uint8_t *buf, obis_code_id_t id, size_t max_len, uint64_t *timestamp, obis_fixed_point_t *result)
static uint16_t crc16_calculate (const uint8_t *buf, size_t len)
static int parse_crc_safe (const uint8_t *buf, size_t len, uint16_t *crc_out)
static int p_one_acquire_data (void)
Acquire P1 telegram from DSMR smart meter.
static void uart_event_handler (const struct device *dev, struct uart_event *evt, void *user_data)
UART asynchronous event handler.
static void task_wdt_callback (int channel_id, void *user_data)
Task watchdog timeout callback.
static void p_one_thread (void)
Main P1 DSMR module thread.
K_THREAD_DEFINE (p_one_thread_id, CONFIG_APP_P_ONE_MODULE_THREAD_STACK_SIZE, p_one_thread, NULL, NULL, NULL, CONFIG_APP_THREAD_PRIORITY_P_ONE, 0, 0)
Variables
static const obis_code_entry_t obis_lut []
const struct gpio_dt_spec p_one_data_request
static const struct device * uart_dev = DEVICE_DT_GET(DT_NODELABEL(uart3))
static uint8_t p_one_uart_rx_buf [(8191)]
static struct uart_user_data uart_user_data = { 0 }
struct {
uint64_t timestamp_epoch_localtime_s
obis_fixed_point_t kwh1_consumed
obis_fixed_point_t kwh1_produced
obis_fixed_point_t kwh2_consumed
obis_fixed_point_t kwh2_produced
obis_fixed_point_t power_delivered_kw
obis_fixed_point_t power_received_kw
obis_fixed_point_t gas_m3_consumed
} p1_data
struct {
char version [2+1]
char equipment_id [96+1]
struct {
obis_fixed_point_t device_type
char equipment_id [96+1]
uint64_t timestamp_epoch_localtime_s
obis_fixed_point_t value
} mbus [4]
} p1_extra_data
struct {
int64_t consumed_sum_w
int32_t consumed_max_w
int32_t consumed_min_w
int64_t consumed_max_timestamp_epoch_s
int64_t delivered_sum_w
int32_t delivered_max_w
int32_t delivered_min_w
int64_t delivered_max_timestamp_epoch_s
uint32_t sample_count
} p1_stats
static const uint16_t crc16_lut []
Macro Definition Documentation
ADD_OBSERVERS
#define ADD_OBSERVERS (_chan, _type)
Value:
    ZBUS_CHAN_ADD_OBS(_chan, p_one_subscriber, 0);
Definition at line 191 of file p_one.c.
CHANNEL_LIST
#define CHANNEL_LIST (X)
Value:
    X(DATA_ACQUISITION_TRIGGER_CHAN, struct timing_event_msg) \
    X(DATA_PUBLISH_REQUEST_CHAN, struct timing_event_msg)
Definition at line 182 of file p_one.c.
CREATE_ENUM_VALUE
#define CREATE_ENUM_VALUE (name_token, str_lit, value_format)
Value:
name_token,
Definition at line 148 of file p_one.c.
CREATE_STRUCT_ENTRY
#define CREATE_STRUCT_ENTRY (name_token, str_lit, value_format)
Value:
    { #name_token, str_lit, ARRAY_SIZE(str_lit) - 1, value_format },
Definition at line 142 of file p_one.c.
DSMR_CHAR_FOOTER
#define DSMR_CHAR_FOOTER '!'
Definition at line 80 of file p_one.c.
Referenced by p_one_parse_data().
DSMR_CHAR_FOOTER_OFFSET_FROM_END
#define DSMR_CHAR_FOOTER_OFFSET_FROM_END (5 + DSMR_STR_LINE_END_LEN)
Definition at line 81 of file p_one.c.
Referenced by p_one_parse_data().
DSMR_CHAR_HEADER
#define DSMR_CHAR_HEADER '/'
Definition at line 77 of file p_one.c.
Referenced by p_one_parse_data().
DSMR_CHAR_HEADER_OFFSET
#define DSMR_CHAR_HEADER_OFFSET (0)
Definition at line 78 of file p_one.c.
Referenced by p_one_parse_data().
DSMR_MIN_LEN
#define DSMR_MIN_LEN (1 + DSMR_STR_START_OF_DATA_LEN + DSMR_CHAR_FOOTER_OFFSET_FROM_END)
Definition at line 89 of file p_one.c.
Referenced by p_one_parse_data().
DSMR_STR_CRC_LEN
#define DSMR_STR_CRC_LEN (4)
Definition at line 84 of file p_one.c.
Referenced by parse_crc_safe().
DSMR_STR_CRC_OFFSET_FROM_END
#define DSMR_STR_CRC_OFFSET_FROM_END (4 + DSMR_STR_LINE_END_LEN)
Definition at line 83 of file p_one.c.
Referenced by p_one_parse_data(), and parse_crc_safe().
DSMR_STR_LINE_END
#define DSMR_STR_LINE_END "\r\n"
Definition at line 74 of file p_one.c.
Referenced by p_one_parse_data().
DSMR_STR_LINE_END_LEN
#define DSMR_STR_LINE_END_LEN 2
Definition at line 75 of file p_one.c.
Referenced by p_one_parse_data().
DSMR_STR_START_OF_DATA
#define DSMR_STR_START_OF_DATA "\r\n\r\n"
Definition at line 86 of file p_one.c.
Referenced by p_one_parse_data().
DSMR_STR_START_OF_DATA_LEN
#define DSMR_STR_START_OF_DATA_LEN (4)
Definition at line 87 of file p_one.c.
Referenced by p_one_parse_data().
MAX_LINE_BUFFER_SIZE
#define MAX_LINE_BUFFER_SIZE 2048
Referenced by p_one_parse_data().
MAX_MSG_SIZE
#define MAX_MSG_SIZE MAX_MSG_SIZE_FROM_LIST(CHANNEL_LIST)
Definition at line 187 of file p_one.c.
OBIS_FIND
#define OBIS_FIND (input_str_ptr, obis_id)
Value:
    (strncmp((input_str_ptr), obis_lut[obis_id].str, obis_lut[obis_id].len) == \
     0)
Definition at line 155 of file p_one.c.
Referenced by p_one_parse_data().
OBIS_LUT_INITIALISER
#define OBIS_LUT_INITIALISER (X)
Value:
    X(DSMR_OBIS_P1_VERSION, "1-3:0.2.8", S2)                      \
    X(DSMR_OBIS_EQUIPMENT_ID, "0-0:96.1.1", S96)                  \
    X(DSMR_OBIS_KWH1_CONSUMED, "1-0:1.8.1", F9_3_3)               \
    X(DSMR_OBIS_KWH2_CONSUMED, "1-0:1.8.2", F9_3_3)               \
    X(DSMR_OBIS_KWH1_PRODUCED, "1-0:2.8.1", F9_3_3)               \
    X(DSMR_OBIS_KWH2_PRODUCED, "1-0:2.8.2", F9_3_3)               \
    X(DSMR_OBIS_POWER_DELIVERED, "1-0:1.7.0", F5_3_3)             \
    X(DSMR_OBIS_POWER_RECEIVED, "1-0:2.7.0", F5_3_3)              \
    X(DSMR_OBIS_TARIFF, "0-0:96.14.0", S4)                        \
    X(DSMR_OBIS_P1_DATETIMESTAMP, "0-0:1.0.0", TST)               \
    X(DSMR_OBIS_MBUS_CH1_DEVICE_TYPE, "0-1:24.1.0", F3_0_0)       \
    X(DSMR_OBIS_MBUS_CH1_EQUIPMENT_ID, "0-1:96.1.0", S96)         \
    X(DSMR_OBIS_MBUS_CH1_VALUE, "0-1:24.2.1", TST_AND_MBUS_VALUE) \
    X(DSMR_OBIS_MBUS_CH2_DEVICE_TYPE, "0-2:24.1.0", F3_0_0)       \
    X(DSMR_OBIS_MBUS_CH2_EQUIPMENT_ID, "0-2:96.1.0", S96)         \
    X(DSMR_OBIS_MBUS_CH2_VALUE, "0-2:24.2.1", TST_AND_MBUS_VALUE) \
    X(DSMR_OBIS_MBUS_CH3_DEVICE_TYPE, "0-3:24.1.0", F3_0_0)       \
    X(DSMR_OBIS_MBUS_CH3_EQUIPMENT_ID, "0-3:96.1.0", S96)         \
    X(DSMR_OBIS_MBUS_CH3_VALUE, "0-3:24.2.1", TST_AND_MBUS_VALUE) \
    X(DSMR_OBIS_MBUS_CH4_DEVICE_TYPE, "0-4:24.1.0", F3_0_0)       \
    X(DSMR_OBIS_MBUS_CH4_EQUIPMENT_ID, "0-4:96.1.0", S96)         \
    X(DSMR_OBIS_MBUS_CH4_VALUE, "0-4:24.2.1", TST_AND_MBUS_VALUE)
Definition at line 118 of file p_one.c.
OBIS_TIMESTAMP_LENGTH
#define OBIS_TIMESTAMP_LENGTH 13
Definition at line 92 of file p_one.c.
Referenced by obis_parse_mbus_value().
P_ONE_DATA_REQUEST_RESPONSE_TIMEOUT_MSEC
#define P_ONE_DATA_REQUEST_RESPONSE_TIMEOUT_MSEC (10000 + P_ONE_UART_MAX_TELEGRAM_TIMEOUT_USEC / 1000)
Definition at line 61 of file p_one.c.
Referenced by p_one_acquire_data().
P_ONE_UART_BAUD_RATE
#define P_ONE_UART_BAUD_RATE DT_PROP(DT_NODELABEL(uart3), current_speed)
Definition at line 43 of file p_one.c.
P_ONE_UART_FRAME_DURATION_USEC
#define P_ONE_UART_FRAME_DURATION_USEC
Value:
    (unsigned long)(1000 * 1000 / (P_ONE_UART_BAUD_RATE / 10) + \
                    1) /* Applies to 8N1 only */
Definition at line 44 of file p_one.c.
P_ONE_UART_MAX_TELEGRAM_SIZE
#define P_ONE_UART_MAX_TELEGRAM_SIZE 8191
Definition at line 42 of file p_one.c.
P_ONE_UART_MAX_TELEGRAM_TIMEOUT_USEC
#define P_ONE_UART_MAX_TELEGRAM_TIMEOUT_USEC
Value:
    (P_ONE_UART_MAX_TELEGRAM_SIZE * P_ONE_UART_FRAME_DURATION_USEC * \
     1.1) /* If you ever experience truncated telegrams, increase this margin */
Definition at line 49 of file p_one.c.
Referenced by BUILD_ASSERT(), and p_one_acquire_data().
UART_MAX_BUF_SIZE_NRF91
#define UART_MAX_BUF_SIZE_NRF91 8191
Definition at line 70 of file p_one.c.
UART_RX_BUF_SIZE
#define UART_RX_BUF_SIZE (UART_MAX_BUF_SIZE_NRF91)
Definition at line 71 of file p_one.c.
Referenced by p_one_acquire_data().
Enumeration Type Documentation
obis_code_id_t
enum obis_code_id_t
Enumerator
DSMR_OBIS_P1_VERSION
DSMR_OBIS_EQUIPMENT_ID
DSMR_OBIS_KWH1_CONSUMED
DSMR_OBIS_KWH2_CONSUMED
DSMR_OBIS_KWH1_PRODUCED
DSMR_OBIS_KWH2_PRODUCED
DSMR_OBIS_POWER_DELIVERED
DSMR_OBIS_POWER_RECEIVED
DSMR_OBIS_TARIFF
DSMR_OBIS_P1_DATETIMESTAMP
DSMR_OBIS_MBUS_CH1_DEVICE_TYPE
DSMR_OBIS_MBUS_CH1_EQUIPMENT_ID
DSMR_OBIS_MBUS_CH1_VALUE
DSMR_OBIS_MBUS_CH2_DEVICE_TYPE
DSMR_OBIS_MBUS_CH2_EQUIPMENT_ID
DSMR_OBIS_MBUS_CH2_VALUE
DSMR_OBIS_MBUS_CH3_DEVICE_TYPE
DSMR_OBIS_MBUS_CH3_EQUIPMENT_ID
DSMR_OBIS_MBUS_CH3_VALUE
DSMR_OBIS_MBUS_CH4_DEVICE_TYPE
DSMR_OBIS_MBUS_CH4_EQUIPMENT_ID
DSMR_OBIS_MBUS_CH4_VALUE
OBIS_CODE_CNT
Definition at line 149 of file p_one.c.
obis_value_format_t
enum obis_value_format_t
Enumerator
F3_0_0
F5_3_3
F8_2_2
F8_3_3
F9_3_3
Fn_3_3
S2
S4
S96
TST
TST_AND_MBUS_VALUE
Definition at line 95 of file p_one.c.
Function Documentation
BUILD_ASSERT() [1/2]
BUILD_ASSERT ()
References P_ONE_UART_MAX_TELEGRAM_TIMEOUT_USEC.
BUILD_ASSERT() [2/2]
BUILD_ASSERT (CONFIG_APP_P_ONE_MODULE_WATCHDOG_TIMEOUT_SECONDS , CONFIG_APP_P_ONE_MODULE_MSG_PROCESSING_TIME_SECONDS , "Watchdog timeout must be greater than message processing time")
crc16_calculate()
uint16_t crc16_calculate (const uint8_t * buf, size_t len) static
Definition at line 793 of file p_one.c.
References crc16_lut.
Referenced by p_one_parse_data().
K_SEM_DEFINE()
K_SEM_DEFINE (p_one_uart_rx_sem , 0 , 1)
K_THREAD_DEFINE()
K_THREAD_DEFINE (p_one_thread_id , CONFIG_APP_P_ONE_MODULE_THREAD_STACK_SIZE , p_one_thread , NULL , NULL , NULL , CONFIG_APP_THREAD_PRIORITY_P_ONE , 0 , 0)
References p_one_thread().
LOG_MODULE_REGISTER()
LOG_MODULE_REGISTER (p_one , CONFIG_APP_P_ONE_MODULE_LOG_LEVEL)
obis_fixed_point_to_thousandths()
int32_t obis_fixed_point_to_thousandths (obis_fixed_point_t fixed_point) static
Convert OBIS fixed-point value to integer (scale by 1/1000)
Converts OBIS fixed-point representation to integer by scaling down by factor 1000. Effectively converts base units to "one thousandth-s" or removes the decimal point for values with 3 decimal places.
OBIS format: whole + frac (6 decimal precision, stored as 1e-6) Conversion: whole * 1000 + frac / 1000 = value scaled by 1/1000
Examples:
123.456789 kWh 123456 Wh
5.678123 kW 5678 W
0.045 m 45 dm
Parameters
fixed_point OBIS fixed-point value with 6 decimal precision
Returns
int32_t Integer value scaled by 1/1000 (no FPU needed)
Definition at line 312 of file p_one.c.
References obis_fixed_point_t::frac, and obis_fixed_point_t::whole.
Referenced by publish_p1_data(), and update_rolling_stats().
obis_parse_fixed_point()
int obis_parse_fixed_point (const uint8_t * buf, obis_code_id_t id, size_t max_len, obis_fixed_point_t * result) static
Definition at line 637 of file p_one.c.
References obis_fixed_point_t::frac, obis_lut, obis_sanity_check(), raw_parse_fixed_point(), and obis_fixed_point_t::whole.
Referenced by p_one_parse_data().
obis_parse_mbus_value()
int obis_parse_mbus_value (const uint8_t * buf, obis_code_id_t id, size_t max_len, uint64_t * timestamp, obis_fixed_point_t * result) static
Definition at line 704 of file p_one.c.
References F8_2_2, F8_3_3, obis_fixed_point_t::frac, obis_lut, obis_sanity_check(), OBIS_TIMESTAMP_LENGTH, raw_parse_fixed_point(), raw_parse_timestamp(), TST, and obis_fixed_point_t::whole.
Referenced by p_one_parse_data().
obis_parse_string()
int obis_parse_string (const uint8_t * buf, obis_code_id_t id, size_t max_len, char * result, size_t result_len) static
Definition at line 660 of file p_one.c.
References obis_lut, obis_sanity_check(), and raw_parse_string().
Referenced by p_one_parse_data().
obis_parse_timestamp()
int obis_parse_timestamp (const uint8_t * buf, obis_code_id_t id, size_t max_len, uint64_t * result) static
Definition at line 682 of file p_one.c.
References obis_lut, obis_sanity_check(), and raw_parse_timestamp().
Referenced by p_one_parse_data().
obis_sanity_check()
int obis_sanity_check (obis_code_id_t id, size_t obis_len, size_t max_len) static
Definition at line 501 of file p_one.c.
References OBIS_CODE_CNT.
Referenced by obis_parse_fixed_point(), obis_parse_mbus_value(), obis_parse_string(), and obis_parse_timestamp().
p_one_acquire_data()
int p_one_acquire_data (void) static
Acquire P1 telegram from DSMR smart meter.
Asserts Data Request pin, enables UART RX, waits for telegram, then deasserts Data Request. Uses async UART with semaphore synchronization.
Returns
0 on success, -ETIMEDOUT if no response, -EIO on UART error
Definition at line 853 of file p_one.c.
References p_one_data_request, P_ONE_DATA_REQUEST_RESPONSE_TIMEOUT_MSEC, P_ONE_UART_MAX_TELEGRAM_TIMEOUT_USEC, p_one_uart_rx_buf, uart_user_data::total_bytes_received, uart_dev, and UART_RX_BUF_SIZE.
Referenced by p_one_thread().
p_one_parse_data()
void p_one_parse_data (void) static
Parse DSMR telegram and extract OBIS values.
Validates header, footer, and CRC16. Extracts energy, power, and M-Bus values into p1_data and p1_extra_data structures.
Definition at line 929 of file p_one.c.
References crc16_calculate(), DSMR_CHAR_FOOTER, DSMR_CHAR_FOOTER_OFFSET_FROM_END, DSMR_CHAR_HEADER, DSMR_CHAR_HEADER_OFFSET, DSMR_MIN_LEN, DSMR_OBIS_EQUIPMENT_ID, DSMR_OBIS_KWH1_CONSUMED, DSMR_OBIS_KWH1_PRODUCED, DSMR_OBIS_KWH2_CONSUMED, DSMR_OBIS_KWH2_PRODUCED, DSMR_OBIS_MBUS_CH1_DEVICE_TYPE, DSMR_OBIS_MBUS_CH1_EQUIPMENT_ID, DSMR_OBIS_MBUS_CH1_VALUE, DSMR_OBIS_MBUS_CH2_DEVICE_TYPE, DSMR_OBIS_MBUS_CH2_EQUIPMENT_ID, DSMR_OBIS_MBUS_CH2_VALUE, DSMR_OBIS_MBUS_CH3_DEVICE_TYPE, DSMR_OBIS_MBUS_CH3_EQUIPMENT_ID, DSMR_OBIS_MBUS_CH3_VALUE, DSMR_OBIS_MBUS_CH4_DEVICE_TYPE, DSMR_OBIS_MBUS_CH4_EQUIPMENT_ID, DSMR_OBIS_MBUS_CH4_VALUE, DSMR_OBIS_P1_DATETIMESTAMP, DSMR_OBIS_P1_VERSION, DSMR_OBIS_POWER_DELIVERED, DSMR_OBIS_POWER_RECEIVED, DSMR_STR_CRC_OFFSET_FROM_END, DSMR_STR_LINE_END, DSMR_STR_LINE_END_LEN, DSMR_STR_START_OF_DATA, DSMR_STR_START_OF_DATA_LEN, MAX_LINE_BUFFER_SIZE, OBIS_FIND, obis_lut, obis_parse_fixed_point(), obis_parse_mbus_value(), obis_parse_string(), obis_parse_timestamp(), p1_data, p1_extra_data, p_one_uart_rx_buf, parse_crc_safe(), and uart_user_data::total_bytes_received.
Referenced by p_one_thread().
p_one_thread()
void p_one_thread (void) static
Main P1 DSMR module thread.
Handles DATA_ACQUISITION_TRIGGER_CHAN (acquire + parse + update stats) and DATA_PUBLISH_REQUEST_CHAN (publish + reset stats) events.
Definition at line 1329 of file p_one.c.
References MAX_MSG_SIZE, MSG_TO_TIMING_EVENT_MSG_PTR, p_one_acquire_data(), p_one_data_request, p_one_parse_data(), publish_p1_data(), reboot_request_publish(), REBOOT_TYPE_ERROR, task_wdt_callback(), task_wdt_util_setup(), uart_dev, uart_event_handler(), update_rolling_stats(), and timing_event_msg::uptime_ms.
Referenced by K_THREAD_DEFINE().
parse_crc_safe()
int parse_crc_safe (const uint8_t * buf, size_t len, uint16_t * crc_out) static
Definition at line 803 of file p_one.c.
References DSMR_STR_CRC_LEN, and DSMR_STR_CRC_OFFSET_FROM_END.
Referenced by p_one_parse_data().
publish_p1_data()
void publish_p1_data (void) static
Publish P1 data with rolling statistics to P_ONE_CHAN.
Called on DATA_PUBLISH_REQUEST_CHAN event. Only publishes if at least one valid P1 sample was collected during the window. Uses p1_stats.sample_count as the authoritative indicator of data availability.
If sample_count is 0, all acquisitions failed in this window and no ZBUS message is published, preventing stale/empty data from being sent.
Converts OBIS fixed-point values to int32_t Wh/W (no FPU needed!). Uses P1 meter's own epoch timestamp from OBIS 0-0:1.0.0.
Definition at line 423 of file p_one.c.
References p_one_msg::energy_consumed_wh_tariff1, p_one_msg::energy_consumed_wh_tariff2, p_one_msg::energy_delivered_wh_tariff1, p_one_msg::energy_delivered_wh_tariff2, p_one_msg::gas_consumed_dm3, obis_fixed_point_to_thousandths(), p1_data, p1_stats, p_one_msg::power_consumed_avg_w, p_one_msg::power_consumed_max_timestamp_epoch_ms, p_one_msg::power_consumed_max_w, p_one_msg::power_consumed_min_w, p_one_msg::power_delivered_avg_w, p_one_msg::power_delivered_max_timestamp_epoch_ms, p_one_msg::power_delivered_max_w, p_one_msg::power_delivered_min_w, reset_rolling_stats(), and p_one_msg::timestamp_epoch_ms.
Referenced by p_one_thread().
raw_parse_fixed_point()
int raw_parse_fixed_point (const uint8_t * buf, obis_value_format_t format, obis_fixed_point_t * result) static
Definition at line 517 of file p_one.c.
References F3_0_0, F5_3_3, F8_2_2, F8_3_3, F9_3_3, Fn_3_3, obis_fixed_point_t::frac, and obis_fixed_point_t::whole.
Referenced by obis_parse_fixed_point(), and obis_parse_mbus_value().
raw_parse_string()
int raw_parse_string (const uint8_t * buf, obis_value_format_t format, char * result, size_t result_len) static
Definition at line 558 of file p_one.c.
References S2, S4, and S96.
Referenced by obis_parse_string().
raw_parse_timestamp()
int raw_parse_timestamp (const uint8_t * buf, obis_value_format_t format, uint64_t * result) static
Definition at line 592 of file p_one.c.
References TST.
Referenced by obis_parse_mbus_value(), and obis_parse_timestamp().
reset_rolling_stats()
void reset_rolling_stats (void) static
Reset rolling statistics.
Called after publishing stats to P_ONE_CHAN.
Definition at line 331 of file p_one.c.
References p1_stats.
Referenced by publish_p1_data().
task_wdt_callback()
void task_wdt_callback (int channel_id, void * user_data) static
Task watchdog timeout callback.
Parameters
channel_id Watchdog channel ID
user_data User data (thread ID)
Definition at line 1298 of file p_one.c.
References reboot_request_publish(), and REBOOT_TYPE_ERROR.
uart_event_handler()
void uart_event_handler (const struct device * dev, struct uart_event * evt, void * user_data) static
UART asynchronous event handler.
Parameters
dev UART device
evt UART event
user_data User data (uart_user_data struct)
Definition at line 1246 of file p_one.c.
References data.
Referenced by p_one_thread().
update_rolling_stats()
void update_rolling_stats (void) static
Update rolling statistics with new P1 measurement.
Uses instantaneous power from OBIS 1-0:1.7.0 (delivered/consumed) and 1-0:2.7.0 (received/produced).
Tracks consumed and delivered separately for peak shaving and DEV analysis. Called after each successful P1 data acquisition and parsing. Uses int32_t arithmetic to avoid FPU usage.
Note: Uses P1 meter's own epoch timestamp for peak timing (from OBIS 0-0:1.0.0).
Definition at line 360 of file p_one.c.
References obis_fixed_point_to_thousandths(), p1_data, and p1_stats.
Referenced by p_one_thread().
ZBUS_CHAN_ADD_OBS() [1/2]
ZBUS_CHAN_ADD_OBS (DATA_ACQUISITION_TRIGGER_CHAN , p_one_subscriber , 0)
References ADD_OBSERVERS.
ZBUS_CHAN_ADD_OBS() [2/2]
ZBUS_CHAN_ADD_OBS (DATA_PUBLISH_REQUEST_CHAN , p_one_subscriber , 0)
ZBUS_CHAN_DEFINE()
ZBUS_CHAN_DEFINE (P_ONE_CHAN , struct p_one_msg , NULL , NULL , ZBUS_OBSERVERS_EMPTY , ZBUS_MSG_INIT(0))
References ZBUS_CHAN_DEFINE().
ZBUS_MSG_SUBSCRIBER_DEFINE()
ZBUS_MSG_SUBSCRIBER_DEFINE (p_one_subscriber)
Variable Documentation
consumed_max_timestamp_epoch_s
int64_t consumed_max_timestamp_epoch_s
Definition at line 274 of file p_one.c.
consumed_max_w
int32_t consumed_max_w
Definition at line 272 of file p_one.c.
consumed_min_w
int32_t consumed_min_w
Definition at line 273 of file p_one.c.
consumed_sum_w
int64_t consumed_sum_w
Definition at line 271 of file p_one.c.
crc16_lut
const uint16_t crc16_lut[] static
Definition at line 760 of file p_one.c.
Referenced by crc16_calculate().
delivered_max_timestamp_epoch_s
int64_t delivered_max_timestamp_epoch_s
Definition at line 280 of file p_one.c.
delivered_max_w
int32_t delivered_max_w
Definition at line 278 of file p_one.c.
delivered_min_w
int32_t delivered_min_w
Definition at line 279 of file p_one.c.
delivered_sum_w
int64_t delivered_sum_w
Definition at line 277 of file p_one.c.
device_type
obis_fixed_point_t device_type
Definition at line 253 of file p_one.c.
equipment_id
char equipment_id[96+1]
Definition at line 251 of file p_one.c.
gas_m3_consumed
obis_fixed_point_t gas_m3_consumed
Definition at line 245 of file p_one.c.
kwh1_consumed
obis_fixed_point_t kwh1_consumed
Definition at line 236 of file p_one.c.
kwh1_produced
obis_fixed_point_t kwh1_produced
Definition at line 237 of file p_one.c.
kwh2_consumed
obis_fixed_point_t kwh2_consumed
Definition at line 238 of file p_one.c.
kwh2_produced
obis_fixed_point_t kwh2_produced
Definition at line 239 of file p_one.c.
[struct]
struct { ... } mbus[4]
obis_lut
const obis_code_entry_t obis_lut[] static
Initial value:
= {
 { "DSMR_OBIS_P1_VERSION", "1-3:0.2.8", ARRAY_SIZE("1-3:0.2.8") - 1, S2 }, { "DSMR_OBIS_EQUIPMENT_ID", "0-0:96.1.1", ARRAY_SIZE("0-0:96.1.1") - 1, S96 }, { "DSMR_OBIS_KWH1_CONSUMED", "1-0:1.8.1", ARRAY_SIZE("1-0:1.8.1") - 1, F9_3_3 }, { "DSMR_OBIS_KWH2_CONSUMED", "1-0:1.8.2", ARRAY_SIZE("1-0:1.8.2") - 1, F9_3_3 }, { "DSMR_OBIS_KWH1_PRODUCED", "1-0:2.8.1", ARRAY_SIZE("1-0:2.8.1") - 1, F9_3_3 }, { "DSMR_OBIS_KWH2_PRODUCED", "1-0:2.8.2", ARRAY_SIZE("1-0:2.8.2") - 1, F9_3_3 }, { "DSMR_OBIS_POWER_DELIVERED", "1-0:1.7.0", ARRAY_SIZE("1-0:1.7.0") - 1, F5_3_3 }, { "DSMR_OBIS_POWER_RECEIVED", "1-0:2.7.0", ARRAY_SIZE("1-0:2.7.0") - 1, F5_3_3 }, { "DSMR_OBIS_TARIFF", "0-0:96.14.0", ARRAY_SIZE("0-0:96.14.0") - 1, S4 }, { "DSMR_OBIS_P1_DATETIMESTAMP", "0-0:1.0.0", ARRAY_SIZE("0-0:1.0.0") - 1, TST }, { "DSMR_OBIS_MBUS_CH1_DEVICE_TYPE", "0-1:24.1.0", ARRAY_SIZE("0-1:24.1.0") - 1, F3_0_0 }, { "DSMR_OBIS_MBUS_CH1_EQUIPMENT_ID", "0-1:96.1.0", ARRAY_SIZE("0-1:96.1.0") - 1, S96 }, { "DSMR_OBIS_MBUS_CH1_VALUE", "0-1:24.2.1", ARRAY_SIZE("0-1:24.2.1") - 1, TST_AND_MBUS_VALUE }, { "DSMR_OBIS_MBUS_CH2_DEVICE_TYPE", "0-2:24.1.0", ARRAY_SIZE("0-2:24.1.0") - 1, F3_0_0 }, { "DSMR_OBIS_MBUS_CH2_EQUIPMENT_ID", "0-2:96.1.0", ARRAY_SIZE("0-2:96.1.0") - 1, S96 }, { "DSMR_OBIS_MBUS_CH2_VALUE", "0-2:24.2.1", ARRAY_SIZE("0-2:24.2.1") - 1, TST_AND_MBUS_VALUE }, { "DSMR_OBIS_MBUS_CH3_DEVICE_TYPE", "0-3:24.1.0", ARRAY_SIZE("0-3:24.1.0") - 1, F3_0_0 }, { "DSMR_OBIS_MBUS_CH3_EQUIPMENT_ID", "0-3:96.1.0", ARRAY_SIZE("0-3:96.1.0") - 1, S96 }, { "DSMR_OBIS_MBUS_CH3_VALUE", "0-3:24.2.1", ARRAY_SIZE("0-3:24.2.1") - 1, TST_AND_MBUS_VALUE }, { "DSMR_OBIS_MBUS_CH4_DEVICE_TYPE", "0-4:24.1.0", ARRAY_SIZE("0-4:24.1.0") - 1, F3_0_0 }, { "DSMR_OBIS_MBUS_CH4_EQUIPMENT_ID", "0-4:96.1.0", ARRAY_SIZE("0-4:96.1.0") - 1, S96 }, { "DSMR_OBIS_MBUS_CH4_VALUE", "0-4:24.2.1", ARRAY_SIZE("0-4:24.2.1") - 1, TST_AND_MBUS_VALUE }, }
Definition at line 144 of file p_one.c.
Referenced by obis_parse_fixed_point(), obis_parse_mbus_value(), obis_parse_string(), obis_parse_timestamp(), and p_one_parse_data().
[struct]
struct { ... } p1_data
Referenced by p_one_parse_data(), publish_p1_data(), and update_rolling_stats().
[struct]
struct { ... } p1_extra_data
Referenced by p_one_parse_data().
[struct]
struct { ... } p1_stats
Referenced by publish_p1_data(), reset_rolling_stats(), and update_rolling_stats().
p_one_data_request
const struct gpio_dt_spec p_one_data_request
Initial value:
=
        GPIO_DT_SPEC_GET(DT_NODELABEL(datarequest), gpios)
Definition at line 218 of file p_one.c.
Referenced by p_one_acquire_data(), and p_one_thread().
p_one_uart_rx_buf
uint8_t p_one_uart_rx_buf[(8191)] static
Definition at line 225 of file p_one.c.
Referenced by p_one_acquire_data(), and p_one_parse_data().
power_delivered_kw
obis_fixed_point_t power_delivered_kw
Definition at line 242 of file p_one.c.
power_received_kw
obis_fixed_point_t power_received_kw
Definition at line 243 of file p_one.c.
sample_count
uint32_t sample_count
Definition at line 282 of file p_one.c.
timestamp_epoch_localtime_s
uint64_t timestamp_epoch_localtime_s
Definition at line 235 of file p_one.c.
uart_dev
const struct device* uart_dev = DEVICE_DT_GET(DT_NODELABEL(uart3)) static
Definition at line 222 of file p_one.c.
Referenced by p_one_acquire_data(), and p_one_thread().
uart_user_data
struct uart_user_data uart_user_data = { 0 } static
Definition at line 228 of file p_one.c.
value
obis_fixed_point_t value
Definition at line 256 of file p_one.c.
Referenced by energy_pulse_settings_set(), and save_energy_channel().
version
char version[2+1]
Definition at line 250 of file p_one.c.