SolarResult Dinnis Core: modules/reboot/reboot.c File Reference
reboot.c File Reference
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/logging/log_ctrl.h>
#include <zephyr/smf.h>
#include <zephyr/sys/reboot.h>
#include <zephyr/task_wdt/task_wdt.h>
#include <zephyr/zbus/zbus.h>
#include "modules_common.h"
#include "reboot_zbus.h"
#include "task_wdt_util.h"
Data Structures
struct reboot_state_object
Macros
#define REBOOT_MODULE_FATAL_ERROR_HANDLE()
#define CHANNEL_LIST(X)
#define MAX_MSG_SIZE MAX_MSG_SIZE_FROM_LIST(CHANNEL_LIST)
#define ADD_OBSERVERS(_chan, _type)
Enumerations
enum reboot_module_state { STATE_OPERATIONAL }
Functions
LOG_MODULE_REGISTER (reboot, CONFIG_APP_REBOOT_MODULE_LOG_LEVEL)
BUILD_ASSERT (CONFIG_APP_REBOOT_MODULE_WATCHDOG_TIMEOUT_SECONDS > CONFIG_APP_REBOOT_MODULE_MSG_PROCESSING_TIME_SECONDS, "Watchdog timeout must be greater than message processing time")
ZBUS_MSG_SUBSCRIBER_DEFINE (reboot_subscriber)
ZBUS_CHAN_ADD_OBS (REBOOT_CHAN, reboot_subscriber, 0)
static void state_operational_entry (void *o)
Entry function for operational state.
static void state_operational_run (void *o)
Run function for operational state.
static void reboot_work_fn (struct k_work *work)
Reboot work function.
static void task_wdt_callback (int channel_id, void *user_data)
Watchdog timeout callback.
static K_WORK_DELAYABLE_DEFINE (reboot_work, reboot_work_fn)
static K_THREAD_STACK_DEFINE (stack_area, CONFIG_APP_REBOOT_MODULE_WORKQUEUE_STACK_SIZE)
static int zbus_chan_enabled_obs_count (const struct zbus_channel *chan)
Count enabled observers on a ZBUS channel.
static void handle_reboot_request (const enum reboot_type type)
Handle reboot request message.
static void handle_shutdown_ack (const struct zbus_observer *observer)
Handle shutdown acknowledgment message.
static void reboot_thread (void)
Main reboot thread.
K_THREAD_DEFINE (reboot_thread_id, CONFIG_APP_REBOOT_MODULE_THREAD_STACK_SIZE, reboot_thread, NULL, NULL, NULL, CONFIG_APP_THREAD_PRIORITY_REBOOT, K_ESSENTIAL, 0)
Variables
static const struct smf_state states []
static struct k_work_q reboot_workqueue
Macro Definition Documentation
ADD_OBSERVERS
#define ADD_OBSERVERS (_chan, _type)
Value:
    ZBUS_CHAN_ADD_OBS(_chan, reboot_subscriber, 0);
Definition at line 62 of file reboot.c.
CHANNEL_LIST
#define CHANNEL_LIST (X)
Value:
X(REBOOT_CHAN, struct reboot_msg)
Definition at line 56 of file reboot.c.
MAX_MSG_SIZE
#define MAX_MSG_SIZE MAX_MSG_SIZE_FROM_LIST(CHANNEL_LIST)
Definition at line 59 of file reboot.c.
REBOOT_MODULE_FATAL_ERROR_HANDLE
#define REBOOT_MODULE_FATAL_ERROR_HANDLE ()
Value:
    do {                                                                       \
        LOG_ERR("Fatal error in reboot module, forcing reboot in 10 seconds"); \
        LOG_PANIC();                                                           \
        k_sleep(K_SECONDS(10));                                                \
        __ASSERT(false, "REBOOT_MODULE_FATAL_ERROR_HANDLE macro called");      \
        sys_reboot(SYS_REBOOT_WARM);                                           \
        CODE_UNREACHABLE;                                                      \
    } while (0)
Definition at line 36 of file reboot.c.
Referenced by handle_reboot_request(), reboot_thread(), and task_wdt_callback().
Enumeration Type Documentation
reboot_module_state
enum reboot_module_state
Enumerator
STATE_OPERATIONAL
Definition at line 79 of file reboot.c.
Function Documentation
BUILD_ASSERT()
BUILD_ASSERT (CONFIG_APP_REBOOT_MODULE_WATCHDOG_TIMEOUT_SECONDS , CONFIG_APP_REBOOT_MODULE_MSG_PROCESSING_TIME_SECONDS , "Watchdog timeout must be greater than message processing time")
handle_reboot_request()
void handle_reboot_request (const enum reboot_type type) static
Handle reboot request message.
Schedules reboot work and initiates shutdown sequence.
Parameters
type Type of reboot requested
Definition at line 168 of file reboot.c.
References REBOOT_MODULE_FATAL_ERROR_HANDLE, REBOOT_TYPE_FOTA, reboot_workqueue, and shutdown_request_publish().
Referenced by state_operational_run().
handle_shutdown_ack()
void handle_shutdown_ack (const struct zbus_observer * observer) static
Handle shutdown acknowledgment message.
Disables the observer and checks if all modules have acknowledged shutdown.
Parameters
observer Pointer to observer acknowledging shutdown
Definition at line 205 of file reboot.c.
References reboot_workqueue, and zbus_chan_enabled_obs_count().
Referenced by state_operational_run().
K_THREAD_DEFINE()
K_THREAD_DEFINE (reboot_thread_id , CONFIG_APP_REBOOT_MODULE_THREAD_STACK_SIZE , reboot_thread , NULL , NULL , NULL , CONFIG_APP_THREAD_PRIORITY_REBOOT , K_ESSENTIAL , 0)
References reboot_thread().
K_THREAD_STACK_DEFINE()
K_THREAD_STACK_DEFINE (stack_area , CONFIG_APP_REBOOT_MODULE_WORKQUEUE_STACK_SIZE) static
K_WORK_DELAYABLE_DEFINE()
K_WORK_DELAYABLE_DEFINE (reboot_work , reboot_work_fn) static
References reboot_work_fn().
LOG_MODULE_REGISTER()
LOG_MODULE_REGISTER (reboot , CONFIG_APP_REBOOT_MODULE_LOG_LEVEL)
reboot_thread()
void reboot_thread (void) static
Main reboot thread.
Monitors reboot channel and coordinates system shutdown/reboot.
Definition at line 332 of file reboot.c.
References reboot_state_object::chan, reboot_state_object::msg_buf, REBOOT_MODULE_FATAL_ERROR_HANDLE, STATE_OPERATIONAL, states, task_wdt_callback(), and task_wdt_util_setup().
Referenced by K_THREAD_DEFINE().
reboot_work_fn()
FUNC_NORETURN void reboot_work_fn (struct k_work * work) static
Reboot work function.
Executes system reboot after checking all modules have acknowledged shutdown.
Parameters
work Pointer to work item (unused)
Definition at line 236 of file reboot.c.
References zbus_chan_enabled_obs_count().
Referenced by K_WORK_DELAYABLE_DEFINE().
state_operational_entry()
void state_operational_entry (void * o) static
Entry function for operational state.
Initializes the reboot workqueue.
Parameters
o Pointer to state object
Definition at line 280 of file reboot.c.
References reboot_workqueue.
state_operational_run()
void state_operational_run (void * o) static
Run function for operational state.
Handles reboot requests and shutdown acknowledgments.
Parameters
o Pointer to state object
Definition at line 300 of file reboot.c.
References reboot_state_object::chan, handle_reboot_request(), handle_shutdown_ack(), reboot_state_object::msg_buf, MSG_TO_REBOOT_MSG_PTR, reboot_msg::observer, REBOOT_REQ, reboot_msg::reboot_type, SHUTDOWN_ACK, and reboot_msg::type.
task_wdt_callback()
void task_wdt_callback (int channel_id, void * user_data) static
Watchdog timeout callback.
Parameters
channel_id Watchdog channel ID
user_data User data (thread ID)
Definition at line 259 of file reboot.c.
References REBOOT_MODULE_FATAL_ERROR_HANDLE.
ZBUS_CHAN_ADD_OBS()
ZBUS_CHAN_ADD_OBS (REBOOT_CHAN , reboot_subscriber , 0)
References ADD_OBSERVERS.
zbus_chan_enabled_obs_count()
int zbus_chan_enabled_obs_count (const struct zbus_channel * chan) static
Count enabled observers on a ZBUS channel.
Iterates through the observers of the zbus channel and counts the number of enabled observations, including runtime observers if configured.
Parameters
chan Pointer to the zbus channel
Returns
Number of enabled observations
Definition at line 129 of file reboot.c.
Referenced by handle_shutdown_ack(), and reboot_work_fn().
ZBUS_MSG_SUBSCRIBER_DEFINE()
ZBUS_MSG_SUBSCRIBER_DEFINE (reboot_subscriber)
Variable Documentation
reboot_workqueue
struct k_work_q reboot_workqueue static
Definition at line 112 of file reboot.c.
Referenced by handle_reboot_request(), handle_shutdown_ack(), and state_operational_entry().
states
const struct smf_state states[] static
Initial value:
= {
    [STATE_OPERATIONAL] = SMF_CREATE_STATE(state_operational_entry,
                                           state_operational_run, NULL,
                                           NULL,
                                           NULL),
}
Definition at line 84 of file reboot.c.