SolarResult Dinnis Core: cloud_state_object Struct Reference
cloud_state_object Struct Reference
Data Fields
struct smf_ctx ctx
const struct zbus_channel * chan
uint8_t msg_buf [CONCAT(MAX_, NUM_VA_ARGS(sizeof(struct network_msg), sizeof(struct cloud_msg), sizeof(struct reboot_msg), 0))(sizeof(struct network_msg), sizeof(struct cloud_msg), sizeof(struct reboot_msg), 0)]
uint32_t connection_attempts
Detailed Description
Definition at line 201 of file cloud.c.
Field Documentation
chan
const struct zbus_channel* cloud_state_object::chan
Definition at line 206 of file cloud.c.
Referenced by cloud_thread(), state_cloud_ready_run(), state_connecting_run(), state_disconnected_run(), state_operational_run(), and state_waiting_for_modem_run().
connection_attempts
uint32_t cloud_state_object::connection_attempts
Definition at line 212 of file cloud.c.
Referenced by state_connecting_attempt_entry(), and state_connecting_entry().
ctx
struct smf_ctx cloud_state_object::ctx
Definition at line 203 of file cloud.c.
msg_buf
uint8_t cloud_state_object::msg_buf[ CONCAT(MAX_, NUM_VA_ARGS(sizeof(struct network_msg), sizeof(struct cloud_msg), sizeof(struct reboot_msg), 0))(sizeof(struct network_msg), sizeof(struct cloud_msg), sizeof(struct reboot_msg), 0)]
Definition at line 209 of file cloud.c.
Referenced by cloud_thread(), state_cloud_ready_run(), state_connecting_run(), state_disconnected_run(), state_operational_run(), and state_waiting_for_modem_run().
The documentation for this struct was generated from the following file:
modules/cloud/cloud.c