SolarResult Dinnis Core: common/task_wdt_util.c File Reference
task_wdt_util.c File Reference
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/task_wdt/task_wdt.h>
#include "task_wdt_util.h"
Functions
LOG_MODULE_REGISTER (task_wdt_util, CONFIG_APP_MODULE_LOG_LEVEL)
int task_wdt_util_setup (uint32_t timeout_ms, task_wdt_callback_t callback, void *user_data)
Sets up a task watchdog channel for the calling thread.
Function Documentation
LOG_MODULE_REGISTER()
LOG_MODULE_REGISTER (task_wdt_util , CONFIG_APP_MODULE_LOG_LEVEL)
task_wdt_util_setup()
int task_wdt_util_setup (uint32_t timeout_ms, task_wdt_callback_t callback, void * user_data)
Sets up a task watchdog channel for the calling thread.
Initializes and adds a task watchdog channel with the specified timeout and callback function.
Parameters
timeout_ms The watchdog timeout period in milliseconds.
callback The function to call when the watchdog times out.
user_data User data to pass to the callback function (typically the thread ID).
Returns
The assigned task watchdog channel ID on success.
Return values
<0 Negative error code from task_wdt_add on failure.
Definition at line 16 of file task_wdt_util.c.
Referenced by cloud_thread(), energy_pulse_thread(), led_thread(), message_queue_thread(), network_thread(), p_one_thread(), and reboot_thread().