SolarResult Dinnis Core: modules/timing/timing.c File Reference
timing.c File Reference
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/zbus/zbus.h>
#include "timing_zbus.h"
Functions
LOG_MODULE_REGISTER (timing, CONFIG_APP_TIMING_MODULE_LOG_LEVEL)
BUILD_ASSERT (CONFIG_APP_TIMING_MODULE_PUBLISH_OFFSET_SECONDS< CONFIG_APP_TIMING_MODULE_SLOW_INTERVAL_SECONDS, "Publish offset must be less than slow interval")
BUILD_ASSERT (CONFIG_APP_TIMING_MODULE_SEND_INTERVAL_SECONDS >=CONFIG_APP_TIMING_MODULE_SLOW_INTERVAL_SECONDS, "Send interval should be >= slow interval for buffering")
ZBUS_CHAN_DEFINE (DATA_ACQUISITION_TRIGGER_CHAN, struct timing_event_msg, NULL, NULL, ZBUS_OBSERVERS_EMPTY, ZBUS_MSG_INIT(0))
ZBUS_CHAN_DEFINE (DATA_PUBLISH_REQUEST_CHAN, struct timing_event_msg, NULL, NULL, ZBUS_OBSERVERS_EMPTY, ZBUS_MSG_INIT(0))
ZBUS_CHAN_DEFINE (DATA_SEND_REQUEST_CHAN, struct timing_event_msg, NULL, NULL, ZBUS_OBSERVERS_EMPTY, ZBUS_MSG_INIT(0))
static void fast_acquisition_timer_expiry_fn (struct k_timer *timer)
Fast acquisition timer expiry handler.
static void slow_publish_timer_expiry_fn (struct k_timer *timer)
Slow publish timer expiry handler.
static void send_timer_expiry_fn (struct k_timer *timer)
Send timer expiry handler.
static void fast_acquisition_work_fn (struct k_work *work)
Fast acquisition work handler.
static void slow_publish_work_fn (struct k_work *work)
Slow publish work handler.
static void send_work_fn (struct k_work *work)
Send work handler.
K_TIMER_DEFINE (fast_acquisition_timer, fast_acquisition_timer_expiry_fn, NULL)
K_TIMER_DEFINE (slow_publish_timer, slow_publish_timer_expiry_fn, NULL)
K_TIMER_DEFINE (send_timer, send_timer_expiry_fn, NULL)
K_WORK_DEFINE (fast_acquisition_work, fast_acquisition_work_fn)
K_WORK_DEFINE (slow_publish_work, slow_publish_work_fn)
K_WORK_DEFINE (send_work, send_work_fn)
static int timing_module_init (void)
Initialize timing module.
SYS_INIT (timing_module_init, APPLICATION, CONFIG_APPLICATION_INIT_PRIORITY)
Function Documentation
BUILD_ASSERT() [1/2]
BUILD_ASSERT ()
BUILD_ASSERT() [2/2]
BUILD_ASSERT (CONFIG_APP_TIMING_MODULE_SEND_INTERVAL_SECONDS >= CONFIG_APP_TIMING_MODULE_SLOW_INTERVAL_SECONDS, "Send interval should be >= slow interval for buffering")
fast_acquisition_timer_expiry_fn()
void fast_acquisition_timer_expiry_fn (struct k_timer * timer) static
Fast acquisition timer expiry handler.
Executed in interrupt context when fast acquisition timer expires. Submits work item to system workqueue for processing in thread context.
Definition at line 97 of file timing.c.
Referenced by K_TIMER_DEFINE().
fast_acquisition_work_fn()
void fast_acquisition_work_fn (struct k_work * work) static
Fast acquisition work handler.
Publishes DATA_ACQUISITION_TRIGGER_CHAN event. Executed in system workqueue thread context. Used by modules that need frequent data acquisition (e.g., P1 UART reading).
Definition at line 146 of file timing.c.
References timing_event_msg::timestamp.
Referenced by K_WORK_DEFINE().
K_TIMER_DEFINE() [1/3]
K_TIMER_DEFINE (fast_acquisition_timer , fast_acquisition_timer_expiry_fn , NULL)
References fast_acquisition_timer_expiry_fn().
K_TIMER_DEFINE() [2/3]
K_TIMER_DEFINE (send_timer , send_timer_expiry_fn , NULL)
References send_timer_expiry_fn().
K_TIMER_DEFINE() [3/3]
K_TIMER_DEFINE (slow_publish_timer , slow_publish_timer_expiry_fn , NULL)
References slow_publish_timer_expiry_fn().
K_WORK_DEFINE() [1/3]
K_WORK_DEFINE (fast_acquisition_work , fast_acquisition_work_fn)
References fast_acquisition_work_fn().
K_WORK_DEFINE() [2/3]
K_WORK_DEFINE (send_work , send_work_fn)
References send_work_fn().
K_WORK_DEFINE() [3/3]
K_WORK_DEFINE (slow_publish_work , slow_publish_work_fn)
References slow_publish_work_fn().
LOG_MODULE_REGISTER()
LOG_MODULE_REGISTER (timing , CONFIG_APP_TIMING_MODULE_LOG_LEVEL)
send_timer_expiry_fn()
void send_timer_expiry_fn (struct k_timer * timer) static
Send timer expiry handler.
Executed in interrupt context when send timer expires. Submits work item to system workqueue for processing in thread context.
Definition at line 125 of file timing.c.
Referenced by K_TIMER_DEFINE().
send_work_fn()
void send_work_fn (struct k_work * work) static
Send work handler.
Publishes DATA_SEND_REQUEST_CHAN event. Executed in system workqueue thread context. Used by Message Queue to send buffered data to cloud.
Definition at line 194 of file timing.c.
References timing_event_msg::timestamp.
Referenced by K_WORK_DEFINE().
slow_publish_timer_expiry_fn()
void slow_publish_timer_expiry_fn (struct k_timer * timer) static
Slow publish timer expiry handler.
Executed in interrupt context when slow publish timer expires. Submits work item to system workqueue for processing in thread context.
Definition at line 111 of file timing.c.
Referenced by K_TIMER_DEFINE().
slow_publish_work_fn()
void slow_publish_work_fn (struct k_work * work) static
Slow publish work handler.
Publishes DATA_PUBLISH_REQUEST_CHAN event. Executed in system workqueue thread context. Used by modules to publish their collected data (e.g., P1 stats, Pulse counters).
Definition at line 170 of file timing.c.
References timing_event_msg::timestamp.
Referenced by K_WORK_DEFINE().
SYS_INIT()
SYS_INIT (timing_module_init , APPLICATION , CONFIG_APPLICATION_INIT_PRIORITY)
References timing_module_init().
timing_module_init()
int timing_module_init (void) static
Initialize timing module.
Validates configuration and starts all timers. Called automatically via SYS_INIT during boot.
Returns
0 on success, negative errno on failure
Definition at line 225 of file timing.c.
Referenced by SYS_INIT().
ZBUS_CHAN_DEFINE() [1/3]
ZBUS_CHAN_DEFINE (DATA_ACQUISITION_TRIGGER_CHAN , struct timing_event_msg , NULL , NULL , ZBUS_OBSERVERS_EMPTY , ZBUS_MSG_INIT(0))
ZBUS_CHAN_DEFINE() [2/3]
ZBUS_CHAN_DEFINE (DATA_PUBLISH_REQUEST_CHAN , struct timing_event_msg , NULL , NULL , ZBUS_OBSERVERS_EMPTY , ZBUS_MSG_INIT(0))
ZBUS_CHAN_DEFINE() [3/3]
ZBUS_CHAN_DEFINE (DATA_SEND_REQUEST_CHAN , struct timing_event_msg , NULL , NULL , ZBUS_OBSERVERS_EMPTY , ZBUS_MSG_INIT(0))